### ISSUE TITLE
Variable minibuffer--require-match doesn't exist in some versions of Emacs

### ISSUE THREAD

**Issue by oantolin** [minad/vertico#10]
I have two computers with different Emacs 28 snapshots, the newer one has the variable and the older doesn't. It looks like Emacs 27 does have the variable, so I think the variable was removed and then re-added. I'm not sure if anything needs to be done about this, since Emacs 28 isn't out yet and it seems to have regained the variable, but I thought I'd let you know.

**Comment by oantolin** [comment]
I'm using `(defvar minibuffer--require-match nil)` as workaround in the version of Emacs that doesn't have the variable, since, as you well know, I believe a match is not required. 😛

**Comment by minad** [comment]
Do you know what this particular Emacs 28 version uses instead? I mean there must be some variable.

I just implemented deferred highlighting for all completion styles (like orderless-skip-highlighting).

https://github.com/minad/vertico/blob/728e52df777683e08dc489e88a6bd017e25434f6/vertico.el#L235-L259

You may want to try this too with your collection of Emacsen, since this is a brittle change.

**Comment by minad** [comment]
I close this, see https://github.com/emacs-mirror/emacs/blob/3af9e84ff59811734dcbb5d55e04e1fdb7051e77/lisp/minibuffer.el#L3769.

**Comment by oantolin** [comment]
I agree with closing this, as I said from the start I didn't really think it was necessary to do anything about it. But I'm curious: what am I supposed to see in the line you linked? I already mentioned that more recent Emacs 28s have the variable again, what was you point in linking to that?

**Comment by minad** [comment]
No point, you already said everything. I only added it as reference if one wants to look again in the future.

**Comment by oantolin** [comment]
> Do you know what this particular Emacs 28 version uses instead?

It only has `minibuffer-completion-confirm`.

**Comment by minad** [comment]
> It only has minibuffer-completion-confirm.

But this value is not pristine.

This is what you find in Emacs 27.1. I guess someone did the fixme?

~~~ elisp
         ;; FIXME: Remove/rename this var, see the next one.
         (minibuffer-completion-confirm (unless (eq require-match t)
                                          require-match))
         (minibuffer--require-match require-match)
~~~

**Comment by oantolin** [comment]
The corresponding section of `minibuffer.el` in my weird Emacs 28:

```elisp
  (let* ((minibuffer-completion-table collection)
         (minibuffer-completion-predicate predicate)
         (minibuffer-completion-confirm (unless (eq require-match t)
                                          require-match))
         (base-keymap (if require-match
```

**Comment by ether42** [comment]
https://github.com/minad/vertico/issues/10#issuecomment-817222698 seconded, but for Emacs 26 (and I can't really upgrade).
Additionally, I had to:
```patch
-  (setq-local resize-mini-windows 'grow-only
-              max-mini-window-height 1.0
-              truncate-lines t
-              completion-auto-help nil
-              completion-show-inline-help nil)
+  (setq-local resize-mini-windows 'grow-only)
+  (setq-local max-mini-window-height 1.0)
+  (setq-local truncate-lines t)
+  (setq-local completion-auto-help nil)
+  (setq-local completion-show-inline-help nil)
```
Because `setq-local` doesn't accept a list of variables yet.

Do you support older Emacs versions? It's fine if you don't, I'm only asking to know if this is a goal.

**Comment by minad** [comment]
No I am only supporting >= 27.1
