### ISSUE TITLE
Add support for hotfuzz

### ISSUE THREAD

**Issue by manuel-uberti** [minad/vertico#100]
https://github.com/axelf4/hotfuzz

I am fairly sure you have already thought about this, so it's me nudging you as usual. Consider me your motivator, unless you're rightly thinking of far worse labels at the moment. ;)

Seriously, though, I was thinking of highlighting support, the only thing I feel like `hotfuzz` is missing at the moment.

**Comment by minad** [comment]
No, we should not add this here. The problem should be fixed upstream (see my deferred highlighting works for how this should go) or in hotfuzz itself.

**Comment by minad** [comment]
I should also give you the reason for the necessity of fixing deferred highlighting upstream for flex or derived completion styles:

https://github.com/minad/vertico/blob/5e612540ed380394fda38cc7938b8734c7001bca/vertico.el#L273-L274
