### ISSUE TITLE
Vertico-flat-mode toggle

### ISSUE THREAD

**Issue by tpeacock19** [minad/vertico#101]
I find it pretty useful in my config to default to `vertico-flat-mode` and have made the below to toggle it when I want more context (especially with `marginalia`). Perhaps this is something that can be included or referenced in the wiki?

```elisp
(defun vertico-flat-toggle ()
  (interactive)
  (vertico-flat-mode (if vertico-flat-mode -1 1))
  ;; this doesn't seem to have an effect or interfere when `vertico-flat-mode' is disabled
  (window-resize nil (* (- vertico-count) (default-line-height)) nil nil 'pixelwise))
```

**Comment by minad** [comment]
Good idea! I added a fix to `vertico-flat-mode`, such that you can use the mode directly as toggle.

**Comment by tpeacock19** [comment]
yep, works great, thanks!

**Comment by tpeacock19** [comment]
Actually, i'll mention here because it may be a one-off. But I also think it is useful to have different values for `vertico-count` based on the current mode, given the varied amount of screen real-estate across the modes. I set this now using this function with the `minibuffer-setup-hook` or the `vertico-*-mode-hook`, but it may be worthwhile to provide an option for an alist for `vertico-count` that would be determined by the current mode. 

```elisp
(defun arx--vertico-count ()
    (cond
     ((and vertico-flat-mode
           (<  (frame-width) 250))
      (setq vertico-count 5))
     (vertico-buffer-mode
      (setq vertico-count 50))
     (t
      (setq vertico-count 10))))
```

**Comment by minad** [comment]
Okay, this is too special to be added to vertico/vertico-flat itself, in order to keep things simple. But I would appreciate if you add such an example to the wiki!

**Comment by tpeacock19** [comment]
ok i will work towards something.
