### ISSUE TITLE
GNU ELPA and GNU-devel ELPA versions

### ISSUE THREAD

**Issue by grolongo** [minad/vertico#102]
Hello minad,

just noticed you published Vertico `0.13` 24 days ago but it hasn't been updated yet on GNU ELPA. Is it normal?

I wasn't aware of GNU-devel ELPA existence until very recently and Vertico version there is much more up-to-date.

Now I don't see Vertico on MELPA unlike Consult or Marginalia.

Is GNU-devel ELPA going to be available by default on Emacs 28 as it will be for NonGNU ELPA?

Nothing serious just was a bit curious about the process.

Have a nice day.

**Comment by minad** [comment]
* There was a build issue with 0.13 therefore it is not available. But I will tag a 0.14 soon.
* elpa devel won't be available by default. You always have to configure it manually.
