### ISSUE TITLE
vertico-directory feature: restart a path

### ISSUE THREAD

**Issue by jdtsmith** [minad/vertico#104]
I nice ido feature: if you start typing `/`, i.e. the beginning of a new path at a directory (e.g. `/path/to/file/~/`) ido removes the early part of the path and replaces it by your new path (here `~/`).  This could be implemented with a post-command hook (i.e. `vertico-exhibit`), or perhaps by re-binding '/' to check for this condition and otherwise self-insert.  

For simple restarted paths like `/path/to/file//` ido waits for another character before replacing the abandoned path in this way, i.e. `/path/to/file//t` -> `/t`.  So that would recommend doing this in a post-command hook.

**Comment by minad** [comment]
See vertico-directory-tidy.

**Comment by jdtsmith** [comment]
Aha!  Shadow was confusing given embark usage of the same name.  I tried this in `vertico-directory-tidy`:

```elisp
                 (seq-contains-p [?/ ?~] (char-before (- (point) 2)))))
```

and it allows restarting with home-directory `~` as well.  Thanks.

**Comment by salutis** [comment]
For the future readers, here is how to enable restarting à la Ido/Ivy:

```emacs-lisp
(with-eval-after-load 'rfn-eshadow
  (setq-default file-name-shadow-properties '(invisible t intangible t)))
(add-hook 'after-init-hook #'file-name-shadow-mode)
```

**Comment by jdtsmith** [comment]
See PR #108 to enable `~` for path shadowing.

**Comment by salutis** [comment]
> For the future readers, here is how to enable path "restarting" à la Ido/Ivy:

Unfortunately, this breaks `savehist-mode`, i.e. the recently opened files do not show in the list. For instance, when I visit `~/org/` in `C-x C-f`, I see the last _n_ files I opened in the past. For `~/org/~/org/`, I do not. Anyone knows how to solve the problem?
