### ISSUE TITLE
minibuffer size stays one line at the beginning when in `tex` mode

### ISSUE THREAD

**Issue by linwaytin** [minad/vertico#105]
This is a weird bug. When the emacs is in `tex` mode, `vertico` starts the minibuffer of one line.
For example, if I press `M-x`, the minibuffer shows `1/10284 M-x` but has size one line until I type something or press the arrow key.
It seems related to #75 , but so far this problem happens only in the `tex` mode. 

This didn't happen until I update the package today. 
Is there some change related to the size of minibuffer?
Thanks.

**Comment by linwaytin** [comment]
I studied this issue a little more. 
The same issue for `selectrum` and `icomplete-vertical`, but not for `ivy`.
Maybe this bug is related to some Emacs built-in function.

**Comment by linwaytin** [comment]
I think I found what's going on. 
The issue seems related to how Emacs calculate and change its frame and window size. 
I use a tiling window manager and Emacs occupies the whole screen by default.
If Emacs is in the floating mode, the issue is gone.

The reason why it happens only in TeX mode (in my case) is because the TeX mode comes with an additional toolbar, and those icons seems not standard. 
This makes the toolbar in the TeX mode has slightly different height with the standard toolbar. 
When the point is in the minibuffer, the toolbar is standard and that changes the height of the windows.
I believe this eventually leads to the strange behavior described above. 

My workaround is turning off the toolbar from TeX mode, by adding `(LaTeX-enable-toolbar nil)` to `custom-set-variables`.
See https://www.gnu.org/software/auctex/manual/auctex.html#index-LaTeX_002denable_002dtoolbar

**Comment by minad** [comment]
> My workaround is turning off the toolbar from TeX mode, by adding
> |(LaTeX-enable-toolbar nil)| to |custom-set-variables|.

Thanks for investigating this.  I've seen problems before with window
size computations. I think these are Emacs bugs but it is difficult to
reproduce them or pinpoint the exact cause of the issue. For example the
Vertico resizing doesn't work correctly on my system if I run emacs -Q.
With emacs -q everything works well, so I have some issue with the X
resources.

**Comment by linwaytin** [comment]
Maybe it's due to the X window system, but as you said, it's hard to track this cause of this issue...
