### ISSUE TITLE
void function `vertico-quick--first` when using `vertico-quick`.

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [minad/vertico#109]
* Description

After `(require 'vertico-quick)` and binding key to the following convenience function I wrote for vertico quick, I'd get an error saying `vertico-quick--first` is not a function.

```emacs-lisp
(defun oo-vertico-quick-insert-and-exit ()
  (interactive)
  (funcall-interactively #'vertico-quick-insert)
  (funcall-interactively #'vertico-exit))
```

* Reason I think this happens

Since `vertico-quick` uses `cl-letf` in the function `vertico-quick--read`. I think it needs a `(eval-when-compile (require 'cl-macs))` at the top. Because it doesn't have this, emacs may not know about `cl-letf` during compile time.

* Recipes

'(vertico
  :type git
  :host github
  :repo "minad/vertico"
  :local-repo "vertico"
  :commit "d00ad0697024aa9555972ea2bce678080272d633")

'(vertico-quick
  :type git
  :host github
  :files ("extensions/vertico-quick.el")
  :repo "minad/vertico"
  :local-repo "vertico")

**Comment by minad** [comment]
You don't need `oo-vertico-quick-insert-and-exit`, since there is already `vertico-quick-exit`. vertico-quick works well in my setup. I installed it with package-install-file. Note that `cl-letf` is autoloaded. How did you install `vertico-quick`?

**Comment by Luis-Henriquez-Perez** [comment]
> You don't need oo-vertico-quick-insert-and-exit, since there is already vertico-quick-exit. vertico-quick works well in my setup.

That's great. I'll ditch `oo-vertico-quick-insert-and-exit` then.

> How did you install vertico-quick, is this quelpa?

I used `straight.el`. I have commits in my recipes because I'm manage them myself instead of using lockfiles (straight doesn't complain with superfluous keywords).
