### ISSUE TITLE
Last choice is highlighted fringe-to-fringe

### ISSUE THREAD

**Issue by jangid** [minad/vertico#11]
Minor issue. But still.

When I have multiple choices to select, the last choice is not highlighted fringe-to-fringe. See the pics.

<img width="1252" alt="Screenshot 2021-04-12 at 4 26 15 PM" src="https://user-images.githubusercontent.com/46752/114384177-04ac1a00-9bac-11eb-9ebb-e62c9f2ad6e9.png">
<img width="1252" alt="Screenshot 2021-04-12 at 4 26 10 PM" src="https://user-images.githubusercontent.com/46752/114384189-083fa100-9bac-11eb-9eee-f384599f6a05.png">

**Comment by minad** [comment]
Thank you for reminding me. I was aware of the issue. This could not be fixed before since Vertico did not manually resize the window, such that I could not add the final newline necessary for the highlighting extension. But I recently switched to manual window resizing.
