### ISSUE TITLE
use a function instead of a cons-cell for `vertico-count-format`

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [minad/vertico#110]
For me I like to just see the total number of candidates when using the minibuffer--that's it. But I had some trouble doing this with `vertico-count-format`. I'm not saying there is not a way, but I wasn't sure how to display _just_ the total number of candidates. The problem is that the format string has two placeholders but I just wanted to use one.

On a side note, I think `vertico-count-format` as it is should have more documentation. Right now it is: "Format string used for the candidate count.". But `vertico-count-format` is not a string, it is a cons cell. I feel the docs should address what the CAR and the CDR represent.

I ended up doing this:

```elisp
(defadvice! just-give-me-the-total (override vertico--format-count)
  "Don't provide me with the index of the current item."
  (alet (cond ((>= vertico--index 0) vertico--total)
	      ((vertico--allow-prompt-selection-p) "*")
	      (t "!"))
    (format "%-6s" it)))
```
When I did this I wondered whether it wouldn't be better to just have `vertico-count-format` accept a function with two arguments: the index of the current candidate, and the total number of candidates. And it should return a string--what to display. To me that would make it clearer and more flexible to customize the display.

**Comment by minad** [comment]
I don't see the need to use a function for now. You can use a field index as follows:

~~~ elisp
(setq vertico-count-format '("%-6s " . "%2$s"))
~~~

I hope this helps!
