### ISSUE TITLE
Can/should vertico-directory-enter only affect filename completions?

### ISSUE THREAD

**Issue by deejayem** [minad/vertico#111]
I tried binding "/" to `vertico-directory-enter` (which roughly matches the behaviour of counsel-find-file - pressing "/" inserts the currently selected directory candidate).

This works fine with find-file (etc), but breaks other things, as now / always chooses the currently selected option in the minibuffer. So, for example if I have some 'my/foo', 'my/bar', etc commands, 'M-x my/' runs one of them, instead of entering 'my/' and allowing me to keep typing.

describe-key-briefly confirms that / is bound to vertico-enter-directory in the minibuffer, even when not completing file names.

Is it possible for it only to be bound when completing filenames, or for vertico-directory-enter to just insert the character when not completing filenames?

**Comment by minad** [comment]
Yes, this is possible of course. But it requires you to write your own command which either inserts "/" or enters the directory. Take a look at the source of `vertico-directory-enter`.

https://github.com/minad/vertico/blob/8a76d26e3f83776eec1dc0907fdd8e79be913ece/extensions/vertico-directory.el#L54-L62

Your command will not look much different:

~~~ elisp
(defun custom-vertico-directory-enter ()
  "Enter directory or exit completion with current candidate."
  (interactive)
  (if (and (>= vertico--index 0)
           (string-suffix-p "/" (vertico--candidate))
           (vertico-directory--completing-file-p))
      (vertico-insert)
    (insert "/"))) ;; insert "/" instead of `vertico-exit'
~~~

Please let me know if you have further questions.

**Comment by deejayem** [comment]
Perfect, thank you.

**Comment by deejayem** [comment]
In case anyone else comes across this, the above works fine, but here's an alternative, based on https://github.com/minad/consult/wiki#add-category-specific-minibuffer-keybindings

```(defun define-vertico-key (key &rest defs)
    "Define KEY conditionally in the vertico.
DEFS is a plist associating completion categories to commands."
    (define-key vertico-map (kbd key)
      (list 'menu-item nil defs :filter
            (lambda (d)
              (plist-get d (completion-metadata-get
                            (completion-metadata (minibuffer-contents)
                                                 minibuffer-completion-table
                                                 minibuffer-completion-predicate)
                            'category))))))

(define-vertico-key "/"
    'file #'vertico-directory-enter
    'project-file #'vertico-directory-enter)
```

(The only differences between my version of the function and the wiki example were to use `vertico-map`, instead of `minibuffer-local-map`, and to call `(kbd key)` instead of just passing `key` to `define-key`).
