### ISSUE TITLE
Issue with `select multiple`

### ISSUE THREAD

**Issue by mplanchard** [minad/vertico#112]
Hi there,

I'm having an issue with the "select multiple" option in vertico. Specifically I see it when when setting options on a PR in magit forge, but that's just the only place I have seen the multiple select screen so far.

For example, if I hit `C-c C-e` on `Review-Requests`, I get the vertico popup for selecting multiple options. If I then start typing to narrow and hit `TAB` to select, it shows that there is 1 selected. If I then type again to narrow to another team member and hit `TAB` to select, it shows there are 2 selected. However, when I press `RET`, only one of the two gets assigned.

The only way I'm able to get two review requests is by using `TAB` to select one, moving my cursor over the (unselected) other reviewer, and then pressing `RET`.

This also has led to me accidentally assigning people I didn't intend, because if I just select one item by using `TAB`, the cursor defaults to being on the top unselected item. Pressing `RET` there then causes both items be used.

Is there something I'm missing about how to use this interface? My intuition would be that, once something is actively selected, only (and all of) the Selected items would be what would be used, regardless of where the current highlight is.

My setup is:
- Doom v3.0.0-alpha (HEAD -> develop 782de48e0 2021-08-14 21:50:50 -0400)
- emacs28 + nativeComp + pgtk
- ubuntu 21.04
- vertico: 9de6709

And I don't have any vertico-specific stuff in my config at the moment

Thanks!

**Comment by minad** [comment]
Yes, this is indeed not behaving as you expect. Note that there are more components involved here. Doom uses consult-crm and doom overwrites the keybondings with its own commands. Please ask on the doom discord about this.

**Comment by mplanchard** [comment]
Cool, thanks for the lead!
