### ISSUE TITLE
Problems renaming directories in dired

### ISSUE THREAD

**Issue by asoroa** [minad/vertico#117]
Hi!

when using vertico I'm having problems renaming directories within a dired
buffer.

Say I have a dir `~/tmp/foo1` and I want to rename it to `~/tmp/foo`. I
perform the following steps:

- C-x d `~/tmp`
- go to line corresponding to `foo1`
- press R (rename)
At his point, the minibuffer reads as: `*/120 Rename foo1 to: ~/tmp/`
- write `foo`, press enter

I get the following error:

```
Move: ‘/home/user/tmp/foo1’ to ‘/home/user/tmp/foo1/foo1’ failed:
(file-error Renaming Invalid argument /home/user/tmp/foo1 /home/user/tmp/foo1/foo1)
```
Any help?

**Comment by Eason0210** [comment]
May be you should press `C-p`  after you input `foo` to move cursor up and then it will not use the name of `fool`.

**Comment by asoroa** [comment]
Yes, that solves the issue for me (still learning how to use vertico). Thank you!
