### ISSUE TITLE
Error in post-command-hook (vertico--exhibit): (file-error "Getting attributes" "Permission denied" ...)

### ISSUE THREAD

**Issue by meedstrom** [minad/vertico#118]
Got this message anytime I call consult-buffer and type a few letters; it's trying to get virtual buffers from the recentf list, and some paths don't exist anymore as they were temporary mounts of an external disk. Fixed for me after calling `recentf-cleanup`, but I guess you'll want some kind of guard clause here.

Full message:

```
Error in post-command-hook (vertico--exhibit): (file-error "Getting attributes" "Permission denied" "/media/me/d1487324-f21d-4201-9336-717924d78a83/trek/Star Trek The Next Generation/Star Trek TNG Season 04/")
```

**Comment by minad** [comment]
I assume you are using Marginalia? Fixed in https://github.com/minad/marginalia/commit/e06d46159442a25c3b99c02cec336a4dfa21693c.

**Comment by meedstrom** [comment]
Confirmed fixed.
