### ISSUE TITLE
Save history of commands and stuff selected?

### ISSUE THREAD

**Issue by bbuccianti** [minad/vertico#12]
Hi!

First, thanks for creating this wonderful package. I was a selectrum user but vertico is definitely a lot better for myself because I don't use at least 80% of what selectrum offers.

But, I'm kind of missing the history capabilities of selectrum-prescient. Do you think would be imprudent or difficult to add this?

I'm referring especially to this use case. Emacs shows you the last used commands in some commands like M-x, but this only lasts for the session, I'm thinking of persist those. Maybe Emacs have that too? I don't know!

Thanks again!

**Comment by minad** [comment]
Yes, there is no need for prescient. You can use the Emacs builtin `savehist-mode`. Note that `savehist-mode` also works with Selectrum. See https://github.com/minad/vertico/commit/ffe34e5960e6d932f7ede9aa38be4aa194feeb8d.

**Comment by bbuccianti** [comment]
Thank you very much!
