### ISSUE TITLE
M-x - not show in Vertico mode

### ISSUE THREAD

**Issue by alexei-28** [minad/vertico#121]
Linux Mint 20.2
Emacs 27.2
Install package Vertico ver. 0.14

In init.el file
```
(require 'vertico)
(vertico-mode t)
```

After restart Emacs here result:

`C-x C-f (find-file)`
![first](https://user-images.githubusercontent.com/303539/132979816-eb0b871a-9907-4aaa-9df9-d24b8dc06a46.png)

Nice.

`C-x b (switch-to-buffer)`
![second](https://user-images.githubusercontent.com/303539/132979821-23d5671a-68e5-4247-80c4-f03c315361cf.png)

Nice.

But when I use `M-x` the minibuffer **is not** in vertico mode
![third](https://user-images.githubusercontent.com/303539/132979832-dfd31c57-d92c-45a4-b7b8-13d8c41ed64f.png)

**Comment by minad** [comment]
There is something wrong with your configuration. This looks like some Ido-mode. Please try to report your issues first with emacs - Q before reporting them.

**Comment by alexei-28** [comment]
> There is something wrong with your configuration. This looks like some Ido-mode. Please try to reproduce your issues first with emacs -Q before reporting them.

I was found the problem. I use package "smex" and use custom key binding
`
(global-set-key (kbd "M-x") 'smex)`

If I remove this keybinding the problem is gone. And Vertico success show on `M-x`
