### ISSUE TITLE
vertico-directory and tramp remote filepaths

### ISSUE THREAD

**Issue by jdtsmith** [minad/vertico#122]
With vertico-directory enabled, hitting `Ret` when selecting a tramp method or hostname (e.g. `/s` select `/ssh:` `Ret`, or `/ssh:p` select `/ssh:pi:` `Ret`) attempts to load that path as a file, rather than entering the method or host as a pseudo-directory as would be expected (and as ido does).

**Comment by minad** [comment]
Yes, this makes sense.
