### ISSUE TITLE
vertico-directory-up does not well handle the case of file

### ISSUE THREAD

**Issue by rememberYou** [minad/vertico#123]
Former user of `ivy` and `counsel`. I used `counsel-up-directory` a lot to easily get back to a parent folder when using the completion file system. Using `vertico-directory-up`, I noticed that if I fill a file instead of a folder, I had to do `M-<backspace>` to delete it instead of `vertico-directory-up` (`C-<backspace>`) to try to return to the parent folder. Probably this behavior is not desirable.

Current behavior with `vertico-directory-up`:
```
Find-file: ~/.emacs.d/config.el
C-<backspace> 
Find-file: ~/.emacs.d/config.el
```

Excepted behavior with `vertico-directory-up` (similar to `counsel-up-directory`):
```
Find-file: ~/.emacs.d/config.el
C-<backspace> 
Find-file: ~/.emacs.d/
```

Similar behavior if a file does not exist or when entering the initials of an existing file. I expect to be able to return to the parent folder anyway.

**Comment by minad** [comment]
I don't understand this issue. See https://github.com/minad/vertico#extensions for a configuration example, where DEL is bound.

**Comment by rememberYou** [comment]
Oops! I modified the second example. My apologies. What I want to illustrate is that `vertico-directory-up` only works when a child folder has been completed. However, if I complete a child file entirely or not, as well as an erroneous file, it is not possible to return to the parent folder.

**Comment by minad** [comment]
Okay, now I understand. This behavior is intentional. vertico-directory-up is used by the vertico-directory-delete-* commands. But you can easily write your own command which always deletes until to the last /.

**Comment by rememberYou** [comment]
I will do that. Thanks for the suggestion.
