### ISSUE TITLE
[Question] I don't see .git directory in candidates when using find-file

### ISSUE THREAD

**Issue by TxGVNN** [minad/vertico#124]
Hi @minad, thank you for great package.

I just switch to `vertico-mode` a few days ago. Today, I discover I don't see .git directory when I use find-file. If I try to type `.git/` it will show into `.git`. 
I tested with load only `vertico` to make sure it does not come from my configs.

`emacs -nw -Q -l ~/.emacs.d/elpa/vertico-0.14/vertico-autoloads.el --eval '(vertico-mode)'`

With emacs default, I can see .git directory. Could you help me how can I do to show .git directory in candidates?

Regards,

**Comment by minad** [comment]
You can adjust completion-ignored-extensions.
