### ISSUE TITLE
Dired: rename current file

### ISSUE THREAD

**Issue by CGenie** [minad/vertico#125]
Hello,
I guess this is more of a question than a bug report.

I would like to navigate a file in dired and be able to rename it "in-place" i.e. with current filename being completed in some way. There's a "down arrow" trick described here:
https://emacs.stackexchange.com/questions/55529/how-to-rename-a-file-with-dired-with-the-current-file-name-as-default
however with Vertico/Consul I'm not able to reproduce it.

Is there some other way to do it in vertico?

**Comment by minad** [comment]
The "down trick" (`next-history-element`) is also available in Vertico. Usually the command is bound to `M-n` in `minibuffer-local-map`/`vertico-map`. As a rule of thumb, almost everything that works with default completion works also with Vertico.

**Comment by CGenie** [comment]
Ah splendid, thank you!

**Comment by CGenie** [comment]
Just for future reference: `M-n` in the minibuffer is the so-called "future-history" https://engineering.collbox.co/post/working-faster-in-emacs-by-reading-the-future/ :)
