### ISSUE TITLE
Submit exact input?

### ISSUE THREAD

**Issue by emacsomancer** [minad/vertico#128]
Is there an equivalent of Selectrum's`selectrum-submit-exact-input`?

I understand that in most cases one can do the "Non-existing candidates can be entered by moving the point to the prompt line" thing, but this doesn't work, for instance, with Org-roam's Node selection.

**Comment by minad** [comment]
See `vertico-exit-input`.

**Comment by minad** [comment]
If vertico-exit-input refuses to exit (match required), you can also bind the command `exit-minibuffer` to some key in the `vertico-map`. You can force exiting with `exit-minibuffer`.
