### ISSUE TITLE
Tramp slow-downs

### ISSUE THREAD

**Issue by jdtsmith** [minad/vertico#129]
I've noticed that vertico is often very slow to complete file names in find-file on remote hosts with tramp.  I assumed this was due to excessive traffic over the SSH link, but upon examining this with `(setq tramp-verbose 6)`, I've come to conclude that is not the problem.  Tramp in fact caches recent directory listings.  Even when hitting this tramp cache (and thus not sending _any_ traffic over the SSH link), every keypress while completing a remote filename with vertico is molasses slow, directory listings come in slow, filtering (with orderless or even basic style) is slow, deleting a single character is slow.  Slow means something of order 1/2 to 1 second for each key event.

Now here is the very strange (and hopefully illuminating) part: when using find-file _starting from a remote file or dired buffer_, vertico is _lightning quick_.  This is true even when navigating to remote filepaths entirely outside of the one where you started.  In its debug logs, you can see tramp doing its thing, quickly giving listing and cached results.  Everything is snappy.  

I haven't been able to figure out what possible difference could arise between:

1. (**SLOW**) Starting with `C-x C-f` showing `~/path/to/some/file/` then (painfully, after the server part) entering `/ssh:server:/path/to/remote/file` , and
2. (**FAST**) starting inside a remote file, `C-x C-f` showing `/ssh:server:/some/other/path/` then `[Del][Del][Del]path/to/remote/file`. 

There must be something!

Update: selectrum also has this issue.  But I'll leave this open in case anyone has any ideas...

**Comment by minad** [comment]
See also #20. You can ask on the tramp mailing list or try to identify which part of is actually slow, e.g., the API call `completion-all-completions`.

**Comment by jdtsmith** [comment]
Thanks for these thoughts.  I also tested with and without marginalia and that didn't make a difference.  I confirmed similar behavior with selectrum, fido, and even default completion (I think; it's much less noticeable there since it doesn't aggressively check `completion-all-completions` on each keypress).  So clearly a deeper tramp-level discrepancy.  I've posted to the tramp devel list and will report back if any clarity arises.   Here's a video of the difference I'm seeing, navigating to the same exact file as fast as possible, first from a remote (dired) buffer, then from `*scratch*`:

https://user-images.githubusercontent.com/93749/133894438-6380dc20-7059-47db-b5eb-ac4d2322ce64.mov

**Comment by minad** [comment]
Can you reproduce this with `emacs -Q`? Can you debug this a bit better and narrow down what *exactly* leads to this slowdown? Ideally add a few debug outputs around function calls which measure the time spent there or use `trace-function`. I am not seeing this behavior, in my setup it is always fast. Of course there is an initial slowdown when the directory listing is retrieved but after that, everything works well.

**Comment by jdtsmith** [comment]
I've been trying that to no avail.  See this [tramp-devel discussion](https://lists.gnu.org/archive/html/tramp-devel/2021-09/msg00003.html).  The tramp maintainer has verified this discrepancy with fido-mode, but not with normal Tab-based completion.  I can clearly see a difference with just `emacs -Q /ssh:datpi:`, whether hitting the cache or not.  It's more subtle with default completion, presumably since `completion-all-completions` is called only on `TAB`, not every keypress.  

As mentioned on the thread, I don't think this can be a completion-style or completion UI issue at all.  As long as you start from a remote buffer, it's fast even when switching hosts!  Profiling was TMI.  Are there any functions "close the action" you can suggest for more focussed timing? (Closing, as this isn't a vertico issue).

**Comment by minad** [comment]
> As mentioned on the thread, I don't think this can be a completion-style or completion UI issue at all.

Yes, this seems to be a deeper Tramp issue. As I mentioned, everything UI-related was resolved in #20. There were two issues: 1. The completion predicate caused a slowdown and 2. Tramp doesn't allow to compute the completions in an interruptible way. Unfortunately Tramp leaks through the completion abstraction and this had to be worked around in #20. However everything happening inside `completion-all-completions` or more low-level the file completion table itself, is not an issue of the upper layers.

> Are there any functions "close the action" you can suggest for more focussed timing?

What do you mean by that? You can investigate the file name completion table `read-file-name-internal` and `completion--file-name-table` and dig deeper from there.

**Comment by jdtsmith** [comment]
I measured a big (>10x) difference in `completion-all-completions`, even with Tab-based completion, but it's especially severe with Vertico.  Vertico seems to call this once per keypress, whereas normal tab-based completion calls it many hundreds of times (but much faster each time).  The ~1/2s per keypress I experience seems to be entirely attributable to something inside `completion-all-completions`. 

Please see the [tramp-devel](https://lists.gnu.org/archive/html/tramp-devel/2021-09/threads.html#00003) thread if interested.

**Comment by minad** [comment]
> Vertico seems to call this once per keypress

Indeed. This is how the API is supposed to be used if you want incremental updates.

> whereas normal tab-based completion calls it many hundreds of times (but much faster each time).

Normal TAB completion should call it *once* when you press TAB before the `*Completions*` buffer is shown. If this is not the case there is something wrong. Since it should only be called once, default completion can be a better choice than Vertico if you are working on very slow remote hosts.

**Comment by jdtsmith** [comment]
That's what I also expected: vertico would make more calls to this function.  I'm not sure why it is called so often for plain completion, but each call is _far_ less expensive than in the case of vertico, so Tab-completion is still faster.  

But both vertico and default completion are very fast when starting from a remote buffer, so something is strange here. There is some test code at the thread above if you want to try it yourself.  I will report back if I find anything.

**Comment by jdtsmith** [comment]
In case anyone is following along here, there is indeed a Mac-specific tramp bug causing this slowdown, unrelated to vertico.  Tramp evaluates the standard value of `temporary-file-directory` many hundreds (standard completion) or thousands of times (with vertico and similar auto-updating UI's).  

Unfortunately, on darwin the standard value of this variable contains `(eval (car (get 'temporary-file-directory 'standard-value)) t))`, i.e. a shell is spawned that many times.  If you have a slow to start shell as I do (zsh with some custom stuff), this really adds up.  A quick fix while we await a proper fix in tramp is to set `shell-file-name` to `/bin/bash` or another quickly-starting shell.  This doesn't eliminate all the spurious calls, but at least makes them faster.

**Comment by minad** [comment]
I assume you could also set the `standard-value` property of `temporary-file-directory` once in your init.el to entirely avoid spawning shells?

**Comment by jdtsmith** [comment]
Good idea:

```elisp
  ;; Workaround a tramp-MacOS bug that dramatically slows completion
  (put 'temporary-file-directory 'standard-value
       (list temporary-file-directory))
```

What is strange is that the standard value first checks `(getenv "TMPDIR")`, which is an environment variable which does in fact exist for me.  Yet some (but not all) of the time (i.e. when called by parts of tramp) it yields `nil`, which leads to the "backup plan" of spawning a shell, and major slowness.   I haven't determined if this is a bug, or something tramp is doing on purpose.  But with this above fix, vertico is once again happily chewing through remote directories.
