### ISSUE TITLE
trailing spaces in completing-read-multiple when used with notmuch

### ISSUE THREAD

**Issue by holgerschurig** [minad/vertico#130]
Hi,

I'm using notmuch and vertico. And I noticed that I always get errors when I want to add a tag, e.g. "+trash": The "+" key in there is bound to `notmuch-search-add-tag`. Which, via `notmuch-read-tag-changes` ultimately calls `completing-read-multiple`.
So when I get the vertico-version of this and I use TAB to select the present "+trash" tag followed by RET I get an error message "notmuch-tag: Tag must be of the form ‘+this_tag’ or ‘-that_tag’".

When vertico-mode is off, and I enter "+trash" manually, it works.

I tracked this down to trailing whitespace. In a notmuch search buffer (e.g. the inbox), I can also directly provoke this error by running M-S-: `(notmuch-search-tag (list "+thrash "))`. But when I am doing `(notmuch-search-tag (list "+thrash"))` I won't get it. So it looks like notmuch expects no trailing space, but somehow get's one.

When I call the function that calls `completing-read-multiple` by hand, then I see however trailing spaces:  M-S-: `(notmuch-read-tag-changes '())`, select the +trash entry, TAB, RET and the return value will be `("+trash " "+replied "). No trailing spaces.

This could now be a notmuch error ...

... but when I turn vertico-mode off, and call the same function, I will get tags back a result without the leading space.

On the other side, if I execute the example call of from docstring, `(completing-read-multiple "> " '("alice" "bob" "eve"))`, even with vertico-mode on, I won't get leading spaces ...  weird. So maybe it's notmuch?

Side notes:
- I'm on vertico git hash 81a4b35f8d11dfad56de1727ee9bdd3b4461d07c (that's what Emacs Doom pulled in)
- I'm on notmuch git hash 63413a5563450bdedee4c077f2f998578e75083a (that's what Emacs Doom pulled in)
- see https://github.com/aclements/notmuch/blob/master/emacs/notmuch-tag.el#L313
- i see that the completing-read-multiple without vertico also doesn't react to C-g, so that's as annoying as the vertico-version of it not reacting to C-g ... but that's another story :-)

**Comment by minad** [comment]
Duplicate #119 and https://github.com/minad/consult/issues/410

**Comment by minad** [comment]
See https://yhetil.org/notmuch/86a6k7hd43.fsf@gmail.com/T/#u
