### ISSUE TITLE
Unknown face

### ISSUE THREAD

**Issue by aaronjensen** [minad/vertico#132]
<img width="563" alt="CleanShot 2021-09-22 at 07 24 58@2x" src="https://user-images.githubusercontent.com/8588/134335452-9398bb95-b1d2-4da2-931f-d27c2413d0b2.png">

In some of my vertico completions, the letter after my search term is highlighted differently than the rest of the line and the term. How do I go about figuring out which face that is so I can adjust it, and why is it doing that?

**Comment by minad** [comment]
It is probably the completion-difference face. There are only two faces used by the built-in completion styles. Don't you use orderless?

In order to debug this you can use vertico-buffer for example and inspect the buffer content or add a `(message "%S" ...)` to the display code.

**Comment by aaronjensen** [comment]
Thanks! I'll look into it. I've used modus before and I like it, but I've switched to my own to as I prefer something even more minimal. It is in fact `completion-first-difference`. I appreciate the troubleshooting help.
