### ISSUE TITLE
Auto-select a single candidate

### ISSUE THREAD

**Issue by haji-ali** [minad/vertico#133]
I am switching from selectrum to vertico (I like the minimalism).

The only functionality I am unable to replicate so far is selecting a candidate as soon as it is matched (see https://github.com/raxod502/selectrum/issues/517). It has two features:
1. The input is matched from the beginning. 
2. Unless the input start with a space, a candidate is accepted automatically when it is the only one remaining, i.e., without having to press RET. 

The solution that was suggested in https://github.com/raxod502/selectrum/issues/517 relies on `selectrum-refine-candidates-function` among other functionality as follows

```lisp
(defun my/completing-char (prompt collection)
  (let ((selectrum-refine-candidates-function
         (lambda (input candidates)
           (prescient-filter (concat "^" (regexp-quote input))
                             candidates))))
    (minibuffer-with-setup-hook
        (lambda ()
          (add-hook 'post-command-hook
                    (defun submit-for-single-cand ()
                      (when (and
                             selectrum--refined-candidates
                             (null (cdr selectrum--refined-candidates))
                             (not (string-prefix-p " " selectrum--virtual-input)))
                        (selectrum-select-current-candidate)))
                    nil t))
      (string-trim-left (completing-read prompt collection) " "))))
```

Is this doable in vertico?

**Comment by minad** [comment]
(2) can be solved by the solution given by @clemera in raxod502/selectrum/issues/517 using the hook.

~~~ elisp
(defun submit-for-single-cand ()
  (when (= 1 vertico--total)
    ;; (2) exit if only a single candidate
    (vertico-exit)))
  
(minibuffer-with-setup-hook
    (lambda ()
      ;; (1) adjust completion style to achieve desired matching
      (setq-local completion-styles '(basic))
      (add-hook 'post-command-hook 'submit-for-single-cand nil t))
  (completing-read "Example: " '("abab" "bcbc" "cdcd"))
~~~

The other question (1) of matching at the beginning is too unspecific. Vertico uses completion styles for filtering. Prescient is unsupported. If you are using Orderless as an alternative you can use an Orderless style dispatcher which was also already pointed out by @clemera. In the example above I set the completion style locally to the `basic` completion style, which always matches from the beginning. You can also write your own completion style and install it locally only for the current completion session. See for example https://github.com/minad/vertico#tramp-hostname-completion, where I define the special `basic-remote` completion style. I hope this answers your questions.

**Comment by haji-ali** [comment]
Update: With the above code, on the latest version of vertico and Emacs 28.1 (not sure what broke it) , it seems that `vertico--exhibit` gets called after `submit-for-single-cand` which means that `vertico--total` is not updated. An easy fix is to explicitly call `vertico--exhibit` in `submit-for-single-cand`:
```
(defun submit-for-single-cand ()
  (vertico--exhibit)
  (when (= 1 vertico--total)
    ;; (2) exit if only a single candidate
    (vertico-exit)))
```

which does mean that `vertico--exhibit` is needlessly called twice, but at least it seems to work.

**Comment by kfiz** [comment]
> Update: With the above code, on the latest version of vertico and Emacs 28.1 (not sure what broke it) , it seems that `vertico--exhibit` gets called after `submit-for-single-cand` which means that `vertico--total` is not updated. An easy fix is to explicitly call `vertico--exhibit` in `submit-for-single-cand`:
> 
> ```
> (defun submit-for-single-cand ()
>   (vertico--exhibit)
>   (when (= 1 vertico--total)
>     ;; (2) exit if only a single candidate
>     (vertico-exit)))
> ```
> 
> which does mean that `vertico--exhibit` is needlessly called twice, but at least it seems to work.

@haji-ali Are you still using this? Is there another way of achieving the same behavior in vertico in the meantime? Would love to have something like this in my current setup.

**Comment by kfiz** [comment]
Figured it out. For me the initial version mentioned in https://github.com/minad/vertico/issues/133#issuecomment-925738676 still works.
