### ISSUE TITLE
`completion-category-overrides` does not seem to be respected

### ISSUE THREAD

**Issue by mcfarljm** [minad/vertico#135]
Vertico does not seem to respect values that are specified via `completion-category-overrides`.  Following is minimal config that was tested using a sandboxed version of Emacs 27.2 with vertico as the only installed package:

```el
(require 'vertico)

(vertico-mode)

(setq completion-styles '(substring)
      completion-category-defaults nil
      completion-category-overrides '((file (styles basic))))
```

With this config, I would expect that for file completions, the `basic` style would be used in accordance with the override (and I did verify this when using the built-in completion UI).  However, vertico seems to still use the originally defined completion style, in this case `substring`, as seen in the below example:

![2021-09-28-195514_934x501_scrot](https://user-images.githubusercontent.com/626029/135185569-24d3a3ec-aae8-4ae4-8185-584b0315785c.png)

I'm new to these configuration settings, so it's very possible that I'm missing something here about how they are supposed to behave.  If so, apologies.

**Comment by minad** [comment]
The overrides are respected, but if they don't yield a result, the completion system falls back to the default styles. In order to verify that this is not a Vertico issue, disable vertico-mode and try the default UI.
