### ISSUE TITLE
Equivalent of helm-org-agenda-files-headings

### ISSUE THREAD

**Issue by balaramadurai** [minad/vertico#137]
Hi @minad,
  I hope you are doing well. I saw vertico's features on reddit. I used the package and I find it to be lightweight and fast!

Thanks a lot for this.

One feature request I would like to make is:
When I am working in an org file, I would like to jump to another headline from another org file in the agenda. When I used `helm`, the function that was used was `helm-org-agenda-files-headings` - https://github.com/emacs-helm/helm-org/blob/d67186d3a64e610c03a5f3d583488f018fb032e4/helm-org.el#L436

Is this something that we can do in vertico or associated packages?

Thanks and have a nice day!
Bala

**Comment by minad** [comment]
> I hope you are doing well. I saw vertico's features on reddit. I used
> the package and I find it to be lightweight and fast!
> 
> Thanks a lot for this.

Thanks!

> Is this something that we can do in vertico or associated packages?

Yes, similar functionality is provided by Consult, see
consult-org-agenda. Generally all the extended/advanced functionality is
provided by the Consult and Embark packages. Vertico provides only the
UI. I don't claim that Vertico/Consult/etc provides everything that Helm
does, but the packages should cover most of the commonly used functionality.

I recommend to take a close look at the Vertico, Consult and Embark
READMEs. The READMEs are quite comprehensive.

**Comment by balaramadurai** [comment]
Hi @minad,
  Thank you for your quick response.

Yes, `consult-org-agenda` is exactly what I was looking for. Thanks a bunch.

Yes, I will look into the READMEs of all the packages.

I love the switchb interface as well!

Have a nice day!
Bala
