### ISSUE TITLE
Vertico on MELPA?

### ISSUE THREAD

**Issue by ReneFroger** [minad/vertico#138]
When I try to install Vertico with the package manager, `use-package-manager` complains that he couldn't find the vertico in the receipes repisotiers with the following setup:

```
 (use-package vertico
  :straight t
  :ensure t
  :init
  (vertico-mode)
  )
```

**Comment by minad** [comment]
Vertico is available on GNU ELPA. Straight should be able to pull from ELPA.

**Comment by daviwil** [comment]
@ReneFroger Looks like you're using both `:straight t` and `:ensure t` there, that would cause `use-package` to try and install Vertico using both `straight.el` and `package.el`.  I'd recommend removing the `:ensure t` line if you intend to use `straight.el`

**Comment by ReneFroger** [comment]
@minad Without any luck, ELPA is in my package repository but I still get the same error that the package couldn't be found.

@daviwil your suggestion is appreciated, but however: when remove `:ensure t` and letting `:straight t` line there, I still get the same error after evaluating:

![image](https://user-images.githubusercontent.com/5211845/135761686-e276f746-e81a-4729-bf69-9b1e5b77e7f2.png)

**Comment by daviwil** [comment]
@ReneFroger Try running `M-x straight-pull-recipe-repositories` and try installing Vertico again.  It's possible that your local repository list is out of date

**Comment by minad** [comment]
@ReneFroger Did you solve your issue?

**Comment by ReneFroger** [comment]
@minad not unfortunately.

@daviwil the command there is not available which is strange, I use the `use-package` version 20120207.1926 version and `straight` prerelease (Head-> master) version with an Git hash. I'll look into straight, perhaps it might solve my problem instead of vertico.

![t0XHtgJ](https://user-images.githubusercontent.com/5211845/135821514-893b4ac7-2a13-466f-b47d-9c9ed3c83f48.gif)

**Comment by minad** [comment]
@ReneFroger Maybe @daviwil or the straight maintainers can provide further help. I keep the issue closed here since it is not a Vertico issue but an installation problem.
