### ISSUE TITLE
Is `current-minibuffer-command` the right call for `vertico-repeat`?

### ISSUE THREAD

**Issue by iyefrat** [minad/vertico#140]
I'm currently investigating a `vertico-repeat` bug in Doom (hlissner/doom-emacs#5547). I haven't whittled it down yet to something that can be reproduced in `emacs -Q`, but It has lead me to the following issue: say we define the following function:

```emacs
(defun test-1 (arg)
  "testing"
  (interactive "P")
  (let ((default-directory user-emacs-directory))
    (consult-grep)))
```
run `M-x test-1`, and then hit the `vertico-repeat` keybinding, due to the fact that for emacs 28, Vertico uses `current-minibuffer-command`, instead of having `#foo` inputted to `consult-grep`, instead we get a `M-x #foo` Vertico session.

Edit: Silly me, for this specific issue there is no need to define a new function, you can just do `M-x consult-grep` to get the same result.

**Comment by minad** [comment]
As far as I understand the variable `current-minibuffer-command` is the correct variable to determine the command which opened the minibuffer on Emacs 28. If you figure this out please let me know!

This also affects Embark and Marginalia, where `embark--command` and `marginalia--this-command` are set to `this-command. One should also use `current-minibuffer-command` for those.

**Comment by minad** [comment]
current-minibuffer-command is better than this-command since its value is consistent for multiple prompts:

~~~ elisp
(defun testcmd ()
  (interactive)
  (minibuffer-with-setup-hook
      (lambda ()
        (message "CMD1 %S %S" current-minibuffer-command this-command))
    (read-from-minibuffer "A: "))
  (minibuffer-with-setup-hook
      (lambda ()
        (message "CMD2 %S %S" current-minibuffer-command this-command))
    (read-from-minibuffer "B: ")))
~~~

**Comment by minad** [comment]
I reverted this for now in marginalia and vertico-repeat. cc @oantolin

**Comment by minad** [comment]
1. Run emacs -Q and the following snippet:

~~~ elisp
(defun test-hook ()
  (message "COMMAND %S %S" this-command current-minibuffer-command))
(add-hook 'minibuffer-setup-hook 'test-hook)
~~~

2. Load Consult (use default completion)
3. Run `M-x consult-grep RET` => `COMMAND consult-grep execute-extended-command`???
4. Run `M-s g` (consult-grep) => `COMMAND consult-grep nil`???

It seems the consult async commands somewhere overwrite or mess up `current-minibuffer-command`.
