### ISSUE TITLE
Selected candidates have face property

### ISSUE THREAD

**Issue by Koekelas** [minad/vertico#142]
Rather than explain the issue, I'll demonstrate it. `emacs -Q`:

```emacs-lisp
;; Select foo
(let ((candidates '("foo" "bar" "baz")))
  (completing-read "Prompt: " candidates)
  candidates) ; → ("foo" "bar" "baz")

;; Load vertico and enable vertico-mode

;; Select foo
(let ((candidates '("foo" "bar" "baz")))
  (completing-read "Prompt: " candidates)
  candidates) ; → (#("foo" 0 3 (face nil)) "bar" "baz")
```

Note that the second time the selected candidate has a face property. When using `completing-read-multiple`, all selected candidates have a face property. As the candidate is mutated, it causes problems down the road. Thank you in advance.

- Emacs 27.2
- vertico 0.14 (ELPA)

**Comment by minad** [comment]
Thanks for noticing this issue!

**Comment by Koekelas** [comment]
Perhaps a tad late. I can confirm the issue is fixed. It took a while to find, completing-read was not on my shortlist of suspects. Thank you for the prompt action and for an otherwise excellent package.
