### ISSUE TITLE
Help implementing tab-n-go style completion

### ISSUE THREAD

**Issue by BlueDrink9** [minad/vertico#143]
I would like to use vertico completion with keybinds that allow using tab for both completing the currently selected value, and for selecting the next option.

(I only want to use this for file paths (to match my shell behavior).)

From the [relevant Company issue](https://github.com/company-mode/company-mode/issues/343#issuecomment-168473085) that spawned company-tng:

* tab selects and completes first option but leaves menu open, with all the same options
* Repeated tab selects & completes next, shift tab selects and completes previous
* Any other key (in my case with files, likely to be `/`) moves on and closes the window.

Would this be possible to create currently with vertico? Could you please help guide me to how I might set this up?

**Comment by TimotheeMathieu** [comment]
Thanks for the snippet, it almost works but I believe I found a bug with this snippet.
 
The bug appear if one types something that does not exists , then press tab. And then pressing on any key does nothing even `C-g` do not quit the process, the only solution is the kill and restart emacs.

To reproduce bug: use the following config
```elisp
(straight-use-package '( vertico :files (:defaults "extensions/*")
                         :includes (vertico-flat)))
(vertico-mode)
(vertico-flat-mode)


(defun vertico--tab-exit ()
  (unless (memq this-command '(vertico-tab-previous vertico-tab-next))
    (setq this-command #'ignore)
    (vertico-exit)))

(defun vertico-tab-previous ()
  (interactive)
  (add-hook 'pre-command-hook #'vertico--tab-exit nil 'local)
  (vertico-previous))

(defun vertico-tab-next ()
  (interactive)
  (add-hook 'pre-command-hook #'vertico--tab-exit nil 'local)
  (vertico-next))

(define-key vertico-map [tab] #'vertico-tab-next)
(define-key vertico-map [backtab] #'vertico-tab-previous)
```
Then, use  `M-x aergaertgaerg <TAB>`. Then, it says "Match required" and nothing works anymore.
