### ISSUE TITLE
[FEATURE] vertico-directory-cd like ivy--cd

### ISSUE THREAD

**Issue by strikerlulu** [minad/vertico#154]
Add a new function to change the current directory in minibuffer to `vertico-directory.el`

Ref 
https://github.com/abo-abo/swiper/issues/2744

**Comment by minad** [comment]
I would like to point you to karthik's [consult-dir](https://github.com/karthink/consult-dir), which offers such directory switcher based on Consult. Does this library work for you? But besides that Vertico does not maintain a separate directory state like Ivy.
