### ISSUE TITLE
How do I make vertico-insert add to the history?

### ISSUE THREAD

**Issue by ngharrison** [minad/vertico#155]
I want directories that I've inserted in find-file most recently to show up at the top of the candidate list. They do go to the top when I use `vertico-exit` with that candidate, effectively opening it in a buffer. What would I need to modify to get insertions into the history too?

**Comment by minad** [comment]
> What would I need to modify to get insertions into the history too?

You can add an `:after` advice to `vertico-insert` which adds the `(minibuffer-contents)` via `add-to-history` to the `minibuffer-history-variable`.

Feel free to add your code to the [wiki](https://github.com/minad/vertico/wiki) if you got something working. It sounds like a good idea!

**Comment by ngharrison** [comment]
Thanks for the help! It looks like it's working:
```emacs-lisp
  (defadvice vertico-insert
      (after vertico-insert-add-history activate)
    "Make vertico-insert add to the minibuffer history."
    (add-to-history minibuffer-history-variable (minibuffer-contents)))
```

I'll put it in the wiki with a couple other things when I get the chance :)

**Comment by minad** [comment]
One more small detail - you may want to check for minibuffer-history-var=t.
