### ISSUE TITLE
find-file make selection always start on first candidate instead of top line

### ISSUE THREAD

**Issue by ngharrison** [minad/vertico#156]
When using find-file, I'd like the first candidate beneath the top line where it says "Find file: " to be selected. I'd like this to be true when I open it and when I switch between directories. Is there a way to do this?

**Comment by minad** [comment]
The candidate preselection logic can be found here:

https://github.com/minad/vertico/blob/9479c5d91c0292328fe385e7d6e6877021caad40/vertico.el#L442-L455

You can also hack this with an advice, but I am not sure I would recommend this. The current behavior is reasonable. So why do you want this change in behavior in the first place?

**Comment by ngharrison** [comment]
I'm creating an easier setup to browse directories. With inserted directories in the minibuffer history (#155) and the first candidate automatically being selected, I can zoom up and down the directory tree (especially through folders I've recently visited) with just a couple keys. Maybe there's a simpler way to do this?

A complementary feature is only sorting the folders alphabetically (order wouldn't change) but keeping track of which candidate was last selected at that directory level. It's useful for quickly exploring the contents of directories I've never been in before.

**Comment by ngharrison** [comment]
Here is some code that is accomplishing what I want for the first one, but I am unsure if it will break anything else.
```emacs-lisp
  (defadvice vertico--update-candidates
      (after vertico-choose-first-candidate activate)
    "Pick the first candidate rather than the prompt after updating candidates."
    (if (and (< 0 vertico--index)
             (> 0 vertico--total))
        (setq vertico--index 0))
```

**Comment by minad** [comment]
The code will break certainly things. Maybe it would be better to create a special command/macro which calls find-file and presses down?

Regarding the sorting - this can be customized. If there is an example in the wiki.

**Comment by minad** [comment]
For browsing unknown directories there may also be better tools beyond completion. Dired, ranger, treemacs, bfs, ...

**Comment by ngharrison** [comment]
> Maybe it would be better to create a special command/macro which calls find-file and presses down?

Yeah, I actually made a command to do this, but the "pressing down" didn't work:
```emacs-lisp
  (defun my/vertico-insert-or-exit ()
    "Insert the candidate if it's a directory, otherwise select it and exit."
    (interactive)
    (let ((cand (vertico--candidate)))
      (if (and (>= vertico--index 0)
               (equal (substring cand -1) "/"))
          (progn (vertico-insert)
                 (vertico-down))
        (vertico-exit))))
```
