### ISSUE TITLE
Error in post-command-hook (vertico--exhibit): (wrong-number-of-arguments (2 . 2) 1)

### ISSUE THREAD

**Issue by hmelman** [minad/vertico#157]
I updated everything today and am now getting this error when running commands (e.g., consult-buffer)

    Error in post-command-hook (vertico--exhibit): (wrong-number-of-arguments (2 . 2) 1)

It seems to be related to using [this code](https://github.com/minad/vertico/wiki#customize-highlighting-based-on-completion-category) from the wiki.  If I comment that out from my init, it all works, though I don't see why.

**Comment by minad** [comment]
The arrange candidates function changed (1 argument).

**Comment by minad** [comment]
I updated the wiki.

**Comment by minad** [comment]
Just update to the latest commit.

**Comment by hmelman** [comment]
Ah I see.  It's not on gnu elpa yet, I'll updated when it is.

**Comment by hmelman** [comment]
Consideration for that wiki section, I think using the face `dired-directory` makes more sense than using `font-lock-function-name-face`.  It defaults to inheriting from `font-lock-function-name-face` so many won't see a difference.

**Comment by minad** [comment]
It is a wiki, feel free to edit it if you have improvements. Personally I am not using the code from the wiki.

**Comment by hmelman** [comment]
Done.
