### ISSUE TITLE
Funny sorting

### ISSUE THREAD

**Issue by astoff** [minad/vertico#16]
In my setup with vertico and marginalia see the following candidates for `insert-char`. As you can see, the emoji `BELL` candidate takes place of the BELL control character.

![image](https://user-images.githubusercontent.com/6500902/114912181-fcf4ab80-9e1f-11eb-9c83-504c8ad5ffd3.png)

**Comment by minad** [comment]
Yes, this is a known issue. The `read-char-by-name` completion table is providing the candidates in this funny order. No idea why it does that. You could ask on emacs-devel or report a bug :shrug: 

Vertico disables sorting for more than `vertico-sort-threshold` candidates. This is necessary to keep the UI reasonably fast.

**Comment by astoff** [comment]
All right, good to know it's someone else's issue.
