### ISSUE TITLE
How to disable sorting for specific pre-sorting commands (like recentf)?

### ISSUE THREAD

**Issue by MicahElliott** [minad/vertico#160]
There are some commands whose data are already sorted, and so we don't want vertico to apply any sorting for them.  Examples of such commands are: `projectile-recentf` and `crux-recentf-find-file`. They basically boil down to something like:
```
(completing-read "Choose recent file: " recentf-list nil t)
```

I've been trying to tweak the advice setup recommended here but not having much luck: https://github.com/minad/vertico/wiki#customize-sorting-based-on-completion-category . Partucularly this:
```
(defvar completion-category-sort-function-overrides
  '((file . directories-before-files)) ; but it's not "file" we want, rather certain commands
```

That explains how to change the behavior for any "file" category, but this case seems more specific to the few commands that shouldn't have vertico/orderless sorting. I can set it to ` '((file . identity))` but that's way too broad a stroke.

My orderless (and vanilla vertico) setup works great for most things:
```
(use-package orderless
  :init
  (setq completion-styles '(orderless)
        completion-category-defaults nil
        completion-category-overrides '((file (styles . (partial-completion))))
	orderless-component-separator " +"))
```

But I don't want vertico sorting to be active for any command like recentf that already has its own order. Do you have any suggestion for how to turn off sorting for just these certain commands? Thanks!

**Comment by MicahElliott** [comment]
Seems like another solution would just be to have `consult-recent-file` (which works great) have knowledge of the project. Then there'd be no real reason to use `projectile-recentf`.

**Comment by minad** [comment]
If these commands want to opt out of sorting they should specify display-sort-function/cycle-sort-function as part of the completion metadata. The commands must specify this themselves if they are presorted. The Consult commands do that usually.

If you want to specifically opt out of sorting for certain commands (from the side of Vertico or your user configuration) you can advise `vertico--sort-function` with an `:before-until' advice. See https://github.com/minad/vertico/wiki#customize-sorting-based-on-completion-category.

Generally I don't see almost no reason anymore to use projectile. You can use project.el for basic project support. Also note that consult-grep/ripgrep/find can be configured with a consult-project-root-function which replaces the corresponding projectile grep commands.

I hope this helps! If you have further questions, please let me know.

**Comment by minad** [comment]
> Seems like another solution would just be to have consult-recent-file (which works great) have knowledge of the project. Then there'd be no real reason to use projectile-recentf.

You can reuse the `consult--soure-project-recent-file` from `consult-buffer`:

~~~ elisp
(defvar consult--source-project-recent-file-visible
  `(:hidden nil ,@consult--source-project-recent-file))

(defun consult-project-recent-file ()
  (interactive)
  (consult--multi '(consult--source-project-recent-file-visible)))
~~~

**Comment by MicahElliott** [comment]
Thanks @minad! I'll try to get this working.

> Generally I don't see almost no reason anymore to use projectile. 

I rely on projectile still for `projectile-toggle-between-implementation-and-test`, which is a really convenient way to bounce between files. But I see that [toggle-test](https://github.com/rags/toggle-test) exists and seems to be working well. So I probably can forgo projectile now.
