### ISSUE TITLE
Org-roam-node-find sorted buffer is not sorted well

### ISSUE THREAD

**Issue by DominikMendel** [minad/vertico#161]
When I run org-roam-node-find the buffer displayed appears to me to not be sorted in any way. I would think the shortest result would appear at the top but it does not. Please see attached for what I am referring to. 

![image](https://user-images.githubusercontent.com/11708209/143779333-2da6429b-d7c8-4267-b88d-80778a8b13cf.png)

**Comment by minad** [comment]
Vertico sorts by history position, length and alphabetically by default. You can change this via the configuration variable `vertico-sort-function`. See https://github.com/minad/vertico/blob/26a96253c53c71e82330eb4d82fd0572653ee22a/vertico.el#L83-L91. Note that the default sorting is only used when the completion command does not explicitly opt out of sorting.
