### ISSUE TITLE
header-line with vertico-buffer

### ISSUE THREAD

**Issue by mclearc** [minad/vertico#162]
For those of us who set a header line as our mode-line, using `vertico-buffer` set to the top means the buffer opens with a mode-line, which is undesirable (particularly if you also use which-key, which doesn't show the header-line when opening at the top). Perhaps add `(setq-local header-line-format nil` to the local settings of `vertico-buffer--setup` (this is what I'm currently doing)?

**Comment by minad** [comment]
I suggest you set this variable in your configuration. The variable `header-line-format` is nil by default. It is out of scope of Vertico to reset settings. It could also be that a user sets `header-line-format` intentionally, then it would be harmful if Vertico overwrites the setting.

**Comment by mclearc** [comment]
> It is out of scope of Vertico to reset settings

I'm a bit confused since you're already setting buffer-local settings for the vertico buffer:

```emacs-lisp
(setq-local display-line-numbers nil
                truncate-lines t
                show-trailing-whitespace nil
                buffer-read-only t
                header-line-format nil
                cursor-in-non-selected-windows 'box)
```
So what is the difference for the header-line, etc.?

**Comment by minad** [comment]
I set the ones which make sense for the functionality of `vertico-buffer` (e.g. `truncate-lines`). Maybe some of these settings are unnecessary but this does not mean that we should add more and more of such settings. Anyways, if you apply heavy tweaks to your configuration it is up to you to ensure that all the packages work will under these circumstances. Using the header as mode line is a heavy change.
