### ISSUE TITLE
Expanded vertico documentation?

### ISSUE THREAD

**Issue by ngharrison** [minad/vertico#164]
First off, thanks for the useful package :)

Since this is mainly a "configure it yourself" package, are there any plans to create docs to explain more how it hooks into emacs completion and how to hook into it to add or change things? I know the options are there, I just don't know which ones I need. Reading through the source code hasn't been sufficient to reveal to me its magic.

Just as one specific example to illustrate, I haven't yet discovered how emacs commands (that create a minibuffer) get specific categories into `vertico--metadata`.

Maybe I just don't know native minibuffer completion well enough, but an explanation of the vertico layer and its entry points (and thus the patterns for augmenting it) would be extremely helpful.

**Comment by minad** [comment]
I suggest you read the chapter https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion.html, in particular "Programmed Completion". There it is documented how to specify a completion category. If you find something lacking there please open a bug report in Emacs. From my perspective the documentation is not entirely sufficient, you should also read through the Emacs source, grep for completing-read.

I don't plan to expand the Vertico documentation with general completion documentation. If you have concrete Vertico issues I can address them here. Which specific problem do you want to solve?

Note that Vertico can be configured heavily and modified via extension I would not say that it is a "configure yourself" package, implying that it does not work well ootb. For a new user it is entirely sufficient to configure completion styles and enable vertico-mode.

~~~ elisp
(setq completion-styles '(basic partial-completion orderless))
(vertico-mode 1)
~~~

That's all that is needed for a decent experience.
