### ISSUE TITLE
vertico-buffer: possible to open minibuf over current window instead of over other window?

### ISSUE THREAD

**Issue by zk** [minad/vertico#167]
Hey minad,

The default behavior when vertico-buffer is enabled and `vertico-buffer-display-action` is set to `'(display-buffer-reuse-window)` is for the minibuf to open over the unfocused window, and currently focused completion candidates in the current window. Is there a way to reverse this, where the minibuf is shown in place of the current window?

I spent some time hacking around trying to get this to work, mostly by passing different `display-buffer` action options here:

From https://github.com/minad/vertico/blob/main/extensions/vertico-buffer.el#L96
```
  (let ((temp (generate-new-buffer "*vertico*")))
    (setq vertico-buffer--window (display-buffer temp vertico-buffer-display-action))
    (set-window-buffer vertico-buffer--window (current-buffer))
    (kill-buffer temp))
```

but wasn't successful. I'm an elisp novice so apologies if it's something obvious.

**Comment by minad** [comment]
Yes, it is possible but probably not a good idea as a general setup. You may want to use it for some commands/categories only, see the section https://github.com/minad/vertico#configure-vertico-per-command-or-completion-category. Let me know if this helps or if you need further advice!

**Comment by zk** [comment]
Ah! Very cool. So the issue is getting consult preview to display in the other window. Will dig in over there. 

Thanks so much.

**Comment by salehmu** [comment]
I used `(setq vertico-buffer-display-action '(display-buffer-same-window)`. Just putting it here in case if someone came across this issue while they were searching.
