### ISSUE TITLE
vertico-flat renders an extraneous newline in minibuffer when used with isearch

### ISSUE THREAD

**Issue by gcv** [minad/vertico#170]
Configuration:

```
  (setq vertico-multiform-category-modes
        '((file flat)))
```

Use `find-file`, and then <kbd>C-r</kbd> to start a search. After typing some characters in the search, the minibuffer is resized to two lines in height, but the second line is blank.

Screenshot before:

<img width="639" alt="before" src="https://user-images.githubusercontent.com/10327/147812708-e0968826-2d99-405b-bfb1-d42984271375.png">

Screenshot after:

<img width="640" alt="after" src="https://user-images.githubusercontent.com/10327/147812721-5e5125c9-8a52-44cc-854a-07a2f01ebd9f.png">

The blank line should not be there.

**Comment by minad** [comment]
I don't see this or rather I cannot reproduce it every time. vertico-flat does not perform any kind of resizing itself (in contrast to normal vertico mode), therefore I don't consider this a vertico-flat issue. Which setting do you use for `resize-mini-windows`?

**Comment by minad** [comment]
On the other hand maybe vertico-flat should override resize-mini-windows according to vertico-resize.

**Comment by gcv** [comment]
I have `resize-mini-windows` and `vertico-resize` both set to `grow-only`. I don't see what I might have done to cause an extra line to appear, except that the candidate list is pretty long (ellipsis display occurred in vertico-flat). It renders like it all fits on one line, though.

**Comment by minad** [comment]
Well this sometimes happens. I assume that for a brief moment the line was too long and then it behaves as expected. If you want to prevent this set `resize-mini-windows=nil`.

**Comment by gcv** [comment]
I can reproduce this behavior with both `resize-mini-windows` and `vertico-resize` set to `nil`. It only happens in GUI Emacs, not terminal. Maybe there's something odd with my frames that causes the minibuffer to misreport its maximum available width? I've seen evidence of this before: with marginalia turned on but vertico-mode off, the display gets mangled; this only happens in GUI mode, not terminal. If so, I don't know how to override or fix that.

I use Mitsuharu Yamamoto's Mac port, in case that matters.

**Comment by minad** [comment]
No idea, but this is not a Vertico issue. One would need a minimal reproducible to investigate this further and the behavior may depend on the Emacs version as there have been recent changes to the minibuffer resizing behavior in 28.

**Comment by gcv** [comment]
Fair enough.

PS: Do you ever sleep? 😃

**Comment by minad** [comment]
You can try to set `truncate-lines=t` in a `vertico-flat--display` after advice. Maybe this fixes the issue. If I recall correctly there has been a bad interaction of `resize-mini-windows` and `truncate-lines`.

> PS: Do you ever sleep?

Yes, but I use the Emacs brain interlink :laughing: 

Happy new year! :tada:

**Comment by gcv** [comment]
`truncate-lines` didn't seem to have made a difference. Oh well. Thanks for your help, and a happy new year to you also!
