### ISSUE TITLE
Error when trying to find a file on a drive other than C: in Windows

### ISSUE THREAD

**Issue by dm19** [minad/vertico#172]
With vertico-mode turned off I can open a file on a mapped drive by starting the path with g:, but with vertico-mode on I get an error. Also if I'm visiting a file on a different drive and run find-file, the error occurs immediately before I input an text.

Sorry for the state of the backtrace, but for some reason I can't select the backtrace window while the minibuffer is open with the error, and after I cancel the find-file command the backtrace buffer is empty.

<img width="741" alt="Untitled" src="https://user-images.githubusercontent.com/31514792/148114681-02ad924d-b5ce-4b88-91ab-36d0848cf3a4.png">

**Comment by minad** [comment]
Please try to reproduce the bug without your configuration and with `emacs -Q`. The issue is with high certainty a misconfiguration on your side. This particular bug occurs if you specify an invalid completion style:

~~~ elisp
(setq completion-styles '(invalid-style)
      completion-category-defaults nil
      completion-category-overrides nil)
~~~

**Comment by dm19** [comment]
Ah yep, I had an error in the completion-categories-overrides setting.
