### ISSUE TITLE
vertico-multiform setting stuck after theme change

### ISSUE THREAD

**Issue by gcv** [minad/vertico#173]
Using commit 9b443506210b5f7, I discovered the following truly bizarre behavior: after unobtrusive mode is activated in a command, then the _second_ subsequent command will be stuck in flat mode.

Configuration:

```elisp
(setq vertico-multiform-commands
      '((consult-imenu buffer indexed)
        (execute-extended-command indexed)))

(setq vertico-multiform-categories
      '((file unobtrusive)
        (buffer flat (vertico-cycle . t))
        (consult-grep buffer)))
```

Steps to reproduce:

0. Fresh Emacs session, etc. etc. etc.
1. Hit `M-x` to verify that Vertico runs normally.
2. Hit `C-x C-f`. It should open in unobtrusive mode. Hit `C-g` to dismiss it (no need to toggle anything).
3. Hit `M-x` and run `load-theme`. Pick any simple theme (say, "wheatgrass" or "dichromancy").
4. Now hit `M-x` again. It's in flat mode! And will remain in flat mode until you enter an unobtrusive mode command and cancel out of it.

In addition, if `load-theme` fails (let's say you select a theme that pops up a warning about running Lisp code and decline to load it), the bug does not occur.

**Comment by minad** [comment]
For me it prints on Emacs 28 when I do this:

~~~
Warning (emacs): vertico-multiform must not be toggled from recursive minibuffers Disable showing Disable logging
Warning (emacs): vertico-multiform state is inconsistent Disable showing Disable logging
Warning (emacs): vertico-multiform must not be toggled from recursive minibuffers Disable showing Disable logging
Warning (emacs): vertico-multiform state is inconsistent Disable showing Disable logging
~~~

However I don't see the issue on Emacs 27. I know that there have been problematic changes to the theme loading infrastructure in 28. I've reported bugs before regarding that. It seems that there is another regression in 28. Just to make sure - you only see that with theme loading? You could try to use the multiform code and minimize it and then report an upstream bug, if it is indeed restricted to themes.

**Comment by gcv** [comment]
At first, I ran into a problem with Vertico switching to grid mode after a theme change. It appeared after commit 71e15710f05cf40c469fe71ee9c85fc0771d9bba. That was with vertico-posframe though, and I started hunting for a simpler reproducible case. Found this, and thought it might be related. Now I no longer think so, because this problem already exists in 71e15710f05cf40c469fe71ee9c85fc0771d9bba. I use Emacs 27, so it shouldn’t be theme regressions in 28.

I have recursive minibuffer turned off. Maybe that’s related.

**Comment by minad** [comment]
I don't understand. If you have recursive mb disabled the recipe above does not work. Can you please specify the precise steps?

**Comment by gcv** [comment]
Sorry! Dismiss the `M-x` invocation in step 1 using `C-g`. Every command occurs in a fresh minibuffer. And in step 3, you need to actually switch themes.

If that does not work to reproduce the bug, I’ll put together an Elisp script that works for me in an `emacs -q` session.

**Comment by minad** [comment]
I cannot reproduce the issue.

**Comment by gcv** [comment]
After some debugging with `emacs -Q`, it turned out that the "customize" system stuck the following entries in my `custom.el` file:

```elisp
'(vertico-flat-mode t)
'(vertico-grid-mode t)
'(vertico-mode t)
```

No wonder Vertico went berserk occasionally. After deleting this nonsense, things started working as expected.

Since I definitely didn't tell customize to do this, was there maybe a code path somewhere in Vertico that might have caused these these entries to have been written?

**Comment by minad** [comment]
> Since I definitely didn't tell customize to do this, was there maybe a code path somewhere in Vertico that might have caused these these entries to have been written?

No. I am not sure what causes this but I've observed this issue too with other customization variables if they are modified and you accidentally save in a customize buffer. Then you save more than you wanted to customize.
