### ISSUE TITLE
Broken file completion prompt over tramp

### ISSUE THREAD

**Issue by realcomplex** [minad/vertico#174]
Hey, and thanks for a great package!

I found a strange bug where the file completion prompt is sometimes broken over tramp.
## How to reproduce

1. Run `emacs -Q` and load (e.g. `load-file`) `vertico.el`. Enable by running `M-x vertico-mode`.
2. Navigate to a home directory on some server over ssh: `C-x C-f /ssh:user@host:~ RET`
2. Suppose `/home/user/` only contains the directory `foo` on the server.
3. Find-file again (`C-x C-f`). The candidate `foo/` will be selected in the minibuffer, while the prompt looks like `/ssh:user@host:~/`. Press `TAB` (`vertico-insert`) to insert the candidate.

## Expected behaviour

The current candidate is inserted, and the prompt now reads `/ssh:user@host:~/foo`

## Actual behaviour

When inserting the candidate, a forward-slash gets dropped and the prompt instead becomes `/ssh:user@host:~foo/`. This breaks the completion session.

## Notes

Sometime (for example when typing out `foo` in the find-file prompt), the sole completion candidate become `/foo/` instead of `foo/`. This does insert correctly.

I hope you can also reproduce this; if not, let me know.

**Comment by minad** [comment]
Congratulations, you found an upstream bug. Do you want to report it or should I do it?

~~~
1. emacs -Q
2. C-x f /sudo::~/
3. Open the completion buffer with ?
4. Click on a directory
~~~

You will end up with a path which looks like this:

~~~
/sudo::~dir/
~~~

The underlying issue is that somewhere a wrong completion boundary is reported by the Emacs completion table.

**Comment by realcomplex** [comment]
Ah great! Good job narrowing it down to such an easy example. If you have time, feel free to report it.

**Comment by minad** [comment]
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=53053

**Comment by protesilaos** [comment]
Sorry in advance for the inconsequential remark:

```
2. C-x f /sudo::~/
```

That needs to be `C-x C-f`.

**Comment by minad** [comment]
@protesilaos Ups, thanks!

This reminds me, there was once the community survey with a `C-x C-f` captcha. The question was "how do you open a file?". One could use the same mechanism for the Emacs bug tracker to reject my invalid reports. ;)

**Comment by protesilaos** [comment]
@minad Sounds good.  Haha!
