### ISSUE TITLE
Small README suggestion for C-RET

### ISSUE THREAD

**Issue by hmelman** [minad/vertico#180]
I have a hard time remembering the binding for `vertico-exit-input` and I found the answer hard to find in the README (though searching for "input" would have found it on the second hit).  I suggest the following change, instead of:

> Non-existing candidates can be entered by moving the point to the prompt line

Non-existing candidates (i.e. the input) can be entered with `C-RET` or by moving the point to the prompt line and using `RET`

**Comment by minad** [comment]
I don't want to blow up the feature list too much. Please take a look.

**Comment by minad** [comment]
Just read the manual more thoroughly :shrug:

**Comment by minad** [comment]
But see also https://github.com/minad/vertico/commit/6f939ac2325cd5168e450f6e3fe361189a9093a8.

**Comment by hmelman** [comment]
Though I still think the `=RET.=` should be `=RET=.`
