### ISSUE TITLE
Visually distinguish in unobtrusive mode when the prompt is selected in file completion

### ISSUE THREAD

**Issue by oantolin** [minad/vertico#181]
When using unobstrusive mode for file completion I sometimes press RET or TAB right away and am surprised to see I've chosen the directory! I don't make this mistake when using any of the obtrusive modes because of the highlighting. Could you add this highlighting of the minibuffer contents (when they are selected) to unobtrusive mode too? When an actual candidate is selected no highlighting is needed in unobstrusive mode, since that is the usual situation.

**Comment by minad** [comment]
I use face remapping for that, see https://github.com/minad/vertico/blob/63912afd40a67191bb68dfb42cfb06a4206a0150/extensions/vertico-unobtrusive.el#L53. Unfortunately I find the visual prompt indication obtrusive, I have to think about a better way.

What about this:

* prompt [only match in green]
* prompt {top match}
* prompt (prompt selected)

Alternatively introduce a separate face for the selected candidate and the selected prompt. However I also dislike the background changing all the time in find-file. This applies to all Vertico modes. But for vertical Vertico I find it less disturbing in the greater scheme of disturbance, where everything is disturbed. If you have a good idea please let me know!

**Comment by minad** [comment]
Ah, no I meant `(top match)`, using parentheses instead of brackets and braces.

**Comment by oantolin** [comment]
As for the other modes, maybe just not highlighting anything when the prompt is selected?

**Comment by minad** [comment]
> As for the other modes, maybe just not highlighting anything when the prompt is selected?

No, for those modes I am happy with the status quo. It really does not bother me at all, or I am accustomed to it. It only matters for unobtrusive where I want to reduce the noise as much as possible. See https://github.com/minad/vertico/commit/716b618791268d14a53a4aa13f56bba6ff3fb346.

**Comment by oantolin** [comment]
Oh, I thought you weren't happy because you said "However I also dislike the background changing all the time in find-file."

**Comment by minad** [comment]
Yes, I don't particularly like it. But I would like it much less to have no visual indication at all. Still it may make sense to define two separate faces `vertico-prompt` and `vertico-current`, then one could at least tweak this. But generally I am very hesitant to make changes to vertico.el, in contrast to tweaking some of its extensions.

**Comment by oantolin** [comment]
The parenthesis look nice. It's a little subtle, but probably enough to keep me from screwing up as often. Thanks!

**Comment by minad** [comment]
vertico-subtle was another name that I considered ;)
