### ISSUE TITLE
Improved multiform toggling

### ISSUE THREAD

**Issue by olivertaylor** [minad/vertico#183]
You've included `vertico-multiform--define-display-toggle` for `grid`, `flat`, `reverse`, and `unobtrusive` -- but sometimes I want to fall back to the default Vertico appearance and the cognitive overhead of thinking about which Vertico mode I'm using causes a slight hitch in my brain. So I extracted some code from `vertico-multiform--display-toggle` to create a function which temporarily makes Vertico use the default appearance.

Might (a version of this) this be useful to include in Vertico itself?

``` elisp
  (defun vertico-multiform-reset nil
    "Temporarily disable all vertico multiform modes."
    (interactive)
    (dolist (m '(vertico-unobtrusive-mode vertico-flat-mode
                 vertico-grid-mode vertico-reverse-mode))
      (vertico-multiform--temporary-mode m -1)))
```

**Comment by minad** [comment]
Yes, I've also thought about that. But I am not sure if it the ideal solution either, so I would like to consider alternatives first. Another idea I've had was to remember the original mode of the current command and then modify the toggles such that they toggle back and forth from that mode. `vertico-multiform-grid` would then toggle between grid and the original mode of the current command etc. Alternatively one could toggle back to the last mode. Yet another idea would be to cycle between the modes with a single command and maybe restrict the mosts which are used for cycling by a configuration variable. All of these possible ideas need experimentation. Therefore I don't want to commit right now on adding the proposed reset.

**Comment by olivertaylor** [comment]
I think remembering the original mode of the command is a great idea.

Maybe Vertico's default appearance could simply be one of these multiform modes, call it `vertico-list` or something (in fact, I've renamed my above function to just that).

Seems like cycling would be useful in a limited way. Most of the time you'd probably want to toggle exactly the mode you want, but it might make sense to go from `unobtrusive` → `flat` → `grid` or something.

Another idea is a dispatcher, like a keymap prompt. You press a key and Vertico asks you which display you'd like to use.

Something similar to `other-window-prefix` (like: `vertico-grid-prefix`) is another idea, though probably not a good one.

Any long term plans for multiform to become the default interface to Vertico? A "list" display would make sense as simply one of the multiform possibilities.
