### ISSUE TITLE
Restore/resume previous minibuffer filter contents

### ISSUE THREAD

**Issue by MicahElliott** [minad/vertico#184]
Example case: I call `project-find-file` to filter down to a handful of candidates by typing something a little tediously long: `disbur clj src`. I see _one_ target I want to open, so `C-n` to it, then `RET`. But there are several matching files I want to subsequently preview or open. Now I have to type the whole `disbur clj src` again to re-filter.

It would be nice if I could recall/restore the prior 3-word search filter with some keystroke. I kinda expect `C-p` to do this already, but it instead completes to whatever the last selection _resolved_ to. (FWIW IIRC, `ivy-resume` did this.)

I see that `vertico-insert` calls `delete-minibuffer-contents`. But could it first save that contents to another `vertico--history-something` that could be used for restoring? Any other solution, or maybe I'm missing something?

**Comment by minad** [comment]
> I kinda expect C-p to do this already, but it instead completes to whatever the last selection resolved to.

Yes, the minibuffer history keeps track of the selected candidates. It is not an input history.

> (FWIW IIRC, ivy-resume did this.)

There is already `vertico-repeat`. Take a look at the Vertico extensions. See also #182 for a discussion on how `vertico-repeat` can be improved.

**Comment by salutis** [comment]
With live previews, one can also `C-x o` to the other window to look around and then `C-x o` back to Vertico to check other candidates.
