### ISSUE TITLE
Untrimmed completions mess up ability to move complete completions to front

### ISSUE THREAD

**Issue by ahyatt** [minad/vertico#185]
This happens with `org-roam`, which for some reason has untrimmed completions (at least in my configuration).  So in org-roam, with vertico, exact matches are not selected right now.

The following patch fixes this issue:
```
diff --git a/vertico.el b/vertico.el
index 5d0fdb3..c2343c9 100644
--- a/vertico.el
+++ b/vertico.el
@@ -255,9 +255,13 @@ The function is configured by BY, BSIZE, BINDEX, BPRED and PRED."
                    (list cand "" suffix)))
       (cl-loop for cand in cands collect (list cand "" "")))))
 
+(defun vertico--string-eq-with-trim (a b)
+  "Whether A and B is equal, with both strings trimmed."
+  (string= (string-trim a) (string-trim b)))
+
 (defun vertico--move-to-front (elem list)
   "Move ELEM to front of LIST."
-  (if-let (found (member elem list))
+  (if-let (found (cl-member elem list :test #'vertico--string-eq-with-trim))
       (let ((head (list (car found))))
         (nconc head (delq (setcar found nil) list)))
     list))
```

**Comment by minad** [comment]
An exact match is an exact match. If the candidate contains spaces and the input does not contain spaces, the candidate is not moved. This works as expected. There is neither a bug here nor in org-roam.

**Comment by ahyatt** [comment]
I think it's fair to say this isn't a problem here, but it really is a problem in org-roam, because there's a bunch of whitespace added at the end for nodes that have no tags.  For nodes that have tags, the whitespace is necessary.  I'll follow up with org-roam, thanks for looking at this.

**Comment by minad** [comment]
I don't think it is a problem in org-roam either. It "breaks" this particular functionality of typing the exact candidate, but this is a fair price to pay for the ability of filtering by tag. If you strip the candidates without tag in org-roam, then these can be typed exactly, but as soon as you add a tag, this is lost again, which introduces an inconsistency. Therefore org-roam should just keep things as they are. As I mentioned, with Orderless you can usually narrow down quickly to the correct candidate. The feature of Vertico which moves the top candidate is more relevant for M-x etc where you may have candidates which are substrings of others.

**Comment by ahyatt** [comment]
Yes, the tradeoff of filtering tag vs exact completion is as you describe.  But I find stripping whitespace is useful for when there isn't a tag.  If there is a tag, you can filter on the tag.  If there isn't a tag, you can find exactly.  Otherwise, I find that, the way I use roam, there's always competition for popular concepts: "foo", "problems with foo", "foo is different than bar", "foo is hungry", and pretty soon "foo" itself is off the page of completions for input "foo".  The only real way around that is to sort by history and just understand that you'll have to patiently scroll through completions to get what you want, and then if you use it enough it will be good most of the time.  But then that breaks the otherwise useful org roam default sorting by file mtime.
