### ISSUE TITLE
Feature suggestion: input at bottom of completion lists

### ISSUE THREAD

**Issue by jaor** [minad/vertico#186]
As discussed in https://gitlab.com/protesilaos/mct/issues/16, it'd be
relatively easy to provide an option in vertico to mimic mct's
completion layout, namely, a mode where the minibuffer input sits at
the bottom but the first candidate still appears at the top.

This is currently almost trivial to attain at the user-configuration
level, e.g.:

``` emacs-lisp

(defun vertico--display-candidates-top (lines)
  (move-overlay vertico--candidates-ov (point-min) (point-min))
  (overlay-put vertico--candidates-ov 'after-string (apply #'concat lines))
  (vertico--resize-window (length lines)))

(advice-add 'vertico--display-candidates :override #'vertico--display-candidates-top)
```

so perhaps a snippet in the wiki would be enough.  Another idea would
be a tiny extension, or including the option in `vertico-reverse`
(but probably "reverse" conveys too different a meaning).

**Comment by minad** [comment]
I added this code to the wiki for now: https://github.com/minad/vertico/wiki#input-at-bottom-of-completion-list. I think you don't use this code currently? It is also not a commonly requested feature. Btw @jaor I saw that consult-spotify landed in your [attic](https://codeberg.org/jao/elibs/src/branch/main/attic/misc.org#headline-39). Is consult-spotify still maintained?
