### ISSUE TITLE
Messages from command predicates error shown during `execute-extended-command`

### ISSUE THREAD

**Issue by ahyatt** [minad/vertico#187]
How to reproduce:

1. Load and turn on `vertico`.
2. `(setq read-extended-command-predicate #'command-completion-default-include-p)`
3. `(require 'tramp)`
4. `(switch-to-buffer "*Empty*")`
5. M-x 

You should see an error message about `read-extended-command-predicate: tramp-setup-debug-buffer: Args out of range: #<buffer *Empty*>, 1, 10`.  If you look at `tramp-debug-buffer-command-completion-p`, you'll see it's definitely going to break on buffers less than 10 characters, but that should be OK.

If you turn off vertico, completion works, basically because the error is caught quickly by `read-extended-command`.  Something in Vertico between Vertico and the `read-extended-command` is causing this error to show.

**Comment by minad** [comment]
>  If you look at tramp-debug-buffer-command-completion-p, you'll see it's definitely going to break on buffers less than 10 characters, but that should be OK.

No, that's not okay. The predicate must not throw an error. This bug should be fixed in Tramp. Please report this upstream.
