### ISSUE TITLE
Universal argument for vertico-directory-delete-word

### ISSUE THREAD

**Issue by abcdw** [minad/vertico#188]
Hi @minad!
 
Have you considered having a universal argument for `vertico-directory-delete-word` and thus `vertico-directory-up` to make their behavior closer to `backward-kill-word`?

It also will make it easier to go up N directories by using prefix argument.

If it sounds good, I can prepare a patch.

**Comment by minad** [comment]
> If it sounds good, I can prepare a patch.

Sounds good!

**Comment by abcdw** [comment]
From 6fe682aba4947bad1ce4a55e6745f44dd6da3f71 Mon Sep 17 00:00:00 2001
From: Andrew Tropin ***@***.***>
Date: Fri, 21 Jan 2022 15:49:48 +0300
Subject: [PATCH] vertico-directory: Add prefix arguments to delete char and
 word fns.

---
 extensions/vertico-directory.el | 22 +++++++++++++---------
 1 file changed, 13 insertions(+), 9 deletions(-)

diff --git a/extensions/vertico-directory.el b/extensions/vertico-directory.el
index 5931657..dad97f0 100644
--- a/extensions/vertico-directory.el
+++ b/extensions/vertico-directory.el
@@ -82,19 +82,23 @@
         t))))
 
 ;;;###autoload
-(defun vertico-directory-delete-char ()
-  "Delete directory or char before point."
-  (interactive)
-  (unless (vertico-directory-up)
+(defun vertico-directory-delete-char (arg)
+  "Delete directory or char before point.  With argument ARG, do
+this that many times."
+  (interactive "p")
+  (if (vertico-directory-up)
+      (dotimes (i (1- arg)) (vertico-directory-up))
     (call-interactively #'backward-delete-char)))
 
 ;;;###autoload
-(defun vertico-directory-delete-word ()
-  "Delete directory or word before point."
-  (interactive)
-  (unless (vertico-directory-up)
+(defun vertico-directory-delete-word (arg)
+  "Delete directory or word before point.  With argument ARG, do
+this that many times."
+  (interactive "p")
+  (if (vertico-directory-up)
+      (dotimes (i (1- arg)) (vertico-directory-up))
     (let ((pt (point)))
-      (forward-word -1)
+      (forward-word (- arg))
       (delete-region pt (point)))))
 
 ;;;###autoload
-- 
2.34.0

**Comment by minad** [comment]
@abcdw Thank you. Can you please change it such that `vertico-directory-up` also takes a prefix argument?

**Comment by abcdw** [comment]
On 2022-01-21 05:01, Daniel Mendler wrote:

> @abcdw Thank you. Can you please change it such that
> `vertico-directory-up` also takes a prefix argument?

Yep, attaching patch as a file.  Probably, not the best implementation
possible, let me know if I can improve it.

**Comment by abcdw** [comment]
From 2ec571ca724bd39440d6dd51ac27e9d647d30903 Mon Sep 17 00:00:00 2001
From: Andrew Tropin ***@***.***>
Date: Fri, 21 Jan 2022 15:49:48 +0300
Subject: [PATCH v2] vertico-directory: Add prefix arguments to delete char and
 word fns.

---
 extensions/vertico-directory.el | 48 ++++++++++++++++++---------------
 1 file changed, 27 insertions(+), 21 deletions(-)

diff --git a/extensions/vertico-directory.el b/extensions/vertico-directory.el
index 5931657..c4b17ae 100644
--- a/extensions/vertico-directory.el
+++ b/extensions/vertico-directory.el
@@ -65,36 +65,42 @@
     (vertico-exit)))
 
 ;;;###autoload
-(defun vertico-directory-up ()
-  "Delete directory before point."
-  (interactive)
+(defun vertico-directory-up (arg)
+  "Delete directory before point.  With argument ARG, do this that
+many times."
+  (interactive "p")
   (when (and (> (point) (minibuffer-prompt-end))
              (eq (char-before) ?/)
              (vertico-directory--completing-file-p))
-    (let ((path (buffer-substring (minibuffer-prompt-end) (point))))
-      (when (string-match-p "\\`~[^/]*/\\'" path)
-        (delete-minibuffer-contents)
-        (insert (expand-file-name path))))
-    (save-excursion
-      (goto-char (1- (point)))
-      (when (search-backward "/" (minibuffer-prompt-end) t)
-        (delete-region (1+ (point)) (point-max))
-        t))))
+    (let ((found (save-excursion
+                   (search-backward "/" (minibuffer-prompt-end) t))))
+      (dotimes (i arg)
+        (let ((path (buffer-substring (minibuffer-prompt-end) (point))))
+          (when (string-match-p "\\`~[^/]*/\\'" path)
+            (delete-minibuffer-contents)
+            (insert (expand-file-name path))))
+        (save-excursion
+          (goto-char (1- (point)))
+          (when (search-backward "/" (minibuffer-prompt-end) t)
+            (delete-region (1+ (point)) (point-max)))))
+      found)))
 
 ;;;###autoload
-(defun vertico-directory-delete-char ()
-  "Delete directory or char before point."
-  (interactive)
-  (unless (vertico-directory-up)
+(defun vertico-directory-delete-char (arg)
+  "Delete directory or char before point.  With argument ARG, do
+this that many times."
+  (interactive "p")
+  (unless (vertico-directory-up arg)
     (call-interactively #'backward-delete-char)))
 
 ;;;###autoload
-(defun vertico-directory-delete-word ()
-  "Delete directory or word before point."
-  (interactive)
-  (unless (vertico-directory-up)
+(defun vertico-directory-delete-word (arg)
+  "Delete directory or word before point.  With argument ARG, do
+this that many times."
+  (interactive "p")
+  (unless (vertico-directory-up arg)
     (let ((pt (point)))
-      (forward-word -1)
+      (forward-word (- arg))
       (delete-region pt (point)))))
 
 ;;;###autoload
-- 
2.34.0

**Comment by minad** [comment]
Okay thanks! Do you have the FSF copyright assignment?

**Comment by abcdw** [comment]
On 2022-01-21 05:38, Daniel Mendler wrote:

> Okay thanks! Do you have the FSF copyright assignment?

No I don't.

I thought about signing it, but didn't yet.

I hope this patch is small enough and should be ok to use it without
assignment.

Anyway, added a task about FSF assignment to my personal backlog, hope
to start this process next week.

-- 
Best regards,
Andrew Tropin

**Comment by minad** [comment]
> I hope this patch is small enough and should be ok to use it without
> assignment.

Unfortunately not. The patch is pretty small and almost below the limit
of 15 lines, but if you want to get the assignment I suggest we wait for
that.

See
https://protesilaos.com/emacs/modus-themes#h:111773e2-f26f-4b68-8c4f-9794ca6b9633
for a short description of the process. Usually you get a response from
the FSF quickly if there are no blockers from your side.

**Comment by abcdw** [comment]
On 2022-01-21 06:57, Daniel Mendler wrote:

>> I hope this patch is small enough and should be ok to use it without
>> assignment.
>
> Unfortunately not. The patch is pretty small and almost below the limit
> of 15 lines, but if you want to get the assignment I suggest we wait for
> that.
>
> See
> https://protesilaos.com/emacs/modus-themes#h:111773e2-f26f-4b68-8c4f-9794ca6b9633
> for a short description of the process. Usually you get a response from
> the FSF quickly if there are no blockers from your side.

Ok, sent an email with all necessary information to assign at gnu dot
org.  Will let you know, when the process will be completed.

-- 
Best regards,
Andrew Tropin

**Comment by minad** [comment]
@abcdw Hey Andrew, any news regarding the assignment?

**Comment by abcdw** [comment]
On 2022-02-07 08:08, Daniel Mendler wrote:

> @abcdw Hey Andrew, any news regarding the

I got a countersigned assignment, yay! :)

-- 
Best regards,
Andrew Tropin

**Comment by minad** [comment]
Great! Merged with slight changes. Please give it a try.

**Comment by abcdw** [comment]
For people intrested in my use case for this feature. I define a `rde-vertico-kill-region-dwim` and bind it in `vertico-map`, which works as `kill-region` in case there is an active mark, but goes up directory if the mark is not active and the point placed after `/` and as delete word in other cases.

It allows quickly go up three directories `C-3 C-w`, but preserving the ability to kill the region containing 3 words `C-SPC C-3 M-b C-w`.

https://git.sr.ht/~abcdw/rde/tree/c5f3671d2e45d76d0318745762c56753a334c600/item/rde/features/emacs.scm#L1541-1550

P.S. The docstring is a little missleading, but the commit with better docstring isn't pushed yet.
