### ISSUE TITLE
Zoom in/out completion list

### ISSUE THREAD

**Issue by abcdw** [minad/vertico#189]
I would like to share one more workflow idea.

Sometimes I want to make completion candidates to temporary occupy the whole frame (to see more candidates or have longer lines to fit annotations and other stuff).

There is a demonstration:

https://user-images.githubusercontent.com/1218615/150669211-a8b0e75a-1c08-47e2-b1e6-0ab9f85b1706.mp4

The idea is similiar to @protesilaos' monocle minor mode, but for vertico.

There is a little hacky implementation:
```emacs-lisp
(defvar rde--vertico-monocle-previous-window-configuration nil
  "Window configuration for restoring on vertico monocle exit.")

(defun rde-vertico-toggle-monocle ()
  "Zoom in/out completion list."
  (interactive)
  (require 'vertico-buffer)
  (if (and rde--vertico-monocle-previous-window-configuration
           vertico-buffer--window)
      (if rde--vertico-monocle-previous-window-configuration
	  (let ((cur-buffer (current-buffer)))
            (set-window-configuration
             rde--vertico-monocle-previous-window-configuration)
	    (setq rde--vertico-monocle-previous-window-configuration nil)
            (switch-to-buffer cur-buffer)))
    (unless vertico-buffer--window
      (vertico-buffer--setup))
    (setq rde--vertico-monocle-previous-window-configuration
          (current-window-configuration))
    (with-selected-window vertico-buffer--window
      (delete-other-windows))))

(define-key vertico-map (kbd "s-f") 'rde-vertico-toggle-monocle)
```

However, there are a few issues with it:
- Live preview is not disabled, but ideally it would be nice to do it. (Probably need to rely on consult functionality here).
- Leaving monocle mode doesn't return candidates list to minibuffer. (It's expected, but would be more intuitive to return back to minibuffer if it was used originally).
- Sometimes the list of candidates has a few empty lines at the end of the buffer.

**Comment by minad** [comment]
Nice idea! I will try it when I find time!

**Comment by protesilaos** [comment]
On 2022-01-22, 23:51 -0800, Andrew Tropin ***@***.***> wrote:

> There is a demonstration:
>
> https://user-images.githubusercontent.com/1218615/150669211-a8b0e75a-1c08-47e2-b1e6-0ab9f85b1706.mp4

Looks cool!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by minad** [comment]
I just wanted to give your monocle a try. Unfortunately it doesn't work anymore since the `vertico-buffer--window` variable is gone. Currently `vertico-buffer` cannot be toggled temporarily with `vertico-multiform` due to some technicalities, in contrast to `vertico-unobtrusive/flat/grid`. So if we add a `vertico-multiform-buffer` toggle function it would be almost like the monocle you have in mind? It only requires appropriate settings of the display action to cover the entire frame?

Regarding the preview, maybe I could add some check to Consult which ensures that preview is disabled if the original window is not visible anymore.

**Comment by abcdw** [comment]
On 2022-02-07 13:23, Daniel Mendler wrote:

> I just wanted to give your monocle a try. Unfortunately it doesn't
> work anymore since the `vertico-buffer--window` variable is
> gone. Currently `vertico-buffer` cannot be toggled temporarily with
> `vertico-multiform` due to some technicalities, in contrast to
> `vertico-unobtrusive/flat/grid`. So if we add a
> `vertico-multiform-buffer` toggle function it would be almost like the
> monocle you have in mind? It only requires appropriate settings of the
> display action to cover the entire frame?

Yep, I think it will work perfectly!  Was missing this function :)

> Regarding the preview, maybe I could add some check to Consult which
> ensures that preview is disabled if the original window is not visible
> anymore.

Would be really nice to have!  The same thing happened to me, when I was
experimenting with mct and different completion buffer layouts.  I think
disabling preview automatically in cases, when original window isn't
visible would be super cool!

-- 
Best regards,
Andrew Tropin

**Comment by workcomplete** [comment]
Hi just wondering if there is a working implementation of vertico-monocle? would be very nice to have!

**Comment by minad** [comment]
@workcomplete No, as far as I know this feature does not exist yet. The difficulty is to make vertico-buffer-mode toggeable during the current minibuffer session, which it is not yet, unlike other modes like vertico-flat-mode or vertico-grid-mode.

**Comment by minad** [comment]
I close this issue due to inactivity. Feel free to contribute a PR which adds this feature.

**Comment by minad** [comment]
With the addition of `vertico-multiform-buffer`, we can easily implement `vertico-monocle`:

~~~ elisp
(defun vertico-monocle ()
  (interactive)
  (let ((vertico-buffer-display-action '(display-buffer-full-frame)))
    (vertico-multiform-buffer)))

(keymap-set vertico-map "M-M" #'vertico-monocle)
~~~

**Comment by abcdw** [comment]
On 2023-12-26 23:34, Daniel Mendler wrote:

> With the addition of `vertico-multiform-buffer`, we can easily implement `vertico-monocle`:
>
> ~~~ elisp
> (defun vertico-monocle ()
>   (interactive)
>   (let ((vertico-buffer-display-action '(display-buffer-full-frame)))
>     (vertico-multiform-buffer)))
>
> (keymap-set vertico-map "M-M" #'vertico-monocle)
> ~~~


Thank you!  I think we now can build upon that.

A few things I noticed:

1. vertico-multiform-buffer doesn't toggle minibuffer back if called
again.
M-x M-S-: (vertico-multiform-buffer) RET M-S-: (vertico-multiform-buffer) RET

2. If during vertico-monocle I do M-x C-g, previously full-frame window
shrinks to half of the frame.

M-x M-S-: (vertico-multiform-monocle) RET M-x C-g

-- 
Best regards,
Andrew Tropin

**Comment by minad** [comment]
Thanks for testing. I cannot reproduce the first issue. Toggling definitely works, pressing M-B twice will toggle between buffer and minibuffer. I can reproduce the second issue. The problem here is that vertico-multiform-mode disables vertico-buffer-mode when entering the nested completion session for M-x. After quitting from M-x, vertico-buffer-mode is reenable, but this time with the default display action. The fix is rather simple:

~~~ elisp
(defun vertico-multiform-monocle ()
  (interactive)
  (setq-local vertico-buffer-display-action '(display-buffer-full-frame))
  (vertico-multiform-buffer))

(keymap-set vertico-multiform-map "M-M" #'vertico-multiform-monocle)
~~~

**Comment by abcdw** [comment]
On 2023-12-27 00:25, Daniel Mendler wrote:

> Thanks for testing. I cannot reproduce the first issue. Toggling definitely works, pressing M-B twice will toggle between buffer and minibuffer. I can reproduce the second issue. The problem here is that vertico-multiform-mode disables vertico-buffer-mode when entering the nested completion session for M-x. After quitting from M-x, vertico-buffer-mode is reenable, but this time with the default display action. The fix is rather simple:
>
> ~~~ elisp
> (defun vertico-multiform-monocle ()
>   (interactive)
>   (setq-local vertico-buffer-display-action '(display-buffer-full-frame))
>   (vertico-multiform-buffer))
>
> (keymap-set vertico-multiform-map "M-M" #'vertico-multiform-monocle)
> ~~~

Thank you very much, when I get a couple spare hours, I'll package a
fresh vertico and will re-try again.  Good job!  Thank you for your
careful and high quality work, it's always a pleasure to work with your
software.

-- 
Best regards,
Andrew Tropin
