### ISSUE TITLE
Bottom prompt input

### ISSUE THREAD

**Issue by grolongo** [minad/vertico#19]
Hi, I'm testing vertico nowadays and remembered a thread in Selectrum issues you participated in regarding bottom prompt input: https://github.com/raxod502/selectrum/issues/525

`(setq selectrum-display-action '(display-buffer-at-bottom))` was a partial solution since it offered the prompt at the bottom line but the display of the candidates wasn't up side down (the top matches are not right above the input).

Do you plan to implement this in vertico as an option or by default by any chance?

**Comment by minad** [comment]
You can use this advice https://github.com/minad/vertico/blob/buffer-display/buffer.el to get a display action as in Selectrum which I wrote as a prototype. But it is not upside down.

----

In case you really want it upside down you can do this by using `nreverse`. And then you also have to remap the up down keys. You can try it out. I didn't really like it tbh.

~~~ elisp
(defun vertico--display-in-buffer (candidates)
  (let ((buffer (get-buffer-create (format " *vertico-%s*" (- (recursion-depth) 1)))))
    (with-current-buffer buffer
      (setq-local display-line-numbers nil
                  show-trailing-whitespace nil
                  inhibit-modification-hooks t)
      (erase-buffer)
      (insert (string-join (nreverse candidates))) ;; NOTE: Reverse the candidates!
      (goto-char (point-min)))
    (display-buffer buffer
                    `(display-buffer-in-side-window
                      (window-parameters (mode-line-format . none))
                      (window-height . ,vertico-count)
                      (side . bottom)
                      (slot . -1)))))

(advice-add #'vertico--display-candidates
            :override #'vertico--display-in-buffer)

(define-key vertico-map [up] #'vertico-next)
(define-key vertico-map [down] #'vertico-previous)
~~~

**Comment by grolongo** [comment]
Hey that works fine thanks!

Is there a way to automatically resize the buffer so there is no gap between the results and prompt? Maybe I'm wrong but is it because for the reverse display we're using a custom buffer while by default we're using the minibuffer, therefore `(setq resize-mini-windows t)` doesn't apply anymore?

![verticotest](https://user-images.githubusercontent.com/34292770/115536517-2b4c0e00-a29a-11eb-919c-2583d5eebf00.jpg)

**Comment by minad** [comment]
> Is there a way to automatically resize the buffer so there is no gap between the results and prompt? Maybe I'm wrong but is it because for the reverse display we're using a custom buffer while by default we're using the minibuffer, therefore (setq resize-mini-windows t) doesn't apply anymore?

Yes, you may want to add your own resizing code to the function `vertico--display-in-buffer`.

I close this issue since I don't have an intention to add this functionality to the package itself as of now.

**Comment by milkypostman** [comment]
Follow up here.

I redid this and added some spacing. @grolongo 

```lisp
(use-package vertico
  :ensure
  :bind (:map vertico-map
	      ("C-n" . vertico-previous)
	      ("C-p" . vertico-next)
	      ([up] . vertico-next)
	      ([down] . vertico-previous))

  :init
  (defun vertico--display-in-buffer (candidates)
    (let ((buffer (get-buffer-create (format " *vertico-%s*" (- (recursion-depth) 1))))
	  (fill-rows (max 0 (- vertico-count (length candidates)))))
      (with-current-buffer buffer
	(setq-local display-line-numbers nil
		    show-trailing-whitespace nil
		    inhibit-modification-hooks t)
	(erase-buffer)
	(insert (apply #'concat (make-list fill-rows "\n")))
	(insert (string-join (nreverse candidates))) ;; NOTE: Reverse the candidates!
	(goto-char (point-min)))
      (display-buffer buffer
		      `(display-buffer-in-side-window
			(window-parameters (mode-line-format . none))
			(window-height . ,vertico-count)
			(side . bottom)
			(slot . -1)))))

  (advice-add #'vertico--display-candidates
	      :override #'vertico--display-in-buffer))
```

This actually looks really nice. 

@minad is there a way to customize the indentation besides modifying this function more? also, I'd like to change the formatting of the currently selected item (maybe prefix with `>`). But so far, it's working well.

**Comment by minad** [comment]
There is currently no possibility to modify the formatting of the candidates. You could do it in this display function or advise vertico--format-candidates.

I could split vertico--format-candidates and introduce some helper functions which could be advised additionally to affect the formatting of individual candidates.

**Comment by minad** [comment]
@milkypostman I split up `vertico--format-candidates` a little bit, you can do this now:

~~~ elisp
(advice-add #'vertico--format-candidate :around
            (lambda (orig cand prefix suffix index)
              (setq cand (funcall orig cand prefix suffix index))
              (concat
               (if (= vertico--index index)
                   (propertize "> " 'face 'vertico-current)
                 "  ")
               cand)))
~~~

Note that using advices for these individual adjustments can be a bit brittle. I am not making guarantees that these internals won't change at some point. But Vertico is simple enough, such that it should be no big deal to follow potential changes.

**Comment by milkypostman** [comment]
yeah advice is whatever. this is pretty great though thank you!

**Comment by grolongo** [comment]
This is great! Thank you for this.

Something I noticed, how could I disable the cursor in the candidates buffer? It doesn't show up by default (without using the function). You can see what I'm talking about in the screenshot I posted above (cursor is top left over `vertico-exit-input`).

**Comment by minad** [comment]
> Something I noticed, how could I disable the cursor in the candidates buffer? It doesn't show up by default (without using the function). You can see what I'm talking about in the screenshot I posted above (cursor is top left over vertico-exit-input).

You can adjust `cursor-in-non-selected-window`. Another alternative one may want to consider is to use an overlay instead of an additional buffer. I will try this, maybe this is even easier than the solution given here.

**Comment by grolongo** [comment]
I figured it out by adding `cursor-in-non-selected-windows` to `nil` in the `setq-local` list of variables.

Maybe you have this set globally so you don't have to do this.

**Comment by minad** [comment]
See https://github.com/minad/vertico/wiki#show-candidates-in-an-overlay-above-the-prompt for a solution which uses the overlay instead of a separate buffer. You may prefer this since it is more lightweight and since it does not introduce the cursor issue.

**Comment by milkypostman** [comment]
wow this is amazing.

To put them at the bottom of the overly.

```
  (defun vertico--display-above-prompt (lines)
      (move-overlay vertico--candidates-ov (point-min) (point-min))
      (overlay-put vertico--candidates-ov 'before-string
		   (concat (make-string (- vertico-count (length lines)) ?\n)
			   (apply #'concat (nreverse lines))))
      (vertico--resize-window (length lines)))
```

**Comment by grolongo** [comment]
@minad maybe I'm wrong but shouldn't the new variable `vertico-resize` you introduced work for both @milkypostman's `vertico--display-in-buffer` function and your overlay solution too?

Or does `vertico-resize` only act on the `*Completions*` buffer when used with vertico like `resize-mini-windows` do by default?

**Comment by minad** [comment]
`vertico-resize` works only for the minibuffer/overlay. `vertico--display-in-buffer` is not taking the variable into account, but you can add this of course.

**Comment by milkypostman** [comment]
@grolongo to clarify the previous comments, the height of the buffer generated by my code is specified in the call to `display-buffer` where the line used is `(window-height . ,vertico-count)`.

**Comment by minad** [comment]
I decided to add Vertico extensions to the repository: These are small packages, which extend Vertico but which are not part of the opinionated main package. I won't use these extensions but I feel more comfortable maintaining them as part of the repository in contrast to the wiki.

See https://github.com/minad/vertico/blob/main/extensions/vertico-reverse.el

**Comment by milkypostman** [comment]
very cool. thanks for that!

I agree it's probably better to have some story about this. I think the extensions are nice.

**Comment by minad** [comment]
Yes, I think extensions fit the spirit very well here, since these allow you to plug together your own completion system and the core is kept simple. One of the main ideas of Vertico/Consult/Marginalia/Orderless/Embark is that you have these pluggable components.

**Comment by grolongo** [comment]
Compartmentalized and organized, that's very good.
Also great for discoverability, I didn't know about the other options.
Is the ido extension for `vertico` similar to `fido-mode` for `icomplete`?

**Comment by minad** [comment]
@grolongo No, `vertico-directory` (as it is now called) only provides better directory navigation commands. But there are also other extensions which give you a more ido-like look (e.g. `vertico-flat`).
