### ISSUE TITLE
Adjusting the font size of prefix of candidates in find-file

### ISSUE THREAD

**Issue by daehwannam** [minad/vertico#190]
The font size of prefix of candidates in find-file is very small in my emacs.
I tried adjusting faces related to vertico, but couldn't change the font size.
Any help or advice? Thanks.

![find-file-candidate-prefix](https://user-images.githubusercontent.com/35688291/150707591-948ec021-1241-4a4f-b8ad-c93efe8c5d1e.png)

**Comment by minad** [comment]
I have no idea what causes this. Closing since it is not a Vertico issue, but a configuration issue.

**Comment by daehwannam** [comment]
I found that the font size can be configured with `completions-common-part`.
e.g.
```(set-face-attribute 'completions-common-part nil :height 145)```

**Comment by minad** [comment]
But I wonder why you have to adjust these faces individually, usually one remaps just the default face to scale all the faces.

**Comment by daehwannam** [comment]
I've just tried changing fonts with `(set-face-attribute 'default nil :height 145)` with option `--no-init', then the completion font size was also changed as you expected.

However, adjusting the default face doesn't affect the completion font size once my emacs config is loaded.

I guess some code of my emacs config affects the font sizes by `default` and `completions-common-part`.

**Comment by daehwannam** [comment]
I found that `monoj-dark` theme triggers the problem.

The initial value of `completions-common-part` is `'unspecified` when no config code is loaded.
However, when `(load-theme manoj-dark)` is evaluted, it changes `height` attribute of `completions-common-part` to a fixed value, regardless of the current value of `(face-attribute 'default :height)`.

For the same scale with `default`, I could set `completions-common-part` as `unspecified` again:
```(set-face-attribute 'completions-common-part nil :height 'unspecified)```
