### ISSUE TITLE
Select First Candidate for `find-file`

### ISSUE THREAD

**Issue by xav-ie** [minad/vertico#192]
When I type `C-x C-f` it calls the find-file command and invokes Vertico. 

However, the first file in the current directory I am looking at is not automatically selected unless I type a space or one of the characters within the file name. How do I get Vertico to always and automatically select the first candidate in the list of files displayed? 

This issue does not happen with `M-x`.

I have tried looking into the issues on Orderless as well but it did not come up. I have tried disabling orderless and using different completion filters, but I don't think that is the issue. I am happy with the list of candidates, the files, currently displayed--I just want the first file/directory automatically selected. I also want the first file/directory automatically selected whenever I enter or leave a directory.

I am already using the vertico-directory extension. I had this issue before using it.

Here is my current config, but I don't think it is relevant:
```src emacs-lisp
  (use-package vertico
    :straight (:files (:defaults "extensions/*")
                      :includes (vertico-directory
                                 vertico-mouse))
    :bind (:map vertico-map
                ("C-j" . vertico-next)
                ("C-k" . vertico-previous)
                ("C-f" . vertico-exit)
                ("RET" . vertico-directory-enter)
                ("M-<backspace>" . vertico-directory-delete-word)
                ("<backspace>" . vertico-directory-delete-char)
                :map minibuffer-local-map
                ("M-h" . backward-kill-word)
                )
    :custom
    (vertico-cycle t)
    :init
    (vertico-mode)
    (vertico-mouse-mode))
```
`M-x` completion
![image](https://user-images.githubusercontent.com/12320165/151732761-d2f34bee-6bae-4994-902a-e81cba4286f8.png)
`C-x C-f` completion
![image](https://user-images.githubusercontent.com/12320165/151732828-1dabf839-f122-49ba-9c1e-66638c245395.png)

**Comment by minad** [comment]
Duplicate #156
