### ISSUE TITLE
Error in post-command-hook (vertico--exhibit): (wrong-number-of-arguments #<subr string-match> 4)

### ISSUE THREAD

**Issue by ingorichter** [minad/vertico#194]
After updating to Emacs 28 on macOS I see this error

I'm using Emacs 28.0.91 (build 1, x86_64-apple-darwin21.3.0, NS appkit-2113.30 Version 12.2 (Build 21D49))

I'm using the first vertico config mentioned in the README

**Comment by minad** [comment]
Vertico does not call string-match directly. Please try to reproduce in a fresh minimal install with emacs -Q and only vertico-mode activated. Delete and reinstall all your packages when upgrading Emacs.
