### ISSUE TITLE
Consider changing the binding of vertico-exit-input to M-RET for terminal emulators's sake

### ISSUE THREAD

**Issue by oantolin** [minad/vertico#196]
The current default binding for vertico-exit-input is C-<return> which I believe is one of those problematic key sequences that many terminal emulators cannot produce. I think M-RET is more widely supported. I'm not sure if you care about non-GUI Emacs enough to change the default binding, so feel free to just close this issue.

**Comment by minad** [comment]
Yes, this is long overdue. I should have made this change a longer time ago.

**Comment by oantolin** [comment]
Cool, thanks!
