### ISSUE TITLE
Part of Emacs?

### ISSUE THREAD

**Issue by dr-scsi** [minad/vertico#197]
Many thanks for providing this package.  I just started using it and it looks very promising.  This might be a minor issue, but the header part of `vertico.el` says:

https://github.com/minad/vertico/blob/e958277f66ec6cb503c0e7c73ce1c5171ed277b5/vertico.el#L10-L12

I would have expected something like:
```
;; This file is not part of GNU Emacs.
```
 Or am I missing something?

**Comment by minad** [comment]
Packages which live on ELPA typically have this message since they are distributed under the same conditions as Emacs itself. The FSF holds the copyright to this package.

**Comment by dr-scsi** [comment]
Thanks for your response.  I always thought "_part of GNU Emacs_" means being in core.  But since you're aware of that line, we can close this (which is already done, thanks).
