### ISSUE TITLE
consult-buffer: left-truncate recentf files

### ISSUE THREAD

**Issue by jdtsmith** [minad/vertico#198]
Recently marginalia added the option to left-truncate the file names associated with a buffer, which works great with consult-buffer.  The recentf files shown by consult-buffer can be even longer, even when abbreviated.  I wonder if it would be possible to similarly enable left truncation of the recentf file names themselves, if they exceed a user-definable fraction of the window width?  This may require a `'display` text property to keep the selection logic clean, but would really help with "unstable consult-buffer layout" when long files are on your recentf list and you navigate down.

**Comment by minad** [comment]
So if we start truncating candidates we are favoring the annotations over the candidate. This is something which I find questionable. Currently the candidate column always has priority and can get arbitrarily large. So maybe this is better left to a user configuration. What do you think?

**Comment by minad** [comment]
> I'm not sure we should add such an option. An issue I discovered is it can make search somewhat inscrutable, since search text can match undisplayed parts of the formatted candidate.

Yes exactly, therefore I also don't want to add this to Consult. Let's close this. We can keep it in mind if the issue comes up more often. In any case I would appreciate an addition of your snippet (and maybe other interesting config bits) to the wiki!

> I do wish I could precisely target it to File in consult buffer. Can I just look for (multi-category (file ...) property on the first character to determine that?

Yes, it should be possible to access the candidate text properties.

**Comment by jdtsmith** [comment]
Will do.  I added a check for the file "multi-category", so it really will only operate in consult-buffer on recentf files, and do no harm otherwise.

**Comment by minad** [comment]
@jdtsmith I wonder about your truncation code in https://github.com/minad/vertico/issues/198#issuecomment-1043547418 - doesn't this lead to misaligned Marginalia annotations since Marginalia uses the candidate width for alignment?

(I just got the report https://github.com/minad/marginalia/issues/145 where we hit the same candidate truncation issue. Unfortunately a good solution is not in sight since we are hitting the affixation/annotation-function limitations.)

**Comment by jdtsmith** [comment]
When the window is too narrow, they have never aligned, with or without truncation.  I do not have the the sense that the full file length is used in laying out, but only the _truncated_ width; i.e. marginalia must consider the candidate length after `vertico--format-candidate` is called on it.  Overall, truncation pretty works well for me, for frame widths of ~80 or above.

Here's the advice I'm using:

```elisp
(defun my/vertico-truncate-candidates (args)
    (if-let ((arg (car args))
	     (type (get-text-property 0 'multi-category arg))
	     ((eq (car-safe type) 'file))
	     (w (max 30 (- (window-width) (consult--display-width (nth 2 args)))))
	     (l (length arg))
	     ((> l w)))
	(setcar args (concat "…" (truncate-string-to-width arg l (- l w)))))
    args)
```

**Comment by minad** [comment]
I only care about the case where we can actually do something about the alignment. For narrow windows there isn't enough room anyway.

> marginalia must consider the candidate length after vertico--format-candidate is called on it. 

No that's no the case. See vertico--arrange-candidates and vertico--affixate. Therefore I am wondering.

**Comment by jdtsmith** [comment]
> No that's no the case.

Figured.  

> Therefore I am wondering

I think it must come down to calculating the width by taking the suffix into account as I now do.

**Comment by ParetoOptimalDev** [comment]
I have long file names in different consult-buffer sources frequently. I always want to see marginalia annotations. What's the current recommended approach to accomplish this?

I tried this code from above:

```
  (defun my/vertico-truncate-candidates (args)
    (if-let ((arg (car args))
             (type (get-text-property 0 'multi-category arg))
             ((eq (car-safe type) 'file))
             (w (max 30 (- (window-width) (consult--display-width (nth 2 args)))))
             (l (length arg))
             ((> l w)))
        (setcar args (concat "…" (truncate-string-to-width arg l (- l w)))))
    args)
  (advice-add #'vertico--format-candidate :filter-args #'my/vertico-truncate-candidates)
```

But it didn't work even after restarting emacs. By didn't work I mean the truncation didn't seem to happen for long items in consult-buffer which I'm assuming uses vertico and should hit this function. Actually I just checked with trace-function... it is hitting it. But display wise I still see very long lines that obscure marginalia annotations.

**Comment by ParetoOptimalDev** [comment]
Actually I just noticed that it does seem to left truncate the very long file name I'm using to test when I narrow to recent files with `f`. However it doesn't happen in `b` or my custom sources.

**Comment by ParetoOptimalDev** [comment]
Here's a screenshot showing it's truncated in one source but not the other:

![2023-05-04_12-34](https://user-images.githubusercontent.com/93023868/236284056-da9cce77-5cdb-4b11-a559-9ac89216f679.png)

I guess that code only applies to filenames when I want it to apply to buffer names?

**Comment by ParetoOptimalDev** [comment]
Ah okay that's it, I took an educated guess and this fixes it:

```
(defun my/vertico-truncate-candidates (args)
  (if-let ((arg (car args))
           (type (get-text-property 0 'multi-category arg))
           ((or (eq (car-safe type) 'file) (eq (car-safe type) 'buffer)))
           (w (max 30 (- (window-width) (consult--display-width (nth 2 args)))))
           (l (length arg))
           ((> l w)))
      (setcar args (concat "…" (truncate-string-to-width arg l (- l w)))))
  args)
(advice-add #'vertico--format-candidate :filter-args #'my/vertico-truncate-candidates)
```

**Comment by jdtsmith** [comment]
Good guess ;).
