### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Ergus** [minad/vertico#200]
Hi!

When I try to execute a command like `M-: (re` I don't get any completion there; it only shows next char not unique when i press tab... If I don't set `completion-auto-help nil` there are completions in the *Completions* buffer, so the question is if this is intended or there is an issue in my vertico config??

Thanks in advance,
Ergus

**Comment by minad** [comment]
See https://github.com/minad/vertico#completion-at-point-and-completion-in-region
