### ISSUE TITLE
Request: An easy way to configure vertico sorting on a per command basis

### ISSUE THREAD

**Issue by hmelman** [minad/vertico#202]
This is similar to issue #160.  I would like an easy way to configure vertico sorting on a per command basis.  In this case I'd like it for Info commands like `Info-menu` and `Info-follow-reference`. As of [emacs bug #38614](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=38614) the former presents the candidates in a useful order and hopefully the latter will after the bug I just filed for it ([#54175](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=54175)).  In general I prefer having vertico sort via its default sort function and in these cases the completion table is just a list with no `display-sort-function` defined so it's not easy to add advice to them to do so.  Also in these cases (unlike with `recentf` in #160) there is no category for the candidates, even when using marginalia.  This advice works for me, but I don't like it:

``` emacs-lisp
(defun my-vertico--sort-function ()
  "Return the sorting function checking for command overrides."
  ;; Don't sort some commands
  (if (memq this-command '(Info-menu Info-follow-reference))
      nil
    (or (vertico--metadata-get 'display-sort-function) vertico-sort-function)))

(advice-add #'vertico--sort-function :override #'my-vertico--sort-function)
```

I wish vertico had an easier way to do this.  If you were considering something like `consult-customize` for vertico, I suggest adding this to its capabilities.

**Comment by minad** [comment]
You can already override the default sort function via vertico-multiform: https://github.com/minad/vertico#configure-vertico-per-command-or-completion-category. (However if a completion tables specifies a sort function in its metadata, the default sort function will not take effect, but I don't think that's the case here.)
