### ISSUE TITLE
vertico doesn't play nice with bbdb-create

### ISSUE THREAD

**Issue by dingesista** [minad/vertico#205]
I just found out that using vertico will create an endless loop for bbdb-create; it will continue to ask for phone records.
I guess here we need to toggle vertico-mode (to off). If that is how it was intended, sorry for the noise.

**Comment by minad** [comment]
I haven't looked at bbdb, but you can probably break out of the look with `vertico-exit-input` or by moving the point to the prompt with up and then pressing RET. Then Vertico will exit with the empty input string and it will break out of the loop. Does this work?

**Comment by dingesista** [comment]
I confirm that a simple 'up' key when asked for the (next phone) is enough to break the loop. 

Thanks!
