### ISSUE TITLE
"clean up" paths when using find-file with vertico?

### ISSUE THREAD

**Issue by garyo** [minad/vertico#210]
I'd like `C-x C-f` (find-file) to "clean up" paths when I complete using TAB; so for instance if I'm in `~/a/b/c` and I type `~/` I'd like TAB to remove the `a/b/c` part, and similarly if I start typing an absolute pathname (`/tmp/`) I'd like it to remove the existing path parts from the prompt. Is there any easy way to do that? I tried enabling `vertico-directory` but not sure I did it right, and I'm not sure if it does that anyway.

**Comment by minad** [comment]
You can use `vertico-directory-tidy`. Then shadowed paths like `/tmp/~/` will be automatically cleaned up.

~~~ elisp
(add-hook 'rfn-eshadow-update-overlay-hook #'vertico-directory-tidy)
~~~
