### ISSUE TITLE
Optionally disable grouping

### ISSUE THREAD

**Issue by noctuid** [minad/vertico#220]
I'm not sure if this is a reasonable request or not. I always disliked this feature in helm, and it was one of the main reasons I switched to ivy. If I'm using something like `consult-buffer` I don't really care if I've already opened a file and it's a buffer or if it's an unopened file. I just want  the best matches to be at the top. This mattered more back then since better matches were actually sorted higher, and a lot of the time the match I wanted was not in the first group. Now that I'm just using orderless and recency sorting, I haven't cared too much. For more complex sorting, grouping could be an annoyance if there are a lot of matches but the best match is in a lower group.

**Comment by minad** [comment]
You can already switch it off, see `vertico-group-format`.

**Comment by minad** [comment]
> For more complex sorting, grouping could be an annoyance if there are a lot of matches but the best match is in a lower group.

This cannot happen in Vertico. The best match will always be in the first group since the group ordering is derived from the candidate ordering.

**Comment by noctuid** [comment]
Setting `vertico-group-format` to nil will still show all buffers before files. Am I misunderstanding?

> This cannot happen in Vertico for example with flex. The best match will always be in the first group since the group ordering is derived from the candidate ordering.

I'm not sure I understand. If the top 3 matches based on some fuzzy sorting algorithm happened to be in 3 separate groups, wouldn't this still be an issue?

I may be misunderstanding the integration with savehist, but if I go to a file, close the buffer, and then call `consult-buffer` again, I would expect that file to be higher.

**Comment by minad** [comment]
> I'm not sure I understand. If the top 3 matches based on some fuzzy sorting algorithm happened to be in 3 separate groups, wouldn't this still be an issue?

Yes. Then it is an issue. I was only talking about the topmost candidate.

> I may be misunderstanding the integration with savehist, but if I go to a file, close the buffer, and then call consult-buffer again, I would expect that file to be higher.

`consult-buffer` uses the `identity` function for sorting (`display-sort-function`, see `:sort nil` in `consult-buffer`), therefore `vertico-sort-function` is not used. If you want you can set `vertico-sort-override-function` to override. You can even set `vertico-sort-override-function` only for the `consult-buffer` command via `vertico-multiform-mode`, see https://github.com/minad/vertico/#configure-vertico-per-command-or-completion-category.

**Comment by minad** [comment]
@noctuid I wonder if your problem got solved with `(consult-customize consult-buffer :group nil :sort t)`?

**Comment by noctuid** [comment]
Hadn't tried it yet, but yep that works :+1: Thanks.
