### ISSUE TITLE
Error in post-command-hook (vertico--exhibit): (wrong-type-argument stringp (windows-nt ms-dos))

### ISSUE THREAD

**Issue by d9d6ka** [minad/vertico#223]
Possible related to #179 

Hi! Thanks for your packages! Using heavily corfu, cape, vertico, marginalia, tempel...

Yesterday I've bumped into a strange problem with vertico. I've invoked searching info about variables `C-h v` and tried to find smth related to "window". After I've entered `win` the following error occured

> Error in post-command-hook (vertico--exhibit): (wrong-type-argument stringp (windows-nt ms-dos))

While searching for callable `C-h f` everything is OK, no error.

As I use savehist I've found out, that if that search query (`win`) is saved in the history then the error is thrown every time I call `C-x v` and the minibuffer doesn't respond to any input.

Screencast attached
![emacs](https://user-images.githubusercontent.com/29946047/165031025-6a5eedb9-cba0-464e-b550-50d0399b9550.gif)

All packages are up to date, reinstalled all yesterday via `straight.el`.
Emacs version "GNU Emacs 28.1 (build 52, x86_64-w64-mingw32) of 2022-04-04"

<details>
  <summary>Vertico is configured as follows</summary>
  
```elisp
(use-package vertico
    :straight t
    :hook
    ((minibuffer-setup . (lambda ()
                             (setq completion-in-region-function
                                   (if vertico-mode
                                           #'consult-completion-in-region
                                       #'completion--in-region)))))
    :init
    (vertico-mode)
    :custom
    (vertico-cycle t))

(use-package orderless
    :straight t
    :custom
    (completion-styles '(orderless))
    (completion-category-defaults nil)
    (completion-category-overrides '((file (styles . (partial-completion))))))

(use-package marginalia
    :straight t
    :init
    (marginalia-mode))
```
  
</details>

**Comment by minad** [comment]
Please provide a backtrace, see https://github.com/minad/vertico/issues/179#issuecomment-1009902151. This is probably not an issue in Vertico but in one of the underlying packages (the completion backend, Marginalia, ...). Also try to reproduce the issue with emacs -Q and only Vertico and the packages you mentioned in your config excerpt.

**Comment by d9d6ka** [comment]
Thanks! Your comment have me a hint to find a problem 👍
