### ISSUE TITLE
Vertico scroll commands

### ISSUE THREAD

**Issue by tpeacock19** [minad/vertico#224]
It may be too late for this now, but it seems like the
`vertico-scroll-{up,down}` commands behave the opposite way than the
`scroll-{up,down}-command`. I've been making an effort to move away from
`evil` and use more traditional commands. This led to some confusion in
expectations. The standard command refers to scrolling the text, whereas
the vertico commands seems to refer to the current candidate. I
currently just switch the mapping, but I was curious as to why the difference.

**Comment by minad** [comment]
Indeed, that's odd. This must be some mistake in my config which proliferated to Vertico.

**Comment by tpeacock19** [comment]
hmm. I think it was something up with my config. sorry for the noise!
