### ISSUE TITLE
Suggestion: Make `vertico-insert` insert entry when there is only one completion even if it is not selected

### ISSUE THREAD

**Issue by ivan-pop** [minad/vertico#225]
Right now when I use `find-file` and open some directory if there is only one file present I still need to either type some part of it to be able to insert it or I need to manually select it. It would be nice if `vertico-insert` just inserted the first candidate even if it is not selected. In my opinion this is better than the current way. Maybe mostly because I am used to the way shell completion does it where it will complete file name when there is only one file/folder in directory. Default Emacs completion appears to behave in the same way.

**Comment by minad** [comment]
Makes sense. But instead of using the first candidate we should simply rely on the completion style to do the right thing. See how TAB is handled in Corfu if no candidate is selected: https://github.com/minad/corfu/blob/bf9bb725f70fb3165e2831c5926217bd6a8bc68d/corfu.el#L991-L1010

**Comment by minad** [comment]
Reverted because of #232
