### ISSUE TITLE
Directories with `.git` suffix are not listed in `find-file`

### ISSUE THREAD

**Issue by mekeor** [minad/vertico#229]
Consider this directory tree:

```
$ tree
.
└── test
    ├── bar.git
    └── foo
```

Where `bar.git` and `foo` are directories. With vertico-mode, find-file won't list `bar.git`. I guess that's because of `completion-ignored-extensions`. But the documentation of latter variable states:

> [Completion] ignores directory names if they match any string in this list which ends in a slash.

I interprete the "match" as an equality, i.e. I think `.git` directories should be ignored but not directories with a `.git` suffix, like `bar.git`.

**Comment by minad** [comment]
Yes, this is due to `completion-ignored-extensions`. If I interpret the function `file-name-completion` in dired.c correctly, "match" means "the suffix matches", not "equal" as in your interpretation.

**Comment by mekeor** [comment]
Thanks for investigating.

**Comment by minad** [comment]
Note that you can advise `vertico--filter-files` with your own function if you would like to change the current behavior.
