### ISSUE TITLE
TRAMP sudo password prompt is not shown (instead connection failed)

### ISSUE THREAD

**Issue by drot** [minad/vertico#23]
When trying to use `/sudo::` the following occurs when attempting to input the password:

![2021-04-26_13-28-46-region-screenshot](https://user-images.githubusercontent.com/85483/116075633-76e42a80-a693-11eb-9911-6e4ee44a3fd9.png)

Tested on:

`GNU Emacs 27.2.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.16.0) of 2021-03-27`

Vertico:
`;; Version: 0.6`

**Comment by minad** [comment]
Currently Tramp is not supported well by Vertico. There is already issue #20 where further steps can be discussed.

**Comment by manuel-uberti** [comment]
FWIW, I don't have this problem. I can use the pattern provided in the picture above and, for instance, visit my `.bashrc` with sudo.

**Comment by minad** [comment]
You visit your .bashrc with sudo?! Why is that? Is your .bashrc not owned by you? Or do you have sudo configured such that it does not ask for a pw?

**Comment by manuel-uberti** [comment]
I was just trying to replicate this issue. :)

**Comment by minad** [comment]
cc @albinus @astoff

Is it necessary to tell Tramp specially that it should query the user for a password?

**Comment by astoff** [comment]
I can reproduce this with the following steps:
1. Open a new Emacs so there is no cached passwords and the like
2. Type `C-x C-f /sudo::` slowly
3. Then I actually see a password prompt
4. But as soon as I type one character, the password prompt exists and I see what's shown in the screenshot.

**Comment by minad** [comment]
Okay, something is messed up with the keybindings. I have to investigate this.

When I add a `read-passwd` call to `vertico--recompute-candidates` everything is messed up.

**Comment by albinus** [comment]
> cc @albinus @astoff
> 
> Is it necessary to tell Tramp specially that it should query the user for a password?

No. Tramp knows, when to read a password.

**Comment by albinus** [comment]
> Okay, something is messed up with the keybindings. I have to investigate this.
> 
> When I add a `read-passwd` call to `vertico--recompute-candidates`, I cannot enter a password. Maybe `read-passwd` doesn't open a recursive minibuffer but somehow abuses the current buffer?

Don't mess with Tramp reading a password. It is very fragile.

This is the idea of let-binding `non-essential`. It tells Tramp to not open a connection if it isn't connected yet, avoiding reading a password. If the connection is already established, it doesn't matter.

Honestly, I feel very uncomfortable to discuss these issues on github. Could we pls switch to email conversation via tramp-devel ML?

**Comment by minad** [comment]
> Don't mess with Tramp reading a password. It is very fragile.

Yes, this fragility seems exactly the problem. But I have a hard time to figure out what should be differently to avoid stepping on Tramp's feet.

> This is the idea of let-binding non-essential. It tells Tramp to not open a connection if it isn't connected yet, avoiding reading a password. If the connection is already established, it doesn't matter.

Of course. But this means giving up. This is not an option here.

> Honestly, I feel very uncomfortable to discuss these issues on github. Could we pls switch to email conversation via tramp-devel ML?

Yes, I will move the discussion there. In my eyes mailing lists are a more formal medium in contrast to commenting here and there. Please don't feel pressed to answer here. Just ignore the ongoing discussion here. I will then come to the ML as soon as I understand better what is going on.

For me this issue is low priority. Tramp works mostly well with Vertico now, except for the password prompts.

**Comment by albinus** [comment]
> > This is the idea of let-binding non-essential. It tells Tramp to not open a connection if it isn't connected yet, avoiding reading a password. If the connection is already established, it doesn't matter.
> 
> Of course. But this means giving up. This is not an option here.

I don't see anything for "giving up". As long as the connection is not established yet, no file name completion happens. So what?
When the connection is established, everything should work as expected.

**Comment by minad** [comment]
> I don't see anything for "giving up". As long as the connection is not established yet, no file name completion happens. So what? When the connection is established, everything should work as expected.

This is understandable out of the perspective of default completion where the connection is established when pressing TAB. For interactive completion UIs like Vertico or Icomplete it is preferable to directly establish the connection, such that the available candidates can be shown directly.

**Comment by albinus** [comment]
> This is understandable out of the perspective of the default completion UI where the connection is established when pressing TAB. For interactive completion UIs like Vertico or Icomplete it is preferable to directly establish the connection, such that the available files can be shown directly.

I don't believe it is a serious restriction for any completion package, that (for remote file names) the connection must be established first. But well, your decision. Good luck fighting with Tramp :-)

**Comment by minad** [comment]
> I don't believe it is a serious restriction for any completion package, that (for remote file names) the connection must be established first. But well, your decision. Good luck fighting with Tramp :-)

I have no intention to fight tramp. What I don't understand about your argument - when should the connection be established then - for example, when I press "C-x C-f" and enter some remote directory?

**Comment by albinus** [comment]
> I have no intention to fight tramp.

Me too. But contrary to, I'm obliged to fight with Tramp. Every single day.

> What I don't understand about your argument - when should the connection be established then? For example, when I press "C-x C-f" and enter some remote path? My current interpretation is that the connection should be established directly after entering the remote path.

No, you must finish this with RET.

**Comment by minad** [comment]
> Me too. But contrary to, I'm obliged to fight with Tramp. Every single day.

Stay strong fighting the TRAMP then! I will see where my fights with it will go. The first one got settled quite quickly. I made the mistake to overwrite the minibuffer-completion-predicate, which is special-cased for file-exists-p and file-directory-p (https://github.com/minad/vertico/commit/f281aac2e875d8333e29206ec25aaeea8f3d6800).

> No, you must finish this with RET.

Okay, I see. This makes sense.

**Comment by astoff** [comment]
In the vanilla minibuffer, typing `TAB` can trigger a password prompt. But in Vertico, the similar thing would be that the `:` or `/` ending a remote identifier would trigger the prompt. Maybe this behavior would be a bit questionable (too electric)?

**Comment by minad** [comment]
Maybe it would make sense to bind some special command which then triggers establishing the connection. On the other hand such an electric behavior is probably expected by users of incrementally updating UIs. In principle this should already work, the problem is only that the prompt breaks. Until now I haven't figured out what the issue is. Maybe someone has an idea?
