### ISSUE TITLE
Error in post-command-hook (vertico--exhibit): (error "Cannot resize mini window")

### ISSUE THREAD

**Issue by laampui** [minad/vertico#230]
here it's the `init.el`

```emacs lisp
;; https://github.com/manateelazycat/sort-tab/blob/main/sort-tab.el
(load "~/.emacs.d/site-lisp/sort-tab/sort-tab.el")
(require 'sort-tab)
(sort-tab-mode 1)

(load "~/.emacs.d/elpa/vertico-0.23/vertico.el")
(require 'vertico)
(vertico-mode)

;; https://github.com/purcell/default-text-scale/blob/master/default-text-scale.el
(load "~/.emacs.d/elpa/default-text-scale-20191226.2234/default-text-scale.el")
(require 'default-text-scale)
(default-text-scale-mode)

(defun force-debug (func &rest args)
  (condition-case e
      (apply func args)
    ((debug error) (signal (car e) (cdr e)))))

(advice-add #'vertico--exhibit :around #'force-debug)
```

step to reproduce
1.`M-x` `default-text-scale-increase`
2. `M-x` again, and the error throws

with `toggle-debug-on-error` turned on, i got this `*Backtrace*`
<details>
  <summary>*Backtrace*</summary>
<pre>
Debugger entered--Lisp error: (error "Cannot resize mini window")
  window--resize-mini-window(#<window 4 on  *Minibuf-1*> 222)
  window-resize(nil 222 nil nil pixelwise)
  (progn (window-resize nil dp nil nil 'pixelwise))
  (if (or (and (> dp 0) (/= height 0)) (and (< dp 0) (eq vertico-resize t))) (progn (window-resize nil dp nil nil 'pixelwise)))
  (let* ((window-resize-pixelwise t) (dp (- (max (cdr (window-text-pixel-size)) (* (default-line-height) (1+ height))) (window-pixel-height)))) (if (or (and (> dp 0) (/= height 0)) (and (< dp 0) (eq vertico-resize t))) (progn (window-resize nil dp nil nil 'pixelwise))))
  (if (frame-root-window-p (active-minibuffer-window)) nil (if vertico-resize nil (setq height (max height vertico-count))) (let* ((window-resize-pixelwise t) (dp (- (max (cdr (window-text-pixel-size)) (* (default-line-height) (1+ height))) (window-pixel-height)))) (if (or (and (> dp 0) (/= height 0)) (and (< dp 0) (eq vertico-resize t))) (progn (window-resize nil dp nil nil 'pixelwise)))))
  vertico--resize-window(10)
  vertico--display-candidates((#("toggle-debug-on-error\n" 0 1 (face (completions-first-difference vertico-current)) 1 22 (face vertico-current)) #("default-text-scale-increase (C-M-=)\n" 0 1 (face (completions-first-difference)) 27 35 (face completions-annotations)) #("cd\n" 0 1 (face (completions-first-difference))) #("5x5\n" 0 1 (face (completions-first-difference))) #("arp\n" 0 1 (face (completions-first-difference))) #("dbx\n" 0 1 (face (completions-first-difference))) #("dig\n" 0 1 (face (completions-first-difference))) #("erc\n" 0 1 (face (completions-first-difference))) #("ert (ert-run-tests-interactively)\n" 0 1 (face (completions-first-difference)) 3 33 (face completions-annotations)) #("eww\n" 0 1 (face (completions-first-difference)))))
  (let* ((buffer-undo-list t) (pt (max 0 (- (point) (minibuffer-prompt-end)))) (content (minibuffer-contents))) (if (or (input-pending-p) (equal vertico--input (cons content pt))) nil (vertico--update-candidates pt content)) (vertico--prompt-selection) (vertico--display-count) (vertico--display-candidates (vertico--arrange-candidates)))
  (closure (t) nil "Exhibit completion UI." (let* ((buffer-undo-list t) (pt (max 0 (- (point) (minibuffer-prompt-end)))) (content (minibuffer-contents))) (if (or (input-pending-p) (equal vertico--input (cons content pt))) nil (vertico--update-candidates pt content)) (vertico--prompt-selection) (vertico--display-count) (vertico--display-candidates (vertico--arrange-candidates))))()
  apply((closure (t) nil "Exhibit completion UI." (let* ((buffer-undo-list t) (pt (max 0 (- (point) (minibuffer-prompt-end)))) (content (minibuffer-contents))) (if (or (input-pending-p) (equal vertico--input (cons content pt))) nil (vertico--update-candidates pt content)) (vertico--prompt-selection) (vertico--display-count) (vertico--display-candidates (vertico--arrange-candidates)))) nil)
  (condition-case e (apply func args) ((debug error) (signal (car e) (cdr e))))
  force-debug((closure (t) nil "Exhibit completion UI." (let* ((buffer-undo-list t) (pt (max 0 (- (point) (minibuffer-prompt-end)))) (content (minibuffer-contents))) (if (or (input-pending-p) (equal vertico--input (cons content pt))) nil (vertico--update-candidates pt content)) (vertico--prompt-selection) (vertico--display-count) (vertico--display-candidates (vertico--arrange-candidates)))))
  apply(force-debug (closure (t) nil "Exhibit completion UI." (let* ((buffer-undo-list t) (pt (max 0 (- (point) (minibuffer-prompt-end)))) (content (minibuffer-contents))) (if (or (input-pending-p) (equal vertico--input (cons content pt))) nil (vertico--update-candidates pt content)) (vertico--prompt-selection) (vertico--display-count) (vertico--display-candidates (vertico--arrange-candidates)))) nil)
  vertico--exhibit()
  #<subr completing-read-default>("M-x " #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_47> #f(compiled-function (sym) #<bytecode 0x1fa4470d2758e7d5>) t nil extended-command-history nil nil)
  apply((#<subr completing-read-default> "M-x " #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_47> #f(compiled-function (sym) #<bytecode 0x1fa4470d2758e7d5>) t nil extended-command-history nil nil))
  (progn (add-hook 'minibuffer-setup-hook setup-hook) (apply args))
  (unwind-protect (progn (add-hook 'minibuffer-setup-hook setup-hook) (apply args)) (remove-hook 'minibuffer-setup-hook setup-hook))
  (let ((fun #'vertico--setup) (setup-hook (make-symbol "minibuffer-setup"))) (fset setup-hook #'(lambda nil (remove-hook 'minibuffer-setup-hook setup-hook) (funcall fun))) (unwind-protect (progn (add-hook 'minibuffer-setup-hook setup-hook) (apply args)) (remove-hook 'minibuffer-setup-hook setup-hook)))
  vertico--advice(#<subr completing-read-default> "M-x " #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_47> #f(compiled-function (sym) #<bytecode 0x1fa4470d2758e7d5>) t nil extended-command-history nil nil)
  apply(vertico--advice #<subr completing-read-default> ("M-x " #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_47> #f(compiled-function (sym) #<bytecode 0x1fa4470d2758e7d5>) t nil extended-command-history nil nil))
  completing-read-default("M-x " #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_47> #f(compiled-function (sym) #<bytecode 0x1fa4470d2758e7d5>) t nil extended-command-history nil nil)
  read-extended-command()
  byte-code("\302\30\11\303 \10E)\207" [execute-extended-command--last-typed current-prefix-arg nil read-extended-command] 3)
  command-execute(execute-extended-command)

<pre>
</details>

**Comment by minad** [comment]
Can you reproduce this without sort-tab or default-text-scale-mode? These packages may be incompatible with Vertico. I have not heard of those packages before. Are they doing something special which prevents minibuffer resizing?
