### ISSUE TITLE
Issues with automatic selection of first candidate

### ISSUE THREAD

**Issue by DamienCassou** [minad/vertico#232]
Recent commit cc5f5421c6270b8fdd12265ccdaffc3cd297d0d8 broke my workflow. I would like to know if it's just me and there is a nice workaround or if there is a fundamental problem with this commit. The following describes a scenario and how the behavior changed after this commit.

Imagine a directory containing a single file. I want to use `find-file` to open `dired` on this directory.

- with the old version of `vertico-mode`, `fido-vertical-mode`, `fido-mode` and `ivy-mode`: as long as you don't explicitly select the file, typing <kbd>RET</kbd> or <kbd>C-j</kbd> will open dired on the directory; this is what I want;
- with the new version of `vertico-mode`: both <kbd>RET</kbd> and <kbd>C-j</kbd> open the file. I couldn't find a way to get a dired buffer on the directory;
- with `ido-mode`: <kbd>RET</kbd> opens the file but <kbd>C-j</kbd> opens the directory; this is another acceptable solution.

You could tell me to use `M-x dired` to open a dired buffer: this would change my workflow but is an acceptable answer. Nevertheless, the exact same problem happens with `dired-do-copy` (bound to <kbd>C</kbd> in `dired-mode` buffers): you can't copy a file to a directory containing a single file! Dired will always ask me if I want to override the single file with the new file which is very different from what I want. If you select more than a file to copy all of them to the directory, you get an error because dired tries to copy all files into a single one.

**Comment by minad** [comment]
You are right that the commit https://github.com/minad/vertico/commit/cc5f5421c6270b8fdd12265ccdaffc3cd297d0d8 wasn't well thought out. I am usually not happy with such special casing anyway. Therefore I reverted this.

(However as a workaround you could have used `vertico-exit-input`, M-RET.)

**Comment by minad** [comment]
Okay, I resolved this in a better way, see https://github.com/minad/vertico/commit/a8420acdbbadd190cdddc173e9f37221e2ffb676.

**Comment by DamienCassou** [comment]
Excellent, thank you very much!
