### ISSUE TITLE
vertico-previous-group/vertico-next-group don't respect vertico-cycle

### ISSUE THREAD

**Issue by agzam** [minad/vertico#233]
It seems vertico-previous/next-group commands don't respect the value of `vertico-cycle`. 

When it's set to `nil`, they should not go beyond the boundaries and should work similar to `vertico-previous`/`vertico-next` in regard to the var.

**Comment by minad** [comment]
The behavior is intentional. By cycling it is ensured that the topmost group stays at the top when filtering with more input.

**Comment by minad** [comment]
Duplicate #91

**Comment by agzam** [comment]
Thank you for explaining it in detail in #91. Gosh, you should've left us some flaws and bugs to discover. For a moment I was so happy. "Ha! I found a bug", I thought. "I shall report this immediately so everyone knows how scrupulous Emacs user I am..."
