### ISSUE TITLE
[Error in post-command-hook (vertico--exhibit): (void-function unset)]

### ISSUE THREAD

**Issue by librarianmage** [minad/vertico#238]
Hello, I am getting the error mentioned in the title when trying to use this, consult, and [mclear-tools/tabspaces](https://github.com/mclear-tools/tabspaces)

Steps to reproduce
1. Install vertico, consult, tabspaces
2. enable tab-bar-mode, tabspaces-mode
3. run `M-x tabspaces-open-or-create-project-and-workspace`

**Comment by minad** [comment]
This is a bug in tabspaces, which runs `completing-read` on `project--list` which is initially `unset`: https://github.com/mclear-tools/tabspaces/blob/24266c6c9a766261a8c8620692dfa4000f3e1d5d/tabspaces.el#L301
