### ISSUE TITLE
[0.24] Space is rebound after enabling vertico-mode

### ISSUE THREAD

**Issue by jsynacek** [minad/vertico#239]
1) Run `emacs -Q`.
2) Load `vertico.el`. I used version 0.24, but 0.23 is the same.
3) M-x `vertico-mode`.
4) Run M-x again and type "vertico " -- note the space at the end.

The space at the end should run `minibuffer-complete-word` instead of adding the literal space into the minibuffer, but for some reason, it remaps it and then the completion doesn't really work as it's supposed to. I haven't even found any place in `vertico.el` that would cause the remapping. This also happens for other minibuffer commands that normally map space to `minibuffer-complete-word` such as `switch-to-buffer`.

**Comment by minad** [comment]
Vertico uses its own vertico-map in the minibuffer, not the minibuffer-local-completion-map. Therefore SPC means literal space in Vertico. This is useful for completion styles like Orderless. If you want minibuffer-complete-word you can bind it in vertico-map.

**Comment by minad** [comment]
See also https://github.com/minad/vertico/issues/214 where I describe the reasoning for the Vertico keymap usage.
