### ISSUE TITLE
delete the whole file name in backspace + a way to create a new file

### ISSUE THREAD

**Issue by RadonBurner** [minad/vertico#243]
In Ido when pressing delete the previous name gets deleted, this is the only thing I really miss when switching from Ido to vertico. Also a way to create a new file like for example you have file1.txt , I can't create a normal file.txt

**Comment by minad** [comment]
Did you take a look at the README? You will find the answer to both your questions there.

**Comment by bhepple** [comment]
As a more explicit clue, the ido backspace behaviour is provided by vertico-directory
