### ISSUE TITLE
Ignoring files and directories

### ISSUE THREAD

**Issue by M-Gregoire** [minad/vertico#246]
Hello,

First of all, thank you for `vertico`: I've discovered it recently and I love it so far!

I'm trying to ignore some results in `+vertico/project-search` (From [Doom](https://github.com/doomemacs/doomemacs/blob/master/modules/completion/vertico/autoload/vertico.el#L8)) but I've been unable to find a way to do that without relying on the VCS level.

For example, I'd like to ignore all files inside `./vendor` (Project folder being the root) from Emacs configuration (not using `.gitignore`). The only related setting I found is `completion-ignored-extensions` but does not really fit my usage.

Does Vertico provide something like `projectile-globally-ignored-directories`?

Thank you for any help you might provide.

**Comment by minad** [comment]
Thanks! Please ask on the Doom Discord or the Doom Discourse about this, since it is not related to Vertico, but to the project search command.
