### ISSUE TITLE
Support numeric sort 

### ISSUE THREAD

**Issue by hwiorn** [minad/vertico#247]
Hi, I want to sort my org file candidates by alphanumeric.

I use org-roam, and I'm trying to use the Folgezettel(handwritten note-number) concept in org title.
Currently, vertico shows files like below

- `{1/1a2} Note 1`
- `{10/2a3} Emacs lisp`
- `{113/2a3} Some note`
- `{12/1a3} Developmenet`
- `{2/2a3} Note 2`

Is there an option for sorting by alphanumeric(human) instead of just alpha sorting like this?

- `{1/1a2} Note 1`
- `{2/2a3} Note 2`
- `{10/2a3} Emacs lisp`
- `{12/1a3} Developmenet`
- `{113/2a3} Some note`

**Comment by minad** [comment]
Thanks for the suggestion. Additional sort functions are out of scope of Vertico, but you can easily define such functions yourself. Then the function can be configured via `vertico-sort-function` or `vertico-sort-override-function`. The configuration is also possible per command or per completion category, see https://github.com/minad/vertico/#configure-vertico-per-command-or-completion-category.
