### ISSUE TITLE
completing-read with vertico-directory from a list of directories leads to unwanted vertico-insert

### ISSUE THREAD

**Issue by jdtsmith** [minad/vertico#251]
The `dirvish` dired enhancement mode calls completing-read like:

```elisp
(let* ((history-w/metadata
          (dirvish--append-metadata
           'file (ring-elements dirvish-history--ring)))
         (result (completing-read "Recently visited: " history-w/metadata)))
      (when result (dirvish-find-entry-ad result))))
```

where history-w/metadata is a completion table function.  Upon selecting one of the directories and hitting `Ret`, this leads `vertico-directory-enter` to call `vertico-insert`.  This is appropriate when doing file completion, but when selecting among a list of directories, it would be better if `vertico-exit` were called.  Dirvish is using `file` for the metadata category btw.  

Here's a simple mockup demoing this behavior (with `vertico-directory-enter` bound to "RET"):

```elisp
(let ((completions '("/tmp/" "/etc/ssh/" "/etc/pam.d/")))
  (completing-read "Testing Dir Completion: "
		   (lambda (string pred action)
		     (if (eq action 'metadata)
			 '(metadata (category . file))
		       (complete-with-action action completions string pred)))))
```

**Comment by minad** [comment]
Yes, the file category is insufficient to detect step wise file completion properly. It should be easy to fix this by checking the completion boundaries. However overall I am not so happy anymore with these directory commands. It may be better to use vertico-multiform and only rebind the commands where appropriate.
