### ISSUE TITLE
Feature Request: completion of annotations

### ISSUE THREAD

**Issue by maxbrieiev** [minad/vertico#253]
It would be good to be able to complete candidates by matching annotation text.

For example,

I have opened several info buffers - `*info*`, `*info*<2>`, `*info*<3>`.

Running `switch-buffer` allows me to only complete by buffer name, like typing `info` and then visually scanning the annotation text in front of each candidate to actually locate the correct Info node, and only then switching to it.

Instead I would like to select the candidate by typing (depending on completion style) part of its Info node name, which is part of annotation.

Is it something feasible?

Same logic can be applied, for example, by completing docstring for M-x command, etc.

**Comment by minad** [comment]
This is out of scope of Vertico. See https://github.com/oantolin/orderless/issues/30 and https://github.com/minad/consult/issues/409 for previous discussions and some prototypes. Such a feature would fit better in a separate package, on the level of the filtering and completion styles.

**Comment by minad** [comment]
We will add annotation matching to Orderless in https://github.com/oantolin/orderless/pull/162. `@pattern` will match pattern in the annotation.
