### ISSUE TITLE
vertico-mouse-mode does not work with pixel-scroll-precision-mode

### ISSUE THREAD

**Issue by maxbrieiev** [minad/vertico#255]
1. M-x pixel-scroll-precision-mode
2. M-x vertico-mouse-mode
3. Start minibuffer session for any command
4. Try to scroll with mouse/touchpad. Notice that it just displays "End of buffer" in the echo area without any scrolling happening.

**Comment by minad** [comment]
Pixel precision mode doesn't use the mwheel infrastructure. It is not backward compatible. But afaik you can set pixel-scroll-mode locally to nil in the minibuffer to disable it there. Hopefully the backward compatibility of this mode gets improved but I don't have high hopes.

**Comment by salutis** [comment]
For the people struggling with this problem:

```emacs-lisp
(add-hook 'vertico-mouse-mode-hook
          (lambda ()
            (pixel-scroll-precision-mode -1)))
```

**Comment by salutis** [comment]
Oops!  The Pixel Scroll Precision mode is a global minor mode, so the above disables it everywhere.  I tried to set `(setq-local pixel-scroll-precision-mode nil)` but that does not fix the problem.  Checkmate?
