### ISSUE TITLE
input three time `C-l` in find-file will hangs emacs

### ISSUE THREAD

**Issue by paomian** [minad/vertico#256]
```
➜  ~ cat abc.el
(package-initialize)

(require 'vertico)
(vertico-mode)
```
```
/Applications/Emacs.app/Contents/MacOS/Emacs -q --load abc.el
```
 and find-file via `C-x C-f` and then press and hold `control`, then press `l` three times
Emacs will be hangs. use 100% CPU and `C-g` become useless.I must close it by force kill.

**Comment by minad** [comment]
Thanks for the report. This seems to be an upstream issue since I can also reproduce it without Vertico. Reported at https://github.com/minad/vertico/issues/256.
