### ISSUE TITLE
consult-buffer case-insensitive matching and read-buffer-completion-ignore-case

### ISSUE THREAD

**Issue by cfal** [minad/vertico#259]
i'm trying to get `consult-buffer` to return search results ignoring case, and came across https://github.com/minad/vertico/issues/52:
```
(setq completion-styles '(basic substring partial-completion emacs22 flex))
(setq read-file-name-completion-ignore-case t)
(setq read-buffer-completion-ignore-case t)
```

`read-buffer-completion-ignore-case` doesn't seem to be respected (specifically, i'm testing by typing "Scratch" and seeing that it doesn't match the `*scratch*` buffer), until i set `(setq completion-ignore-case t)`. since i don't want general completions to ignore case, i had to use vertico-multiform to only set it for consult-buffer.

wondering if i'm doing something wrong or if this is expected behavior?

thanks!

**Comment by minad** [comment]
consult-buffer does not use read-buffer, therefore read-buffer-completion-ignore-case is not respected. vertico-multiform is the best solution to override settings per command.
