### ISSUE TITLE
c-<tab> switch to buffer

### ISSUE THREAD

**Issue by MarcRohrer** [minad/vertico#263]
Hi Minad,

I absolutely love Vertico! I have set C-\<tab> to switch-to-buffer
Is it possible to have a setting that keeping C-\<tab> pressed, selecting
a buffer with the arrow keys and upon release of C-\<tab> switching to
that buffer (similar to Windows Alt-Tab)?

Keep up the great work, thanx!
Best wishes!

Marc

**Comment by minad** [comment]
Thanks! It is surely possible to implement such a C-tab command or extension for switch-to-buffer, but there is no easy way. My recommendation is the consult-buffer command from my Consult package. Did you try this? Maybe it fits your workflow, even if it is different from the C-tab behavior.
