### ISSUE TITLE
Subgroups for extensions

### ISSUE THREAD

**Issue by mattiasdrp** [minad/vertico#264]
I couldn't find the buffer extension customizations and reading the files I wondered why they were not defined in their own subgroup like this:

```elisp
(defgroup vertico-buffer nil
  "Buffer customization."
  :group 'vertico
  :tag "Vertico-buffer customization")

(defcustom vertico-buffer-hide-prompt t
  "Hide prompt in the minibuffer."
  :group 'vertico-buffer
  :type 'boolean)

...
```

This allows to have 

![image](https://user-images.githubusercontent.com/5543639/184340933-a09f199f-f27d-4727-84de-55f900ead490.png)

I can create a PR to define a subgroup for each extension if you think it's not a bad idea.

**Comment by minad** [comment]
I think the reason is that most extensions only define very few defcustoms. Having a group for a single defcustom isn't great and having some extensions with a group and some without isn't great either.
