### ISSUE TITLE
`vertico-directory-enter` tries to enter projects in `projectile-completing-read`

### ISSUE THREAD

**Issue by Atemu** [minad/vertico#268]
When I `projectile-switch-project` and execute `vertico-directory-enter` on a project directory candidate in the resulting `projectile-completing-read`, it inserts the candidate.

What I'd actually expect it to do is to select the project and exit; allowing projectile to run its `projectile-switch-project-by-name` on the project.

Would making a new metadata category `project` make sense? That way anything that tries to do special stuff with files (guarded behind the completion context's metadata being tagged with the `file` category) would stop doing so when confronted with projects.

**Comment by minad** [comment]
Duplicate #251. Should already be fixed, but the fix hasn't been released yet.
