### ISSUE TITLE
`vertico-repeat` doesn't restore position in `consult-ripgrep`

### ISSUE THREAD

**Issue by Atemu** [minad/vertico#270]
1. `consult-ripgrep`
2. Search for something
3. Select candidate 2
4. `C-g`
5. `vertico-repeat-last`

Expected behaviour: Candidate 2 should be selected again.

Actual behaviour: The first candidate is selected unconditionally.

**Comment by minad** [comment]
This is not possible since the consult-ripgrep candidates come in asynchronously. This issue has been reported before.

**Comment by minad** [comment]
Previously discussed in https://github.com/minad/consult/issues/433.

**Comment by Atemu** [comment]
Thanks for the pointer, I was not able to find it using GH's search.
