### ISSUE TITLE
Cycling and groups

### ISSUE THREAD

**Issue by salutis** [minad/vertico#271]
`vertico-cycle` set to `nil` applies to `vertico-next` but not `vertico-next-group`, which I found immensely confusing.  Bug or feature?  If a feature, how to disable cycling for good?

**Comment by minad** [comment]
Duplicate #233

**Comment by minad** [comment]
I suggest you copy the non cycling group commands from the old issues (or some other issue, search the tracker!) and add them to your configuration. You can then remap the group commands.

I don't plan to add the non cycling variants to Vertico since they are far less useful.
