### ISSUE TITLE
Can't make custom sorting functions work in vertico-multiform-commands for some commands

### ISSUE THREAD

**Issue by mattiasdrp** [minad/vertico#273]
First of all, let me start by thanking you for your awesome packages, I rewrote my config to use them and I'm so glad I did because it fits my needs of customisation perfectly :-)

I set both variables like this 

```
(setq vertico-multiform-commands
          '((consult-imenu buffer)
            (consult-line buffer)
            (execute-extended-commandmouse)
            ;; (find-file (vertico-sort-function . sort-directories-first))
            (insert-char (vertico-sort-functions . vertico-sort-alpha))
            (describe-symbol (vertico-sort-functions . vertico-sort-alpha))))

    (setq vertico-multiform-categories
          '((file (vertico-sort-function . sort-directories-first))))
```

If I use the `find-file` line instead of the `file` one it works the same, when I try to find a file it will sort by directories first then files. But I can't make it work for `insert-char` and `describe-symbol`. 

If I `(setq vertico-sort-function 'vertico-sort-alpha)` everything will be sorted alphabetically and `find-file` or `file` will overwrite this behaviour. 

I even put unbound symbols for `insert-char` and `describe-symbol` and no error was raised. It looks like these functions are not taken into account but I don't know how to check it.

**Comment by minad** [comment]
Thanks! Try vertico-sort-function or vertico-sort-override-function. The override will take precendence over the sort function specified by the command itself (e.g. insert-char).

**Comment by mattiasdrp** [comment]
Wait, I just realised I wrote `vertico-sort-functions` with an `s`, it works perfectly without it. Sorry for the noise :D I thought there would be a package error if I miswrote something.

**Comment by minad** [comment]
I meant you should set the variable vertico-sort-override-function if vertico-sort-function doesn't work. This variable will always ensure that sorting is overriden.

> Wait, I just realised I wrote vertico-sort-functions with an s, it works perfectly without it.

Yes, I noticed this typo. Glad that this was the only issue.
