### ISSUE TITLE
Add a vertico-common-or-insert function

### ISSUE THREAD

**Issue by mattiasdrp** [minad/vertico#275]
`vertico-insert` will insert the candidate at point and I wasn't able to find a `vertico-common-or-insert` function that would insert the common part of all candidates or the candidate if there's only one. Is that already available or do you think it could be added?

**Comment by minad** [comment]
This command exists already under the name `minibuffer-complete`. You should specify the `basic` completion style to enable prefix completion. See https://github.com/minad/vertico#completion-styles-and-tab-completion
