### ISSUE TITLE
Extended search (e.g. Marginalia)

### ISSUE THREAD

**Issue by sienic** [minad/vertico#277]
Hi there, I am wondering if we can have extended search, i.e. not only through candidates, but the whole line that gets rendered in the completion minibuffer.

The following is an example (note: Consult here is just for illustrative purposes).

## given: 
- having Vertico + Consult + Marginalia installed and configured.
- calling `consult-buffer`, and
- having the completion buffer filled with file names as candidates, and their directory path as marginalia comments.

## when:
- entering a query string

## then:
- only candidates that match the query string are displayed

## my-desirable-then
- candidates and directory path which match the query string are displayed

Any insights are much appreciated.
Happy to contribute as well, but would need some hints please 🙏

**Comment by minad** [comment]
Thanks for the proposal! See https://github.com/minad/vertico/issues/253, https://github.com/minad/marginalia/issues/126, https://github.com/minad/consult/issues/409 and https://github.com/oantolin/orderless/issues/30 for prior discussions. You can try https://github.com/oantolin/orderless/issues/30#issuecomment-898196817.

**Comment by sienic** [comment]
Hi @minad! 
Great, many thanks for the references! 🙌 
It didn't occur to me to search the issues for meta data or annotations 🤦

**Comment by minad** [comment]
We will add annotation matching to Orderless in https://github.com/oantolin/orderless/pull/162. `@pattern` will match pattern in the annotation.
