### ISSUE TITLE
global-visual-mode (visual-kill-line more specifically) and vertico

### ISSUE THREAD

**Issue by dmitrym0** [minad/vertico#278]
Howdy,

When I invoke vertico for `C-x C-f` (or `find-file`), I frequently use `C-a C-k` to kill the existing prompt. However it looks like global-visual-mode rebinds it to `kill-visual-line`:

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  kill-visual-line(nil)
  funcall-interactively(kill-visual-line nil)
  call-interactively(kill-visual-line nil nil)
  command-execute(kill-visual-line)
  read-from-minibuffer("......
```

I tried to rebind it back for vertico-map, but I must admit I don't quite know what I'm doing:

```
           (define-key vertico-map (kbd "C-k") #'kill-line)
```

Can you provide some guidance?

**Comment by minad** [comment]
See https://www.emacswiki.org/emacs/VisualLineMode and the workarounds to prevent it from being activated in the minibuffer.

**Comment by minad** [comment]
I suggest to not use global-visual-mode. Instead use this:

~~~
(add-hook 'text-mode-hook 'visual-line-mode)
~~~

**Comment by dmitrym0** [comment]
Thanks @minad , I'll give that a go!
