### ISSUE TITLE
org-roam-node tag name are truncated

### ISSUE THREAD

**Issue by YorkZ** [minad/vertico#280]
Firstly, thanks for this cool package. I'm switching to `vertico` from `Helm`, and so far I'm impressed!
However, my biggest issue at the moment is that when completing for `org-roam-node-find`, the tag names at right side have been truncated. I've spent some time trying to figure out how to config this, but because `vertico` is completely new to me, I wasn't able to find out a solution by myself. Therefore, I would appreciate it if someone could point out how to config vertico so that it won't truncate the tags for `org-roam`.
I've attached a screenshot to help understanding the issue I'm having. Thanks in advance.

![2022-09-16_16-12](https://user-images.githubusercontent.com/742238/190686457-ba8b2af8-2be6-4d8f-a04e-6c3f2de79255.png)

**Comment by minad** [comment]
The truncation must be happening on the side of org-roam when the candidates are formatted. Please open an issue there. Thanks!

**Comment by YorkZ** [comment]
@minad I actually don't believe this is an issue of `org-roam` because there was no truncation at all when I was using `Helm`. The problem shows up only after I switched to `vertico`. I can post the screenshot of using `Helm` (no truncating) if you need, please just let me know. Thank you.

**Comment by YorkZ** [comment]
@minad  OK, I just quickly switched back to using `Helm`, and here's the screenshot showing that nothing was truncated. Could you please have a look? Thank you.
![2022-09-17_03-13](https://user-images.githubusercontent.com/742238/190838574-243b64d7-fda9-49b3-92a8-0bef0fece37f.png)

**Comment by minad** [comment]
https://github.com/org-roam/org-roam/issues/2066

**Comment by YorkZ** [comment]
Thank you so much @minad for the link, and I've solved it after reading it by adjusting the tag length in `org-roam-node-display-template` from the previous `10` to `100`. For the record, here's what works in my `org-roam` setting in case someone come to here in the future:
```
(setq org-roam-node-display-template
      (concat "${title:*} " (propertize "${tags:100}" 'face 'org-tag)))
```
