### ISSUE TITLE
Prescient sorting when completing file names

### ISSUE THREAD

**Issue by Riyyi** [minad/vertico#282]
When completing file names and entering a directory, when you go back 1 level, prescient sorting doesnt seem to have applied. This only happens when youre completing a path that gets prefilled with the `default-directory` (in this example I opened `init.el` and then ran `M-x find-file`). However, if you clear the minibuffer contents then the sorting does seem to take place.

Vertico with prefilled path doesnt get sorted:
![vertico-bug](https://user-images.githubusercontent.com/1911807/191310252-eb75a667-e2a2-4db9-b1c4-4a2b3c0291d1.png)

Vertico with empty minibuffer contents gets sorted:
![vertico-bug-not-with-empty-minibuffer](https://user-images.githubusercontent.com/1911807/191310290-0f11bb23-2be3-4914-a203-ae9b6528fa8e.png)

Selectrum works in both cases:
![vertico-bug-selectrum-works](https://user-images.githubusercontent.com/1911807/191310317-4b3d3615-6e18-4750-a271-5a03902377d7.png)

I have tested this with a minimal working example for both Vertico and Selectrum:
``` emacs-lisp
;;; init.el --- -*- lexical-binding: t; -*-

;; Stop messing with my init.el
(setq custom-file "/dev/null")
(load custom-file 'noerror)

(require 'package)

(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))

(defun dot/install (package)
  (unless (package-installed-p package)
    (package-refresh-contents)
    (package-install package)))

(dot/install 'prescient)
(require 'prescient)
(setq completion-styles '(prescient basic))
(setq prescient-completion-enable-sort nil) ; dont know if this matters, but doesnt change behavior in this example
(prescient-persist-mode)

(dot/install 'vertico)
(require 'vertico)
(setq vertico-sort-function #'prescient-completion-sort)
(setq vertico-sort-override-function #'prescient-completion-sort)
(advice-add #'vertico-insert :after (lambda () (prescient-remember (vertico--candidate))))
(vertico-mode)

;; (dot/install 'selectrum)
;; (require 'selectrum)
;; (selectrum-mode)

;; (dot/install 'selectrum-prescient)
;; (require 'selectrum-prescient)
;; (selectrum-prescient-mode)

;;; init.el ends here
```

**Comment by minad** [comment]
I guess the issue is that the "prefilled path" (called the completion base string) gets added to the candidate.

https://github.com/minad/vertico/blob/8078b8cb940d6b2fe7578bc2e9c7cf1838cd092f/vertico.el#L732-L733

We need a different advice like this:

~~~ elisp
(advice-add #'vertico-insert :after
            (lambda ()
              (when (>= vertico--index 0)
                (prescient-remember
                 (substring-no-properties
                  (nth vertico--index vertico--candidates))))))
~~~

cc @okamsn who implemented the Prescient support. Maybe one should offer a prescient-vertico-mode as part of Prescient to simplify the integration?

**Comment by Riyyi** [comment]
Besides the unbalanced parens on the defun ;) it works as desired, thanks!

**Comment by minad** [comment]
> Besides the unbalanced parens on the defun ;) it works as desired, thanks!

It's a wiki!

**Comment by Riyyi** [comment]
> It's a wiki!

I wasn't aware the Wiki on GitHub was open to edit, I fixed the parentheses.
