### ISSUE TITLE
[Q] Do vertico, consult & embark together replace smex?

### ISSUE THREAD

**Issue by mhlr** [minad/vertico#284]
I am currently using ido-ubiquitous, ido-grid & smex.
I would like to try embark & consult, but those are not compatible with ido-ubiquitous.
If I switch to vertico & consult, how do I get the functionality of smex?

**Comment by minad** [comment]
I am not 100% familiar with amx/smex but as far as I know it provides the following features:

- Sorting by history/frequency -> Replaced by Vertico sorting by history
- Annotations -> Replaced by Marginalia
- Alternative actions (jump to help) -> Replaced by Embark
- Mode specific commands -> Replaced by consult-mode-command

Note that the packages are conceptually quite different. amx/smex aims to only improve M-x while vertico/orderless/marginalia/embark are much more far reaching and enhance every Emacs completion command.

Please let me know if there are other interesting features in amx/smex. We may already have equivalent features or could add them.

**Comment by mhlr** [comment]
What does M-x need to be bound to to get completions for executing commands?

**Comment by minad** [comment]
You don't have to bind anything except enabling vertico-mode and marginalia-mode.
