### ISSUE TITLE
How to sort by history but not alphabetically?

### ISSUE THREAD

**Issue by liushihao456** [minad/vertico#286]
I see that all `vertico-sort-*` functions includes "alpha", so what is the proper way to adjust the behavior of sorting to sort only by history but not by alphabet?

**Comment by minad** [comment]
Such a function doesn't exist yet. Unfortunately my macro `vertico--define-sort` cannot be used directly to produce such a sorting function. But you can use the macro expansion of

~~~ elisp
(vertico--define-sort (history alpha) 32 (if (eq % "") 0 (/ (aref % 0) 4)) string< string<)
~~~

to extract only the history sorting. I hope this is helpful for you. I am not sure if it makes sense to provide such a function out of the box. Can you please describe your use case precisely? If there are good reasons we could also adjust the define-sort macro to handle sorting by history only.

**Comment by liushihao456** [comment]
> But you can use the macro expansion of
>
> (vertico--define-sort (history alpha) 32 (if (eq % "") 0 (/ (aref % 0) 4)) string< string<)
> to extract only the history sorting.

OK, let me try it. The macro looks intimidatingly complex, tho, LOL.

>  Can you please describe your use case precisely?

I want to create a custom sorting function based on [flx](https://github.com/lewang/flx) that sorts the candidates in a fuzzy-scoring style. Meanwhile I want to keep the sort-by-history feature of vertico so that frequently used items, if any, come at top. Therefore, I'm thinking of adding the flx-sorting function as an advice to the function `vertico-sort-history` which unfortunately does not exist.

**Comment by minad** [comment]
> I want to create a custom sorting function based on [flx](https://github.com/lewang/flx) that sorts the candidates in a fuzzy-scoring style. Meanwhile I want to keep the sort-by-history feature of vertico so that frequently used items, if any, come at top. Therefore, I'm thinking of adding the flx-sorting function as an advice to the function vertico-sort-history which unfortunately does not exist.

Okay, I see. This sounds like a use case on the experimental side. For now I won't add sorting by history only to Vertico. Btw, are you aware of https://github.com/jojojames/fussy?

**Comment by liushihao456** [comment]
> Btw, are you aware of https://github.com/jojojames/fussy?

Yes. I saw you mention this in another issue. It registers a new completion style. According to my understanding, the problem  of it is that it cannot be used together with orderless, meaning I can't split queries into subqueries with spaces. Only one completion style can be active at the same time.
