### ISSUE TITLE
(idea) Is it possible to display line numbers in vertico buffer mode?

### ISSUE THREAD

**Issue by yusi1** [minad/vertico#287]
Hi minad, amazing package!

I have a question about whether you are able to show line numbers inside `vertico-buffer`, protesilaos' `mct` has this ability, I wonder if `vertico-buffer` can do this too.

I tried adding `display-line-numbers-mode` to `vertico-buffer-mode-hook` but it doesn't work.

**Comment by minad** [comment]
Thanks. Yes, you can enable `vertico-indexed-mode`.

**Comment by yusi1** [comment]
Nice! That's exactly what I wanted.
