### ISSUE TITLE
vertico-buffer with more than one frame: brief flashes of the prompt underneath vertico-buffer

### ISSUE THREAD

**Issue by yusi1** [minad/vertico#288]
Hi minad.

I have a strange bug with `vertico-buffer` where if you spawn more than one frame, when you have `vertico-buffer-mode` enabled, and do anything like `find-file` or `exectute-extended-command`, a brief flash of the prompt is displayed in the echo area below the `vertico-buffer` popup.

This doesn't occur when only one frame is being used.

I've attached a video that tries to show the behavior:
(at 0:06 I spawn the new frame)
(at 0:12 you can see the problem)
(at 0:17 you can see it again)
(at 0:20 I delete the other frame)
(at 0:22 I do `find-file` and the problem doesn't appear with only one frame)

https://user-images.githubusercontent.com/82241382/192985093-51279816-9fa2-4104-a26f-d22905b9f54a.mp4

**Comment by minad** [comment]
See the code which hides the prompt:

https://github.com/minad/vertico/blob/8078b8cb940d6b2fe7578bc2e9c7cf1838cd092f/extensions/vertico-buffer.el#L86-L88

You can play around with this code. Maybe you have a better idea how the prompt could be hidden? If I recall correctly, I also tried to use an overlay to push the content down. It could also be that the code is executed too late for some reason.

Anyway I am not fond of multi frame setups and I don't recommend them. The Emacs display system is overall quite brittle, and even more so in combination with multiple frames which brings the window manager into the game.
