### ISSUE TITLE
Candidates are invisible when prompt is too long

### ISSUE THREAD

**Issue by DamienCassou** [minad/vertico#29]
The prompt is sometimes very long, preventing the user from seeing candidates:
![2021-05-11-150208](https://user-images.githubusercontent.com/217543/117819576-f6fcb980-b269-11eb-9441-0a42eaf98a47.png)

In this screenshot, the beginning of the prompt and the candidate are off-screen.

**Comment by minad** [comment]
Selectrum adds spaces in front of the candidates in this case. I am not particularly fond of this fix. It would be better to somehow wrap the prompt. Alternatively each command should ensure that it does not create these mega prompts. You can fix this using an advice on `completing-read-prompt`, which truncates the prompt.

**Comment by DamienCassou** [comment]
Thank you very much!
