### ISSUE TITLE
Vertico doesn't show in *shell* buffers

### ISSUE THREAD

**Issue by snan** [minad/vertico#290]
I have sometimes found that Vertico doesn't open the vertical part, only a single line minibuffer (which then starts flickering as I'm typing). The one place I'm getting this behavior consistently is in \*shell\* buffers. I'll troubleshoot more if you have somewhere I could start unraveling.

**Comment by snan** [comment]
The entire lower half of the screen is flickering since Vertico does open but then immediately closes.

**Comment by minad** [comment]
Thanks for the report. I could not observe this issue so it is likely due to some interaction in your configuration. Which Emacs version and which operating system do you use? Please try to create a minimal setup based on emacs -Q which reproduces the issue.

**Comment by snan** [comment]
Thank you for taking a look. Yeah, you're absolutely right, not only can't I reproduce it on emacs -Q, I can't even reproduce it with my own full .emacs.d loaded on restart. I must have something loaded in my existing session that's not in my conf files. 🤦🏻‍♀️
