### ISSUE TITLE
Select first candidate by default during `find-file`

### ISSUE THREAD

**Issue by muirdm** [minad/vertico#291]
When running find-file I'd like the first candidate file to be selected/highlighted by default instead of the `default-directory` input value. For example, If I `find-file` in a directory that only contains one file/directory, I want to be able to press `vertico-directory-enter` immediately without having to first select the only candidate. How can I tweak this behavior? Thanks!

**Comment by minad** [comment]
You can press TAB to always enter the first directory. Besides that there is currently no option to always select the first candidate, but you can use an advice. Duplicate #272

**Comment by muirdm** [comment]
Note that there doesn't seem to be a way to choose the first file with a single key. I want to do this relatively frequently when a directory only has a single file (and I want to open it).

For others, this advice worked for me (the tip in the linked issue above is slightly out of date):

```elisp
(advice-add #'vertico--update :after #'muir-vertico-select-first-candidate)
(defun muir-vertico-select-first-candidate (&optional interruptible)
  (when (and (= vertico--index -1) (> vertico--total 0))
    (setq vertico--index 0)))
```

Note that this makes it impossible to manually go up and select the input. I bind <C-return> to vertico-exit-input for cases when I want to select the input and not a candidate.

**Comment by minad** [comment]
> Note that there doesn't seem to be a way to choose the first file with a single key. I want to do this relatively frequently when a directory only has a single file (and I want to open it).

I don't think it is frequent or you use directories in the wrong way :-P A better argument would be that you always want the first file selected since the most recently used file will be sorted to the top.

> Note that this makes it impossible to manually go up and select the input. 

I guess a better advice is this:

~~~ elisp
(advice-add #'vertico--recompute :filter-return #'vertico--select-first)
(defun vertico--select-first (state)
  (when (> (alist-get 'vertico--total state) 0)
    (setf (alist-get 'vertico--index state) 0))
  state)
~~~
