### ISSUE TITLE
Sort specified via vertico-multiform-commands is not always used

### ISSUE THREAD

**Issue by ALSchwalm** [minad/vertico#292]
Currently, the `vertico-multiform` extension allows the user to specify `vertico-multiform-commands` which can be used to (among other things) set `vertico-sort-function` on a per-command basis. However, the implementation of `vertico--sort-function` means that these command-specific overrides will not be used if there is any `display-sort-function` in the metadata for the command:

```
(defun vertico--sort-function ()
  "Return the sorting function."
  (or vertico-sort-override-function
      (vertico--metadata-get 'display-sort-function)
      vertico-sort-function))
```

These is particularly troublesome when using `flex` completion style, which seems to insert its own `display-sort-function` if one isn't defined. It seems to me that if a user is specifying a specific sort function to use via `vertico-multiform-commands`, it should definitely be used regardless of any `display-sort-function` that may be defined for the command.

I realize that switching to this behavior could be a breaking change for some users (though probably unlikely). To maintain backward compatibility, perhaps there could be a `:force` flag used to indicate that the command-specific override should definitely be used?

**Comment by minad** [comment]
vertico-sort-override-function
