### ISSUE TITLE
vertico--candidates access in post-command-hook

### ISSUE THREAD

**Issue by haji-ali** [minad/vertico#293]
I followed the answer that @minad have in #133 write the following 

```lisp
(minibuffer-with-setup-hook
    (lambda ()
      (add-hook 'post-command-hook
                (lambda ()
                  ;; Exit directly if a quick key is pressed
                  (let ((prefix (minibuffer-contents-no-properties)))
                    (let ((cand vertico--candidates))
                      (with-current-buffer (get-buffer-create "*DEBUG*")
                        (goto-char (point-max))
                        (insert (format "%S %S\n" prefix cand))))
                    (mapc (lambda (cand)
                            (when (equal prefix
                                         (substring cand 0 1))
                              (setq quick-result cand)
                              (exit-minibuffer)))
                          vertico--candidates)))
                -1 'local))
  (completing-read
   "Pick: " '("great" "test" "jar" "icon")))
```

If I execute this command and press `g` then `great` gets selected and, in `*DEBUG*` I get the output 
```
"" nil
"g" ("jar" "icon" "test" "great")
```
as expected. I've adopted this for many interfaces where I execute this code with key-press and quickly/immediately press `g` to select the correct candidate (almost like a keymap instead of a completing menu).
However, sometimes (not consistently though persistently), when I press `g` really fast after executing the previous command (or when my computer is busy with something else that Emacs is sufficiently slow) `great` is not selected and I get the output

```
"" nil
"g" nil
```

Any idea why this could be happening? It's super difficult to debug because the behavior is not consistent and I couldn't find a reliable way to reproduce the wrong behavior.

**Comment by minad** [comment]
The candidate computation in Vertico is interruptible (by key presses). Therefore vertico--candidates may be nil. See vertico--update to force the candidate computation. I hope this helps :)

**Comment by haji-ali** [comment]
Yep, that fixed it. Thanks!

I assume that you mean that I should call it in my `post-command-hook`? If I do this, I would be calling `vertico--update` multiple times, one in `vertico--exhibit` and one in mu `post-command-hook`, correct?
This didn't seem to have a significant performance hit, but can I suggest that the argument that is passed to `vertico--update` in `vertico--exhibit` be made into a variable so that it can be customized in such and similar situations?

**Comment by minad** [comment]
vertico--update caches the result and avoids unnecessary recomputations.
