### ISSUE TITLE
Vertigo does not respect `:exit-function` from `completion-extra-properties`

### ISSUE THREAD

**Issue by iwahbe** [minad/vertico#295]
`completion-extra-properties` can be let bound to give extra behavior to a completion session. According to the doc comment for `completion-extra-properties`:
```
Property list of extra properties of the current completion job.

These include:

...

:exit-function: Function to run after completion is performed.

   The function must accept two arguments, STRING and STATUS.
   STRING is the text to which the field was completed, and
   STATUS indicates what kind of operation happened:
     finished - text is now complete
     sole     - text cannot be further completed but
                  completion is not finished
     exact    - text is a valid completion but may be further
                  completed.
```

It would be great if `vertico` respected this setting. 

---

If you don't have time/energy/interest, I would be happy to open a PR for this. Let me know if that would be helpful. I think the call should go right before `(exit-minibuffer)` in `vertico-exit`. https://github.com/minad/vertico/blob/8078b8cb940d6b2fe7578bc2e9c7cf1838cd092f/vertico.el#L663-L671.

**Comment by minad** [comment]
Yes, we can add this. But is this feature used anywhere? As far as I know this API is only relevant for completion-in-region. I also have to check the behavior of the default completion ui.

**Comment by minad** [comment]
I just tried this with the default completion UI. The exit function is not called if you type `foo RET` or `first RET`.

~~~ elisp
(let ((completion-extra-properties (list
                                    :exit-function
                                    (lambda (&rest args)
                                      (message "EXIT %S" args)))))
  (completing-read "Prompt: " '(first second third fourth)))
~~~

As I wrote above, the exit function is meant for completion in-buffer. Note that `minibuffer-complete` uses `completion-in-region` internally. This conflates minibuffer completion with in-buffer completion.

**Comment by iwahbe** [comment]
Ok. 

I really appreciate the quick response. The docs for `completion-extra-properties` don't mention anywhere (that I saw) that `:exit-function` only applies to `complete-in-region`. Thanks for clarifying.

**Comment by minad** [comment]
> I really appreciate the quick response. The docs for completion-extra-properties don't mention anywhere (that I saw) that :exit-function only applies to complete-in-region. Thanks for clarifying.

Yes, the docs regarding completion are not comprehensive unfortunately. I concluded this from the behavior of the default completion UI, see my example above.

But more importantly, is there a use case for this? Do you need the exit-function somewhere with completing-read and Vertico? If yes, then the upstream behavior could be clarified and improved and Vertico could be adapted accordingly.

**Comment by iwahbe** [comment]
I have a use case for a package I'm working on. I build a pretty heavy in-memory structure and would like a supported method of cleanup that is aware of how the completion ended.

I'll email emacs with a patch to clarify the documentation for the existing functionality. If I can't find a clean alternative, I'll also add a patch supporting functionality as I though existed.

**Comment by minad** [comment]
On 11/21/22 19:16, Ian Wahbe wrote:
> I have a use case for a package I'm working on. I build a pretty heavy
> in-memory structure and would like a supported method of cleanup that is
> aware of how the completion ended.
>
> I'll email emacs with a patch to clarify the documentation for the
> existing functionality. If I can't find a clean alternative, I'll also
> add a patch supporting functionality as I though existed.

I don't think an addition is needed. You can probably use the
minibuffer-exit-hook for this. Can you be more clear about your use
case? Why do you need the result of the completion? Do you control the
completing-read call or do you want a mechanism to hook into existing
completion commands?

**Comment by iwahbe** [comment]
I'll look at the `minubuffer-exit-hook`. 

Use case: I have a package (called jsonian, if your interested) to read/explore json documents. I need this package to be fully functional for very large documents (> 500k lines), so both performance and memory footprint are unfortunately relevant. I'm looking to provide more information for each node when I'm doing an interactive `completing-read` (`jsonian-find`) exploring the document, and I would like to clean up cached information not near the path of the selected completion. This cleanup needs to know what completion was selected, and if it was valid.

I control the completing read call, so I should be able to do this with existing features, but I think it would have been nicer if `completion-extra-properties` worked as I expected.

**Comment by minad** [comment]
> I control the completing read call, so I should be able to do this with existing features, 

I strongly recommend to stick to the existing features. Since you control completing-read you get the selected candidate obviously (the return value). Also you don't need a hook, better use unwind-protect around the completing-read call.

> but I think it would have been nicer if completion-extra-properties worked as I expected.

Well, this just means your expectation was wrong. I don't see why it would be nicer. The exit-function as designed is useful for in-buffer completion, but not for completing-read, since you can get by with the existing features. This is also the reason why Vertico doesn't support the exit-function. In contrast, my Corfu package of course supports the exit-function. I also make heavy use of the exit-function in my Cape and my Tempel packages, which provide Capfs (completion-at-point-functions).

**Comment by minad** [comment]
Let me add this general advice: If your first reaction is that your exception wasn't met and that something obvious must be missing and should be added, better take a step back and think again if you can get by with what is already there. Minimal APIs are advantageous for both the API implementor and the user, since the API will be easier to understand. Less is more. ;)

This is also the approach I try to follow with my packages, which aim to be minimal and try to stick to the essentials.

(Of course there are exceptions, where adding API features is justified, e.g., if a certain pattern is used repeatedly and leads to a lot of duplication.)

**Comment by iwahbe** [comment]
> > I control the completing read call, so I should be able to do this with existing features,
> 
> I strongly recommend to stick to the existing features. Since you control completing-read you get the selected candidate obviously (the return value). Also you don't need a hook, better use unwind-protect around the completing-read call.

I didn't think of `unwind-protect`. Thanks!

> 
> > but I think it would have been nicer if completion-extra-properties worked as I expected.
> 
> Well, this just means your expectation was wrong. ...

Yes, my expectation was completely wrong. What I said was unclear. I meant it would have been nicer for me if it worked as I expected it to. I did not mean that it would be a better API in general.

> Let me add this general advice: If your first reaction is that your exception wasn't met and that something obvious must be missing and should be added, better take a step back and think again if you can get by with what is already there. Minimal APIs are advantageous for both the API implementor and the user, since the API will be easier to understand. Less is more. ;)

I agree. The only thing that threw me was that the docs mentioned that `completion-extra-properties` effects completion sessions, and some parts definitely effect `completing-read`. More important than minimalism, APIs should have clear contracts. That certain properties are only respected in certain kinds of sessions wasn't obvious to me, especially as someone who doesn't have much experience with the completion API.

**Comment by minad** [comment]
> More important than minimalism, APIs should have clear contracts.

Fully agree. I try to enforce the contracts in Vertico precisely. But due to missing documentation, I sometimes have to make guesses based on my understanding of the design, as in the case of the exit-function.
