### ISSUE TITLE
file-name-history sorting

### ISSUE THREAD

**Issue by tpeacock19** [minad/vertico#296]
I've been running into this issue for a little while now but I don't believe I understand how the `vertico-sort-history-*` functions should work. I would expect them to sort by history according to the `minibuffer-history-variable`, then subsequently length/alpha. However, I don't seem to get that when running `project-find-file`. I've made a repo since it was the easiest way for me to test and share without creating files on someone else's system.

You can clone this repo https://github.com/tpeacock19/vertico-sort-test and run `emacs --init-directory path/to/repo/vertico-sort-test/.emacs.d` and it should run. You'll need to complete the `project-find-file`
interactive call (i couldn't find a way to do this non-interactively) and then the scratch buffer should populate with the differences I see between `vertico-sort-history-*` versus something like `(minibuffer--sort-by-position file-name-history cands)`

**Comment by minad** [comment]
But find-file sorts as expected? In Vertico find-file/file-name-history is special cased.

Unfortunately project-find-file works differently. It uses a path relative to the project directory. Furthermore it stores relative paths in the find-file-history, instead of absolute paths. I've seen that @astoff made a change in Emacs master, such that absolute paths are used.

Probably these differences break project-find-file vs find-file. Now I could also special case project-find-file such that it works out of the box. Not sure how big the required change would be. But given that project.el is in flux it is better to not do this.

The better solution is to use vertico-multiform and use a custom vertico-sort-function for project-find-file. One can probably reuse many of the existing vertico sort helper functions.

**Comment by minad** [comment]
To give more background - the only problem is really how the history hash table is built. See:

https://github.com/minad/vertico/blob/a28503bcd92d14c77438dd0796b1d7368da4c33e/vertico.el#L195

The bucket sort function itself could stay as is.

**Comment by tpeacock19** [comment]
In the repo I shared I hard coded the `file-name-history` variable. I've just now tried it with both `project-find-file` and `find-file` and neither of them reflect exactly what I've set it to.

**Comment by tpeacock19** [comment]
> The better solution is to use vertico-multiform and use a custom vertico-sort-function for project-find-file. One can probably reuse many of the existing vertico sort helper functions to write the custom sort function.

Yes, I've already gotten a workaround for this. I just was curious if it was really necessary. I`m happy with what it does, even though it is a bit verbose.

```elisp
(defun project-files-sort (files)
  (let* ((f (buffer-file-name
             (window-buffer (minibuffer-selected-window))))
         (hist (symbol-value minibuffer-history-variable))
         (root (expand-file-name (project-root (project-current)))))
    (if (file-name-absolute-p (car files))
        (minibuffer--sort-by-position
         hist (cl-remove f files :test #'cl-equalp))
      (minibuffer--sort-by-position
       (minibuffer--sort-preprocess-history root)
       (cl-remove (string-remove-prefix root f) files
                  :test #'cl-equalp)))))
```

**Comment by tpeacock19** [comment]
> Unfortunately project-find-file works differently. It uses a path relative to the project directory. Furthermore it stores relative paths in the find-file-history, instead of absolute paths. I've seen that @astoff made a change in Emacs master, such that absolute paths are used.

This is only the case if you choose to have it show relative file names. I set it to absolute in the repo specifically for this.

**Comment by minad** [comment]
Okay, is there anything we could do to improve the situation? I mean specifically the hash table computation, which is used by the sort function. If we could fix this with a simple change I am open to a fix. But ideally I'd like to avoid project-find-file specifics.

**Comment by minad** [comment]
I just looked into `project-find-file`. There are two problems due to the candidates being relative paths:

- The candidates are not path components like for `find-file`.
- The candidates are relative, but the history contains absolute paths (at least since @astoff's patch).

If we would add special casing we would just have to remove the project root from the candidates. For now you could also try an advice around `vertico--history-hash`.

~~~
(advice-add #'vertico--history-hash :around #'vertico--project-history-hash)

(defun vertico--project-history-hash (&rest app)
  (let ((file-name-history (mapcar #'vertico--project-remove-the-root file-name-history)))
    (apply app)))
~~~

Alternatively project.el could avoid using `file-name-history`, then this problem would go away automatically.

**Comment by astoff** [comment]
> I've seen that @astoff made a change in Emacs master, such that absolute paths are used.

To clarify, my patch only changes how history entries are created (they now contain the absolute file name); this makes sense because `project-find-file` shares the history variable with `find-file` et al. The  candidate list of `project-find-file` is unchanged, and I'm pretty sure it's an intentional decision to present the file names relative to the project root.

**Comment by tpeacock19** [comment]
I don't know if my point is being understood. The issue exists with both `find-file` and `project-find-file`. Not sure if you had a chance to look at the repo but it should show this. 

I'm not sure I understand what you mean by the special casing for `find-file`? I'll work on a more simple example to show you in a bit. It's just difficult for me to understand your macro.

**Comment by tpeacock19** [comment]
The relative name vs absolute history can also be handled with `minibuffer--sort-preprocess-history` as I did with my sorting function above. Essentially does what you mention with the advice. I am not sure how generalized that could be though.

**Comment by minad** [comment]
@tpeacock19 I think I don't understand your issue then. find-file works well for me (sorting by history). project-find-file doesn't work, but that's expected. It is a wontfix. Can you describe the problem better in words, such that I don't have to checkout your external recipe? Does find-file sorting work for you?

@astoff I agree with your change. But I am a bit sceptical regarding the history sharing.

**Comment by tpeacock19** [comment]
This is the directory 

```shell
.
├── a-four.org
├── b-three.el
├── c-two.el
├── d-one.el
├── .emacs.d
├── .emacs.dauto-save-list
├── .git
└── .gitignore

3 directories, 5 files
```

The comments below each command is an export of the minibuffer prior to any input.
```elisp
(let* ((default-directory "/home/user/src/emacs/pkg/vertico-sort/")
       (file-name-history  '("/home/user/src/emacs/pkg/vertico-sort/d-one.el"
                             "/home/user/src/emacs/pkg/vertico-sort/b-three.el"
                             "/home/user/src/emacs/pkg/vertico-sort/c-two.el"
                             "/home/user/src/emacs/pkg/vertico-sort/a-four.el"))
       (minibuffer-history-variable 'file-name-history)
       (vertico-sort-function #'vertico-sort-history-length-alpha))

  (call-interactively 'find-file)
  ;; -rw-r--r-- 1 user 1.1K Nov 27 19:37 c-two.el
  ;; -rw-r--r-- 1 user 1.1K Nov 27 19:37 d-one.el
  ;; drwxr-xr-x 1 user   72 Nov 27 20:23 .emacs.d
  ;; -rw-r--r-- 1 user   37 Nov 27 19:54 .gitignore
  ;; -rw-r--r-- 1 user   14 Nov 27 19:36 a-four.org
  ;; -rw-r--r-- 1 user 1.1K Nov 27 19:59 b-three.el
  ;; drwx------ 1 user    0 Nov 27 22:39 .emacs.dauto-save-list

  
  (call-interactively 'project-find-file)
  ;; -rw-r--r-- 1 user 1.1K Nov 27 19:37 c-two.el
  ;; -rw-r--r-- 1 user 1.1K Nov 27 19:37 d-one.el
  ;; -rw-r--r-- 1 user   37 Nov 27 19:54 .gitignore
  ;; -rw-r--r-- 1 user   14 Nov 27 19:36 a-four.org
  ;; -rw-r--r-- 1 user 1.1K Nov 27 19:59 b-three.el
  ;; -rw-r--r-- 1 user 3.4K Nov 27 22:27 .emacs.d/init.el
  ;; -rw-r--r-- 1 user   58 Nov 27 20:04 .emacs.d/projects
  )
```

**Comment by tpeacock19** [comment]
> > I've seen that @astoff made a change in Emacs master, such that absolute paths are used.
> 
> To clarify, my patch only changes how history entries are created (they now contain the absolute file name); this makes sense because `project-find-file` shares the history variable with `find-file` et al. The candidate list of `project-find-file` is unchanged, and I'm pretty sure it's an intentional decision to present the file names relative to the project root.

@astoff another note. The `file-name-history` will now have a mix of absolute and abbreviated file names. It would be great to have that consistent. For example: 

default adding history
https://github.com/emacs-mirror/emacs/blob/master/lisp/files.el#L1784-L1786
```elisp
(defun file-name-history--add (file)
  "Add FILE to `file-name-history'."
  (add-to-history 'file-name-history (abbreviate-file-name file)))
```

loading from recentf
https://github.com/emacs-mirror/emacs/blob/5b325a03c50d5d828d2a7934bb74f30a45fa108d/lisp/recentf.el#L1330-L1344
```elisp
(defun recentf-load-list ()
  "Load a previously saved recent list.
Read data from the file specified by `recentf-save-file'.
When `recentf-initialize-file-name-history' is non-nil, initialize an
empty `file-name-history' with the recent list."
  (interactive)
  (let ((file (expand-file-name recentf-save-file))
        ;; We do not want Tramp asking for passwords.
        (non-essential t))
    (when (file-readable-p file)
      (load-file file)
      (and recentf-initialize-file-name-history
           (not file-name-history)
           (setq file-name-history (mapcar #'abbreviate-file-name
                                           recentf-list))))))
```

I'll send an email to the mailing list to avoid cluttering this issue.

**Comment by minad** [comment]
@tpeacock19 I think the problem may be that your paths are absolute. The mini buffer initial input is ~/src/emacs/...

**Comment by minad** [comment]
Right, you also saw that project.el adds absolute paths. This is indeed wrong and should be fixed.

**Comment by minad** [comment]
Not sure what's wrong then. I will try your recipe later.

**Comment by minad** [comment]
@tpeacock19 There is nothing wrong in my setup and with emacs -Q. I tried the following and got the expected result:

~~~ elisp
(let* ((default-directory "/home/user/foo/")
       (file-name-history  '("~/foo/d-one.el"
                             "~/foo/b-three.el"
                             "~/foo/c-two.el"
                             "~/foo/a-four.el"))
       (minibuffer-history-variable 'file-name-history)
       (vertico-sort-function #'vertico-sort-history-length-alpha))
  (call-interactively 'find-file))
~~~

**Comment by tpeacock19** [comment]
I really don't know what the difference between ours is. I've

**Comment by astoff** [comment]
(FWIW, I've submitted a fix for the `project-find-file` history business.)

**Comment by minad** [comment]
@tpeacock19 I don't observe any disruption with a .temp file or directory.
