### ISSUE TITLE
disable fetching initial candidates (for M-x man)

### ISSUE THREAD

**Issue by lina-bh** [minad/vertico#297]
On macOS at least, trying to use M-x man attempts to index every manual page in the system, which takes Emacs about a second and a half before it is ready to accept input. Is it possible using vertico-multiform-commands to stop Vertico from gathering all candidates before input?

**Comment by minad** [comment]
Yes, you can, but you have to write your own completion style. Generally all filtering is performed by completion styles. The mechanism is very flexible. The following example style is wrapping Orderless, but you could of course use a different style.

~~~ elisp
(defun +orderless-min-input-all-completions (string table pred point)
  ;; Refuse to compute candidates if input is too short
  (and (length> string 2)
       (or (orderless-all-completions string table pred point)
           ;; Fallback to prefix completion to support dynamic completion tables
           (completion-emacs21-all-completions string table pred point))))

(defun +orderless-min-input-try-completion (string table pred point)
  ;; Refuse to compute candidates if input is too short
  (and (length< string 2)
       (or (orderless-try-completion string table pred point)
           ;; Fallback to prefix completion to support dynamic completion tables
           (completion-emacs21-try-completion string table pred point))))

(add-to-list 'completion-styles-alist
             '(+orderless-min-input
               +orderless-min-input-try-completion
               +orderless-min-input-all-completions
               "Orderless completion style, which requires minimal input."))

(setq completion-styles '(+orderless-min-input)
      completion-category-defaults nil
      completion-category-overrides nil)
~~~

After having written such a style you can use it only for a few commands or completion categories via `vertico-multiform-mode`. Does this help?

**Comment by minad** [comment]
But I should add - the problem you have is not actually a problem, since the candidate computation is interruptible. You can just starting typing and Vertico will directly start filtering, even if the prompt is not yet visible. If you want to see the prompt immediately you can add this:

~~~ elisp
(advice-add #'vertico--setup :before #'redisplay)
~~~

The downside is then that the prompt will flicker for commands which start much faster. Therefore Vertico doesn't usually redisplay before initialization.

**Comment by lina-bh** [comment]
I tried both approaches but the lag doesn't go away. I think the problem is not with vertico and is with man itself, since when vertico is disabled completions take forever anyway. Is there a way to disable vertico for this or any other specific command? M-x woman doesnt have this lag, but doesn't pick up man pages on my system.

You can see how the lag prevents input even after vertico-setup is adviced:
https://user-images.githubusercontent.com/36717206/205398245-eb45b36d-7ad6-4a68-910d-133e5fa254e6.mov

**Comment by minad** [comment]
Then there is no fix, but you can send a bug report to the Emacs Mac maintainer. 

As an alternative there exists my asynchronous consult-man command.

**Comment by lina-bh** [comment]
To conclude this, what I did was install man-db from homebrew, run gmandb, do (setq manual-program "gman") and just be done with it

**Comment by lina-bh** [comment]
This still bugs me, and using gman or mandoc doesn't actually help since they don't index macOS pages by default and I cannot figure out how to make them do that. So just do this instead:

```elisp
(defun macos-man-completion-table-before-while (&rest _)
    "If running under macOS, do not attempt to complete manual page names, since the whatis index is broken post-SIP."
    (not (eq system-type 'darwin)))
(advice-add #'Man-completion-table :before-while #'macos-man-completion-table-before-while))
```

Unfortunately `consult-man` sets `require-match` so you get the same issue of having to wait for `makewhatis` to run each time.
