### ISSUE TITLE
vertico-buffer behavior with read-minibuffer-restore-window

### ISSUE THREAD

**Issue by marcolgl** [minad/vertico#299]
Hi,
using `vertico-buffer-mode` when `read-minibuffer-restore-window` is set to `nil` leaves the window used for vertico displaying the inactive minibuffer, after executing the command (or aborting it). I hope the video is more explanatory:

https://user-images.githubusercontent.com/33786518/207187150-599df692-9416-48fe-a85f-60a57ffc3ac3.mp4

That is tested with `emacs -Q` on emacs-30.0.50.1 and vertico 0.29 (last commit from source 89987d9).

That probably isn't what any user would expect after calling the command. I think the expected behavior should be to:
- restore whatever buffer was in the window if it was reused by the vertico buffer
- kill the window if it was created for the vertico buffer 

Note that in both cases, it shouldn't restore the whole window config. since `read-minibuffer-restore-window` is unset.

I managed to achieve that, saving the buffers per-window and then, in case, restoring the one of the chosen window, like follows:

```diff
 (defun vertico-buffer--setup ()
   "Setup buffer display."
   (add-hook 'pre-redisplay-functions 'vertico-buffer--redisplay nil 'local)
      (let* ((action vertico-buffer-display-action) tmp win
> 	     (winbuf-alis (cl-map 'list (lambda (el)
> 			                  `(,el . ,(window-buffer el)))
> 	                          (window-list)))
---
                    (when (window-live-p win)
> 		      (with-selected-window win
> 			(if-let ((prev-buf (cdr (assoc win winbuf-alis))))
> 				(set-window-buffer win prev-buf)
> 			  (delete-window win)))
```
Do you agree on intended behavior, and in case do you think there is a more elegant solution?
Thanks for your consideration and, again, for the great work on this package.

**Comment by minad** [comment]
Thanks. I will give your patch a try.

**Comment by marcolgl** [comment]
Thanks for looking into it, now works fine.
