### ISSUE TITLE
Behavior when pressing backspace on empty command

### ISSUE THREAD

**Issue by joshcho** [minad/vertico#300]
I am coming over from Selectrum, and noticed a different behavior. I am not sure if this is by design.

When I press backspace when the command is empty, I get my cursor placed after [Text is read-only], instead of before it.

p.s. Also I have been looking at getting just the # of entries displayed before command like in Selectrum, but haven't fonud how.

**Comment by minad** [comment]
Yes, the only issue is that the cursor placement is wrong, behind the minibuffer message overlay instead of before it. It could also be that this is an emacs bug. The overlay is created by set-minibuffer-message.

**Comment by minad** [comment]
See also this comment in set-minibuffer-message: https://github.com/emacs-mirror/emacs/blob/1568123196cd8b57ed64e284b7deb058026be713/lisp/minibuffer.el#L755-L757. So one could ask on the Emacs bug tracker about this issue.
