### ISSUE TITLE
Not showing M-x org-show-all

### ISSUE THREAD

**Issue by Ypot** [minad/vertico#301]
After updating to org-mode 9.6 I can't see at least this function:
"org-show-all" with M-x

I can write it down, and it works, of course.
![imagen](https://user-images.githubusercontent.com/30699014/207674568-592ed44c-0c75-4148-9c9d-cedc04eaa94a.png)

**Comment by minad** [comment]
The command is obsolete. You probably use `(setq read-extended-command-predicate #'command-completion-default-include-p)`.

**Comment by Ypot** [comment]
"This command is obsolete since 9.6; use org-fold-show-all instead."
https://list.orgmode.org/c7b94f21-d9ec-eea3-c973-2692b5308bc2@gmail.com/T/#e0baa7903684f61d2455d62ee463f6235963f2bc5
