### ISSUE TITLE
vertigo-directory-enter does not behave like ido ret

### ISSUE THREAD

**Issue by vspinu** [minad/vertico#302]
The docs of `vertigo-directory` states "Ido-like directory navigation for Vertico" but it's not quite the same. RET does not enter the first option in the completion list when there is no input. From the code it seems that it's by design which renders the doc of the package inaccurate. 

I see that there are multiple closed issues on the tracker specifically for this feature of IDO and all link or propose some extra elisp. Given that there are a ton of people switching from ido, wouldn't it make sense to have a dedicated extension which would approximate ido behavior as close as possible? Then people could contribute their favorite missing ido feature freely and others would use it as a one-stop transition package.

**Comment by vspinu** [comment]
I have just started playing with vertico so I am almost certainly doing something stupid here, but the following patch would come closer to true ido behavior. 

  1. Insert first candidate on RET regardless of the input
  2. If the first candidate is a file open it directly. 

What is missing is the highlight of the first candidate, which is a bit confusing. Also on `vertigo-next` one gets to first candidate first instead of the second (more useful) candidate. 

This makes me wonder that if I could make vertigo select the first candidate automatically I would not need to modify any code, things would work by default, but how do I do that?

```diff
2 files changed, 9 insertions(+), 4 deletions(-)
extensions/vertico-directory.el | 6 ++++--
vertico.el                      | 7 +++++--

modified   extensions/vertico-directory.el
@@ -44,7 +44,7 @@
 (defun vertico-directory-enter ()
   "Enter directory or exit completion with current candidate."
   (interactive)
-  (if (and (>= vertico--index 0)
+  (if (and
            (let ((cand (vertico--candidate)))
              (or (string-suffix-p "/" cand)
                  (and (vertico--remote-p cand)
@@ -52,7 +52,9 @@
            ;; Check vertico--base for stepwise file path completion
            (not (equal vertico--base ""))
            (eq 'file (vertico--metadata-get 'category)))
-      (vertico-insert)
+      (let ((cand (vertico-insert)))
+        (unless (string-suffix-p "/" cand)
+          (vertico-exit)))
     (vertico-exit)))
 
 ;;;###autoload
modified   vertico.el
@@ -704,8 +704,11 @@ When the prefix argument is 0, the group order is reset."
   ;; suffix "/calc". Default completion has the same problem when selecting in
   ;; the *Completions* buffer. See bug#48356.
   (when (> vertico--total 0)
-    (let ((vertico--index (max 0 vertico--index)))
-      (insert (prog1 (vertico--candidate) (delete-minibuffer-contents))))))
+    (let* ((vertico--index (max 0 vertico--index))
+           (cand (vertico--candidate)))
+      (delete-minibuffer-contents)
+      (insert cand)
+      cand)))
 
 (defun vertico--candidate (&optional hl)
   "Return current candidate string with optional highlighting if HL is non-nil."

```

**Comment by minad** [comment]
Ido-like doesn't necessarily mean that the behavior should match Ido exactly. The vertico-directory extension only provides an alternative enter command. As you figured, the real issue is that Vertico doesn't preselect the first candidate (#272, #291). We could add a `vertico-preselect` option, which allows you to configure this. This has been requested a few times, so I may add this now. For now you have to use an advice to modify the preselection behavior (see the other issues). However I am a bit hesitant to add new options, in particular if requested by new users, who just started with the package and want it to behave exactly as something else. The existing design is reasonable and new users may switch to something else anyway after a while, given the plethora of alternatives.

**Comment by vspinu** [comment]
I see. Thanks. I have read the issues but I still fail to see the benefits of the current design choice (sorry, feel dumb today :disappointed: )

To summarize, when no candidate is selected:

  1. it's confusing that RET acts on something implicitly. All other frameworks that I have used (ido, helm, ivy) highlight the candidate on which they act. So this vertico's behavior certainly feels strange.
  2. to get to non-default candidate (second) I need to press C-n twice.
  3. to enter a file I need first to TAB then RET

To me these are all conceptual issues regarding efficiency. I don't want to press extra TABs or C-n to select the obvious item before entering it. Now matter how long I use vertico it will still be an extra TAB. 

You briefly mentioned in the other issue that the reason for selecting the prompt by default is to be able to select directories. I fail to see the benefits of it :thinking:  All editing commands work fine if prompt is not selected. I can press M-j to enter the directory So what's the point?

**Comment by minad** [comment]
> it's confusing that RET acts on something implicitly. All other frameworks that I have used (ido, helm, ivy) highlight the candidate on which they act. So this vertico's behavior certainly feels strange.

That's not the case. The prompt is selected. There is no implicit behavior here.

> To me these are all conceptual issues regarding efficiency. I don't want to press extra TABs or C-n to select the obvious item before entering it. Now matter how long I use vertico it will still be an extra TAB.

This only matters when you select the first candidate. For me this doesn't happen too often since I have recent files already available via consult-buffer

> I can press M-j to enter the directory So what's the point?

The point is that the input is a valid candidate. As such the prompt is preselected. This is consistent with other behavior where we also prioritize matching input. For example try this completion table, which accepts every input. In this case the prompt is always selected.

~~~ elisp
(completing-read "Prompt: "
                 (lambda (str pred action)
                   (or (eq action 'lambda)
                       (complete-with-action action '(first second third) str pred))))
~~~

**Comment by minad** [comment]
Made the change now. I agree with you that the behavior we had wasn't efficient, since in most cases one doesn't want to open the directory. I think in the beginning, I always selected the prompt for valid input, which would be reasonable for only a small subset of all completion tables. But then I moved away from that in general since it was too annoying and only preserved the behavior for `find-file`. There it made at least a little bit of sense since directories are valid candidates.

**Comment by vspinu** [comment]
Wow. Amazing! Thanks a bunch!

**Comment by aaronjensen** [comment]
As a matter of feedback, this change has made vertico a lot harder to use for me when selecting directories (moving files around w/ dired, etc). I'm trying to get used to the new way, but there is so much cognitive load now when selecting directories or navigating directories and selecting files. I'm sure I'm missing something, so I'll keep working with it.

**Comment by DamienCassou** [comment]
@aaronjensen I'm in exactly the same position: the new behavior is annoying me a lot but am trying to get used to it. In the meantime, I frequently open files when I wanted to open the containing directory. I also replaced a file with the content of another one when what I wanted was to move the later in the directory of the former.

**Comment by minad** [comment]
@aaronjensen @DamienCassou Yes, I know. Of course I observed the same during my daily use of Dired and then I remembered why we got what we had. I guess, there is no perfect solution too resolve this except by introducing a user option. I will revert the change for now.

**Comment by minad** [comment]
I reverted the breaking change for now. If we cannot come up with a better solution, a user option will be the way to go. There is the minor complication that my Corfu package, which is very similar to Vertico (or at least aims to be), already comes with a corfu-preselect-first option which does something different. I have to think more about how these settings could be harmonized. Maybe I would be the only one confused about this, but I still have to think more about it.

**Comment by aaronjensen** [comment]
Thanks, @minad. FWIW, I use Corfu and `corfu-preselect-first nil` because I use tng. Just mentioning it if you want a test subject for any potential changes.

**Comment by minad** [comment]
@aaronjensen Yes, please keep an eye on both repositories then.

**Comment by vspinu** [comment]
Input at point is entered with `M-RET` vertico-exit-input`. Or if you are like me and used IDO before, you can bind it to C-j or M-j. 

The new behavior is consistent across all commands and more [efficient](https://github.com/minad/vertico/issues/302#issuecomment-1356223077). If the user option is really needed then I think the new behavior should be the default. New users are likely to find it more intuitive.

**Comment by aaronjensen** [comment]
Respectfully, I disagree. Even if efficiency were the goal (usability should be) then when selecting a directory, it is bad from an efficiency and usability perspective. I have to highlight the dir, press return and then M-return. This is where it falls apart. There’s nothing usable or efficient about that. But again, maybe I’m missing something.

**Comment by minad** [comment]
@vspinu There is no point in arguing. The priority is to preserve existing behavior.

**Comment by vspinu** [comment]
By efficiency I meant efficiency in selecting files == usability. 

> I have to highlight the dir, press return and then M-return.

I am not sure I understand. The only thing changed is you need to change RET to M-RET.

**Comment by vspinu** [comment]
To summarize the "consistency" argument (efficiency is [above](https://github.com/minad/vertico/issues/302#issuecomment-1356223077)):

Old behavior:

  1. Different behavior for file completion vs other commands
  2. Within file completion RET acts either as a completion (when dir candidate is selected) or as an entering action (when input is selected)
  3. When candidate is selected you still need to press M-RET in order to select the directory at the input. Similarly when creating new files which are sub-stings of the existing candidates. Basically one maintains two keys for same action depending on the context.

Proposed behavior:

 1. Same behavior across all commands
 2. and 3. M-RET always acts on input, RET always acts on candidates unless there are no candidates.

On a related note, with the proposed change input selection does no longer seem necessary. That is, when cycling candidates through the top the extra stop at the input is no longer needed (this does not occur with other commands). Perhaps internal code which maintains input selection could also be simplified.

**Comment by aaronjensen** [comment]
@minad @vspinu ok, I think I see my problem. I had RET RET as muscle memory for "select a directory". That would need to be replaced by RET M-RET. 

As for whether or not efficiency == usability, we can agree to disagree on that. I'm sure I could get used to anything, but there is a very natural familiarity to the way it works now. Some lists allow free-form selection and others don't. They are inherently different types of lists. FWIW I believe ivy worked as proposed when selecting files. The major difference was that `.` was at the top of the list in a directory, so you could select the directory by pressing enter (I think it also had `..` but I'm not sure that's necessary). That would also alleviate the usability concerns.

I don't remember what command it was, but one of my commands actually had `./` and `../`. When I pressed enter on it using the proposed changes it appended it to the path in the prompt. I could press enter several times and it kept appending. It was infuriating and what caused me to write my initial comment. I wish I remembered which command it was.

**Comment by minad** [comment]
@vspinu I wrote above "there is no point in arguing" and yet you reiterate your argument, including erroneous assumptions.

> When candidate is selected you still need to press M-RET in order to select the directory at the input. Similarly when creating new files which are sub-stings of the existing candidates. Basically one maintains two keys for same action depending on the context.

This is incorrect. Did you actually try?

I will look for a better solution when I find time. See https://github.com/minad/vertico/issues/302#issuecomment-1360106650 for the complications. In the meantime you can use an advice to change the behavior.

**Comment by minad** [comment]
I think there is one more not so serious argument for the current behavior - the current behavior pushes you more aggressively to use Dired. At least I use Dired more often thanks to this setting. ;)

I opened a new issue to discuss how a potential configuration could look like in https://github.com/minad/vertico/issues/306. Feel free to continue the discussion there.

**Comment by vspinu** [comment]
@minad 
>  I wrote above "there is no point in arguing" and yet you reiterate your argument, 

I am sorry if my writing style made an impression that I am "arguing" or demanding something. I would definitely be happy with any solution here. I just tried to compile a comprehensive list of pros for the new behavior and I tried hard not to repeat the arguments.

Of course  I understand it's a trade off, and it's breaking habits and of course it's annoying for existing users :stuck_out_tongue:  ... But still, there will be 100x more new users in the future, and who knows, maybe all Emacs users will be using this package in the future:rocket:. Hence, to my mind, a consistent and rigorous default seems like a good goal to aim for in a long run.

> This is incorrect. Did you actually try?

I didn't explain it well. I meant that in a situation like below, when a candidate is selected and you want to act on an input at a prompt you would still need to use M-RET. So M-RET is kinda unavoidable even in the current setup when RET does most of the work most of the time.
![image](https://user-images.githubusercontent.com/1363467/209111758-8f8f5265-acb6-4b27-98fe-5deac8a69294.png)

Similarly when you want to create a new file which is a substring of an existing entry:

![image](https://user-images.githubusercontent.com/1363467/209112126-11ed3590-6bd0-4f60-8369-a62088f43fe3.png)

**Comment by minad** [comment]
@vspinu I must admit, I perceived your style as a little bit demanding. Note that my packages are already mature. In fact I plan to release stable versions soon. Furthermore I've heard these arguments that Ivy or Helm do it that way or have this feature a bit too often. There is no question that my packages took a lot of inspiration there, but it still makes sense to rethink the design decisions. 

Generally I fully agree with you that reasonable defaults are the way to go. My packages are developed in this way. But I thought more about this in #306 and I am confident that I found a good and unifying solution. The corfu-preselect-first customization variable in Corfu always bothered me a little bit. I will implement this such that the available options are uniform across both packages. Not sure if you use Corfu, but this matters at least for me and the maintainance.

**Comment by minad** [comment]
> So M-RET is kinda unavoidable even in the current setup where RET does most of the work most of the time.

I agree of course. My point is just that pressing RET quickly (and accidentally) is more likely to happen. Anyway, there will be a solution in the form of an option soon. Then we can see how this evolves in the long term.
