### ISSUE TITLE
Configuring the keymap for Vertico + evil in buffer mode 

### ISSUE THREAD

**Issue by mukundzare** [minad/vertico#303]
Here's my vertico config:
```emacs-lisp (use-package vertico
    :init
    (vertico-mode)
    (setq vertico-scroll-margin 0)
    (setq vertico-count 15)
    ;; Grow and shrink the Vertico minibuffer
    (setq vertico-resize 'grow-only)
    :custom
    (vertico-cycle t)
    (vertico-multiform-categories
     '((file grid reverse)
       (consult-grep buffer)
       (imenu buffer)
       (consult-ripgrep buffer)))
    (vertico-multiform-commands
     '((consult-imenu buffer indexed)))
    :bind  (:map vertico-map
                 ("C-j" . vertico-next)
                 ("C-k" . vertico-previous)
                 ("TAB" . vertico-insert)
                 ("?" . minibuffer-completion-help)
                 ("C-'" . vertico-quick-jump))
    :hook
    (minibuffer-setup . vertico-repeat-save)
    :config
    (vertico-multiform-mode)
    (global-set-key (kbd "M-s s") #'vertico-repeat))
```

Since I am an evil user and configured the `C-k` key to `vertico-previous`, am having trouble understanding why it does not call `vertico-previous` when I am using `consult-ripgrep`? Note that `consult-ripgrep` is being called in the buffer mode. I don't see any configuration variable for `vertico-buffer-mode` where I can set it. I also have `evil-want-minibuffer` to `nil`. Setting it to `t` didn't work either.

**Comment by minad** [comment]
Thanks for the report. I am not an Evil user so I cannot help you here. There is no code in Vertico which would explain the odd behavior in combination with Evil. You may want to search through old issues, ask other experienced evil users or ask on other platforms (reddit, irc). Note that Doom Emacs successfully uses Vertico, Evil and consult-ripgrep. You could potentially find some clues over there.
