### ISSUE TITLE
How to get virtual buffers as in `consult`?

### ISSUE THREAD

**Issue by nurdann** [minad/vertico#305]
I am switching to `vertico` because of warnings I get that `consult` is being deprecated.

I used to be able to issue `consult-buffer` and go to previously opened files. How'd I replicate it in `vertico`? See https://github.com/minad/consult#virtual-buffers

**Comment by minad** [comment]
Vertico works like Selectrum. You can continue to use consult-buffer. Consult is not deprecated, only the Selectrum support.
