### ISSUE TITLE
Preselection configuration

### ISSUE THREAD

**Issue by minad** [minad/vertico#306]
The prompt/candidate preselection behavior of Vertico has been critized a few times (#272, #291, #302). It would be best if we introduce a configuration variable, such that the user can decide if the prompt should be preferably selected (if the input is valid) or the first candidate. A similar problem occurs in my Corfu package, which already comes with the `corfu-preselect-first` configuration variable. Ideally a solution can be found which generalizes over both packages.

Vertico currently selects the prompt when the input is a directory or if there are no candidates. Otherwise the first candidate is selected. The reasoning for the current behavior is that for example when moving files in Dired, directories are selected to prevent accidentally selecting other files. Furthermore the behavior makes it slightly easier to open directories in Dired at the cost of slowing down path navigation.

Corfu currently selects the prompt if `(not corfu-preselect-first)` or if the input is valid and not equal to the first candidate. Otherwise the first candidate is selected. `corfu-preselect-first=nil` is needed for TNG completion (Tab 'n Go).

Both behaviors are a little special (and weird) and maybe one should ask if the obvious options should be supported:

1. Select the first candidate if there are candidates
2. Select the prompt if the input is valid

**Comment by DamienCassou** [comment]
> I would appreciate some testing. Of course it is perfectly fine if you only try the setting which you are interested in.

I switched and will report any issue.

**Comment by anticomputer** [comment]
I know some folks are yearning for an ivy/counsel-find-file style directory navigation due to muscle memory, using the `vertico-preselect` and the following ugly hack you can get a behavior that is muscle memory compliant on ivy style find-file navigation:

```elisp
(use-package vertico
  ;; using quelpa until elpa version contains vertico-preselect
  :quelpa
  :ensure t
  :demand
  :config
  (setq vertico-cycle t)
  (setq vertico-preselect 'directory)
  :init
  (vertico-mode)
  ;; make things compatible with my ivy muscle memory
  ;; if first candidate is a directory then "/" should
  ;; vertico-insert, if not, then it should just do the
  ;; char
  (defun my/vertico-insert ()
    (interactive)
    (let* ((mb (minibuffer-contents-no-properties))
           (lc (if (string= mb "") mb (substring mb -1))))
      ;; make sure we can still reset to ~ and // ivy style
      (cond ((string= lc "/") (self-insert-command 1 ?/))
            ((string= lc "~") (self-insert-command 1 ?/))
            ((file-directory-p (vertico--candidate)) (vertico-insert))
            (t (self-insert-command 1 ?/)))))
  :bind (:map vertico-map
              ("/" . #'my/vertico-insert)))
```

**Comment by minad** [comment]
@anticomputer Please add your snippet to the wiki with some additional description, which explains the background.
