### ISSUE TITLE
Odd candidate display behavior in some cases when using find-file

### ISSUE THREAD

**Issue by lambdadog** [minad/vertico#307]
Apologies for the vague issue title, but I'm not sure of how to briefly summarize this behavior.

`find-file` supports a behavior in which if you type a `/` or `~/` right after a previous `/`, it essentially "restarts" the file search from that root.

As an example, if I'm in visiting the file `~/devel/vertico/vertico.el`, then use the `C-x C-f` keybind to launch `find-file`, `find-file` will launch with the path `~/devel/vertico/`.

If I then wish to visit a file in my `HOME` directory, I will type `~/`, and `find-file` will show `~/devel/vertico/~/`, but with `~/devel/vertico/` greyed out, and my completions will now show files in my home directory.

This all works correctly, but vertico then seems to display candidates in a way that is incorrect, sometimes, when you begin typing again and are also matching the original, now greyed out, path.

![](https://user-images.githubusercontent.com/36526063/209219548-85eb3997-a1f1-44f6-9e26-18d682756126.png)

(all actual candidate *matching* behavior seems correct, only the display display is incorrect)

This doesn't persist past the first segment of the path.

![](https://user-images.githubusercontent.com/36526063/209219682-1b8f14f1-7f6b-45f6-b1cb-97b5b3021058.png)

It's worth noting this behavior also occurs with `/`, but only when the previous root and the new root are matching. (ex. the first root can't be `~/` and the new one `/`, they must both either begin with `~/` or `/`, or any other root Emacs supports)

![](https://user-images.githubusercontent.com/36526063/209220566-aeb19656-e0e5-49c4-a020-d52917d25eb7.png)

-----

Some other variants:

![variant3](https://user-images.githubusercontent.com/36526063/209220608-36e53494-447a-4039-ae39-59dae5d4f1f3.png)
![variant2](https://user-images.githubusercontent.com/36526063/209220609-03ef3097-9cd5-4a09-850f-e6a7da4bd89a.png)
![variant1](https://user-images.githubusercontent.com/36526063/209220612-ab34f1eb-b4f5-4f8d-a78b-24a1a37fd650.png)

From my experimenting the candidate display issue seems to occur when your new input matches the last path that has at least one path segment.

**Comment by minad** [comment]
Oh, I like this one. The graying out is called path shadowing. It is one of the darker areas of path completion. You can automatically get rid of the grayed out path (see the README configuration example):

~~~ elisp
(add-hook 'rfn-eshadow-update-overlay-hook 'vertico-directory-tidy)
~~~

There still remains the bug if you enter `/etc//s` in `find-file`. But to be clear this is an upstream bug of Emacs itself. I can reproduce it in default completion on plain `emacs -Q` (Emacs version 27 and 29).

1. Start emacs -Q
2. C-x C-f
3. Delete the entire input
4. Enter /etc//s
5. Press ?

You will see candidates like etc//sbin/.

Reported upstream: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=60264

**Comment by lambdadog** [comment]
Huh, I didn't even think to test this without vertico, sorry about that! Thank you for pushing it upstream.

**Comment by minad** [comment]
To be fair, in Vertico/Corfu such issues are triggered much more often since you usually don't press ? so often during default completion.
