### ISSUE TITLE
How to complete what I have input, instead  of choosing from possible candidates?

### ISSUE THREAD

**Issue by suliveevil** [minad/vertico#309]
I want to create `disc` node instead of choosing from the candidate list.

<img width="830" alt="截屏2022-12-23 21 44 26" src="https://user-images.githubusercontent.com/35763237/209346605-ce1f9646-04e1-419d-8cf9-e7f010d92af2.png">

**Comment by suliveevil** [comment]
Is this managed by vertico or org-roam-node-find?

**Comment by minad** [comment]
Please take a look at the README first.

**Comment by suliveevil** [comment]
I find my way out.

```text
vertico: vertico-exit-input
ivy: ivy-immediate-done
```

**Comment by suliveevil** [comment]
Thank you very much for your awesome package!

**Comment by minad** [comment]
Thanks! Always glad to help ;)
