### ISSUE TITLE
How do I use the text I entered without accepting a completion?

### ISSUE THREAD

**Issue by robenkleene** [minad/vertico#311]
E.g., in a Dired buffer, if I hit `+` to create a directory, Vertico returns results as I'm typing, and hitting enter completes to the first result, but what I want to do is just create the directory with the name I type and ignore the Vertico result.

Same with `find-file`, how do I create a new file instead of accepting an existing match?

**Comment by minad** [comment]
Please take a look at the README first. Thanks!

**Comment by robenkleene** [comment]
The answer was to use `M-RET` (which is bound to `vertico-exit-input`), or use `<up>` to highlight the prompt line itself before hitting return (I find the second option particularly elegent).
