### ISSUE TITLE
How to use space as a separator like in Selectrum?

### ISSUE THREAD

**Issue by cyrus-and** [minad/vertico#312]
This is probably a dummy question and caused my lack of knowledge of the Emacs internals... but switching today from Selectrum to Vertico I noticed that a space cannot any longer be used as a separator. How can I obtain the same behaviour in Vertico?

**Comment by minad** [comment]
Please check out the [migration guide](https://github.com/minad/vertico/wiki/Migrating-from-Selectrum-to-Vertico) and the [example configuration](https://github.com/minad/vertico#configuration). You should configure the `completion-styles`.
