### ISSUE TITLE
Per-command setting using vertico-multiform

### ISSUE THREAD

**Issue by bcmertz** [minad/vertico#314]
Hello! 

The problem I am trying to solve is to have a specific command (in this came `magit-status`), not follow the config as specified globally for vertico. I would like everywhere to use `vertico-preselect t`, except for `magit-status`.

My config is as follows
```
(use-package vertico
  :straight (vertico :files (:defaults "extensions/*")
                     :includes (vertico-multiform))
  :init
  (vertico-mode)
  :config
  (setq vertico-preselect t)
  )

(use-package vertico-multiform
  :after vertico
  :straight nil
  :init (vertico-multiform-mode)
  :config
  (setq vertico-multiform-commands
        '((magit-status (vertico-preselect . nil))                  ;; attempt 1
          (magit-status ,(lambda (_) (setq vertico-preselect nil))) ;; attempt 2
          )))

```

Above are my two best ideas for how to accomplish this using vertico-multiform, after reading the README and the existing closed github issues relating to multiform.

I am wondering if this is a feature that is supported, and if so what I might be doing wrong. Thank you very much for your time and this excellent package.

**Comment by bcmertz** [comment]
It is worth noting, this is a simplified config and other multiform use-cases have been working properly for me, such as the example for sorting directories before files in the README

**Comment by minad** [comment]
Maybe the problem is only that you use invalid values for `vertico-preselect`. Neither `t` nor `nil` are valid. Take a look at the variable definition. Besides that your attempt 1 looks alright. Does this help?
