### ISSUE TITLE
Add autocomplete for a custom prefix

### ISSUE THREAD

**Issue by aeslaughter** [minad/vertico#315]
When you type `M-x` you get a nice menu of the available commands. I would like to add a similar completion to another prefix keybinding (e.g. `C-d`), so when I press `C-d` I would see the two commands: `deft` and `deft-new-file`.
```
 (define-prefix-command 'deft-map)
 (global-set-key "\C-d" 'deft-map)
 (define-key deft-map "d" 'deft)
 (define-key deft-map "n" 'deft-new-file)
```

Is this possible? If so, how can I implement it?

https://emacs.stackexchange.com/questions/75269/add-vertico-autocomplete-to-custom-prefix-key

**Comment by minad** [comment]
This is not a Vertico issue, but these are two possibilities to get you started:

~~~ elisp
(defun deft-commands ()
  (interactive)
  (minibuffer-with-setup-hook
      (lambda ()
        (insert "deft-"))
    (call-interactively #'execute-extended-command)))

(defun deft-commands ()
  (interactive)
  (funcall-interactively (intern (completing-read "Command: " '(deft deft-new-file)))))
~~~
