### ISSUE TITLE
Emacs Freezes when swiitching to buffer

### ISSUE THREAD

**Issue by omarbassam88** [minad/vertico#316]
I've been struggling with this for the past couple of days. My Emacs Freezes and CPU jumps to 100% when i try to switch to a buffer using vertico (even the *Messages* buffer). 
It also happens when trying to open a file from `dired` or `dirvish`.
The reason I think this is a vertico issue. Because I disabled every single package in my config. Only when I disabled vertico every thing worked normaly. 
This only happens in the GUI mode though. in the terminal it works fine.

Here's my system-configuration-options:
```
--prefix=/nix/store/3ncm8bcyvvkgwz3frxc7xyzk9n9l5d0q-emacs-28.2   --disable-build-details --with-modules --with-x-toolkit=lucid --with-xft --with-cairo    --with-native-compilation
```

My Emacs Version :
```
GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll
bars)
```

I am using NixOS 22.11
And using vertico-1.0

**Comment by minad** [comment]
Can you please update all your packages and try again? There was an issue in the Compat package which may have caused freezing. If this doesn't solve your issue I would need a minimal configuration in order to reproduce.

**Comment by omarbassam88** [comment]
That was it I guess. I added `(use-package compat)` in my config. deleted the elpa folder and then it reinstalled the package apparently
