### ISSUE TITLE
Exact case-insensitive matches don't  have precedence

### ISSUE THREAD

**Issue by vspinu** [minad/vertico#317]
I have a command `R` which does not pop up to the top when input is `r`.

![image](https://user-images.githubusercontent.com/1363467/212469239-06bb6bb8-5e8e-4bfa-a07f-681f87875f84.png)

I know it's a corner case in some sense, but still, I wonder if it should be treated on vertico side.

**Comment by minad** [comment]
"exact case-insensitive" is an oxymoron. Uppercase commands are also not common. I want to keep it as is. You can override the function `vertico--move-to-front` with an advice in your user configuration.

**Comment by vspinu** [comment]
> "exact case-insensitive" is an oxymoron. 

Used intentionally as the the most parsimonious and clear way of expressing this particular idea.

> Uppercase commands are also not common.

Same logic applies for other completions - buffers, Imenu etc. where mixed or upper case are more common. But well, fair enough it's a somewhat marginal case.

**Comment by minad** [comment]
My reasoning is that exact-case exact matches must be prioritized in any case. Now if we add additional heuristics to prioritize other candidates too we are moving into the territory of "advanced sorting functions" and sorting completion styles like Prescient.

Furthermore my goal is always to keep Vertico small and simple. If I would agree that prioritizing non-exact-case exact matches, then I could add an option. But if we do this for all edge cases we would quickly end up with a much more complex system which is harder to understand. I think it is actually a feature to have a simpler system which is more easily hackable. More users will profit from the simplicity and the hackability than from accumulating more and more complexity and edge case behavior.

**Comment by vspinu** [comment]
I am completely with you here. The simplicity of the packages and "hackability" is precisely why I am hacking my way through by trying to move from my previous setup.

> But if we do this for all edge cases we would quickly end up with a much more complex system 

To my mind this case is more of a consistency requirement rather than an edge use case workaround. If `completion-ignore-case` is non nil, don't you think that non-exact-case matches should be treated the same as exact matches throughout? If the ordering logic is part of the completion proper, then `completion-ignore-case` should be honored even in the `vertico--move-to-front`. Otherwise it's an exception. But I see your pain, it would definitely uglify that function and add a small performance overhead.

**Comment by minad** [comment]
@vspinu Yes, I also thought about that. completion-ignore-case is a good argument. But already the performance impact makes this a no-go. At first sight it may not have a huge consequences, but comparing 50k strings on every keypress is not free unfortunately.
