### ISSUE TITLE
vertico-flat-mode number of candidates

### ISSUE THREAD

**Issue by bluewww** [minad/vertico#318]
When using `vertico-flat-mode` for example with `find-file` it presents fewer candidates than possible already cutting off the list with `...`.

For example, completing in my home folder shows:
```
~/ (.emacs.d/ | vm/ | .nv/ | .nx/ | .p2/ | .qt/ | tmp/ | ...)
```
but there is much more space to the right side which is not used . `fido-mode` for example would use the full space to the right.

I tweaked `vertico-flat-max-lines` but that doesn't seem to have an effect.

**Comment by minad** [comment]
I cannot reproduce the problem. Please try emacs -Q and provide more details, e.g., your Emacs version.

**Comment by bluewww** [comment]
Thanks. Yes indeed it's vertico-count that I needed to tweak
