### ISSUE TITLE
Suggestion for vertico-directory-up

### ISSUE THREAD

**Issue by gtusr** [minad/vertico#319]
In `vertico-directory-up` I commented out the check

> (eq (char-before) ?/)

so that I can use my keyboard shortcut to move to the previous slash character even if there is a filename already sitting in the mini-buffer prompt.  

This is a little easier than reaching for a separate command like `...delete-char` or `...delete-word` to clean up any trailing characters or words after the last directory separator.  

In particular, I didn't like that `vertico-directory-up` didn't do anything when the point was not precisely next to a directory separator.

Seems to work well so far ... so may be worth removing that check in order to make the command slightly more functional.

**Comment by minad** [comment]
Yes, good point.
