### ISSUE TITLE
How to have a different keymap for buffer and unobtrusive when using multiform

### ISSUE THREAD

**Issue by TimotheeMathieu** [minad/vertico#320]
I just began using vertico, great work :+1:

I am trying to define different keymap for buffer and unobstrusive mode, is this possible ?

When using M-x, I use unobtrusive and in consult-bookmark I use buffer. 

Intuitively I want M-x to behave like my zsh shell with up and down listing history (`vertico-next` and `vertico-previous`) and I want bookmarks to use up and down for scroll  ( `vertico-scroll-up` and `vertico-scroll-down`) as this seems more intuitive to me with a vertical display and because history is less useful for bookmarks.

**Comment by minad** [comment]
Hi! Thanks for the kind words. You can modify the vertico-flat-map which is used only by flat and unobtrusive mode. vertico-buffer does not install its own keymap. 

If you need more flexibility, you can define your own setup functions:

~~~ 
(defun my-setup (arg)
  ;; Install a local keymap here, see `use-local-map'...
  (message "SETUP %S %S" arg (current-buffer)))

(setq vertico-multiform-commands
      `((consult-imenu buffer my-setup)))
~~~

I hope this helps.
