### ISSUE TITLE
Customizing Keybindings for Vertico Multiform 

### ISSUE THREAD

**Issue by gtusr** [minad/vertico#321]
Is it possible to customize keybindings in a stanza for ```vertico-multiform-commands``` or  ```vertico-multiform-categories```?

If not, is there another way to set custom keybindings for different commands and/or categories?

**Comment by minad** [comment]
Yes, you can use `vertico-multiform-mode` to install custom keymaps or to perform an arbitrary minibuffer setup. There is no convenient shortcut syntax for that, you have to write a function. See also #320.

**Comment by minad** [comment]
I think there is an easier way. You can also do the following, but I haven't checked how it interacts with some of the extensions, which install their own keymaps, e.g., `vertico-flat-mode`.

~~~ elisp
(defvar-keymap my-map
  :parent vertico-map
  ;; some additional commands here...
  )
(setq vertico-multiform-commands
      `((consult-imenu (vertico-map . ,my-map))))
~~~
