### ISSUE TITLE
How to cancel a vertico completing read session?

### ISSUE THREAD

**Issue by gtusr** [minad/vertico#322]
Corfu offers the command ```corfu-quit```.  It appears to mimic for all practical purposes entering 'C-g'.

```Vetico-quit``` and ```vertico-quit-input``` on the other hand both drop the user into a dired session if one suddenly decids to cancel a vertico ```find-file``` operation after initiating it by using these commands.  

Is there a command that accomplishes 'C-g' for vertico completion as well?

**Comment by minad** [comment]
C-g works in Vertico. Again please try it first before opening issues.

**Comment by minad** [comment]
You can easily ask Emacs the same question: `M-x C-h k C-g`.

**Comment by gtusr** [comment]
Not sure if you meant to include the ```M-x``` in your suggestion above, but in any event, I already tried that suggestion only to learn that the ```C-g``` cancels the ```C-h k``` request by printing Quit in the mini-buffer before quitting the command.  The Quit is a message, not an Elisp function or command that can be bound in ones ```vertico-map```.  Again, I think that this could be due to special handling that 'C-g' receives in the event processing loop.

It's a small issue for sure, and if it's too much trouble to implement for some reason that's fine.  I just thought it would make sense to offer the same 'cancel' feature in both Vertico and Corfu, preferably using the same naming convention to describe a function that is essentially the equivalent of 'C-g.'  

In any event, I appreciate all of the hard work that you have invested in the emacs ecosystem by creating packages like Vertico.  I'm already using Vertico/Orderless/Consult/Embark/Corfu/Cape plus about a dozen sub-extensions and enjoying them immensely.   Also look forward to trying out ```modern-org``` during my spare time.

**Comment by minad** [comment]
Something seems broken in your Emacs if this doesn't work. Start `emacs -Q` and type `M-x C-h k C-g` *exactly as I wrote*.

> It's a small issue for sure...

There is no issue here.

I appreciate the kind words but this is not a support tracker, but a bug tracker. Please do more reading and experimenting first, in particular if you aim to do something special like replacing the "non-ergonomic" Emacs bindings. My recommendation is to learn the basics and the defaults well, before replacing them.

**Comment by minad** [comment]
> I just thought it would make sense to offer the same 'cancel' feature in both Vertico and Corfu, preferably using the same naming convention to describe a function that is essentially the equivalent of 'C-g.'

Vertico and Corfu behave differently. Vertico is a minibuffer completion UI, while Corfu is an in-buffer completion UI. The minibuffer already comes with a cancellation command out of the box to exit the recursive editing context. This command is executed when you press `C-g`. Corfu doesn't enter such a recursive editing context and as such has to provide its own quitting command.
