### ISSUE TITLE
[Question] Target command sub-calls with vertico-multiform

### ISSUE THREAD

**Issue by bcmertz** [minad/vertico#323]
I am attempting to add a multiform command setting to a function which is called by another interactive function. However, vertico-multiform doesn't seem to apply command settings to these sub-calls, perhaps because vertico completion has already begun from the outer function. Is there any way around this in order to make `choose-directory` always preselect the prompt? Thank you!

```
(setq vertico-multiform-commands
      '((choose-directory (vertico-preselect . prompt))
        (consult-line (vertico-cycle . t))))

(defun choose-directory ()
  "Choose directory."
  (file-name-as-directory
   (read-directory-name "Directory: "
                        (or (file-name-directory (or buffer-file-name "")) default-directory))))

(defun my-consult-locate () "My consult-locate." (interactive "") (consult-locate (choose-directory)))
(defun my-consult-grep () "My consult-grep." (interactive "") (consult-grep (choose-directory)))
(defun my-consult-git-grep () "My consult-git-grep." (interactive "") (consult-git-grep (choose-directory)))
(defun my-consult-ripgrep () "My consult-ripgrep." (interactive "") (consult-ripgrep (choose-directory)))
(defun my-consult-find () "Consult find." (interactive "") (consult-find (choose-directory)))
```

Note: multiform settings work for `choose-directory` called interactively on its own, so it seems I'm having trouble due to it being a sub-call

**Comment by bcmertz** [comment]
Perhaps the ability to add a new completion category for such a command / set of commands would be a clean way to do this, but I haven't been able to figure out how this is done. Just a thought if the architecture of vertico isn't compatible with what I'm trying to do

**Comment by minad** [comment]
`vertico-multiform-mode` uses `this-command` to determine the settings. You could bind `this-command` around `choose-directory`, but this may have other unwanted side effects. As you figured, another option would be to add a completion category to `choose-directory`, which however is not possible since you reuse `read-directory-name`.

But I wonder, why don't you just use `(consult-grep t)` which will also show you a directory prompt? There the prompt will also be preselected automatically with the `default-directory` even without any change to `vertico-preselect`.

I hope this helps you solve the problem!

**Comment by bcmertz** [comment]
This is very helpful, thank you! I reread this comment a number of times and did some digging and understand your point that re-using `read-directory-name` makes this impossible as one must add completion category metadata directly onto the completing-read call.

Out of curiousity, how might one bind `this-command` around `choose-directory` as you described? I can't seem to get the `this-command` variable to persist to vertico.

To answer your question, I reuse `choose-directory` extensively in my own custom functions outside of  `consult-grep` and thus wanted to change it's handling in vertico but I see now that vertico goes off the current `this-command` and or `completing-read` category metadata. :)

Thank you very much for your time and help.

**Comment by minad** [comment]
> Out of curiousity, how might one bind this-command around choose-directory as you described? I can't seem to get the this-command variable to persist to vertico.

Just let bind it? This should work. If it doesn't please do a bit more digging, I don't know.
