### ISSUE TITLE
No completion candidates displayed until typing

### ISSUE THREAD

**Issue by thomasheartman** [minad/vertico#325]
Hi,

Just got started with this package (coming from selectrum) yesterday, and am very happy with it so far; thanks a lot 😄 

But I have run into an issue that I can't find the solution for and I'd like some help.

## Description

Sometimes the vertico selection menu won't show any candidates until I provide any input.

The prompt starts with `!/0` instead of `n/m` (e.g. `1/62`)

However, it still seems to have all the candidates. If I know that the first candidate is what I want, then I can press `RET` and the selection is what I expect.

If I start typing or move to the next option, then the candidates appear. If I try and move to the next option, then the candidates appear and I start at option 2.

An interesting point is that this doesn't happen when I first start emacs. It seems to be something that happens during use. I do not know why.

### Screenshot:

Here's what it looks like when it happens:

<img width="449" alt="image" src="https://user-images.githubusercontent.com/17786332/216581566-2f1c4096-fef3-4214-bc15-a6b9f052ef16.png">

This is what it looks like before it happens

![image](https://user-images.githubusercontent.com/17786332/216581815-1be19f9e-d08e-44ad-a0d8-32422de3f867.png)

## Expected outcome

I'd expect all the candidates to be listed when the minibuffer opens.

## Potential source of error?

When writing this report, I noticed that disabling `mini-frame-mode` made the issue disappear. That is: once the issue had appeared, I could disable `mini-frame-mode` and I wouldn't see the problem anymore. If I re-enable `mini-frame-mode`, the problem seems to reappear. 

This makes me think that there is something up with how it interacts with `mini-frame-mode`.  But why it only happens after some time, I don't know. Do you have any idea what could trigger it?

(Oh, and for what it's worth, I know you're critical of the use of child frames for this, but it **does** feel smoother to me)

----

I'd be happy to answer any more questions you have; just ask ☺️ 

Emacs version: GNU Emacs 28.2 (build 1, aarch64-apple-darwin20.6.0, NS appkit-2202.70 Version 11.7.2 (Build 20G1020))

Vertico version: e5dfaa60eebcbefdb4514f180e344e25fbcf43df

**Comment by minad** [comment]
Thanks!

This is not a Vertico issue, since the problem is caused by mini-frame. In my tests my own unreleased mini-popup package does not have this problem in my setup. I still don't recommend to use that and it work anyway since your are an EXWM user iirc? 

My general recommendation is to avoid child frames for minibuffer completion, see https://github.com/minad/vertico#child-frames-and-popups.

**Comment by thomasheartman** [comment]
> This is not a Vertico issue, since the problem is caused by mini-frame.

Yeah, that's fair. I've been considering testing out mini-popup anyway, so I might just give it a go.

>  It may not work anyway since your are an EXWM user iirc?

Thanks for recalling! But no, I went off EXWM about ... two years ago, I think? Anyway, I've only seen this issue on macOS for now, but I'll see if it pops up NixOS over the weekend. 

> As an alternative there exists also vertico-posframe, but I don't know its current status.

Oh, sick! That might work.

> You could try something like this (untested):

Perfect! I'll try out a couple of the options you've presented and see what I need.

Thanks so much for the help for now 😄
