### ISSUE TITLE
Feature Request: Add a command that sets the selected candidate to the location of point

### ISSUE THREAD

**Issue by rswgnu** [minad/vertico#326]
One may use a non-vertico movement command, including using a mouse to relocate point in the minibuffer when vertico is active.  It would be nice to have a command that resets the selected candidate to the line at point.  Thanks for vertico.

**Comment by minad** [comment]
Thanks!

You probably mean Vertico in combination with `consult-line`, since only there the candidates correspond to lines in the buffer? This is not a generally applicable command. I don't see that this functionality belongs to Vertico - it seems more like wiki material.

One can of course implement this easily. You can take the line at point `buffer-substring`, find its position in `vertico--candidates` and finally update the currently selected candidate with `vertico--goto`. If you create such a command, feel free to add it to the wiki.

**Comment by rswgnu** [comment]
I am working on such a command but it is not yet working properly.  The minibuffer is a buffer where one could potentially move point as I mentioned without changing the selected candidate, so I don't see why a simple way of selecting the candidate at point should not be a part of vertico.  I think as you show above that vertico--candidates and vertico--goto should be made public so they can be built upon.  Cheers.

**Comment by minad** [comment]
Maybe I misunderstood you. Did you try `vertico-mouse-mode`?

**Comment by rswgnu** [comment]
I did not know about vertico-mouse-mode.  I will have a look.  I see that you are using overlays now to display the candidates so I can't just use point setting commands as I would like.  Probably vertico-mouse-mode will tell me what I need to know.  Thanks.

**Comment by minad** [comment]
> I see that you are using overlays now to display the candidates so I can't just use point setting commands as I would like. Probably vertico-mouse-mode will tell me what I need to know.

What do you want to achieve?

**Comment by rswgnu** [comment]
I want a mouse key that with the first click, makes the candidate at the click point the active selection in the minibuffer but does not exit the minibuffer.  Then if the active selection matches the candidate clicked on with the same mouse button, I want to use it and exit the minibuffer, so a double click will do that.  This lets me look at the choice made and see if it is correct before activating that selection.  This is how Hyperbole works and I would like that consistency.On Feb 13, 2023, at 11:20 AM, Daniel Mendler ***@***.***> wrote:﻿

I see that you are using overlays now to display the candidates so I can't just use point setting commands as I would like. Probably vertico-mouse-mode will tell me what I need to know.

What do you want to achieve?
