### ISSUE TITLE
Error when trying to run completing-read-multiple on completion-table

### ISSUE THREAD

**Issue by mohkale** [minad/vertico#327]
Hi Minad, I'm finding when using completing-read-multiple and vertico on a functional completion-table then vertico fails with an `1/3    Test:  [Error in post-command-hook (vertico--exhibit): (wrong-type-argument listp "foo")]` message. For example the following:

```lisp
(let ((cands '("foo" "bar" "baz")))
  (completing-read-multiple
   "Test: "
   (lambda (str pred action)
     (if (eq action 'metadata)
         `(metadata (affixation-function . ,#'identity))
       (complete-with-action action cands str pred)))
   nil t))
```

On the other hand just passing the completion candidates directly like so works fine:

```lisp
(let ((cands '("foo" "bar" "baz")))
  (completing-read-multiple
   "Test: "
   cands
   nil t))
```

I tried reproducing with `emacs -Q` but `M-x package-install vertico` just fails with `https://elpa.gnu.org/packages/vertico-0.28.tar: Not found`. Let me know if you think this is an issue with my config. I'll try narrowing it down more thoroughly then. Thanks :-).

**Comment by minad** [comment]
Your affixation-function is incorrect. See also https://github.com/minad/vertico#debugging-vertico.
