### ISSUE TITLE
Tramp partial-completion hangs

### ISSUE THREAD

**Issue by a1ks** [minad/vertico#329]
Hi, I used this snippet from docs for remote completion https://github.com/minad/vertico#tramp-hostname-and-username-completion, but completion  hangs on remote connections, if there are a lot of files in the directory. About ~3000 files in my case. For example, if I need file named "1234.log", I start typing:
`C-x C-f /ssh:server:/some/path/1`
And then completion hangs, only C-g helps.

After some unsuccessful attempts, I came to this snippet that works perfectly, without hanging:

```elisp
(defun pcm-remote-try-completion (string table pred point)
  (if (vertico--remote-p string)
      (completion-basic-try-completion string table pred point)
    (completion-pcm-try-completion string table pred point)))
(defun pcm-remote-all-completions (string table pred point)
  (if (vertico--remote-p string)
      (completion-basic-all-completions string table pred point)
    (completion-pcm-all-completions string table pred point)))
(add-to-list
 'completion-styles-alist
 '(partial-completion-remote-fix
   pcm-remote-try-completion
   pcm-remote-all-completions
   "Partial completion for local path and basic completion for remote path"))
(setq completion-category-overrides
      '((file (styles orderless partial-completion-remote-fix))))
```

My Emacs Version :
`GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)`

**Comment by minad** [comment]
Very good. Yes, it makes sense to defer to basic completion if partial completion is too slow. Also check that your Tramp cache settings are adequate. But feel free to also discuss this with Michael Albinus - maybe improvements on the side of Tramp are possible.
