### ISSUE TITLE
vertico-multiform-commands doesn't seem to work with commands with multiple prompts

### ISSUE THREAD

**Issue by lzhoucs** [minad/vertico#332]
With the following setup:
```
  (setq project-switch-commands '(
                                  (consult-project-buffer "Find project buffer")
                                  ))

  (setq vertico-multiform-commands
        '((consult-project-buffer buffer)
          (t reverse)))
```
when I execute `project-switch-project` to pick a project, then pick "Find project buffer", the `consult-project-buffer`  doesn't launch in buffer-mode unexpectedly, it launches in reverse mode instead.

when I execute `consult-project-buffer` directly, it launches both the project prompt (if not in a project) and buffer name prompt in buffer-mode as expected.

**Comment by minad** [comment]
I could not reproduce this for `consult-project-buffer` but we can indeed improve support for multi prompt commands by using `current-minibuffer-command`.

**Comment by lzhoucs** [comment]
Thanks for the quick action which does seems to improve it in general. 

I just tried again with the latest code. In my case though, both `this-command` and `current-minibufer-command` is `project-switch-project` instead of `consult-project-buffer` when I run `project-switch-project` then pick "Find project buffer". It seems `project-switch-project` is calling ` (call-interactively command)` which somehow does not register `command` to be either `this-command` or `current-minibufer-command`. So `consult-project-buffer` ends up falling back to reverse-mode

**Comment by minad** [comment]
@lzhoucs I don't understand. But anyway there is nothing we can do.

**Comment by minad** [comment]
Alternativelyyou could ask the maintainer of project.el Dmitry Gutov (dgutov on github) to let-bind `this-command` or `current-minibuffer-command` to the selected command in `project-switch-project`. I am not sure if that's a good idea though and if Dmitry will agree.

**Comment by lzhoucs** [comment]
Thanks. Sorry for the confusion. I think I was having two slightly different issues : one reported originally, the other edited.  And the fix did work for the former, but not the latter. And I agree this might not even be an issue with vertico. I'll try `vertico-multiform-categories`. Thanks for looking at it.
