### ISSUE TITLE
Adding project-find-file sort function

### ISSUE THREAD

**Issue by ST-Saint** [minad/vertico#335]
I noticed that the `project-find-file` is using relative file-name-history and it is not well sorted by vertico. I saw discussion here #296 and I think using `vertico-multiform-commands` to add a specific sort function for `project-find-file` is necessary.

I tried to customize my own sort function though I didn't make it work. Would you like to provide a sample configuration to patch the sort function or could you please elaborate on how to use the `vertico-multiform-commands`. 

Really appreciated your help.

**Comment by minad** [comment]
Yes, I am aware of that change in project.el. You are right that we need a special sort function, but that is out of scope of Vertico. We cannot introduce special sort functions for all kinds of special completion tables.

**Comment by dgutov** [comment]
@ST-Saint probably didn't get the notification about the reference commit since the issue was already closed.

This is fixed now.
