### ISSUE TITLE
vertico-preselect and magit-clone

### ISSUE THREAD

**Issue by rossabaker** [minad/vertico#337]
Thanks for the great package!  

On `magit-clone`, I would like to preselect the prompted value (`magit-clone-default-directory` plus the repo name) when choosing the directory to clone to.  This is the behavior of `(setq vertico-preselect 'prompt)`, but I like the default `'directory` semantics for most other completions.

`'directory` fails [on line 370](https://github.com/minad/vertico/blob/aaea4baad35d40377c50446ae1d3fa2d98a675e7/vertico.el#L367-L372).  `content` is the full proposed path, but `vertico--base` is just the `magit-clone-default-dir`.  Also, `test-completion` on the next line would be false, because the prompted directory doesn't exist yet.

https://github.com/minad/vertico/blob/aaea4baad35d40377c50446ae1d3fa2d98a675e7/vertico.el#L367-L372

I thought `vertico-multiform-commands` might work, but `magit-clone` first asks for the Git path.  By the time we complete the directory, `this-command` is `exit-minibuffer`, so I can't figure out how to target `magit-clone`.  I came up with the following advice hack.  Can anyone think of a cleaner way, without going to `'prompt` everywhere?

```emacs-lisp
    (defun ross/magit-clone-read-args-a (orig-fun &rest args)
      "Sets vertico-preselect to 'prompt when cloning repos, so we clone to the default prompted directory, and not some random existing directory under magit-clone-default-directory."
      (let ((vertico-preselect 'prompt))
	(apply orig-fun args)))
    (advice-add 'magit-clone-read-args :around #'ross/magit-clone-read-args-a)
```

**Comment by minad** [comment]
Unfortunately there is no better solution for commands which prompt multiple times if you use Emacs 27. On Emacs 28 and newer we use current-minibuffer-command, but then you will change the configuration for every prompt. See:

https://github.com/minad/vertico/blob/aaea4baad35d40377c50446ae1d3fa2d98a675e7/extensions/vertico-multiform.el#L123

We could add support for multi prompts if we count the number of prompts and then extend vertico-multiform-commands accordingly to take both command symbol and prompt index. This issue doesn't come up often, therefore we don't have this. Furthermore I consider completion categories as more robust for configuring vertico-multiform.

**Comment by rossabaker** [comment]
Oops, I hadn't noticed I was on v1.1!  #332 makes it work without the advice hack:

```
  (use-package vertico-multiform
    :after vertico
    :custom
    (vertico-multiform-commands '((magit-clone (vertico-preselect . prompt))))
    :config
    (vertico-multiform-mode))
```

I agree that categories seem more robust, but this one is just `'file`. I'm glad commands are also supported.  Thanks again!
