### ISSUE TITLE
Emojies other than unicode ones are not displayed with "emojify-completing-read"

### ISSUE THREAD

**Issue by jumper047** [minad/vertico#339]
Result of the 'emojify-completing-read' execution with ivy-mode enabled:
![image](https://user-images.githubusercontent.com/1407838/224124349-88396c11-5925-47be-9340-dcb8ee3d5ad6.png)

with vertico-mode enabled:
![image](https://user-images.githubusercontent.com/1407838/224123856-6259f5f7-7f81-4456-9e7a-c1c9e5189ffb.png)

unicode emojies, though, displayed correctly with vertico:
![image](https://user-images.githubusercontent.com/1407838/224124747-3583c3ea-1942-41ed-8d95-62f18826abf2.png)

**Comment by jumper047** [comment]
Also formatting in ivy seems more accurate (at least for my taste), but this is minor issue

**Comment by minad** [comment]
This should be fixed in emojify. I am not sure how emojify works, but it seems rather complex. In Emacs 29 you can use `emoji-search` instead, which displays correctly.

**Comment by jumper047** [comment]
Found relevant issue in emojify repo - https://github.com/iqbalansari/emacs-emojify/issues/107

**Comment by jumper047** [comment]
Interesting - seem like in case of custom emojies `emojify` displays them as propertized strings with images. `emojify-completing-read` function adds `emojify-mode` activation to the minibuffer-setup-hook here  - https://github.com/iqbalansari/emacs-emojify/blob/1b726412f19896abf5e4857d4c32220e33400b55/emojify.el#L1849
As far as I can understand, vertico buffer should be affected too, but for some reason it doesn't. For now I ended up with that workaround:
```
(cl-defmethod vertico--format-candidate :around
  (cand prefix suffix index start)
  (setq cand (emojify-string cand))
  (cl-call-next-method cand prefix suffix index start))
```
I don't like it because it affects all functions, and, in theory, it can have some performance impact.

**Comment by minad** [comment]
> I don't like it because it affects all functions, and, in theory, it can have some performance impact.

Overriding `vertico--format-candidate` is the correct approach. See https://github.com/minad/vertico/wiki#candidate-display-transformations-custom-candidate-highlighting if you want to do it properly and apply the transformation only to certain completion candidate types. *In theory*, there won't be a negative performance impact since `vertico--format-candidate` is only called for visible candidates and there aren't many.
