### ISSUE TITLE
Incorrect completion case when read-file-name-completion-ignore-case is on

### ISSUE THREAD

**Issue by vifon** [minad/vertico#341]
When `read-file-name-completion-ignore-case` is set to `t` and `~/` is used to anchor the path at the home from some other directory, accepting a completion candidate from among the `~/*` files doesn't correct the case before returning it.

I've prepared a minimal example, with what I've found so far in the comments:

```elisp
#!/usr/bin/env -S emacs -Q -l
;; Test scenario:
;;   - Ensure the ~/Documents/ directory exists.
;;   - Ensure there are no other files starting with ~/Docu or ~/docu.
;;   - Load this file from some subdirectory of ~/, not ~/ directly.
;;     - When running from ~/, no error occurs.
;;
;; Expected:
;;   Browse ~/Documents with `dired'.
;;
;; Actual:
;;   > Setting current directory: No such file or directory, ~/documents/

(setq read-file-name-completion-ignore-case t)

(package-install 'vertico)
(package-initialize)

;; With Vertico turned off, ~/Documents gets opened as expected.
(vertico-mode 1)

;; Simulate keypresses for easy reproduction.  Can be done manually, of course.
(execute-kbd-macro "\C-xd~/docu\C-i\C-m")

;; Further notes:
;;   - Only happens for ~/*, but not for deeper paths,
;;     such as ~/Documents/sOmEtHinG (this gets completed correctly).
;;     - Happens for both files and directories in ~/*
;;   - Does not happen for /*, tested on /TmP (gets completed as /tmp).
;;   - Does work correctly when executed from /tmp, which would imply
;;     only subdirectories of ~/ are affected (as cwd) for some reason.
```

**Comment by minad** [comment]
Thanks for the report. This is an upstream bug, since invalid candidates are generated. Can you please report it? These are the steps needed:

1. Create directory `~/Documents`.
1. emacs -Q
3. `(setq read-file-name-completion-ignore-case t)`
4. Open some directory `~/foo/`.
5. Press `C-x d`
6. Enter `~/doc`, the minibuffer content will now be `~/foo/~/doc`
7. Press `?`
8. Click on invalid candidate `foo/~/documents`.
9. Press RET in the minibuffer, we will open a new file `documents` which is undesired.

**Comment by vifon** [comment]
Like I mentioned, if I don't have Vertico enabled, the candidate is correctly completed with its case corrected.

**Comment by minad** [comment]
> Like I mentioned, if I don't have Vertico enabled, the candidate is correctly completed with its case corrected.

Yes, but that's irrelevant. It hides the underlying issue. The problem here is that `completion-all-completions` produces invalid candidates. Try the recipe I've given for default completion.

**Comment by minad** [comment]
Related issue #307 and https://debbugs.gnu.org/cgi/bugreport.cgi?bug=60264

**Comment by vifon** [comment]
Oh, you're absolutely right, when I use `?` for the completion instead of `TAB`, the problem indeed occurs. Thank you for clarifying! I'll check if it still happens in the fresh Emacs checkout, and then report.

I think I actually prefer the behavior with the shadowed paths being deleted, thank you. I see it now that it's mentioned in the readme too.

**Comment by minad** [comment]
> I think I actually prefer the behavior with the shadowed paths being deleted, thank you. I see it now that it's mentioned in the readme too.

Yes, it should probably be the default behavior (and I also recommend that one uses that). It wasn't the best decision when I removed this from vertico.el and moved it to vertico-directory.el. However I also don't want to hide vanilla features in Vertico. I thought that path shadowing could be useful. Furthermore by not deleting shadowed paths automatically, bugs like these are exposed and can be reported upstream. I think it is crucial that the base infrastructure gets fixed.
