### ISSUE TITLE
Vertico, AUCTeX and RefTeX: disable/change Vertico completion in a RefTeX minibuffer

### ISSUE THREAD

**Issue by johannesnauta** [minad/vertico#342]
I am trying to insert citations using `AUCTeX` and `RefTeX` while using Vertico. I was having trouble inserting multiple citations (see my question on StackExchange [here](https://tex.stackexchange.com/q/679327/235935)) until I realized that Vertico is messing with my Regex input. The issue is that, similar to the answer posted [here](https://tex.stackexchange.com/a/68719/235935), I want to insert multiple citations and thus need to provide a Regex that matches multiple citations. However, Vertico always completes the current Regex (with either `TAB` or `Enter`) and does not allow me to execute the full Regex (e.g. `Author1\|Author2`). 
When I disable Vertico entirely (`M-x vertico-mode`) this problem disappears. 

How can I disable Vertico in the `RefTeX` minibuffer? In other words, after the command to insert a citation (`C-c [`), how can I disable Vertico in that specific minibuffer? Should I look more into [`vertico-demand`](https://github.com/minad/vertico/blob/demand/extensions/vertico-demand.el)?

Of course, if there is any other way of executing the Regex at point, or an entirely different workflow that lets me easily include multiple citation entries in the same `\cite` command I would be happy to know. 
I apologize in advance if this is not the correct place to ask for this.

**Comment by johannesnauta** [comment]
Minutes after posting this I learn about `vertico-exit-input` (bound to `M-RET`). I think this is exactly what I was actually looking for, so I'll close this issue for now. Feel free to comment other solutions if those are better.

**Comment by minad** [comment]
You can submit the current minibuffer input with vertico-exit-input. Furthermore you can move with the up key to the prompt.

If this is not good enough, you can set vertico-preselect to prompt, such that Vertico will always select the prompt by default. Since you probably don't want to set vertico-preselect to prompt for every command, you can use vertico-multiform to set it only for specific commands.
