### ISSUE TITLE
De-prioritize current file in find-file?

### ISSUE THREAD

**Issue by vspinu** [minad/vertico#348]
Within directories with a few files I often end up pressing `C-x C-f` and seeing current file as the default due to the history being promoted to the top. 

Would it make sense to push current file down the list to gain some speedup for this common case? This is how ido/fido works FWIW.

**Comment by minad** [comment]
Makes sense, but as you probably know, I am not fond of adding too much special casing. This is a pretty marginal improvement.

**Comment by vspinu** [comment]
To me this does not feel marginal. The problem is not just with the default option but with any input which matches the current file, the current file will be on the top polluting the completion.  We know 100% that the user would not want that file in this situation. So maybe simply drop it from completion history altogether?

**Comment by minad** [comment]
> To me this does not feel marginal. 

It is an improvement for a single command, marginal in the greater scheme. This is hard to justify. There may be other commands which need similar treatment and then we end up with a package full of special cases.

> The problem is not just with the default option but with any input which matches the current file, the current file will be on the top polluting the completion. 

Vertico with `find-file` preselects the `default-directory` by default. You probably use `vertico-preselect=first`. But you are right that the top spot is polluted.

> We know 100% that the user would not want it. So maybe simply drop it from completion history for the current completion altogether?

Yes, it would be the easiest to filter it out in `vertico--history-hash`.

**Comment by vspinu** [comment]
> You probably use vertico-preselect=first

Indeed. 

> Yes, it would be the easiest to filter it out in vertico--history-hash.

Thanks!

**Comment by minad** [comment]
Let's see if this change works for most users. I see the risk that there may be some commands which may behave better if the current file is at the top, some operations acting on files.
