### ISSUE TITLE
suggestion: add equivalent of ivy-partial-or-done 

### ISSUE THREAD

**Issue by mpenet** [minad/vertico#35]
Hi! 

First of all thanks for the package, it's really neat.

Can I ask you how would you convert the following to vertico? I could give it a try but I suspect that's something you might even want to add to the package.

```elisp
(defun selectrum-insert-or-submit-current-candidate ()
  "Insert current candidate depending, or forward to
`selectrum-select-current-candidate' if input text hasn't changed since
last completion
Similar to ivy's `ivy-partial-or-done'."
  (interactive)
  (progn
    (let ((prev-input (selectrum-get-current-input)))
      (when (> (length (selectrum-get-current-candidates)) 0)
        (selectrum-insert-current-candidate))
      (when (string= prev-input (selectrum-get-current-input))
        (selectrum-select-current-candidate)))))

```

**Comment by minad** [comment]
It should be pretty easy to convert this command to Vertico.

* selectrum-get-current-input -> minibuffer-contents
* length of selectrum-get-current-candidates -> vertico--total
* selectrum-insert-current-candidate -> vertico-insert
* selectrum-select-current-candidate -> vertico-exit

I am not interested in adding functionality to Vertico. I consider it feature complete. Additional enhancements can be provided by external packages or can be maintained individually in the config. There is also nothing wrong with using Selectrum if you are interested in a more UI features.
