### ISSUE TITLE
Setting vertico-multiform-commands sometimes failed 

### ISSUE THREAD

**Issue by BooAA** [minad/vertico#350]
Hi, I tried to make `consult-company` display contents in normal buffer by tuning `vertico-multiform-commands`, but failed. Below is my steps to reproduce:

Emacs version: 30.0.50, commit 6f496105e392af45c2248b4523ef19804837a8a6
Start Emacs with `emacs -Q` and evalute snippets below:
```emacs lisp
(package-initialize)
(require 'vertico)
(require 'vertico-multiform)
(require 'consult)
(require 'consult-company)
(require 'company)

(setq company-idle-delay nil)
(company-mode)

(vertico-mode)
(vertico-multiform-mode)

(setq vertico-multiform-commands '((consult-company buffer)
				   (t grid)))

(global-set-key (kbd "C-i") #'consult-company)
```

Press `C-i` and observe that `consult-company` is still using minibuffer with grid layout. 

Screencast:

https://user-images.githubusercontent.com/32809182/229584276-5253248e-4fcc-47b5-91f0-4c0b16b2dc75.mp4

**Comment by minad** [comment]
The problem is that `consult-company` does not preserve `this-command` before invoking `completing-read`.

**Comment by BooAA** [comment]
@minad 

Thanks for the quick reply, I have filed another issue to `consult-company`. 

> preserve this-command before invoking completing-read

Is this documented? If not, how about adding this in the README?

**Comment by mohkale** [comment]
Hi @minad, just wanted to double check how am I supposed to persist this-command? `let` bind it to `'consult-company` within the body of the function and prior to calling completing-read? Is this something all completing-read interactive commands should be doing?

**Comment by minad** [comment]
@mohkale The problem is that your command overrides `this-command` by calling `company-complete`. You can prevent this with `(let ((this-command this-command)) ...)` around `company-complete`. Usually such a measure is not necessary.

**Comment by mohkale** [comment]
I see, thanks for clarifying :-).
