### ISSUE TITLE
prompt and input in minibuffer, completions in buffer directly above it?

### ISSUE THREAD

**Issue by nickalcock** [minad/vertico#351]
So it was quite easy to make Selectrum mimic the buffer usage look and feel of built-in Emacs completion (asking for input in the minibuffer, but displaying corresponding completions in a temporarily displayed buffer right above it). I find deviating from this disconcerting to the point that it makes me literally nauseous (yes, it surprised me too: that I've never noticed this before shows how rare it is for packages to violate it, I think).

But acting like this appears to be impossiible (out of the box) with Vertico: even the completion-at-the-bottom snippet in the wiki only lets you choose between two unsatisfactory-to-me options. The first is "input in the minibuffer as normal but all the completions stuffed in the minibuffer directly above it" (good luck switching to the buffer and hunting some down with C-s or whatever, should you want to: working like this feels constraining, as there is suddenly part of the Emacs UI that is neither obviously the minibuffer nor a buffer, but something in between and I have no idea how to manipulate it). The second, with vertico-buffer mode on, is "completions *and* input in a buffer" (which to me looks utterly bizarre and induces the aforementioned nausea).

I'm frankly astonished that nobody has complained about this before: surely "input in the minibuffer, completions in a buffer directly above it" is the *norm* in Emacs? Where's it gone? Is my almost-directly-from-the-README config breaking something, or what?

(Sorry for the relative lack of info, but I honestly have no idea what to provide because I have no idea if this bizarre behaviour is intentional.)

**Comment by minad** [comment]
> I find deviating from this disconcerting to the point that it makes me literally nauseous
> I'm frankly astonished that nobody has complained about this before

First, let me say that I find such wording unfriendly. Please use a more appropriate tone.

You can try this snippet from the wiki: https://github.com/minad/vertico/wiki#input-at-bottom-of-completion-list
