### ISSUE TITLE
Vertico shows a duplicated section above the normal section

### ISSUE THREAD

**Issue by leira** [minad/vertico#352]
Vertico shows a duplicated section above the normal section, as in the picture. Is it a feature or bug? If a bug, what might be the cause? Where should I look at?
![scrot-duplications](https://user-images.githubusercontent.com/39118/230713964-09c215fa-70c5-4c73-87c1-aa2c7da31f2e.png)

Below is my settings for Vertico:

```
(when (require 'vertico nil 'noerror)
  (require 'vertico-directory)
  ;; Cycle back to top/bottom result when the edge is reached
  (customize-set-variable 'vertico-cycle t)

  ;; Start Vertico
  (vertico-mode 1))
```

**Comment by minad** [comment]
There are probably other completion modes activated in your configuration, e.g., ivy-mode or selectrum-mode. Make sure that you deactivate those.

**Comment by leira** [comment]
Thanks for the reply. How do I find out what completion modes are activated? Can you please give some pointers?

**Comment by leira** [comment]
Mystery solved. `fido-vertical-mode` was enabled, interfered with `vertico`. Thanks for pointing me to the right direction!
