### ISSUE TITLE
Compound tag search with `org-tags-view`

### ISSUE THREAD

**Issue by gusbrs** [minad/vertico#353]
When trying to complete for a compound tag search, like `foo|bar`, with `vertico-mode` enabled, attempts to complete the second part with `TAB` replace the whole input with the current candidate, instead of adding it. As far as I can tell, this is the same case as the one documented for `org-agenda-filter` in the manual/readme. So, if this turns out to be correct, it is only a matter of documenting it too.

To reproduce, start `emacs -Q` (I have here Emacs 28.2 with built-in Org 9.5.5). Setup:

```elisp
(add-to-list 'load-path "~/.emacs.d/elpa/vertico-1.2")
(add-to-list 'load-path "~/.emacs.d/elpa/compat-29.1.4.1")
(require 'vertico)
(vertico-mode)
(setq org-agenda-files '("~/test.org"))
(global-set-key (kbd "C-c a") 'org-agenda)
```
Where `~/test.org` contains:
```org
* Heading 1                                                             :foo:
* Heading 2                                                             :bar:
```
Now try to perform a tag match for, say, "foo OR bar" with `C-c a m f TAB | b TAB` and the result (current input) is `bar` instead of expected `foo|bar` (which would be the case without `vertico-mode` for the same input).

The actual completing task is done by `org-make-tags-matcher` which calls `completing-read` with `org-tags-completion-function` as completion function.

Also, from the documented problematic completion commands in the manual, this seems to be the only one for which a workaround is not provided. The best I could come up with in this case was:

```elisp

(defun gb/vertico-inhibit (orig-fun &rest args)
  (let ((orig-vertico (default-value 'vertico-mode)))
    (vertico-mode -1)
    (unwind-protect
        (apply orig-fun args)
      (when orig-vertico (vertico-mode 1)))))
(advice-add 'org-agenda-filter :around #'gb/vertico-inhibit)
(advice-add 'org-tags-view :around #'gb/vertico-inhibit)
```
Not particularly pretty, I know, but I couldn't think of anything better. And I'd say some workaround is better than none. WDYT?

**Comment by minad** [comment]
Please report such issues to the Org issue tracker in the future. These bugs should really be fixed there. That's also the reason why I am documenting them - I hope that they get finally fixed at some point.

**Comment by gusbrs** [comment]
Thank you!

And I agree with you, of course. It is just these are known cases, and one takes it for granted they are "not priority" from Org's side. Sure it would be better if these issues were fixed there but, in the meantime, we need to somehow live with them. And I reported here assuming it was in the interest of Vertico to have such problematic cases documented.

**Comment by minad** [comment]
> It is just these are known cases, and one takes it for granted they are "not priority" from Org's side.

I wonder why one should take this for granted. In the end someone needs to submit a patch, fixing these issues. For example Tramp host name completion got fixed recently. This is also documented in the Vertico README. Also note that it is not only Vertico which is affected, but every other completion UI if you use completion style different than `basic`. You can try `(setq completion-styles '(flex))` with default completion.

**Comment by gusbrs** [comment]
@minad I tested the workaround in the commit, and I think there's still something amiss. I can get completion for `foo|bar` but submitting that input with `RET` sends only `bar` as result, `M-RET` works though. So probably a binding for `RET` would be in order too?

**Comment by minad** [comment]
I already improved the workaround by setting `vertico-preselect=prompt`.

**Comment by gusbrs** [comment]
Ah, I missed the other commits. Thanks again!

**Comment by minad** [comment]
@manuel-uberti Yes, that's right. This means it is doable, also for Org. ;)
