### ISSUE TITLE
Vertico  in reverse-mode, marginalia, and all-the-icons do not work together

### ISSUE THREAD

**Issue by drewmoseley** [minad/vertico#354]
If I use marginalia-mode with the hook all-the-icons-completion-marginalia-setup and vertico-reverse-mode,
the minibuffer display seems to have trouble showing the right contents.  If I disable all-the-icons-completion-marginalia-setup, or disable vertico-reverse-mode, it seems to work as I expect.

Screenshots attached.

**Comment by minad** [comment]
This doesn't look right. Do you have `icomplete-mode` enabled at the same time? Please create a minimal recipe starting from emacs -Q only, then we can investigate if the issue persists.

**Comment by drewmoseley** [comment]
OK. I'm not sure what happened here. I was going to get back to this and see if I could narrow it down but now I cannot reproduce it. I did not have icomplete enabled.  I don't know what changed but I will keep an eye out for a recurrence.

**Comment by Cletip** [comment]
I had exactly the same problem, and indeed, impossible for me to do it again. However, when the bug occurred, I could do it by activating vertico-reverse-mode, and remove it by desactivating vertico-reverse-mode.
I also use marginalia, and all-the-icons.

To give a more complete description of the bug: when choosing the candidate, some candidates make the total display of consult disappear: no more "goto-line" with consult-line, no more candidate, just the minibuffer. You can go to the next candidate or the previous one, candidates reappear. If you go back to a candidate that bugs, then the bug reappears. I tested with different candidates, and I didn't find any elements that could be displayed wrong: icons, weird characters (like "é"), etc.
So it must come from somewhere else.

Also, I restarted my emacs, and no more bugs
