### ISSUE TITLE
Why can't I find  vertico in the package manager

### ISSUE THREAD

**Issue by ajaxxor** [minad/vertico#357]
![图片](https://user-images.githubusercontent.com/129724342/232494144-dd3a8155-3e8b-44b6-a581-a545b2dafcfe.png)

my archives
```
(setq package-archives
      '(("gnu"   . "http://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
        ("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")))
(package-initialize)
```

enviroment
win10、emacs28.1

**Comment by minad** [comment]
Vertico is available on GNU ELPA. It seems your mirror misses packages.
