### ISSUE TITLE
Space doesn't work

### ISSUE THREAD

**Issue by Compro-Prasad** [minad/vertico#36]
In `M-x` space isn't working like it works in `selectrum`.

**Comment by minad** [comment]
You have to configure a proper completion style, e.g., orderless.

**Comment by Compro-Prasad** [comment]
I don't understand `orderless` well enough. Can you give the specific configuration that might work?

**Comment by Compro-Prasad** [comment]
Its working. I had a mis-configuration on my side. Sorry, for bugging you.
