### ISSUE TITLE
run-with-timer and vertico-quick keys display

### ISSUE THREAD

**Issue by Cletip** [minad/vertico#360]
Hi there !

I tried to run the following code:
`(run-with-timer 3 nil #'vertico-quick-exit)`

So, I run this code, I do M-x, the vertico-quick keys appear well after a while: everything works perfectly. The only problem is this: when the vertico-quick keys are displayed, whether you press C-g or a key that is not present in vertico-quick1 or vertico-quick2, normally the vertico-quick keys should disappear. However, this is not the case here, where the keys remain. I don't understand why. Also, a number (or vector ?) appears from time to time when the wrong key is pressed (I get "[6]" or "[566]" from time to time).

Is this because of run-with-timer, or vertico-quick, or something else ?

**Comment by minad** [comment]
I believe the problem is that when you call `vertico-quick-exit` from a timer that `read-key` is then called outside the normal main event loop. In other words, one should maybe not use `read-key` in a timer. You could instead push a key which triggers 'vertico-quick-exit` to `unread-command-events` from the timer. This may fix the problem. But anyway, this is not an intended use case of `vertico-quick-exit`.

**Comment by Cletip** [comment]
Is there a possibility to call vertico-quick-exit automatically at a certain moment then? If not, how can this be done properly?

**Comment by minad** [comment]
Yes, as I explained, it may work if you use `unread-command-events`.

**Comment by Cletip** [comment]
Thanks you again,

> You could instead push a key which triggers vertico-quick-exit

Sorry, I think I misspoke: I don't want a button to trigger vertico-quick-exit, I want it to be automatic. 

> You could instead push a key which triggers vertico-quick-exit to unread-command-events from the timer.

If I understand correctly, I would have to get the inputs "from a timer" into the unread-command-events variable, then pass them to vertico-quick-exit?

I think I can write the code, but I thought I misunderstood your explanation. Would it be possible to have a pseudocode or more explanation ?
