### ISSUE TITLE
Configure the keybinding that is shown in M-x?

### ISSUE THREAD

**Issue by ckeschnat** [minad/vertico#362]
Hi,

Some commands have more than one keybinding. Vertico seems to always be showing the "first" one (however that is defined).

Example from the help:
![image](https://user-images.githubusercontent.com/2363565/235445997-fcbe84f6-c644-4904-965d-64a62e4fcda4.png)

And vertico:
![image](https://user-images.githubusercontent.com/2363565/235445902-851d3a17-7782-4112-a641-5ec478e4e194.png)

Does anyone know if this can configured? I am not sure if this can/should be done in vertico or the default completion settings. A hint where I could start looking would already be helpful.

Thank you

PS: Just for why I want this: I am using Xah Fly Keys, which has a keybinding for basically everything and I would love for Vertico to show that to me instead of the default binding.

**Comment by minad** [comment]
You can write your own Marginalia annotator which prioritizes Xah keys. See marginalia-annotate-binding, marginalia-annotate-command and marginalia-annotator-registry.
