### ISSUE TITLE
Vertico does not show options when in new frame

### ISSUE THREAD

**Issue by arael** [minad/vertico#364]
If I run the completing-read in the same frame like this:

```
(completing-read "Select: " '("first" "second" "third"))

```
I see the options already and can pick one.

But if I try the same in a new frame like this:

```
(defun test-miniframe-completing-read ()
    "Test miniframe completing read"
    (interactive)
    (with-selected-frame (make-frame '((name . "emacs-miniframe")
    (minibuffer . only)
    (width . 120)
    (height . 33)))
    (unwind-protect
	(let ((choices '("first" "second" "third")))
	    (completing-read "Select: " choices))
	(delete-frame))))

(test-miniframe-completing-read)

```

then I do not see the options. The only way to see them is to insert a character and then delete it. This forces a refresh. But otherwise I just see the prompt. Is there a way to see the options right away also in the new frame?

**Comment by minad** [comment]
This is not a Vertico problem, more likely an upstream issue. You can also try the child frame packages listed in the [Vertico README](https://github.com/minad/vertico#child-frames-and-popups), but I don't recommend this.

**Comment by arael** [comment]
Thank you! The timer suggestion works well, also I learned something new about Emacs in this exchange.

Inserting this line of code before I call the completion-read works well:

```
(run-at-time "0.3 sec" nil #'vertico--exhibit)
```

**Comment by arael** [comment]
Sorry for disturbing again. What is vertico-buffer? I searched for this function in my Emacs and I cannot find it. How would I go about using vertico-buffer in order o avoid timers?

**Comment by minad** [comment]
Take a look at the readme.
