### ISSUE TITLE
Questions about wiki entry on highlighting directories

### ISSUE THREAD

**Issue by hmelman** [minad/vertico#366]
I have some questions about the wiki entry [Candidate display transformations, custom candidate highlighting](https://github.com/minad/vertico/wiki#candidate-display-transformations-custom-candidate-highlighting).  It was mentioned recently and I looked at it and realized I have an older version in my config. I'd be happy to update the wiki after getting answers to these and playing with it in my config.  Thanks.

1. This code highlights with `propertize`, my old code uses `add-face-text-property` to do the highlighting.  A difference is that `propertize` returns a new string.  Is this recommended for such a function, that the candidate string should not be mutated (in this case having properties changed vs the text changing)?

2. Is `sort-directories-first` a real function or just a placeholder for such a function?  I don't have a function named this.  If it's just a placeholder I think the wiki entry should make this clear.

3. This uses `vertico-multiform-commands` to modify `find-file`, my old code affects the `file` category which I think is better.  This should be as simple as setting `vertico-multiform-categories` with `file` instead, right?

4. My knowledge of `cl-` is pretty weak, so this was an opportunity to relearn some of `cl-defmethod`.  Still I wonder if the ability to customize candidates could be made more accessible via an actual `vertico-transform-functions` user option.  In my setup only the vertico extensions and embark make use of `vertico--format-candidate` so perhaps this is really more for "internal" use, but the case of highlighting directories is I think pretty common; maybe it's the only one?

5. My code uses the face `'dired-directory` to highlight directories, the wiki code uses `marginalia-file-priv-dir`.  I prefer using a built in face for this (which more themes are likely to set) and not having a dependency on another package, but if you'd prefer to reference a sister package here I understand.

**Comment by minad** [comment]
1. I don't know if a new string is needed. If yes, then propertize is the way to go.

2. It should be in the wiki.

3. Yes.

4. There are almost no use cases for a transform function.

5. Dired may not be loaded while Marginalia is in my setup.

**Comment by hmelman** [comment]
Thanks.

**Comment by hmelman** [comment]
Rather than using `setq` I'd prefer not to completely overwrite `vertico-multiform-categories`.  Is there a better way to accomplish that than this?

```elisp
(add-to-list 'vertico-multiform-categories
	     '(file
		;; sort-directories-first is defined in the wiki
		;; (vertico-sort-function . sort-directories-first)
		(+vertico-transform-functions . +vertico-highlight-directory)))
```

**Comment by minad** [comment]
You could also use `(setf (alist-get ...`. Not sure if that's better.

**Comment by hmelman** [comment]
Wiki updated.
