### ISSUE TITLE
vertico-mode-map is not honored in bind

### ISSUE THREAD

**Issue by rickalex21** [minad/vertico#367]
Hello,

I tested this on a bare bones configuration with the default vertico config in the Readme.
I have been using embark to yank but I decided to use vertico instead.

Steps to reproduce:
1. C-h f Describe Function
2. Choose one and C-k

It opens up the help instead of running the function. However, if I bind C-k to
vertico-previous function it works fine.

Why does C-k work fine when I bind it to `vertico-previous` but not `my/vertico-yank-candidate`?

```lisp
(use-package vertico
  :init
  (vertico-mode)

  :config
  (defun my/vertico-yank-candidate ()
        "Copy the current candidate to the clipboard."
        (interactive)
        (kill-new (vertico--candidate))(vertico-exit))

  :bind (:map vertico-map
                  ("C-n" . vertico-next)
                  ("C-p" . vertico-previous)
                  ("C-k" . my/vertico-yank-candidate)
                  ;; ("C-k" . vertico-previous)
                  ("C-d" . vertico-scroll-down)
                  ("C-u" . vertico-scroll-up)))

(use-package savehist
  :init
  (savehist-mode))

(use-package emacs
  :init
  (defun crm-indicator (args)
    (cons (format "[CRM%s] %s"
                  (replace-regexp-in-string
                   "\\`\\[.*?]\\*\\|\\[.*?]\\*\\'" ""
                   crm-separator)
                  (car args))
          (cdr args)))
  (advice-add #'completing-read-multiple :filter-args #'crm-indicator)
  (setq minibuffer-prompt-properties
        '(read-only t cursor-intangible t face minibuffer-prompt))
  (add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)
  (setq enable-recursive-minibuffers t))
```
Thanks

**Comment by minad** [comment]
Honestly I don't know, since I haven't used use-package for a while. Please check the use-package manual or other example configurations. Maybe your command should be defined in the :init section? You can also expand the use-package macro to see if the expansion is correct.

**Comment by minad** [comment]
Note that there is already the command `vertico-save` which seems to do what you want?

**Comment by rickalex21** [comment]
I can use vertico-save but the problem is I need a way to close the minibuffer.
This will not work even when done with eval-expression. All of them open the help.

```lisp
(keymap-set minibuffer-local-map "C-k" (lambda ()(interactive)(vertico-save)(vertico-exit)))
(keymap-set minibuffer-mode-map "C-k" (lambda ()(interactive)(vertico-save)(vertico-exit)))
(keymap-set vertico-map "C-k" (lambda ()(interactive)(vertico-save)(vertico-exit)))


```

**Comment by minad** [comment]
Did you try this with emacs -Q? I strongly recommend to use Embark for that btw. Embark can close the minibuffer if desired. The exiting behavior is even configurable or toggable with C-u.

**Comment by minad** [comment]
Ah, I completely misunderstood the issue. You should use `keyboard-escape-quit` or `minibuffer-keyboard-quit` instead of `vertico-exit`.

**Comment by rickalex21** [comment]
Thanks `keyboard-escape-quit`, that fixed it :).

>Honestly I don't know, since I haven't used use-package for a while.

What do you use? Plain elisp   ?
