### ISSUE TITLE
Error on integration with Marginalia

### ISSUE THREAD

**Issue by shanbhardwaj** [minad/vertico#368]
Hi @minad not sure if to put this here or in marginalia, since it's vertico throwing the error I'm putting this here. Since updating the packages yesterday I get the following error message on activating vertico. Both the packages have been installed/updated from git using straight.el

> Error in post-command-hook (vertico--exhibit): (void-variable string-width)

Vertico still work but I can't see the completions in the mini buffer and only see this message. If I disable marginalia, then vertico works as expected and I see the vertical completions.

**Comment by minad** [comment]
https://github.com/radian-software/straight.el/issues/1083
