### ISSUE TITLE
`C-h a` doesn't trigger the incremental minibuffer completion behavior.

### ISSUE THREAD

**Issue by hongyi-zhao** [minad/vertico#369]
I use the vertico configuration given [here](https://github.com/minad/vertico#configuration), but I noticed that `C-h a` doesn't trigger the incremental minibuffer completion behavior:

![image](https://github.com/minad/vertico/assets/11155854/f7ebe9c7-6868-43e0-91fb-0828e2ee2381)

While other similar commands, such as, `C-h v` does:

![image](https://github.com/minad/vertico/assets/11155854/e5d0fd80-e41a-43c8-a8cf-74918753c182)

Any tips for fixing this problem?

Regards,
Zhao

**Comment by minad** [comment]
apropos is not a completion command. You can use embark-export after narrowing C-h v.
