### ISSUE TITLE
M-x suggestions change to (seemingly) random commands after switchting to a go buffer

### ISSUE THREAD

**Issue by TLINDEN** [minad/vertico#372]
Hi,

After using smex for more than the last decade I decided to give vertico a try. It works ok so far, but its behavior after chaning to a buffer with a go file looks weird to me. This is what happens:

When I start emacs, `M-x` w/o entering anything shows this:

![mx-start](https://github.com/minad/vertico/assets/1322812/f2aba7a7-f4e7-4e96-af6d-768cfb48aa72)

This is what I'd expect, it shows past history (savehist is enabled). So far so good. Now I open a go file and enter `M-x` again. This is what I get now:

![mx-golang](https://github.com/minad/vertico/assets/1322812/4be6c854-dfdc-4d73-afba-e03c3a9a3ccf)

These are all random command candidates which doesn't have anything to do with golang. It doesn't make any sense how these candidates have been selected. Really weird.

However, when I switch back to an elisp or any other buffer, always this list is being presented:

![mx-back](https://github.com/minad/vertico/assets/1322812/a7ac290d-85ff-4efd-973a-c5067df60213)

Even if I enter some command, it doesn't show up in the list as it should. The only way to make an end to this behavior is to restart emacs.

One more thing: as can be seen in the last two screenshots, a number (8324) is shown which doesn't change while I scroll through the candidates. This number is different each time I restart emacs but always above 8k. Whatever that means.

Also I tried this with many different other modes like yaml, shell, perl etc. This behavior really only occurs when I start editing a go file.

My vertico related config is pretty standard. I'm using lsp-mode for golang stuff. But the whole thing is a mystery to me. The vertico related config is [here](https://github.com/TLINDEN/dot-emacs/blob/master/lisp/init-smarter-than-emacs.el), the go stuff [here](https://github.com/TLINDEN/dot-emacs/blob/master/lisp/init-go.el), and the lsp stuff [here](https://github.com/TLINDEN/dot-emacs/blob/master/lisp/init-lsp.el).

Any help would be very appreciated because the only alternative for me would be to switch back to smex.

Thanks in advance,
Tom

**Comment by minad** [comment]
Thanks for reaching out. Can you try to reproduce the problem in a minimal example configuration starting from emacs -Q only with vertico-mode and savehist-most? Otherwise it is not possible to debug this problem. 

I have not observed such problems before. For me Vertico always sorts reliably according to the current `minibuffer-history-variable`. To me it looks as if go-mode turns on some other completion UI (Ivy, Ido, Icomplete, ...), since the current candidate is displayed differently  in the different screenshots - without underline in the first screenshot and with underline in the other two screenshots.

**Comment by TLINDEN** [comment]
Thanks a lot! You were right, I had this hook in my go config:
```
(add-hook 'go-mode-hook #'ivy-mode)
```

So, now it works like a charm. And while I was at it, I installed corfu as well and I love it.

Thank you for your work and help!
