### ISSUE TITLE
Vertico hides some candidates

### ISSUE THREAD

**Issue by ahmadv0** [minad/vertico#373]
Vertico doesn't show all candidates. For example, using vertico if I do C-h v, search for "features" (where | is the cursor position) I get:

```
1/1    Describe variable: features|
features
```

but if I move the cursor back I get:
```
1/2    Describe variable: |features
features
system-configuration-features
```

I don't like this behavior, and the problem is related to other packages because when I use any other minibuffer completion package I see all the candidates. For example using (fido-vertical-mode) I get:
```
1/4    Describe variable: features|
features
system-configuration-features
treesit-font-lock-feature-list
browse-url-firefox-startup-arguments
```

I'm using:
Windows 10
Emacs Pretest 29.0.91 (Installed from GNU ftp)
Vertico 1.3 (Installed from ELPA)

Thanks for reading!

**Comment by minad** [comment]
This filtering behavior depends on your configuration of the `completion-styles` variable. I recommend the `orderless` completion style. See the Orderless README, the Vertico README and the Emacs documentation for further information.

**Comment by ahmadv0** [comment]
I don't think it's related to my `completion-styles` value, because If I use for example selectrum with the same `completion-styles` value it doesn't hide anything. However if I use vertico it hides candidates. I even tried it on an instance of `emacs -q` without orderless and without customizing `completion-styles`, and it still hides candidates.

Here is my completion-styles configuration:
```
(setq completion-styles '(orderless basic))
(setq completion-category-overrides '((file (styles basic partial-completion))))
(setq orderless-matching-styles '(orderless-initialism orderless-flex orderless-regexp))
```

**Comment by minad** [comment]
On 5/29/23 08:25, ahmadv0 wrote:
> I don't think it's related to my |completion-styles| value

There exist three variables, which control the completion styles:
completion-styles, completion-category-overrides and
completion-category-defaults. The problem is the setting for symbol-help
in completion-category-defaults. I recommend to reset this variable if
you want Orderless matching everywhere. Please take a look at the
example configuration from the Vertico README.

**Comment by ahmadv0** [comment]
Setting `completion-category-defaults` to `nil` fixed the problem. Thank you!
