### ISSUE TITLE
No completion candidates displayed until typing for async commands

### ISSUE THREAD

**Issue by yanchith** [minad/vertico#375]
Hi! Thanks for vertico <3

I recently tried it out vertico/consult, and I really like it so far - especially the negligible startup speed impact compared to ivy.

I do have one issue, however. It has the exact same symptoms as #325, but I don't use mini-frame-mode.

From what I've observed, this only happens for async commands, like `consult-ripgrep`, `consult-git-grep`, or vertico-completed project.el `project-find-file` or `project-find-dir`, but not for synchronous commands like `consult-line`.

Interesting that this becomes much harder to reproduce for `consult-ripgrep` and `consult-git-grep` after I increase async input debounce, throttle, and delay. This does not, however, help with project.el things, because those are not governed by consult's async settings.

Could this be a race?

OS: Windows 10
Emacs: GNU Emacs 28.2 (build 2, x86_64-w64-mingw32) of 2022-09-13
vertico: 17d7cf79888114c1cbea89cd8e58a3bba986f369
consult: 0e90f516c8cae705709a24ea8071a0c2400360d8

**Comment by minad** [comment]
Thanks. 

Can you please be more precise about the issue? I have never observed such a problem. In order to investigate further, I need a detailed recipe along the lines of https://github.com/minad/consult#bug-reports, ensuring that your configuration does not interfere.

Asynchronous Consult commands require a minimal amount of input in order to start the search. Only after that, candidates may arrive. You probably don't mean that?

Note that `project-find-file` is a synchronous command and candidates should be visible right away (if there are any).If `consult-line` always works reliably for you, it is unlikely that we have a problem with synchronous commands. 

Maybe you still observe some form of #325. From my understanding #325 is caused by an Emacs bug in combination with child frames.

**Comment by minad** [comment]
Rereading the issue again, I suspect that `find`, `grep` or `rg` do not function properly on your system. Unfortunately such issues are not uncommon on Windows. `consult-ripgrep` relies on `rg`, `consult-find` and `project-find-file` rely on `find`. Such a problem with a backend executable is not related to #325 and also not to Vertico. It is rather an installation issue. You could be missing the `find` or `rg` executable or the executable is not found on the path.

**Comment by yanchith** [comment]
> Asynchronous Consult commands require a minimal amount of input in order to start the search. Only after that, candidates may arrive. You probably don't mean that?

Nope. I really meant the issue as described in #325 

> Unfortunately such issues are not uncommon on Windows. consult-ripgrep relies on rg, consult-find and project-find-file rely on find

Note that all of these things worked without issues for me for years with ivy/counsel. I don't believe this is an installation issue, but it may be a Windows-specific issue that ivy/counsel patches over?

> You could be missing the find or rg executable or the executable is not found on the path

I do have them installed. The issue is that sometimes the results arrives late. No results are displayed, until I press a key, such as `C-f`, after which they are displayed.

I am attaching a video of the bug reproduction. While trying to reproduce, I actually noticed even more strange behavior. It looks like the results lag behind. Sometimes one character, sometimes more, and if I type fast enough, no results are displayed.

[repro.webm](https://github.com/minad/vertico/assets/1099245/02fed3e8-0bb7-48c3-873f-f7b86166148a)

If it helps, this is my config: https://github.com/yanchith/emacs.d/blob/4f63d0b39d664e6fedc910965c305788018260ce/init.el

To make this reproduction, I had to change the debounces to zero, but otherwise the video is recorded with this exact config.

```lisp
  (setq consult-async-refresh-delay 0
        consult-async-input-debounce 0
        consult-async-input-throttle 0)
```

**Comment by minad** [comment]
> To make this reproduction, I had to change the debounces to zero, but otherwise the video is recorded with this exact config.

Okay, setting these settings to 0 is not valid. The debouncing, throttling and delay are there for a reason.

**Comment by minad** [comment]
After investigating a bit further in the internals I think `consult--async-refresh-timer` doesn't handle a value of `consult-async-refresh-delay=0` well. If I use `consult--async-refresh-immediate` instead, the problem seems to go away, even if the other variables are set to zero.
