### ISSUE TITLE
Do not complete ambigous filenames

### ISSUE THREAD

**Issue by link2xt** [minad/vertico#383]
I have both `~/src/deltachat/` and `~/src/deltachat-bot/` folders.

With Emacs 28.2 by default if I type `C-x C-f` and then start with a path `~/src/delta` then press `TAB`, Emacs shows possible completions instead of completing to anything. If I configure Emacs with `(setq completion-cycle-threshold t)`, pressing TAB cycles through `~/src/deltachat/` and `~/src/deltachat-bot/`. If I enable `vertico-mode`, pressing `TAB` in the same situation immediatly completes to `~/src/deltachat/` because minibuffer with both completions is open and both completions are selected.

What I want is a bash-like behaviour: pressing TAB completes to `~/src/deltachat` (but not to `~/src/deltachat/`) and offers me to type the next character. If I press `-` then TAB, it completes to `~/src/deltachat-bot/`. If I press `/` then TAB, I start looking at files in `~/src/deltachat/`.

**Comment by minad** [comment]
Please take a look at the README before opening issues. Changing the TAB behavior is documented there: https://github.com/minad/vertico#completion-styles-and-tab-completion. You basically have to bind `minibuffer-complete`.
