### ISSUE TITLE
Replacement for `selectrum-select-from-history` in Vertico

### ISSUE THREAD

**Issue by ghoseb** [minad/vertico#386]
I have recently switched to Vertico from Selectrum. I am trying to figure out a replacement for the `selectrum-select-from-history` function ([selectrum.el#L2473](https://github.com/radian-software/selectrum/blob/284523cf9ab724bb5e73b62e6e80d5a8dc01f535/selectrum.el#L2473)) in Vertico but I couldn't find it in the docs or source-code.
It'd be great if Vertico could support this because that's one thing I use quite often (bound to `C-r` in the minibuffer). If there is any other way of achieving the same result I would appreciate a pointer.
Thank you.

**Comment by minad** [comment]
Hi, you can use `consult-history` for that.
