### ISSUE TITLE
Highlight enabled modes in the command palette (M-x)

### ISSUE THREAD

**Issue by krvpal** [minad/vertico#389]
Hi, thank you for this excellent package. I hope one day this will be merged into Emacs core, as I find this package indispensable while it also adheres to a philosophy of keeping the code lean and clean.

I'm struggling to write a simple function that would help highlight enabled modes in the command palette (M-x). Looking at the history of the wiki page, I notice the below used to be suggested:

> And the following could be added to the previous code to highlight enabled modes
> in the command palette (=M-x=).
> 
> #+begin_src elisp
> (defun +completion-category-highlight-commands (cand)
>   (let ((len (length cand)))
>     (when (and (> len 0)
>                (with-current-buffer (nth 1 (buffer-list)) ; get buffer before minibuffer
>                  (or (eq major-mode (intern cand)) ; check major mode
>                      (ignore-errors (auto-minor-mode-enabled-p (intern cand)))))) ; check minor modes
>       (add-face-text-property 0 len '(:foreground "red") 'append cand))) ; choose any color or face you like
>   cand)
> 
> (add-to-list '+completion-category-hl-func-overrides `(command . ,#'+completion-category-highlight-commands))
> #+end_src

Is there an anologous function one could use, using `vertico-multiform` instead? Thanks in advance for help on this.

**Comment by minad** [comment]
Thanks! Yes, you can adapt the function given in https://github.com/minad/vertico/wiki#candidate-display-transformations-custom-candidate-highlighting. Feel free to add the major mode highlighting function to that wiki section if you figured it out.

**Comment by Aaronzinhoo** [comment]
@minad @krvpal [Added to wiki](https://github.com/minad/vertico/wiki#candidate-display-transformations-custom-candidate-highlighting)

**Comment by krvpal** [comment]
Thanks very much @Aaronzinhoo! I had to make a minor edit and remove one set of parentheses in the below, right before `execute-extended-command`:
```emacs-lisp
(add-to-list 'vertico-multiform-commands
             '(execute-extended-command 
                reverse
                (+vertico-transform-functions . +vertico-highlight-enabled-mode)))
```
I was getting a `wrong type argument: stringp, (execute-extended-command...` error.

Many thanks again!

**Comment by rennsax** [comment]
I just found the default configurations in Wiki did not help, and I need to modify this piece:

```elisp
(add-to-list 'vertico-multiform-commands
             '(execute-extended-command 
               reverse
               (+vertico-transform-functions . +vertico-highlight-enabled-mode)))
```

to

```elisp
(add-to-list 'vertico-multiform-commands
             '(execute-extended-command 
               ;;reverse (this line is removed)
               (+vertico-transform-functions . +vertico-highlight-enabled-mode)))
```

Could anyone kindly explain the reason behind? Thanks!
