### ISSUE TITLE
Highlight group titles?

### ISSUE THREAD

**Issue by minad** [minad/vertico#39]
In consult-grep the file name is moved to the group title and not highlighted anymore. If an Orderless highlight matches the filename it will be neither visible in the group title nor the candidate, even if it appears again in the candidate. Orderless only highlights the first match.

**Comment by oantolin** [comment]
Ah, interesting problem.

**Comment by minad** [comment]
Luckily the question didn't come up before the patch landed in Emacs master ;)

**Comment by minad** [comment]
I think a best effort approach could be as follows:

1. Apply the deferred highlighting function to the group titles (hopefully this does not mess up things)
2. Use the highlighting function after removing the group titles, this should fix the Orderless-specific issue.

Alternatively Orderless could highlight all matches. But I am sure you did this on purpose to avoid some color overstimulation ;)

**Comment by oantolin** [comment]
> But I am sure you did this on purpose to avoid some color overstimulation ;)

Correct. I will not highlight all matches, that way madness lies. 😆

**Comment by minad** [comment]
Wontfix for now.
