### ISSUE TITLE
Question about key mappings (`<minibuffer-end-of-buffer>`)

### ISSUE THREAD

**Issue by xparq** [minad/vertico#390]
Just curious about this asymmetry in `vertico.el`:

    "<remap> <beginning-of-buffer>" #'vertico-first
    "<remap> <minibuffer-beginning-of-buffer>" #'vertico-first
    "<remap> <end-of-buffer>" #'vertico-last

What's the reason of no `"<remap> <minibuffer-end-of-buffer>" #'vertico-last`?

_(Again, just wondering; I'm not familiar enough with the entrails of Emacs. I've seen no difference when I added it myself for a try -- but I'm familiar with Vertico even less then Emacs yet, so...)_

**Comment by minad** [comment]
A command `minibuffer-end-of-buffer` doesn't exist.
