### ISSUE TITLE
vertico-buffer Minibuf window gets lodged in winner ring

### ISSUE THREAD

**Issue by jdtsmith** [minad/vertico#391]
Using vertico-buffer for e.g. consult-line, the temporary ` *Minibuf-XX` window gets placed in the winner ring, if (and only if?) the command is aborted with `C-g`.  Subsequent calls to winner-undo bring that defunct `Minibuf` window back (with its prior contents), at which point the window is not deletable, and the frame has to be closed.

A workaround is `:custom (winner-boring-buffer-regexp " \*Minibuf-[0-9]+")`.  I'm not sure if this is solvable in some other more generic manner, but at least documenting might be useful.

**Comment by minad** [comment]
Sure, thanks. Unclear if we can do much about it. Maybe we can add some window parameter. I am thinking of a hypothetical winner-ignore property. Did you check if something like this exists?

Can you please also check if tab-bar-history-mode is affected? tab-bar-history-mode is the new replacement of winner-mode, so if that is not affected I would rather chose to not document a workaround for winner. Maybe a window parameter could also help there.

If no workaround exists, feel free to open a PR which adds some documentation. Maybe in vertico-buffer.el?  If tab-bar-history-mode is affected, a workaround for it should be documented too.

**Comment by jdtsmith** [comment]
I use native tabs so I'm afraid I don't have much insight into tab-bar-history-mode.

**Comment by minad** [comment]
The tab-bar is something different than tabs. They are more like perspectives. They are also not necessarily visible.

**Comment by minad** [comment]
Okay, from my quick test it seems that `tab-bar-history-mode` is not affected. I recommend to use that instead of `winner-mode`.

**Comment by jdtsmith** [comment]
I tried out tab-bar-mode (with `tab-bar-show=nil`) and unless I'm missing something, it doesn't seem to be a replacement for winner, since you have to actively create a new tab/configuration with `tab-new`.  With winner, every time you change window configurations, it effectively does `tab-new` for you, so you can always go backward to prior configs, no matter what some crazy tool has done to your windows.

**Comment by minad** [comment]
You should enable both `tab-bar-mode` and `tab-bar-history-mode`. This effectively replaces winner and should be more powerful since you can create different separate tabs.
