### ISSUE TITLE
Space bar no longer auto inserts a hyphen when typing in minibuffer

### ISSUE THREAD

**Issue by ghost** [minad/vertico#392]
Hi,

Space bar no longer auto-inserts a hyphen when typing in the mini buffer.

For example, when typing `M-x eval-buffer` in emacs with default settings, you only have to type space and the hyphen is auto inserted. While admittedly minor, this is nice default behaviour.

After installing Vertico as the only package, this no longer works.
Is this a known issue? Or an intentional design decision?

Thanks

**Comment by minad** [comment]
Yes, this is intentional. SPC is important for insertion, for example when the Orderless completion style is used. Default completion binds SPC to minibuffer-complete-word. You can of of course add that binding back to vertico-map if this is desired.
