### ISSUE TITLE
Feature request - vertico-kill-buffer[-next]

### ISSUE THREAD

**Issue by sebyte** [minad/vertico#394]
I was a huge fan of `iswitchb.el`.   `vertico-flat-mode` looks a little like `iswitchb.el` and, with a few altered key bindings, can be made to feel like `iswitchb.el` too, with one important caveat; with `iswitchb.el`, `C-k` could be used to kill the currently selected buffer (and cycle on to the next buffer).  Of course, `vertico.el` does a lot more than just buffer completion but I thought I'd ask in any case; is there any chance of adding a `vertico-kill-buffer[-next]` command, bound to `C-k` while performing buffer completion?

**Comment by minad** [comment]
You can use Embark, which provides this action and many more for other completion contexts.

**Comment by sebyte** [comment]
Installing Embark and employing it for this purpose is complete overkill (if it can even be done).

All that is needed is something like this:

```emacs-lisp
(defun vertico-kill-buffer ()
  (interactive)
  (when (eq (vertico--metadata-get 'category) 'buffer)
    (let ((buff (vertico--candidate)))
      (quit-windows-on buff 'kill)
      (vertico-next)
      (setq vertico--candidates
            (seq-remove (lambda (b) (string= b buff))
                        vertico--candidates)
            vertico--total (1- vertico--total)))))

(keymap-set vertico-map "C-k" 'vertico-kill-buffer)
```
This works well enough for me (in flat mode) but no doubt there's more housekeeping that should be done.

**Comment by minad** [comment]
Embark provides this feature, so it can be done. Using Embark only for this feature is a bit out of proportion, yes. Still, I avoid any kind of overlap with Embark regarding candidate actions. 

Generally, installing Embark is not overkill and I recommend it highly. There are many more features provided by it and it enables new workflows. But Embark is admittedly a complex and featureful package, probably on the level of Helm or Icicles.

**Comment by sebyte** [comment]
I say "if it can even be done" for two reasons:

1. "C-. k" is two key sequences, not one (like "C-k"), plus the "C." prefix key brings up the Embark Actions buffer (which is very much not wanted).
2.  "C-. k" does not cycle to the next candidate.
