### ISSUE TITLE
Feature request: vertico-multiform-buffer

### ISSUE THREAD

**Issue by ashton314** [minad/vertico#398]
I'd like a toggle for `vertico-multiform-buffer` like exists with `vertico-multiform-{vertical,grid,flat,…}`. I just tried adding a binding to the `vertico-multiform-map` and a line like

```emacs-lisp
(vertico-multiform--define-display-toggle buffer)
```

but that didn't work. I take it the buffer display is a little more complicated than the others, yes? Is there a technical reason why this *couldn't* exist?

**Comment by ashton314** [comment]
Woah! Thanks for implementing this!

**Comment by minad** [comment]
You're welcome. Does it work in your setup?

**Comment by ashton314** [comment]
Yes—it works so well!
