### ISSUE TITLE
`vertico-quick` ambiguous tagging for larger candidate lists

### ISSUE THREAD

**Issue by bartkl** [minad/vertico#399]
Hi there,

I'm loving Emacs, and vertico and consult play a big role in that liking, thanks!

I've notived `vertico-quick` seems to only support two-level quick keys, which causes duplicate tagging of the candidates to occur in larger lists. In the following screenshot I've just entered `l` to narrow down all possible selections, and as you can see, due to the big amount of candidates, there's several candidates with the same quick key left.

![image](https://github.com/minad/vertico/assets/2497867/b50f5807-32f7-464b-b563-99109ce75217)

What is particularly confusing is that if I now press `d`, the second matching candidate is chosen. I'm not necessarily sure what would be the most natural behavior here, but at the very least I would expect the first possible candidate to be chosen. Preferably though, I think instead of having a fixed two keys to tag candidates with, you might want to use as many as are necessary to disambiguate all candidates. This way, regardless of the size of displayed candidates, `vertico-quick` works exactly as expected/promised.

What do you think?

Thanks!

**Comment by minad** [comment]
Hi! I adjusted the scheme slightly to support more candidates. Please let me know if it works for you.
