### ISSUE TITLE
How to determine the number of completion candidates?

### ISSUE THREAD

**Issue by Alexander-Miller** [minad/vertico#42]
In am having a rather particular problem in my attempts to potentially migrate to vertico:

In my setup I am using the mini-frame package to show my minibuffer in a child-frame. It does have an option to change the child-frame's size depending on the size of the input. However the way it is implemented the frame will flicker when its size changes between calls: https://github.com/muffinmad/emacs-mini-frame/issues/38

As a workaround I use a function that dynamically determines the mini-frame's frame parameters to include a `height` value. That way the frame has the right size before it appears and there is no flicker.

To make that happen I need to know how many completion candidates there are, so I can adjust the height when there are fewer than X candidates or reduce it to 1 line when I'm seeing a `read-string` or `y-or-n-p` call.

With my current selectrum setup I advise `selectrum--read` which allows me to grab the list off candidates and use it for my height check. However with vertico I haven't been able to find such an entry point. The order of execution is such that when mini-frame's hook is called both `vertico--candidates` and `minibuffer-completion-table` are nil.

Is my convoluted setup workable with vertico, or should I stick with selectrum?

If you want to see for yourself you'll need about the following setup:

```Elisp
(setf
 mini-frame-resize          nil
 mini-frame-show-parameters #'std::mini-frame-show-parameters)

(defun std::mini-frame-show-parameters ()
  ;; determinig the height goes here
  `((background-color . "#2E2E32")
    (left . 0.5)
    (top . 40)
    (height . 10)
    (width . 0.9)))

(mini-frame-mode)
```

**Comment by minad** [comment]
> Is my convoluted setup workable with vertico, or should I stick with selectrum?

There is nothing wrong with sticking too Selectrum. Depends on your preferences. The READMEs describe the differences between the packages.

> To make that happen I need to know how many completion candidates there are, so I can adjust the height when there are fewer than X candidates or reduce it to 1 line when I'm seeing a read-string or y-or-n-p call.

You can try to advice vertico--resize-window, which receives the number of displayed lines. Does this help?

**Comment by Alexander-Miller** [comment]
> There is nothing wrong with sticking too Selectrum.

There isn't, but this completion & minibuffer eco-system that's shot up recently is certainly worth exploring. I've been sticking with helm since the very beginning, so this more minimalist building blocks approach is quite a novel experience for me since I get to learn about all the small details (like `completion-styles`) I've never been exposed to until now.

> You can try to advise vertico--resize-window, which receives the number of displayed lines. Does this help?

Unfortunately it does not. Selectrum it is then. I'll go play around with orderless and embark now :shrug: .

**Comment by minad** [comment]
> so this more minimalist building blocks approach is quite a novel experience for me since I get to learn about all the small details (like completion-styles) I've never been exposed to until now.

Yes, that's the same for me. I understand much better how everything works under the hood. I also think it is easier to understand components separately step by step.

> Unfortunately it does not. Selectrum it is then. I'll go play around with orderless and embark now.

Of course. That's the point that you can replace components a bit more freely :)

**Comment by minad** [comment]
Okay, so I tested this a little bit more and figured out a few more things: mini-popup cannot work with EXWM since it uses child frames. mini-frame works around with a "standalone mode". But in the simple setup I am using, mini-popup seems to work well :)

**Comment by daviwil** [comment]
Now I noticed this comment after posting my issue :)
