### ISSUE TITLE
Should there be a wiki?

### ISSUE THREAD

**Issue by oantolin** [minad/vertico#43]
Someone just asked me how to get ido-like behavior for RET during file completion in Vertico. Apparently in ido RET enters a directory instead of submitting it (you probably remember this from your ido days). I told that person to try this:

```elisp
(defun ret-enters-drectory (_)
  (and minibuffer-completing-file-name
       (>= vertico--index 0)
       (string-suffix-p "/" (vertico--candidate))
       (progn (vertico-insert) t)))

(advice-add 'vertico-exit :before-until #'ret-enters-drectory)
```

I thought maybe I'd put that on the Vertico wiki, only to discover there isn't one. Would be worth adding one? (Maybe not, this is a very focused package and I don't imagine tons of tweaks to it.)

Also, while I'm here: does that seem like a good way to achieve the behavior?

**Comment by minad** [comment]
> I thought maybe I'd put that on the Vertico wiki, only to discover there isn't one. 

There is one. But its empty ;)

See https://github.com/minad/vertico/issues/33. I wrote pretty much the same command as you. I guess we should fill the wiki to have a central place to collect such things.

**Comment by astoff** [comment]
Maybe those [category-specific minibuffer bindings](https://github.com/minad/consult/wiki#add-category-specific-minibuffer-keybindings) in the Consult wiki would make more sense in Vertico's wiki?

**Comment by minad** [comment]
Hmm, I think all the general stuff should be in the Consult wiki. The Vertico wiki should be really restricted to only Vertico-specific UI stuff.

**Comment by daviwil** [comment]
When I click on the Wiki tab on this repo, it jumps back to the main page of the repo.  Weird!

**Comment by minad** [comment]
There was a checkbox "restrict editing to collaborators". Should work now.

**Comment by minad** [comment]
See also https://github.com/minad/vertico/blob/main/extensions/vertico-ido.el
