### ISSUE TITLE
[question] possible to have a fixed height of minibuffer and completion buffer?

### ISSUE THREAD

**Issue by poulpoulsen** [minad/vertico#44]
hello,
i whant to have to following design using vertico with minibuffer and completions buffer.
minibuffer should be e.g. max 3 line high and the completions buffer e.g. max 10 lines high.
if there are more candidates, i want scroll inside the buffers.
is it possible with vertico?
i googled a while and set some related variables, but none works.
`
(setq resize-mini-windows nil) ;; or t
(setq max-mini-window-height 3)
`
do you know a way?

Regards
Poul

**Comment by minad** [comment]
You can set `vertico-count=3` and `resize-mini-windows=nil`.

**Comment by poulpoulsen** [comment]
Hello,
 the first variable works. Fine!
But unfortunately the second one don't.
The minibuffer height is ignored.
I discussed this with user protesilaos, because I use his configuration. His first idea about the reason was a posdible hardcoded setting in minibuffer.el.
but I'm not a developer and therefore I can't understand that in detail.
Is it possible for you to set the minibuffer height to e.g 2 for two lines?
I'm on Emacs 28 Fedora 34.
Perhaps there are differences in the Emacs versions?

Regards
Poul

**Comment by minad** [comment]
I am not sure if you can resize the minibuffer to 2 and 3. But this seems to be a question unrelated to Vertico. Therefore I am closing this issue here. 

You may want to ask on some other channel for that, reddit, irc, some of the discords. Maybe @protesilaos can be of help here?

**Comment by protesilaos** [comment]
> Is it possible for you to set the minibuffer height to e.g 2 for two lines?

I am playing with those in `emacs -Q`:

```elisp
(icomplete-mode 1)

(setq resize-mini-windows nil
      max-mini-window-height 1)

(setq resize-mini-windows t
      max-mini-window-height 1)

(setq resize-mini-windows t
      max-mini-window-height 2)
```

Try `C-h v` and input a single character to see the difference.  It works.

As for the height of the completions' buffer, I need to experiment more with it.  Let's move the discussion to my repo as vertico is not related to it.

**Comment by minad** [comment]
@protesilaos Thanks! I think @poulpoulsen also wants to set a `min-mini-window-height` or did I misunderstand that?

> Let's move the discussion to my repo as vertico is not related to it.

Can you link here to the relevant discussion please? Maybe other people are interested in the outcome of your discussion.

**Comment by protesilaos** [comment]
> Thanks! I think @poulpoulsen also wants to set a min-mini-window-height or did I misunderstand that?

You mean `max-mini-window-height`?  Because I do not have a `min-mini-window-height` here.

> Can you link here to the relevant discussion please? Maybe other people are interested in the outcome of your discussion.

Sure! https://gitlab.com/protesilaos/dotfiles/-/issues/37.

My relevant quote for posterity:

> In general, Vertico is the better option.  Its developer, Daniel Mendler, is an expert and produces high quality packages (consult, corfu, vertico, etc.).  My prot-minibuffer.el started out as an experiment and I just stuck with it: it is not even a complete package, in that it does not define its features as a minor mode, whereas, say, my prot-vc.el does that.

**Comment by minad** [comment]
> You mean max-mini-window-height? Because I do not have a min-mini-window-height here.

Right, it does not exist. I think I didn't understand fully what @poulpoulsen is trying to achieve here. I think I got mostly confused since he was talking about the size of the minibuffer and the completions buffer, which of course there is none in Vertico.

And thanks for praising my packages in such high terms ;)

**Comment by protesilaos** [comment]
No worries: we will figure it out as we go.

> And thanks for praising my packages in such high terms ;)

You are welcome!
