### ISSUE TITLE
Emacs 30 freezes if there isn't enough room due to window-size-fixed

### ISSUE THREAD

**Issue by tarsius** [minad/vertico#446]
To reproduce, create a rather narrow frame, split it vertically and `(setq window-size-fixed 'height)` in one of them. Maybe increase `vertico-count`.

Then invoke `execute-extended-command`, for example. Emacs 30 freezes (pressingly only if it cannot make enough room by resizing the window whose height isn't fixed). I couldn't reproduce with 29.2. This started fairly recently, I believe.

**Comment by minad** [comment]
Thanks. This issue has already been reported here: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=69140
