### ISSUE TITLE
Vertico breaks TRAMP

### ISSUE THREAD

**Issue by TheBlackBeans** [minad/vertico#45]
When `vertico-mode` is enabled, TRAMP breaks.
More specifically, when typing `C-x C-f` `/sudo::`, the password of the computer is asked. 
Once the first key is pressed, TRAMP complains `[Tramp: Opening connection for root@hostname using sudo...failed]`.
When vertico is disabled, TRAMP works perfectly.

**Comment by minad** [comment]
I claim it works. See previous discussion in #2 (duplicate). Do you use the newest commit (Version 0.11)?

**Comment by minad** [comment]
It is already in the repository, see https://git.savannah.gnu.org/cgit/emacs/elpa.git/commit/?h=externals/vertico. The new version 0.11 will probably be available in the package manager in a few hours.

**Comment by TheBlackBeans** [comment]
That was the simplest and fastest problem solving: it already works, but in a few hours. Nice! :)
