### ISSUE TITLE
vertico-flat-mode with vertico-flat-max-lines > 1 does not respect (setq vertico-resize 'grow-only)

### ISSUE THREAD

**Issue by rntz** [minad/vertico#464]
GNU Emacs 29.2 (build 1, aarch64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6.6 (Build 21G646)) of 2024-01-18

Vertico 1.7
Commit: cf8b2abf5207696c054c33214c86e3969d415054

Setup to reproduce:
```elisp
(require 'vertico)
(vertico-flat-mode)
(setq vertico-flat-max-lines 4)
(setq vertico-resize 'grow-only)
(setq resize-mini-windows 'grow-only)
```

Now do something to trigger vertico completion, eg `M-x` or `C-x b`. Probably `M-x` will work well since there will be many possible completions initially, and it will flow over multiple lines if you keep your emacs frame reasonably narrow. Now type until the number of matches is restricted enough to fit on one line.

On my system, the minibuffer *shrinks vertically* to fit onto one line, despite `vertico-resize` and `resize-mini-windows` both being `grow-only`.

Context: I'm trying to use vertico and want it, in some contexts, to emulate `ido-mode` closely (because I'm used to it). `ido-mode` appears to respect `(setq resize-mini-windows 'grow-only)`, which is nice because it keeps my eyes from having to jump around so much as the number of completions narrows.

**Comment by rntz** [comment]
I believe [this line](https://github.com/minad/vertico/blob/68e51fda552a2f91caab69e83564bc91275b09b1/extensions/vertico-flat.el#L88), which temporarily binds `resize-mini-windows` to `t`, is the cause.

Suggested patch:
```diff
--- vertico-flat-original.el    2024-03-31 13:35:08
+++ vertico-flat.el     2024-03-31 13:34:25
@@ -84,8 +84,7 @@
     (push `(vertico--input . ,vertico-flat-map) minor-mode-map-alist)))
 
 (cl-defmethod vertico--display-candidates (candidates &context (vertico-flat-mode (eql t)))
-  (setq-local truncate-lines nil
-              resize-mini-windows t)
+  (setq-local truncate-lines nil)
   (move-overlay vertico--candidates-ov (point-max) (point-max))
   (overlay-put
    vertico--candidates-ov 'after-string
```

Or perhaps it should be `(setq-local resize-mini-windows vertico-resize)`.

But perhaps this is intentional for some reason?

**Comment by minad** [comment]
The behavior is intentional, since for multiform setups we want grow only (or fixed size) for the large vertical mini buffer but still use the least amount of vertical space for the flat mini buffer. Ideally the candidates in flat mode fit on a single line anyway so there won't be too much jumping.

**Comment by rntz** [comment]
I must admit I strongly prefer `grow-only` behavior even for flat/ido-style completions. Is there any way to get this behavior with vertico-flat-mode?

With my patch, you can still get your preferred behavior via, eg:

```elisp
(setq vertico-multiform-commands
      '((execute-extended-command flat (resize-mini-windows . t))))
```

**Comment by minad** [comment]
> I must admit I strongly prefer grow-only behavior even for flat/ido-style completions. Is there any way to get this behavior with vertico-flat-mode?

I strongly do not. ;) You can use an advice to get your desired behavior and override the variables.

**Comment by rntz** [comment]
Fair enough. In case anyone with the same problem stumbles on this thread, here's the advice I used:

```elisp
(defadvice vertico--display-candidates (after reset-resize-mini-windows compile)
  (setq resize-mini-windows vertico-resize))
```
