### ISSUE TITLE
Previous / Next group navigation for multi-sources

### ISSUE THREAD

**Issue by inigoserna** [minad/vertico#47]
Regarding my comment on https://github.com/minad/consult/issues/6#issuecomment-848589198

``` emacs-lisp
(defun vertico-next-group ()
  (interactive)
  (let ((group (car (get-text-property 0 'consult-multi (vertico--candidate))))
        (loop t))
    (while (and group loop)
      (if (= vertico--index (1- vertico--total))
          (progn
            (vertico-first)
            (setq loop nil))
        (vertico-next)
        (unless (equalp group (car (get-text-property 0 'consult-multi (vertico--candidate))))
          (setq loop nil))))))


(defun vertico-previous-group ()
  (interactive)
  (let ((group (car (get-text-property 0 'consult-multi (vertico--candidate))))
        (loop t))
    (while (and group loop)
      (if (zerop vertico--index)
          (progn
            (vertico-last)
            (setq loop nil))
        (vertico-previous)
        (unless (equalp group (car (get-text-property 0 'consult-multi (vertico--candidate))))
          (setq loop nil))))))


(define-key vertico-map '[C-left]  'vertico-previous-group)
(define-key vertico-map '[C-right] 'vertico-next-group)
```

I know, the implementation is very ugly, but it works ;-).
I don't specially like the mention of `consult-multi` text property to get the group symbol here in the vertico package, I don't know if there is a standard way to get it.

What do you think?

**Comment by minad** [comment]
Instead of consult-multi, you should access the group-function of the completion metadata of the minibuffer-completion-table.

**Comment by inigoserna** [comment]
> Instead of consult-multi, you should access the group-function of the completion metadata of the minibuffer-completion-table.

I see I could do it with `(completion-metadata-get metadata 'group-function)`, but where I can get `metadata` from the candidate?

**Comment by inigoserna** [comment]
New version:

``` emacs-lisp
(defun vertico--group-name (cand)
  (let* ((metadata (completion-metadata (minibuffer-contents)
                                        minibuffer-completion-table
                                        minibuffer-completion-predicate))
         (groupfun (completion-metadata-get metadata 'group-function)))
    (funcall groupfun cand nil)))

(defun vertico-next-group ()
  (interactive)
  (let ((group (vertico--group-name (vertico--candidate)))
        (loop t))
    (while (and group loop)
      (if (= vertico--index (1- vertico--total))
          (progn
            (vertico-first)
            (setq loop nil))
        (vertico-next)
        (unless (equalp group (vertico--group-name (vertico--candidate)))
          (setq loop nil))))))

(defun vertico-previous-group ()
  (interactive)
  (let ((group (vertico--group-name (vertico--candidate)))
        (loop t))
    (while (and group loop)
      (if (zerop vertico--index)
          (progn
            (vertico-last)
            (setq loop nil))
        (vertico-previous)
        (unless (equalp group (vertico--group-name (vertico--candidate)))
          (setq loop nil))))))


(define-key vertico-map '[C-left]  'vertico-previous-group)
(define-key vertico-map '[C-right] 'vertico-next-group)
```

**Comment by astoff** [comment]
Maybe remapping forward/backward paragraph or forward/backward page would be better keybindings.

**Comment by inigoserna** [comment]
> Maybe remapping forward/backward paragraph or forward/backward page would be better keybindings.

Something like
``` emacs-lisp
(define-key vertico-map [remap backward-paragraph] 'vertico-previous-group)
(define-key vertico-map [remap forward-paragraph]  'vertico-next-group)
```
?

Uhmmm... yes, it looks better.

**Comment by minad** [comment]
Paragraph sounds good :+1:

**Comment by minad** [comment]
@inigoserna Can you write the code above more compactly? There is too much code duplication above. Probably there should be a single vertico--goto-group function which takes a flag and then this is used by vertico-next-group/previous-group.

**Comment by inigoserna** [comment]
I thought they were tiny functions so some duplication was ok.
Anyway, here you have a new version.

``` emacs-lisp
(defun vertico-next-group (&optional backwards)
  "Move to next group.  If BACKWARDS is t go to previous group instead."
  (interactive)
  (let ((op (if backwards '1- '1+))
        (group (completion--metadata-group-name (vertico--candidate)))
        (loop t))
    (while (and group loop)
      (cond
       ((and (not backwards) (= vertico--index (1- vertico--total)))
        (vertico-first)
        (setq loop nil))
       ((and backwards (zerop vertico--index))
        (vertico-last)
        (setq loop nil))
       (t
        (vertico--goto (funcall op vertico--index))
        (unless (string= group (completion--metadata-group-name (vertico--candidate)))
          (setq loop nil)))))))

(defun vertico-previous-group ()
  "Move to previous group."
  (interactive)
  (vertico-next-group t))

(define-key selectrum-minibuffer-map [remap backward-paragraph] 'selectrum-previous-group)
(define-key selectrum-minibuffer-map [remap forward-paragraph]  'selectrum-next-group)
```
I'm not completely fond of the loop, but I can't think of a better and smaller way.
What do you think?

**Comment by minad** [comment]
It is probably possible to write this more compactly. I will take a look soon. Furthermore `vertico-cycle` should be respected.

**Comment by inigoserna** [comment]
> This is my current version. I am not entirely happy with it.

Sorry, IMHO it looks more complex to understand and uglier than my last version.

Btw, why the use of `before` to get metadata?
I see that, in contrast to selectrum (where I took it from) which uses `minibuffer-contents`, you use only a portion of minibuffer contents in vertico... Is there any advantage in doing so?

**Comment by minad** [comment]
> Sorry, IMHO it looks more complex to understand and uglier than my last version.

Yes, but your version was not correct from what I've seen regarding the cycling (both vertico-cycle=nil/t must be supported). My version also has the ability to jump to the prompt. The prompt is treated as an extra paragraph. If you add this we can compare the versions! If you manage to beat my version, please do so!

> Btw, why the use of before to get metadata?

This is the correct way to retrieve the metadata by definition of Emacs. This is not my invention. The completing read APIs are pretty baroque :shrug: 

But overall I am not happy with this yet. I have to think about it a bit more.

**Comment by inigoserna** [comment]
New version:
- respects `vertico-cycle`
- jump to/from prompt
- retrieve metadata using proper code. I keep the external defun for readibility reasons, but it could be inside the let-clause in main function if you prefer.

```emacs-lisp
(defun completion--metadata-group-func ()
  (let* ((pt (max 0 (- (point) (minibuffer-prompt-end))))
         (before (buffer-substring (minibuffer-prompt-end)
                                   (+ (minibuffer-prompt-end) pt)))
         (metadata (completion-metadata before
                                        minibuffer-completion-table
                                        minibuffer-completion-predicate)))
    (completion-metadata-get metadata 'group-function)))

(defun vertico-next-group (&optional backwards)
  "Move to next group.  If BACKWARDS is non nil go to previous group instead."
  (interactive)
  (let* ((op (if backwards '1- '1+))
         (group-func (completion--metadata-group-func))
         (group (unless (= vertico--index -1)
                  (funcall group-func (vertico--candidate) nil)))
         (loop t))
    (if group
        (while loop
          (if (or (and (not backwards) (= vertico--index (1- vertico--total)))
                  (and backwards (zerop vertico--index)))
              (progn
                (when vertico-cycle
                  (vertico--goto -1))
                (setq loop nil))
            (vertico--goto (funcall op vertico--index))
            (unless (string= group (funcall group-func (vertico--candidate) nil))
              (setq loop nil))))
      (vertico--goto (if backwards (1- vertico--total) 0)))))

(defun vertico-previous-group ()
  "Move to previous group."
  (interactive)
  (vertico-next-group t))

(define-key vertico-map [remap backward-paragraph] 'vertico-previous-group)
(define-key vertico-map [remap forward-paragraph]  'vertico-next-group)
```

**Comment by minad** [comment]
@inigoserna With your recent version I cannot select the prompt when invoking 'vertico-previous-group from the first group. Furthermore if you are in the last group, and invoke 'vertico-next-group, the last element will be selected, which is not consistent. These are subtle details of course.

**Comment by minad** [comment]
Current version:

~~~ elisp
(defun vertico--goto-group (next)
  "Move to next group if NEXT is non-nil, otherwise move to previous group."
  (let* ((end (minibuffer-prompt-end))
         (metadata (completion-metadata (buffer-substring end (max end (point)))
                                        minibuffer-completion-table
                                        minibuffer-completion-predicate))
         (group-fun (or (completion-metadata-get metadata 'group-function) #'ignore))
         (title-fun (lambda ()
                      (if (< vertico--index 0)
                          'vertico--prompt-selected
                        (funcall group-fun (nth vertico--index vertico--candidates) nil))))
         (orig-title (funcall title-fun))
         (orig-index vertico--index))
    (while (let ((last-index vertico--index))
             (if next (vertico-next) (vertico-previous))
             (if (or (= vertico--index orig-index) (= last-index vertico--index))
                 (and (vertico--goto orig-index) nil)
               (equal orig-title (funcall title-fun)))))))

(defun vertico-next-group ()
  "Move to next group."
  (interactive)
  (vertico--goto-group 'next))

(defun vertico-previous-group ()
  "Move to previous group."
  (interactive)
  (vertico--goto-group nil))
~~~

**Comment by inigoserna** [comment]
> @inigoserna With your recent version I cannot select the prompt when invoking 'vertico-previous-group from the first group. 

Can't understand, it works correctly here.

> Furthermore if you are in the last group, and invoke 'vertico-next-group, the last element will be selected, which is not consistent. 

Yeah, I haven't cached this because my last group only contained one entry in my tests

**Comment by inigoserna** [comment]
> Current version:

I like this version the more.
That let inside the while looks a bit hackish for me, but anyway, this last version is more compact. So it's ok for me.

**Comment by minad** [comment]
What do you think about this version which always jumps to the candidate below the headline, also if `vertico-previous-group` is invoked? I like this a bit better since then I can jump back to the old position.

~~~ elisp
(defun vertico--goto-group (next)
  "Move to next group if NEXT is non-nil, otherwise move to previous group."
  (let* ((end (minibuffer-prompt-end))
         (metadata (completion-metadata (buffer-substring end (max end (point)))
                                        minibuffer-completion-table
                                        minibuffer-completion-predicate))
         (group-fun (or (completion-metadata-get metadata 'group-function) #'ignore))
         (title-fun (lambda ()
                      (if (< vertico--index 0)
                          'vertico--prompt-selected
                        (funcall group-fun (nth vertico--index vertico--candidates) nil))))
         (orig-title (funcall title-fun))
         (orig-index vertico--index))
    (while (let ((last-index vertico--index))
             (if next (vertico-next) (vertico-previous))
             (if (or (= vertico--index orig-index) (= last-index vertico--index))
                 (and (vertico--goto orig-index) nil)
               (equal orig-title (funcall title-fun)))))))

(defun vertico-next-group ()
  "Move to next group."
  (interactive)
  (vertico--goto-group 'next))

(defun vertico-previous-group ()
  "Move to previous group."
  (interactive)
  (vertico--goto-group nil))
~~~

**Comment by inigoserna** [comment]
> What do you think about this version which always jumps to the candidate below the headline, also if `vertico-previous-group` is invoked? I like this a bit better since then I can jump back to the old position.

It's perfect!

**Comment by minad** [comment]
@inigoserna Thanks for taking another look. I forgot to credit you in the commit - I force pushed the updated commit.

**Comment by inigoserna** [comment]
> @inigoserna Thanks for taking another look. I forgot to credit you in the commit - I force pushed the updated commit.

Oh, it was not necessary!
But thanks a lot, I appreciate it.

**Comment by minad** [comment]
@inigoserna I am sorry, I had to force push the old commit again. Stefan Monnier just activated the autosync for Vertico to ELPA today and it seems that ELPA already synced in the meantime. This repository should not diverge from the ELPA branch. When I force pushed, the auto sync had not yet happend :(

Next time I will get it right I hope.
