### ISSUE TITLE
vertico doesn't seem to like orderless-flex

### ISSUE THREAD

**Issue by hammerandtongs** [minad/vertico#49]
`Error in post-command-hook (vertico--exhibit): (void-function nil)`

vertico doesn't display or work beyond there using orderless-flex as the method.

vertico works fine with orderless as the method.

to reproduce --

```
(use-package orderless
  :ensure t
  :custom (completion-styles '(orderless-flex)))
```

**Comment by minad** [comment]
There is no such thing as orderless-flex. orderless-flex is an orderless matching style, not a completion style. Take a look at the orderless readme.

**Comment by hammerandtongs** [comment]
ah sorry about that, also thanks for the great packages
