### ISSUE TITLE
Optionally shrink to match candidate list length/height

### ISSUE THREAD

**Issue by protesilaos** [minad/vertico#5]
Hello again Daniel! This is more of a stylistic point, but what do you think about reducing the height of the minibuffer when there is empty space? In this scenario I would expect the minibuffer to contract:

![Screenshot from 2021-04-07 09-19-41](https://user-images.githubusercontent.com/12828033/113819744-69b5d900-9782-11eb-8eef-b303ee7a6dad.png)

**Comment by manuel-uberti** [comment]
I am not seeing this behaviour:

![Screenshot from 2021-04-07 08-34-41](https://user-images.githubusercontent.com/8199224/113821238-20fb2180-977c-11eb-83ee-e473ecd17a93.png)

Although this is from my configuration, not with `emacs -Q`.

**Comment by minad** [comment]
Yes, I am overwriting the variable `(setq-local resize-mini-windows 'grow-only)`, since it must not be nil in order for the display to work. What I could do is to overwrite it only when it is nil and keep it otherwise. If you set the variable to t in your config, it should then grow and shrink as you expect. Does that sound like a good solution?

**Comment by protesilaos** [comment]
> If you set the variable to t in your config, it should then grow and shrink as you expect. Does that sound like a good solution?

Yes, that sounds good, though it did not work in my case. The screenshot I shared originally had it to `t`. Same here:

![Screenshot from 2021-04-07 09-51-02](https://user-images.githubusercontent.com/12828033/113823025-d4691380-9786-11eb-8865-0f9a891e82df.png)

**Comment by manuel-uberti** [comment]
Same for me here with `(setq-default resize-mini-windows t)`.

**Comment by minad** [comment]
> Yes, that sounds good, though it did not work in my case. The screenshot I shared originally had it to t. Same here:

This sounds like an Emacs 28 bug then, you are both using Emacs 28, right? There have been some recent changes in Emacs 28 on how it resizes the minibuffer and Selectrum has also been affected by that.

**Comment by manuel-uberti** [comment]
Yes, I am on Emacs 28, and I did chat with @clemera about this problem on Selectrum [here](https://github.com/raxod502/selectrum/issues/520).

**Comment by minad** [comment]
@manuel-uberti Yes, I've seen that discussion but didn't fully read it. Note that Vertico does not perform its own resizing, it simply relies on Emacs doing the right thing. For this reason I am also not setting `truncate-lines` to t since this would break the resizing on Emacs 27.

**Comment by manuel-uberti** [comment]
FTR, even with `truncate-lines` set to `t` (and `resize-mini-windows` set to `t` at the same time) the problem remains. I guess something is changed on Emacs `master` then.

**Comment by minad** [comment]
If you have time I would appreciate if you report a bug or take a look if such a bug already exists. So to be precise, the minibuffer is grown correctly if you set `'grow-only`? And if you set the variable to `t` it also grows but does not shrink as it should? If you set it to `nil`, the variable is still overwritten locally by Vertico with `'grow-only`.

**Comment by minad** [comment]
Maybe we can create a minimal reproducible example.

~~~ elisp
(defvar-local test-resize-ov nil)

(defun test-resize ()
  (if (overlay-get test-resize-ov 'after-string)
      (overlay-put test-resize-ov 'after-string nil)
    (overlay-put test-resize-ov 'after-string "Multiple Lines 1\nMultiple Lines 2\nMultiple Lines 3")))

(minibuffer-with-setup-hook
    (lambda ()
      (setq-local resize-mini-windows t)
      (setq test-resize-ov (make-overlay (point-max) (point-max) nil t t))
      (add-hook #'post-command-hook #'test-resize nil t))
  (read-from-minibuffer "Test: "))
~~~

**Comment by manuel-uberti** [comment]
These are the results with different values for `resize-mini-windows`:

- `'grow-only`: the minibuffer is grown as expected but doesn't shrink as it should
- `t`: the minibuffer is grown as expected but doesn't shrink as it should
- `nil`: the value for `resize-mini-windows` is locally set by `vertico` (i.e., `Local in buffer  *Minibuf-1*; global value is nil`), but the behavior is as reported for `'grow-only` and `t`

Let me try with your example.

**Comment by manuel-uberti** [comment]
With your code in `emacs -Q`, I get this.

![Screenshot from 2021-04-07 14-25-16](https://user-images.githubusercontent.com/8199224/113866043-1f961d00-97ad-11eb-967f-ca9f29528eb8.png)

How can I test the shrinking, though?

**Comment by minad** [comment]
It is a toggler, just press a few keys "xxxxx"

**Comment by manuel-uberti** [comment]
Right, here we go:

![Screenshot from 2021-04-07 14-29-29](https://user-images.githubusercontent.com/8199224/113866488-b1058f00-97ad-11eb-8c72-9a6d7d84eb8e.png)

**Comment by minad** [comment]
Hmm :( So now we have to expand the minimal example...

**Comment by minad** [comment]
Variant 1:

~~~ elisp
(defvar-local test-resize-ov nil)

(defun test-resize ()
  (if (or (not (overlay-get test-resize-ov 'after-string)) (string-match-p "Three" (overlay-get test-resize-ov 'after-string)))
      (overlay-put test-resize-ov 'after-string "Two Lines 1\nTwo Lines 2")
    (overlay-put test-resize-ov 'after-string "Three Lines 1\nThree Lines 2\nThree Lines 3")))

(minibuffer-with-setup-hook
    (lambda ()
      (setq-local resize-mini-windows t)
      (setq test-resize-ov (make-overlay (point-max) (point-max) nil t t))
      (add-hook #'post-command-hook #'test-resize nil t))
  (read-from-minibuffer "Test: "))
~~~

Variant 2:

~~~ elisp
(defvar-local test-resize-ov nil)

(defun test-resize ()
  (if (or (not (overlay-get test-resize-ov 'after-string)) (string-match-p "Three" (overlay-get test-resize-ov 'after-string)))
      (overlay-put test-resize-ov 'after-string "Two Lines 1\nTwo Lines 2")
    (overlay-put test-resize-ov 'after-string "Three Lines 1\nThree Lines 2\nThree Lines 3")))

(minibuffer-with-setup-hook
    (lambda ()
      (setq-local resize-mini-windows t)
      (setq-local truncate-lines nil)
      (setq test-resize-ov (make-overlay (point-max) (point-max) nil t t))
      (add-hook #'post-command-hook #'test-resize nil t))
  (read-from-minibuffer "Test: "))
~~~

Variant 3:
~~~ elisp
(defvar-local test-resize-ov nil)

(defun test-resize ()
  (if (or (not (overlay-get test-resize-ov 'after-string)) (string-match-p "Three" (overlay-get test-resize-ov 'after-string)))
      (overlay-put test-resize-ov 'after-string "Two Lines 1\nTwo Lines 2")
    (overlay-put test-resize-ov 'after-string "Three Lines 1\nThree Lines 2\nThree Lines 3")))

(minibuffer-with-setup-hook
    (lambda ()
      (setq-local resize-mini-windows t)
      (setq-local truncate-lines nil)
      (setq-local max-mini-window-height 1.0)
      (setq test-resize-ov (make-overlay (point-max) (point-max) nil t t))
      (add-hook #'post-command-hook #'test-resize nil t))
  (read-from-minibuffer "Test: "))
~~~

Can you play a bit around with the various settings of `vertico--setup` if it is possible to figure out which setting causes the issue?

**Comment by minad** [comment]
Another thing to try:

~~~
(add-hook #'post-command-hook #'test-resize -99 t) ;; Note the priority!
~~~

**Comment by manuel-uberti** [comment]
Some results from `emacs -Q`:

**Variant 1**
![1](https://user-images.githubusercontent.com/8199224/113867932-6a189900-97af-11eb-9d28-96ce3b79b032.png)

![2](https://user-images.githubusercontent.com/8199224/113867940-6d138980-97af-11eb-848b-41439d181d64.png)

![3](https://user-images.githubusercontent.com/8199224/113867947-700e7a00-97af-11eb-837a-dbaed9f22d0f.png)


**Variant 2**
![4](https://user-images.githubusercontent.com/8199224/113868162-aa781700-97af-11eb-98db-c36c72d55c9d.png)

![5](https://user-images.githubusercontent.com/8199224/113868174-af3ccb00-97af-11eb-8967-408d1e2ed307.png)

![6](https://user-images.githubusercontent.com/8199224/113868181-b19f2500-97af-11eb-969b-230f23a20185.png)

**Variant 3**
Without posting other screenshots, same as above.

**Comment by manuel-uberti** [comment]
Also, with my `init.el` loaded and with these enabled:
```
Enabled minor modes: Auto-Composition Auto-Compression Auto-Encryption
Auto-Image-File Column-Number Cursor-Intangible Delete-Selection Electric-Indent
Envrc-Global File-Name-Shadow Git-Identity-Magit Global-Company Global-Diff-Hl
Global-Eldoc Global-Font-Lock Global-So-Long Line-Number Menu-Bar
Minibuffer-Depth-Indicate Minibuffer-Electric-Default Mouse-Wheel Recentf
Save-Place Savehist Shell-Dirtrack Show-Paren Smartparens Smartparens-Global
Tool-Bar Transient-Mark Vertico Window-Divider Winner
```
I get the same behavior as in `emacs -Q`. My only customization for `vertico` is `(setq vertico-count-format nil)`.

**Comment by minad** [comment]
Okay, so we don't get a minimal example like this. You may want to try to stab randomly at `vertico--exhibit` and `vertico--setup` to see what causes this. I am pretty certain that this is a regression introduced in Emacs 28 since on 27 everything works as expected and I am not doing anything very unreasonable. Note that we used `read-from-minibuffer` in the above examples, you may want to replace that with `completing-read` instead and `vertico-mode` disabled in order to see if that changes anything.

**Comment by manuel-uberti** [comment]
Perhaps asking for help on emacs-devel might be the quicker route? I tried playing with the functions you mentioned, but beside what you already offered above in terms of setting I wasn't able to nail down the problem. I am fairly sure on emacs-devel who changed this behavior in Emacs 28 can give you some ideas.

**Comment by minad** [comment]
Yes, sure. I should also install Emacs 28 at some point. Then I can produce a minimal reproducible example. However this is low priority for me right now. Since minibuffer growing works on 28 which is more important and on my 27.1 setup everything works as is.

**Comment by minad** [comment]
I changed my mind and implemented this differently now. I truncate lines since this generally gives a better UI experience. And then I manually resize to the desired numbers of lines, which also gives a less bumpy experience in some cases. For example I use a resized face for the consult-buffer group titles. Please give it a try.

**Comment by manuel-uberti** [comment]
Just tried with `resize-mini-windows` set to `t` and it works as expected! Thank you for this.

**Comment by minad** [comment]
Thank you for checking!
