### ISSUE TITLE
Completion items title are invisible, but embark still showing their data

### ISSUE THREAD

**Issue by WorldsEndless** [minad/vertico#50]
Trying out Vertico for the first time, I've done everything as shown in the readme. But when I try to open any menu, such as M-x for Find-File, the list is populated but actual items are invisible. Note that the marginalia stuff still shows up, and likewise if I `M-w` I copy the actual name of the item (the same name that I am unable to see). 

When I turn off `vertico-mode` and turn on, e.g. `selectrum-mode` (after loading its package), Selectrum results show up fine. Why are my vertico results hidden? 

![image](https://user-images.githubusercontent.com/5042778/120085398-087cf880-c095-11eb-99a2-4c6366aafc2d.png)

**Comment by WorldsEndless** [comment]
Apparently it has something to do with my marginalia setup; when I turn off `marginalia-mode`, I can see the names again.

**Comment by WorldsEndless** [comment]
After a reboot the problem behavior seems to have gone away. Future users know that it might just be an instantiation issue, since these libraries are dealing with pretty core parts of emacs and swapping them may require a fuller reboot.

**Comment by minad** [comment]
You mean reboot Emacs or the lowlevel OS? From my experience Marginalia and Vertico should not require you to reboot Emacs. :smile:
