### ISSUE TITLE
Error in post-command-hook (vertico--exhibit)

### ISSUE THREAD

**Issue by Antigen-1** [minad/vertico#500]
```
$ emacs --version
GNU Emacs 29.
```

With a recent package update, vertico.el doesn't work now. Emacs says `Error in post-command-hook (vertico--exhibit): (void-function compat--completion-metadata-get)`.

**Comment by mukundzare** [comment]
I have this similar problem in Emacs 29:
`Error in pre-command-hook (vertico--prepare): (invalid-function static-if)`

My analysis: The macro `static-if` is defined in **compat-30.el** but can be found via `M-x describe-function` and it correctly points to the macro being defined in **compat-30.el**. Thinking that there could be a problem with the bytecode, I cleared all occurrences of **compat-30.el** as well as **compat-30.eln** and all the cached data. Reinstalled compat.el but the error won't resolve.
