### ISSUE TITLE
No Info Manual?

### ISSUE THREAD

**Issue by hmelman** [minad/vertico#509]
I believe I used to have an info manual for vertico and vertico.el still has:

>   :link '(info-link :tag "Info Manual" "(vertico)")

but I don't have an info manual installed.   Same thing for corfu (no manual installed and I think there used to be one), though I do have manuals for embark and orderless.  Have these manuals been removed or is my install somehow broken? I know I can just use README.org but some features of info are nice.

I use package.el and the macport of emacs 29.1.

**Comment by minad** [comment]
I have Vertico installed from ELPA and there is a manual.

**Comment by minad** [comment]
Yes, I believe MELPA doesn't provide a build process which converts from Org to Info.

**Comment by hmelman** [comment]
Ah, I see that's true.  Might be nice to put a note to this effect in the README.org
