### ISSUE TITLE
Inconsistent behavior on the pointer in the minibuffer.

### ISSUE THREAD

**Issue by Doodler8888** [minad/vertico#510]
If i execute `previous-history-element` or `next-history-element` in the minibuffer invoked using `M-x`, and the cursor was at the very beginning, after a history item is inserted, the cursor doesn't move to the end of the inserted item. However, it does if there is any character already written. It seems to me that it doesn't really work as it's supposed to. If this is not a bug and it works as designed, is there any way to make the behavior consistent so that the cursor always ends up at the end of the inserted history item, regardless of the situation?

![image](https://github.com/user-attachments/assets/249658b5-9dab-49b5-bc81-a25358550157)

executing `previous-history-element` gives:

![image](https://github.com/user-attachments/assets/3cdd5173-fa6c-4c6a-aedc-90af71618e6f)

and if i insert any character then:

![image](https://github.com/user-attachments/assets/ce494687-6e31-494b-8f94-1af18bf9198a)

executing `previous-history-element` gives:

![image](https://github.com/user-attachments/assets/37efdc73-c081-4c63-ba14-ee0efaeb7257)

GNU Emacs 30.0.60 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.0) of 2024-08-20

**Comment by minad** [comment]
This problem seems to occur too if Vertico is disabled. The commands `previous-history-element` and `next-history-element` are not managed or modified by Vertico.

**Comment by Doodler8888** [comment]
Yeah, my bad. The fix is easy for anyone wondering:

(defun my-previous-history-element (arg)
  "Insert the previous history element, moving the cursor to the end."
  (interactive "p")
  (previous-history-element arg)
  (move-end-of-line 1))

(defun my-next-history-element (arg)
  "Insert the next history element, moving the cursor to the end."
  (interactive "p")
  (next-history-element arg)
  (move-end-of-line 1))
