### ISSUE TITLE
readme information about build-in completion styles - ignore case

### ISSUE THREAD

**Issue by ssnnoo** [minad/vertico#52]
I use vertico with emacs build-in completion styles: 

`(setq completion-styles '(basic substring partial-completion emacs22 flex))`

and this works quite well (similar to ido etc) with

```
(setq read-file-name-completion-ignore-case t)
(setq read-buffer-completion-ignore-case t)
```

would it be worthwhile to mention these two variables in the readme when mentioning that it is also possible to not use orderless?

**Comment by minad** [comment]
Of course we can expand the readme a bit. This has been suggested before. The readme states that Vertico is fully compliant with the Emacs completion infrastructure, this basically says it all. But it is a bit abstract :)
