### ISSUE TITLE
Feature request add an option to add a prefix character before selected candidate

### ISSUE THREAD

**Issue by jessy836** [minad/vertico#525]
Would it be possible to add a variable or an extension to prefix the currently selected candidate by a prefix ? To be more clear, I would like to be able to have something like in ivy. for example:

``` text
2/3 M-x candidate
   first-candidate
>  second-candidate
   third-candidate
```

In this example `>` indicate that `second-candidate` is selected and will be executed if I press RET.

And I would like to take this opportunity to say you thanks for this greatpackage !

**Comment by minad** [comment]
See https://github.com/minad/vertico/wiki#prefix-current-candidate-with-arrow

**Comment by jessy836** [comment]
> See https://github.com/minad/vertico/wiki#prefix-current-candidate-with-arrow

Thanks, I tryed to put the suggested elisp code in my config but it had no effect. I also tryed to do that starting f from emacs -Q like that:

1. emacs -nw -Q
2. package-install RET vertico RET
3. M-x vertico-mode(to check if vertico was correctly installed and it was)
3. put the suggested code in scratch buffer and execute it
4. M-x to open mini-buffer and check if something happened but nothing changed
4. M-x vertico-mode two times, to disable then  reenable vertico-mode and even like that nothing changed, is just the standard vertico

I'm using  emacs 29.4 emacs in terminal with emacs -nw, don't know if one of this things can have an impact. 

please let me know if I can do something else to help you to diagnose the issue.

**Comment by minad** [comment]
> I'm using emacs 29.4 emacs in terminal with emacs -nw, don't know if one of this things can have an impact.

Yes, the snippet relies on the fringe which is only available on GUI Emacs. But you can rewrite it to alternatively add a prefix string instead.
