### ISSUE TITLE
Newest commit breaks vertico when `vertico-resize` is `nil`

### ISSUE THREAD

**Issue by realcomplex** [minad/vertico#538]
Hi! Love the package. I just happened to pull the latest version a few minutes ago, and noticed that things were not working anymore. It turns out, when `vertico-resize` is set to `nil`, somehow this prevents vertico from showing up at all; I only get the "regular" minibuffer without any completion. When the variable is set to `t` or `'grow-only`, everything works fine.

This should be trivial to reproduce (just set `vertico-resize` to `nil` and see what happens), but let me know if for some reason that doesn't work; then I can put more work into providing a proper minimal working example. But it looks like a simple issue to me, so I thought I'd try with a simple bug report first.

**Comment by minad** [comment]
Thanks for the early report!
