### ISSUE TITLE
Undo doesn't work reliably

### ISSUE THREAD

**Issue by jakanakaevangeli** [minad/vertico#55]
Similar to https://github.com/raxod502/selectrum/issues/31 .
Maybe something like the following fix, copied from selectrum:

```diff
@@ -470,7 +470,8 @@ (defun vertico--add-face (face beg end add &optional obj)
 (defun vertico--exhibit ()
   "Exhibit completion UI."
   (vertico--tidy-shadowed-file)
-  (let* ((pt (max 0 (- (point) (minibuffer-prompt-end))))
+  (let* ((buffer-undo-list t)
+         (pt (max 0 (- (point) (minibuffer-prompt-end))))
          (content (minibuffer-contents-no-properties))
          (before (substring content 0 pt))
          (after (substring content pt))
```

**Comment by minad** [comment]
I don't see why this fixes anything. Vertico does not manipulate the buffer itself.

**Comment by jakanakaevangeli** [comment]
Daniel Mendler ***@***.***> writes:

> I don't see why this fixes anything. Vertico does not manipulate the buffer itself. It only adds overlays.

It seems like moving overlays means moving markers and according to
buffer-undo-list's doc string, that is recorded in the undo list. I'm no
undo expert though.

You can try it: From a file, deep in a FS hierarchy, type C-x C-f, and
then press M-DEl a few times in the minibuffer. Undoing these deletions
will not work without this patch applied.
