### ISSUE TITLE
If truncate-lines is set to nil, annotations are wrapped

### ISSUE THREAD

**Issue by jakanakaevangeli** [minad/vertico#56]
![2021-06-09-112915_675x376_scrot](https://user-images.githubusercontent.com/75501874/121329979-323fe600-c905-11eb-8f1a-540f439615c0.png)

Perhaps experimenting with setting auto-hscroll-mode to `current-line` could be
worth considering.

**Comment by minad** [comment]
Yes, you can try hscroll. But the behavior here is intentional. This happens for small frames such that the prompt and input wraps and is completely visible.

**Comment by jakanakaevangeli** [comment]
Yup, I understand why we want the input to wrap and I prefer it that way
myself. This report is more about the candidates and their annotations
wrapping.

Here I attach another screenshot where every shown candidate is
wrapped, which can be quite distracting.

![2021-06-09-181306_675x601_scrot](https://user-images.githubusercontent.com/75501874/121391376-d34a9300-c93d-11eb-8b72-af1eb0e16b1a.png)

**Comment by minad** [comment]
It is not easily possible to avoid wrapping the candidates and wrap the prompt or is it? 

For me this scenario is unimportant, it is only a fallback such that the prompt stays usable for small frames. I don't want to have messy workarounds here.

**Comment by jakanakaevangeli** [comment]
Yeah, I looked a bit into this and it doesn't seem like selective
truncation like this is possible.

> I don't want to have messy workarounds here.

Vertico already truncates candidates to window-width in
vertico--format-candidates, but before concatenation with affixations.
We could try truncating after concatenation.

Or we could have marginalia.el calculate truncation width more
correctly, taking into account the width of candidates.

**Comment by minad** [comment]
> We could try truncating after concatenation.

No, this will not work well. Marginalia does its own formatting and alignment which is not compatible with truncation.

Marginalia already truncates as much as it can but it simply does not work well for a large range of window widths. This is okay. In order to fix the problem at the root one would need sth better than an annotation/affixation-function, which returns multiple fields. The alignment is then performed by the UI completely.

My tendency is to close this as wontfix.

**Comment by minad** [comment]
One more comment - Vertical only truncates multiline candidates.

**Comment by minad** [comment]
Closing as wontfix
