### ISSUE TITLE
First group title not shown if vertico-count is even

### ISSUE THREAD

**Issue by jakanakaevangeli** [minad/vertico#57]
To reproduce, make a bunch of buffers, `M-x consult-buffer` and press `C-v`.
Behaviour is different if vertico-count is set to an odd or an even number.

**Comment by minad** [comment]
Yes, this can happen when you scroll. This is hard to fix if you don't want the current candidate line to jump when scrolling.

**Comment by minad** [comment]
I think the scrolling Vertico is doing right now is simple and reasonable. Both candidates and group titles are scrolled over. Wontfix.
