### ISSUE TITLE
Cycle groups

### ISSUE THREAD

**Issue by minad** [minad/vertico#63]
Add commands to cycle the groups. After cycling the topmost group should stay at the top even when changing the filtering string. Is it reasonable to replace `vertico-next/previous-group` with this? Do we need both `vertico-cycle-group-forward/backward` and `vertico-next/previous-group`, or are group cycling commands more useful such that these are sufficient? To me the cycling commands seem to be more useful actually.

*Original Consult issue by @Crandel: https://github.com/minad/consult/issues/337*

*Issue regarding `vertico-next/previous-group` #47*

cc @inigoserna @astoff

**Comment by minad** [comment]
*Copied from https://github.com/minad/consult/issues/337#issuecomment-862988424:*

-------

There is one more feature I wanted to make you aware of - [Consult Narrowing](https://github.com/minad/consult/#narrowing-and-grouping). This allows you to quickly narrow down to a source. For example if you have set `consult-narrow-key` to `<`, you can press `<f`, `<m`, `<b` to restrict to **f**iles, book**m**arks or **b**uffers only. To unrestrict you can press `<<`. Imo this feature is better than the cycling feature of helm since it allows you to go directly to the desired source. Of course this means adjusting your muscle memory in contrast to the Helm cycling ;)

I looked into how cycling could be implemented in Vertico and thought about this a bit more. And I have my doubts if it should be added because of the narrowing I just described, because of the additional complexity and also because we already have `vertico-next/previous-group` which allows you to jump between the groups in a way which is familiar from the paragraph navigation in normal buffers. I am not so sure I want to add multiple features which overlap a lot.

**Comment by minad** [comment]
Prototype here: https://github.com/minad/vertico/pull/64

**Comment by astoff** [comment]
At first glance the cycling seems indeed nicer to use. I think it makes sense to provide only one kind group command, whatever it will be in the end.

**Comment by minad** [comment]
@astoff I pushed an updated version of the cycling group commands, which work well. I would appreciate if you give it a try.

@inigoserna What do you think about this? I am interested in your opinion since you proposed the patch for the `vertico-next/previous-group` movement commands.

I think the cycling variants of the group commands are more useful. But they also introduce significant complexity. The non-cycling commands in contrast are nicely isolated and non-intrusive. One thing I am missing with the cycling grouping commands is a possibility to reset. This is of course trivial to implement, but it would require an additional weird keybinding.

**Comment by Crandel** [comment]
Why this issue was closed?

**Comment by minad** [comment]
I merged it into the main branch https://github.com/minad/vertico/commit/02579f59d3e0e28f553a575e423fcaf83349dd6d

**Comment by Crandel** [comment]
Ohh, I see. I subscribed to another PR and missed this one.

**Comment by Crandel** [comment]
When new release will be published to `elpa`?

**Comment by minad** [comment]
I will wait a bit if there are some upcoming issues before tagging a new release.

**Comment by Crandel** [comment]
OK, thank you very much!

**Comment by astoff** [comment]
> I think the cycling variants of the group commands are a bit more useful, since they are more than plain movement commands

To me, the main advantage of the cycling commands is that the selected candidate remains at the top of the candidate list, so one can see more items in the current group.

Apart from this, I actually liked that the group forward/backward were plain movement commands. This meant one could see updates to the match counter; or move to the end of a group with `C-<down> <up>`; or other minor things like this. But those are all minor details, I think.

**Comment by inigoserna** [comment]
> @inigoserna What do you think about this? I am particularly interested in your opinion since you proposed the patch for the `vertico-next/previous-group` movement commands.

Sorry for the late reply, too busy with work and family these days.

> I think the cycling variants of the group commands are a bit more useful,

I totally agree, cycling variants are better. It does not have much sense to have both of them.
After a quick test it is working perfectly here.

Thanks!

**Comment by minad** [comment]
@astoff 

> Apart from this, I actually liked that the group forward/backward were plain movement commands. This meant one could see updates to the match counter; or move to the end of a group with C-down up; or other minor things like this. But those are all minor details, I think.

Yes, I agree with that. But overall the cycling variants are more powerful. And I think it is better to kick out the plain movement commands. 

One can of course also using the cycling commands for movement with the same effect, let's say, if you are only interested in moving down, except that you lose the counter/location information. You are right that for the `C-down up` movement there is no substitute, but I think that this is not really a good use of the UI, since it involves too much movement. Ideally the user narrows down more such that such a movement would rarely be beneficial.

I want Vertico to stay a bit small and maintainable. Probably I am also a bit more opinionated in what this UI should offer, since there are so many alternatives :)

@inigoserna Thanks for taking a look. I am glad you like it.

**Comment by Crandel** [comment]
Hi @minad . I had tested cycling groups. Works like a charm, thank you again!
