### ISSUE TITLE
Is it possible to have vertico-backward-kill-sexp?

### ISSUE THREAD

**Issue by Crandel** [minad/vertico#65]
In Selectrum I used `<right>` keybinding as selectrum-insert and `<left>` keybinding as [selectrum-backward-kill-sexp](https://github.com/raxod502/selectrum/blob/master/selectrum.el#L1925). I already mapped `<right>` to vertico-insert, but I can not find anything similar to `selectrum-backward-kill-sexp` in vertico to remove current candidate or move to previous folder in case of `find-file`. Is it possible to have `vertico-backward-kill-sexp`?

**Comment by minad** [comment]
What about plain `backward-kill-sexp` and `kill-sexp`?

**Comment by Crandel** [comment]
I tried to map backward-kill-sexp, but it works very strangely for files.

**Comment by minad** [comment]
See also https://github.com/minad/vertico/issues/33

**Comment by Crandel** [comment]
Actually `backward-kill-word` works as was expected for me. Thank you for your help and for this wonderful package.

**Comment by minad** [comment]
I think there may still be issues with spaces in directory names, but who uses spaces in directory names ;)
In any case, such special navigation commands are very easy to write on the level of the user configuration.

**Comment by milkypostman** [comment]
just leaving a note here about inheriting "close to IDO behavior" type thing. I dislike the way that "C-w" works with paths. I have, for a long time, relied on `C-w` deleting the previous word and had IDO configured similar.

The following snippet is enough for me,

```
  (defun vertico--backward-updir ()
    "Delete char before or go up directory, like `ido-mode'."
    (interactive)
    (if (eq (char-before) ?/)
	(save-excursion
	  (goto-char (1- (point)))
	  (when (search-backward "/" (point-min) t)
	    (delete-region (1+ (point)) (point-max))))
      (call-interactively 'backward-kill-word)))
```

**Comment by minad** [comment]
@milkypostman Can you add this to the wiki please maybe with a link to this issue?

**Comment by milkypostman** [comment]
totally happy to. give me a few days if you don't mind. find some time to get the push/editing done.

**Comment by milkypostman** [comment]
Done! @minad thanks for your help and being so responsive!

Out of curiosity, is there any way to know if we're completing for files vs buffer or help or something else? I'm not actually asking for a solution because (i) I don't want to complicate vertico and (ii) it's not really necessary, but if it was already there it could help with binding of the helper function above.

**Comment by minad** [comment]
> Out of curiosity, is there any way to know if we're completing for files vs buffer or help or something else?

Yes, there is - it is called the completion category. Look for `completion-metadata` and `completion-metadata-get` in the Vertico source.

**Comment by iyefrat** [comment]
Hey, I don't know if this is overkill for your purposes, but I use the following function for this:

```emacs
(defun vertico--backward-updir ()
  "Delete char before or go up directory for file cagetory completions."
  (interactive)
  (let ((metadata (completion-metadata (minibuffer-contents)
                                       minibuffer-completion-table
                                       minibuffer-completion-predicate)))
    (if (and (eq (char-before) ?/)
             (eq (completion-metadata-get metadata 'category) 'file))
        (let ((new-path (minibuffer-contents)))
          (delete-region (minibuffer-prompt-end) (point-max))
          (insert (abbreviate-file-name
                   (file-name-directory
                    (directory-file-name
                     (expand-file-name new-path))))))
      (call-interactively 'backward-delete-char))))
```
Other than only activating on `file` category completions, it also goes up a directory correctly on `~/` which I find very useful.

**Comment by minad** [comment]
See also https://github.com/minad/vertico/blob/main/extensions/vertico-ido.el
