### ISSUE TITLE
CRM prompt cursor issue with long candidate strings, or many selections

### ISSUE THREAD

**Issue by bdarcus** [minad/vertico#70]
When selecting multiple candidates in bibtex-actions, or many candidates such that in general they extend beyond the width of the window, the cursor "drops" from the prompt to below the narrowed candidate.

Screenshot:

![Screenshot from 2021-07-04 11-49-50](https://user-images.githubusercontent.com/1134/124391313-07f00700-dcbe-11eb-9530-a2a8bf7a6f15.png)

Is there anything you can do about that? I believe Selectrum scrolls with the list?

**Comment by minad** [comment]
Probably related to #9

**Comment by minad** [comment]
Fixed in https://github.com/minad/vertico/commit/897e214a40173d9bc34731eddabc5e78967bea93
