### ISSUE TITLE
Disable Sorting

### ISSUE THREAD

**Issue by tpeacock19** [minad/vertico#71]
Is there a way to disable the sorting vertico does for individual functions? I understand it does default to the `display-sort-function` in the `minibuffer-completion-table`, but there are some functions I rely on that do not comply with this. For example `org-refile`, `org-agenda-refile`, and from [org-mru-clock](https://github.com/unhammer/org-mru-clock) `org-mru-clock-in`.

**Comment by minad** [comment]
You can advise `completion-metadata-get` and return `identity` for `display-sort-function/cycle-sort-function`. This disables sorting completely. Alternatively you can advise `vertico--sort` and replace it with `identity`. For now I have no plans to add extra facilities to customize sorting. Why do you want to disable `org-refile` sorting? For me `org-refile` works well as is with `org-refile-use-outline-path=file`.

**Comment by tpeacock19** [comment]
Well when using Selectrum with sorting disabled it seems like the refile candidates are sorted by file. Whereas with vertico they are sorted by length. I do not believe this is something specific to Selectrum as I have disabled sorting so I have to imagine the candidates are presented by file from `org-refile`. 

selectrum

![2021-07-04T13:04:22,849136870-07:00](https://user-images.githubusercontent.com/6407145/124398040-1d3b5480-dd03-11eb-8066-60faf676f07a.png)


vertico

![2021-07-04T13:04:37,598109720-07:00](https://user-images.githubusercontent.com/6407145/124398045-20364500-dd03-11eb-8c15-bc143915be1e.png)

The issue is not really pressing as I often know where I want to refile. But moreso wanted to know how to go about preventing vertico sorting by length. I will proceed with advising `vertico--sort` for the time being. (I had earlier tried but used `ignore` instead of `identity` which of course did not work.

**Comment by tpeacock19** [comment]
And using the advise does get me the same sorting as above so that works for me! sorry for the simple question and thanks for the quick response.

**Comment by minad** [comment]
> But moreso wanted to know how to go about preventing vertico sorting by length. 

I considered offering a configurable sorting, but decided against it for now. I like the UI of sorting by length. Then the current sorting is quite optimized - sorting by length allows bucketing and sorting in linear time. In order to achieve the same performance with alphabetical sorting we would have to bucket by prefix strings, which would add a bit of complexity. It is unfortunately not as simple as just disabling sorting by length via some configuration variable.

**Comment by minad** [comment]
I added configurable sorting https://github.com/minad/vertico/commit/e2c91a69566616f1fe07816b0ea989b55ae49c8d

**Comment by tpeacock19** [comment]
that is great! thank you. will the `vertico-sort-recency-*` be redundant if you use `savehist-mode`?

**Comment by minad** [comment]
No nothing changed with respect to savehist-mode.
