### ISSUE TITLE
Issue with `embark-act` and `switch-to-buffer` when using vertico

### ISSUE THREAD

**Issue by plattfot** [minad/vertico#72]
# Description
I have an embark function that copies the path associated with a buffer, which I'm calling in the `switch-to-buffer` to quickly copy a path instead of having to switch to the actual buffer then call =find-file= and copy the path that way.

But I notice in =vertico= it will only pick the first buffer listed regardless of which one is highlighted. This works as expected in =selectrum= and emacs default completion system. 

# Repro
## Versions
emacs: 28.0.50
vertico: 0.12
embark: 0.10
## Steps

Save the following to `/tmp/init.el`:
```
(require 'vertico)
(require 'embark)

(defun plt/embark-copy-buffer-file-name (buffer)
   "Copy buffer filename of BUFFER to `kill-ring'.

 If the buffer has no file associated to it, it will use the
 `default-directory' associated with BUFFER."
   (interactive "bBuffer: ")
   (with-current-buffer buffer
     (kill-new (or (buffer-file-name) default-directory))))

(define-key embark-buffer-map (kbd "c") 'plt/embark-copy-buffer-file-name)
(global-set-key (kbd "<f7>") 'embark-act)
(vertico-mode)
```
- Run `emacs -Q -l /tmp/init.el`.
- Open two files/directories. It doesn't really matter what files or directories, just that they have different paths.
- Switch to `*scratch*`.
- Open the `switch-to-buffer` (`C-x b`) again.
- Navigate to one of the buffers further down the list that is associated with one of the files or directories open previously.
- Hit `f7` to call `embark-act` then `c` to copy the path.
- Yank the result in the `*scratch*` buffer and you should see it inserting the path to the first buffer in the `switch-to-buffer` and not the one selected.

It will work if in the `switch-to-buffer` list you narrow down so that the buffer you want ends up on top.

**Comment by minad** [comment]
I cannot reproduce this. I assume it is because your Embark version is outdated (0.10 vs 0.11).

**Comment by plattfot** [comment]
I don't see an `0.11` version released for [Embark](https://github.com/oantolin/embark/releases). Anyway I switched to following the master branch of `embark` and indeed that fixed the issue.

Thank you for taking the time to look into this.

**Comment by minad** [comment]
Indeed 0.11 misses the release tag (cc @oantolin).
