### ISSUE TITLE
`(setq vertico-resize nil)` doesn't open minibuffer up to size `vertico-count` when there are no candidates

### ISSUE THREAD

**Issue by iyefrat** [minad/vertico#75]
To reproduce what I'm talking about, do `(setq vertico-resize nil)`, and run `consult-grep`. The minibuffer will stay at the size of one line until you type something in, at which point it will jump up to `vertico-count` size (+ 1 for the prompt) if there are matches. If further input leads to no matches, it'll stay at the expanded size. But if you type a no-match input fast enough to avoid loading any matches at all, it'll stay at 1 line size.

In my opinion, the most intuitive behavior here is for the minibuffer to expand immediately before the input is given and just stay there. The reason I like setting `vertico-resize` to `nil` is to minimize unexpected/unneeded buffer resizing, so the best time to do this is when invoking the command, not a few moments after I'm done typing. This behavior keeps also the resizing time of the minibuffer consistent across all commands.

 I tried to check what is the analogous behavior of:
```lisp
(setq resize-mini-windows nil
      max-mini-window-height 3)
```
But it seems that the minibuffer stays fixed at size 1 here, since `max-mini-window-height` only dictates the maximum growing size, and has nothing to do with the initial size. #44 seems to have reached the conclusion that minibuffer resize behavior is only of tangential interest to Vertico's behavior anyway, but I thought I'd mention it.

What are your thoughts on the subject?

cc @Zetagon

**Comment by minad** [comment]
Thanks, you found a bug :+1:
