### ISSUE TITLE
How do you customize sorting and highlighting?

### ISSUE THREAD

**Issue by mohkale** [minad/vertico#76]
I'd like to customize the sorting and highlighting of candidates depending on the completion category. 
For example for files I'd like to give directories a separate face from files and I'd like to sort them before files.

See also [selectrum#353](https://github.com/raxod502/selectrum/issues/353).

For highlighting I can advise `vertico--all-completions` which works well enough (although it isn't deferred like regular highlighing which isn't ideal), but I can't find any documentation on configuring sorting like you can with `selectrum-preprocess-candidates-function`.

**Comment by minad** [comment]
Related #71 

For sorting you can advise `vertico--sort`. As you may have seen, I am currently exploring extensions for Vertico (https://github.com/minad/vertico#extensions) to provide various enhancements. Currently all these extensions are done using a small amount of advices, but maybe I will add some entry points in the future to facilitate such extensions, e.g., a `vertico-sort-function` variable. But for now advices are the way to.

**Comment by mohkale** [comment]
@minad 

I considered advising `vertico--sort` but I'm not sure how to access the completion-category in it. It appears that all it recieves is the candidates so how can I customize sorting for files but leave it the same for other completion categories?

**Comment by minad** [comment]
> ...how to access the completion-category in it.

It is a bit complicated, but this is how one usually accesses the completion category.

~~~ elisp
(defun vertico-directory--completing-file-p ()
  "Return non-nil when completing file names."
  (eq 'file
      (completion-metadata-get
       (completion-metadata
        (buffer-substring (minibuffer-prompt-end)
                          (max (minibuffer-prompt-end) (point)))
        minibuffer-completion-table
        minibuffer-completion-predicate)
       'category)))
~~~

**Comment by mohkale** [comment]
@minad 

Much appreciated. Thank you.

**Comment by mohkale** [comment]
@minad 

I've gotten sorting working. Is there a similair approach for highlighting? I've been advising `vertico--all-completions` and changing its cdr to apply the highlight but I've just notices when I hit vertico-insert with that approach the faces are included in the prompt as well.

![Screenshot_20210709_211847](https://user-images.githubusercontent.com/23294780/125132078-b69ba980-e0fb-11eb-88a7-9b34bf742c68.png)

**Comment by minad** [comment]
What about advising `vertico--format-candidate`? (Generally regarding the advices to private functions, be aware that they may change any time.)

**Comment by mohkale** [comment]
All right, this works pretty well. Thanks again.

```lisp
(defun +minibuffer-file-highlight (cand)
  (when (string-suffix-p "/" cand)
    (add-face-text-property 0 (length cand) 'font-lock-function-name-face 'append cand))
  cand)

(defvar +minibuffer-category-highlight
  `((file . ,#'+minibuffer-file-highlight))
  "Custom highlight functions based on completion categories.")

(advice-add #'vertico--format-candidates :around #'vertico-format-candidates+)

(defun vertico-format-candidates+ (func metadata)
  (let* ((cat (completion-metadata-get metadata 'category))
         (hl-func (or (alist-get cat +minibuffer-category-highlight)
                      (alist-get t +minibuffer-category-highlight)
                      #'identity)))
    (cl-letf* (((symbol-function 'actual-vertico-format-candidate)
                (symbol-function #'vertico--format-candidate))
               ((symbol-function #'vertico--format-candidate)
                (lambda (cand prefix suffix index)
                  (actual-vertico-format-candidate
                   (funcall hl-func cand) prefix suffix index))))
      (funcall func metadata))))
```

**Comment by minad** [comment]
I added configurable sorting e2c91a6

**Comment by minad** [comment]
The best way to override the sorting functionality is like this:

~~~ elisp
(advice-add #'vertico--sort-function :before-until #'completion-category-sort-function)

(defun completion-category-sort-function (metadata)
  (alist-get (completion-metadata-get metadata 'category)
             completion-category-sort-function))

(defvar completion-category-sort-function
  '((file . directories-before-files)))

(defun directories-before-files (files)
  (setq files (vertico-sort-history-length-alpha files))
  (nconc (seq-filter (lambda (x) (string-suffix-p "/" x)) files)
         (seq-remove (lambda (x) (string-suffix-p "/" x)) files)))
~~~
