### ISSUE TITLE
`org-set-tags-command` to be fixed soon

### ISSUE THREAD

**Issue by darkfeline** [minad/vertico#77]
`org-set-tags-command`  should be fixed soon, so you can update the docs when this lands in a stable release.

https://lists.gnu.org/archive/html/emacs-orgmode/2021-07/msg00287.html

**Comment by darkfeline** [comment]
I don't know if you want a separate bug for this, but vertico's `completing-read-multiple` doesn't play well with `org-set-tags-command` with input longer than the window width and `truncate-lines` set to `t`.  vertico defaults to positioning positioning point at the very end of the input, with all of the initial input and prompt truncated on the left.

Here's an example directly after invoking `org-set-tags-command`:

![2021-07-09-144623_1919x1033_scrot](https://user-images.githubusercontent.com/855210/125138962-28292700-e0ff-11eb-8db2-4015b6f9099e.png)

Here's what it looks like pressing `C-a` after the above state:

![2021-07-09-144633_1919x1034_scrot](https://user-images.githubusercontent.com/855210/125138971-2d867180-e0ff-11eb-814f-dbc3173ed2bd.png)

I *think* vertico's `completing-read` does not suffer from this problem.

**Comment by minad** [comment]
Thanks, this is good news! @bdarcus already told me the same before. Regarding the scrolling, did you try the newest Vertico version? You may also want to give `consult-completing-read-multiple` a try, which provides an enhanced `completing-read-multiple` implementation.

**Comment by darkfeline** [comment]
I'm using 0.12.  I haven't tried `consult-completing-read-multiple`, but I don't think it's an option to make Org depend on consult.

**Comment by bdarcus** [comment]
> I'm using 0.12. I haven't tried `consult-completing-read-multiple`, but I don't think it's an option to make Org depend on consult.

Well, it won't depend on Vertico either; how is this different?

**Comment by darkfeline** [comment]
Org uses (will use) the standard Emacs `completing-read-multiple` API.  vertico claims to be a drop in replacement UI that adheres to the semantics of the standard `completing-read-multiple` API.  I'm pointing out a case where the vertico UI isn't user friendly for a valid use of the standard `completing-read-multiple` API.  I don't see `consult` as being relevant for the above point.

**Comment by bdarcus** [comment]
Consult-CRM is just a different interface for CRM.

It works with my package, and I don't require Consult.

Just FYI; your points on the default are of course valid too.

**Comment by minad** [comment]
> I'm using 0.12.

The issue should be fixed on Vertico master.

> I don't see consult as being relevant for the above point.

`consult-completing-read-multiple` is relevant since it provides an improved `completing-read-multiple` implementation, which works much better with long candidate strings and ensures that the prompt does not grow without bounds. I didn't imply that Org should depend on Consult. `consult-completing-read-multiple` is meant for the user-level configuration as a drop-in for `completing-read-multiple`.

**Comment by darkfeline** [comment]
I see, sorry for misunderstanding.  I will try vertico master later.  Is `consult-completing-read-multiple` in `consult` master branch too?  I don't see it in my stable `consult` install.

**Comment by minad** [comment]
Yes, the Vertico fix and `consult-completing-read-multiple` are both very recent and only available in the main branches.
