### ISSUE TITLE
Alter/refresh candidate list dynamically

### ISSUE THREAD

**Issue by scfrazer** [minad/vertico#79]
I'm trying to replicate some ido behavior, where when selecting a buffer if you press "C-k" it kills that buffer and continues letting you select from the remaining buffers.  Actually I want to understand how to do this in general, like if you are selecting a file it would delete the file and let you keep selecting, and so on.  The buffer example is the simplest case, if I can figure that out I can do other ones.

The extension `vertico-repeat` seems very close to what I need, but when I kill the buffer and do repeat the killed candidate is still there.  I looked around at the code and it's not obvious to me how to remove a candidate from the list and refresh the UI.

**Comment by minad** [comment]
You can call `vertico--exhibit` to force an update of the UI. In order to get updates you have to pass a function to `completing-read`:

~~~ elisp
(let ((items ...)) ;; items is a list which is mutated, after the mutation call `vertico--exhibit`
  (completing-read "Prompt: "
    (lambda (str pred action)
       (complete-with-action action items str pred))))
~~~

You may want to look into Embark. Embark offers general actions in the minibuffer, including `kill-buffer`. I hope this helps!

**Comment by scfrazer** [comment]
Thanks for the info.  I don't think Embark does quite what I want, but I'll look again.

I tried to follow your suggestion but don't quite get what the code should be.  I tried experimenting like this:

```elisp
(defvar test-items)

(defun my-vertico-remove-candidate ()
  "Remove the current candidate"
  (interactive)
  (setq test-items
        (delete (substring-no-properties (vertico--candidate))
                (mapcar #'substring-no-properties test-items)))
  (vertico--exhibit))

(define-key vertico-map (kbd "C-k") #'my-vertico-remove-candidate)

(progn
  (setq test-items (mapcar
                    (lambda (buf) (substring-no-properties (buffer-name buf)))
                    (buffer-list)))
  (completing-read "Buffer: "
    (lambda (str pred action)
       (complete-with-action action test-items str pred))))
```
But the selected candidate remains in the vertico UI, even though it has been removed from `test-items`.  I feel like I should be doing something inside the `lambda` instead.  Can I get another hint please?

**Comment by minad** [comment]
~~~ elisp
(defun my-vertico-remove-candidate ()
  "Remove the current candidate"
  (interactive)
  (setq test-items (delete (vertico--candidate) test-items))
  (setq vertico--input t)) ;; Force candidate recomputation in Vertico
~~~

I forgot to mention this, you have to recompute the candidates by setting `vertico--input`.

**Comment by scfrazer** [comment]
That did the trick, thanks!
