### ISSUE TITLE
Move Embark/Consult integration

### ISSUE THREAD

**Issue by minad** [minad/vertico#8]
For consistency it makes sense to move the Consult/Embark integrations to Consult/Embark, since these packages already provide integration code themselves and they somehow sit downstream of the actual completion systems. @oantolin I want to check first with you if you like this, since I am unsure how you feel about supporting such fringe completion systems.

(Secret motivation: The 500 line limit is about to fall...)

**Comment by manuel-uberti** [comment]
You know I only use this package because it is under 500 lines of code, so it's clear that this is right thing to do. Move, before it's too late!

Seriously, though, the lesser logic that refers to non-built-in features the better if you ask me.

**Comment by oantolin** [comment]
I'd be happy to have the Vertico integration in Embark!

**Comment by oantolin** [comment]
Done, oantolin/embark@7de30edc3c353d482b5b848f5e1254a104c38572.

**Comment by manuel-uberti** [comment]
I gave it a try for Vertico here: https://github.com/minad/consult/pull/267

**Comment by minad** [comment]
@manuel-uberti Sorry, I already pushed my version. Thank you for your help - your version is as good as mine, if not better since you have this "ext:" strings. What are these good for?

**Comment by minad** [comment]
I am glad to report that we are back to 465 sloc according to github. You can use Vertico for a little longer.

**Comment by manuel-uberti** [comment]
> @manuel-uberti Sorry, I already pushed my version. Thank you for your help - your version is as good as mine, if not better since you have this "ext:" strings. What are these good for?

They work as an indication for something belonging to an external package, or at least that's how I intend them for. Truth be told, I did ~~copy~~ learn from @oantolin.

**Comment by oantolin** [comment]
I didn't know about `ext:` either! Embark has them thanks to PR oantolin/embark#196 from @leungbk. It's a cool feature of `check-declare`: if you use `ext:`, `check-declare` will check such files if they are found, and skip them without error if they are not.
