### ISSUE TITLE
Vertico & Evil mode keybindings

### ISSUE THREAD

**Issue by mclearc** [minad/vertico#81]
I've noticed that vertico doesn't seem to cooperate with rebinding keys in evil very well. I've gotten the following to work in GUI:

```emacs-lisp
(use-package vertico
  :general
  (:states '(normal insert motion emacs) :keymaps 'vertico-map
   "<escape>" #'minibuffer-keyboard-quit
   "C-J"      #'vertico-next-group
   "C-K"      #'vertico-previous-group
   "C-j"      #'vertico-next
   "C-k"      #'vertico-previous
   "M-RET"    #'vertico-exit)
  :hook (after-init . vertico-mode))
```

But that doesn't work in terminal sessions for some reason. 

Nor does the evil rebinding command work (either in terminal or in GUI):
```emacs-lisp
  (with-eval-after-load 'evil
    (evil-define-key 'motion vertico-map
      "C-j"      #'vertico-next
      "C-k"      #'vertico-previous))
```

Any ideas what might be going wrong? I didn't have this problem with selectrum or icomplete-vertical.

**Comment by minad** [comment]
> Any ideas what might be going wrong? I didn't have this problem with selectrum or icomplete-vertical.

Vertico sets the keymap differently than the other packages. 

* In the minibuffer setup, Vertico does this:

~~~ elisp
(use-local-map vertico-map)
~~~

* In contrast, Icomplete does this:

~~~ elisp
(use-local-map (make-composed-keymap icomplete-minibuffer-map (current-local-map)))
~~~

* Selectrum does not replace the keymap, but sets it via `read-from-minibuffer`.

Maybe some evil user sees this and can help out, but it is more likely to get an answer if you ask on some evil issue tracker. I have no real clue about evil, but maybe `(advice-add :vertico--setup :after 'evil-normalize-keymaps)` helps.

**Comment by mclearc** [comment]
Thanks for that info. I'll report it to evil and see if any useful solutions appear. If so I'll come back to this issue.

**Comment by minad** [comment]
@iyefrat Maybe you can be of help here? Did you observe issues with the Vertico due to Evil mode in Doom?

**Comment by iyefrat** [comment]
I think the problem is that you're trying to do `evil-mode` specific things, and you don't really need to. Try this:

```lisp
(eval-after-load 'vertico
   '(general-define-key :keymaps '(vertico-map)
      "C-J"      #'vertico-next-group
      "C-K"      #'vertico-previous-group
      "C-j"      #'vertico-next
      "C-k"      #'vertico-previous))
```

**Comment by mclearc** [comment]
So it looks like setting `evil-want-minibuffer t` resolves the issue. Otherwise I have to use[ different settings](https://github.com/noctuid/general.el/issues/488#issuecomment-879135122) whether I'm using vertico in a child frame or in the minibuffer (and so different settings in the terminal as well, since child frames are not useable there). This might be worth putting a note in the README, since this isn't an issue that shows up with other completion packages that bind keys differently.
