### ISSUE TITLE
vertico-flat impressions as an Ido user

### ISSUE THREAD

**Issue by jdtsmith** [minad/vertico#86]
I like the idea of a simple upgrade path for ido users, and `vertical-flat` is an important part of that.  

I gave a try and noticed a couple small things right away:

- In ido, Left/Right arrows also act like C-n C-p to rotate selection.  Would be great to have that too.
- Rotating the list of completions in ido does just that, but on C-n, `vertico-flat` instead shows only the _remaining_ items on the list, so you can't see the other choices any more.  Easy fix is to have the choices shown "wrap around". 
- `vertico-flat` now entirely defeats `marginalia`.  It would be ideal to have it only "go flat" when the `marginalia` completion category is `'none` or (maybe) `'builtin`, and disable itself when marginalia wants to show lots of rich info. 

Thanks for vertico, and your major contributions to the full constellation of "back to basics" completion tools/UIs!

**Comment by minad** [comment]
Thanks for the suggestions, but note that I don't have the intention to replicate Ido precisely.

1. C-n/p - users can easily add these bindings to vertico-map. The vertico-map relies mostly on remapping and I don't want to add redundant bindings.
2. There is vertico-cycle. But this option doesn't affect the display.  One could add this but I see some value in seeing the discontinuity at the end.
3. Users who want this functionality should add it in their configuration. I think vertico-flat is mostly useful if you want to have a compact view. So you could enable it by default or only for certain commands and add a key binding to vertico-map which allows to turn flat mode off during completion.

**Comment by jdtsmith** [comment]
Thanks for your thoughts.  On #2, I would add that this represents a break from vertical layout, where you have the full context of other candidates at all times.  

I'll close this for now, but if others have similar opinions about ido-alike defaults, perhaps they can reopen. 

PS: I'm actually liking vertical layout more and more...

**Comment by minad** [comment]
2) we could implement this wrap around in vertico-flat if vertico-cycle=t, but not generally in vertico iself. I would accept a patch which implements this.

**Comment by jdtsmith** [comment]
Vertical view IMO doesn't need it, since the "current selection" doesn't have to stay right at the top, so it's easy to see many other candidates before/after the selected one.  In a flat context where the current selection is "rotated to the front", it makes more sense.  vertico-flat could also stylize one of the separator bars to indicate "here the list wraps".   I don't believe Ido does that.

**Comment by minad** [comment]
Yes, I also thought about using a different bar separator for this. Let's keep this open for now.
