### ISSUE TITLE
Need a `vertico-refresh`

### ISSUE THREAD

**Issue by jdtsmith** [minad/vertico#87]
One of the nice suggestions on the orderless docs is a binding like `C-l` to toggle to a literal style.  There it is suggested to implement this in `minibuffer-local-completion-map`, which vertico disables.  It also works fine in `vertico-map`, but when altering settings like `orderless-matching-styles`, you'd like to have the vertico UI update afterwards.  I found I could:

```Elisp
(setq vertico--input nil)
(vertico--goto vertico--index)
```

and it refreshes display.  If that's all it takes, perhaps it's worth a user-facing function for this.  

Somewhat relatedly: I'd also like to add a tag like `[literal]` to the prompt; not sure the most convenient/completion-UI-agnostic way to do so.  Thanks for vertico.

**Comment by minad** [comment]
Setting vertico--input=t is all it takes to force a candidate recomputation, the rest happens in the post command hook. I don't want to add a user facing function for this. Vertico only offers user facing commands publicly. There in is no Vertico API. You may also want to reset vertico--lock-... and vertico--history-hash depending on the use case. See consult-vertico for the refreshing code used by Consult.

**Comment by jdtsmith** [comment]
Works perfectly, thanks.  For others who want to try this, here's how I accomplished a toggle-able `Ctrl-l` in vertico+orderless (with a `[lit]` prompt addition):

```elisp
  (defvar my/orderless-match-save nil)
  (defvar my/orderless-overlay nil)
  (defun my/match-components-literally ()
    "Toggle literal match in orderless+vertico."
    (interactive)
    (if my/orderless-match-save
	(progn
	  (setq-local orderless-matching-styles
		      (aref my/orderless-match-save 0)
		      orderless-style-dispatchers
		      (aref my/orderless-match-save 1)
		      my/orderless-match-save nil)
	  (delete-overlay my/orderless-overlay))
      (setq-local my/orderless-match-save
		  (vector orderless-matching-styles orderless-style-dispatchers)
		  orderless-matching-styles '(orderless-literal)
		  orderless-style-dispatchers nil)
      (let ((prompt-end (minibuffer-prompt-end)))
	(setq my/orderless-overlay
	      (make-overlay prompt-end prompt-end))
	(overlay-put my/orderless-overlay 'before-string
		     (propertize "[lit] " 'face 'minibuffer-prompt))))
    (setq vertico--input t))

  (define-key vertico-map (kbd "C-l") #'my/match-components-literally)
```

**Comment by minad** [comment]
One thing I forgot to mention - I don't recommend introducing such a literal style switcher. Orderless offers matching styles and style dispatchers where one can specify the style per word.

The disadvantage of the literal dispatcher here is that the input string introduces "out of band" state, while the style dispatcher relies only on the input string without additional state. Therefore one also needs the [literal] indicator overlay here.

Consult narrowing has a similar problem, where the narrowing state is separate from the input filter string.

**Comment by jdtsmith** [comment]
Yeah, that's a good point.  Sometimes out of band state is easier to compose just in time.  I suppose foo# or so could be read as "this is literal", but the more special categories you introduce, the more state you need to keep in your head.   That aside, I do find the orderless style dispatchers to be quite simple and powerful.

**Comment by minad** [comment]
I use foo= as literal, which I find easy to understand. But you are of course right that the filter language could be arbitrarily complicated so it may make sense to off load some filtering to out of band state, like the Consult narrowing. But in the particular case of Consult narrowing one could also come up with the idea to also support narrowing to buffers *and/or* files, which would lead to an additional out of band filter language. At this point the advantage of going out of band is lost.
