### ISSUE TITLE
Truncate-string-to-width error in annotations

### ISSUE THREAD

**Issue by bdarcus** [minad/vertico#90]
@minad - my brain is a bit fried having been trying to figure this out for the past few hours, but I think I've concluded there's a bug in Vertico when dealing with `truncate-string-to-width` in annotations; possibly when using with `concat`.

This is the code at issue, but the error happens even without `propertize` there.

https://github.com/bdarcus/bibtex-actions/blob/ba0c732efb72813ad04b77c0b151ce50aa44a60a/bibtex-actions-org-cite.el#L226

When I run `bibtex-actions-org-cite-select-style` from `ielm`, it works in Selectrum, but fails with this error in Vertico.

```console
 (wrong-type-argument stringp nil)
```

https://github.com/bdarcus/bibtex-actions/pull/182

**Comment by minad** [comment]
If you call `truncate-string-to-width` with a nil-argument you will see this error. This means the annotation function gets called with a style which is not present in the natbib association list. The candidates you use are natbib+biblatex styles, but in the annotation function you only lookup the bibtex-actions-org-cite--natbib-style-preview association list. So I conclude that this is not a Vertico bug ;)

Please recheck - if the problem persists, try to find a more minimal reproducible example, which I could run check directly.

**Comment by bdarcus** [comment]
I'll give it a try again in the morning. Doesn't appear to be that straightforward.

**Comment by bdarcus** [comment]
I simplified the code, and the function works correctly on its own.

I think the problem is with some not very helpful error reporting, and maybe a bug, in org-cite.
