### ISSUE TITLE
Mode to avoid movement of the default candidate

### ISSUE THREAD

**Issue by minad** [minad/vertico#92]
If sorting is disabled (display-sort-function=identity) and a default candidate is specified, Vertico could try to preserve the candidate order and avoid moving the default candidate. During filtering the candidates should still be matched starting from the default candidate, basically the UI should scroll right away to the default position. Unfortunately this seems to be a major complication - therefore I have not implemented something like this yet. Selectrum has a no-move-default option, however it is lacking since it does not affect the filtering starting point. As soon as filtering starts, the position is lost.

**Comment by minad** [comment]
*Copying my comments from https://github.com/minad/consult/issues/366*:

The main complication is the preservation of the starting point when you filter. The optimal (complicated) solution looks like this:

~~~
1       ==filtering==>       1
2                            x <- removed by filtering
3 <- default/selected        x <- removed by filtering
4                            4 <- selected after filtering
5                            5
~~~

With wrap around (as implemented in consult-line for example), the order is preserved naturally:

~~~
3 <- default/selected       x <- removed by filtering
4                           4 <- selected after filtering
5        ==filtering==>     5
1                           1 
2                           x <- removed by filtering
~~~

And Selectrum does this, which is not optimal (1 is selected instead of 4, which comes after the default 3)

~~~
1       ==filtering==>       1 <- selected after filtering
2                            x <- removed by filtering
3 <- default/selected        x <- removed by filtering
4                            4
5                            5
~~~

**Comment by minad** [comment]
Maybe candidate locking which is already presnt can help to fix this easily.

**Comment by Atemu** [comment]
The non-optimal selectrum behaviour is preferable to the current wrap-around behaviour IMO.

Could the candidate-locking approach be implemented despite being non-optional?

**Comment by minad** [comment]
With the no-move-default branch](https://github.com/minad/vertico/tree/no-move-default) I just tried the following simple command and executed it at point over a symbol:

~~~ elisp
(defun select-symbol ()
  (interactive)
  (completing-read "Symbol: " obarray nil nil nil nil (thing-at-point 'symbol)))
~~~

I must say I don't really like the no-move-default behavior. By moving the default to the top it is much more obvious what is going on. Note that we are talking about *all possible Emacs completing-read commands*, not only a few of them. Vertico implements the behavior which works best for most commands.

**Comment by Atemu** [comment]
My largest gripe with the current wrap-around behaviour is that it doesn't allow me to search "upwards"; selecting the previous result doesn't wrap around to the bottom and instead moves the cursor to the input line.  
To search for something that is located above the current point, you have to go through results of the *entire* file minus the section between target and point and that's obviously not very efficient.

I now see what you meant by selectrum's behaviour. It jumps to the top as soon as you have any filter and doesn't consider your point in the total list at all. That is indeed worse behaviour than the current wrap around.

Could wrap-around be made to also wrap at the top? That could alleviate my problem.

**Comment by minad** [comment]
> My largest gripe with the current wrap-around behaviour is that it doesn't allow me to search "upwards"; selecting the previous result doesn't wrap around to the bottom and instead moves the cursor to the input line.

This is not entirely true. Vertico does not allow you to select the input line for `consult-line`, since `consult-line` sets `REQUIRE-MATCH=t`.

> To search for something that is located above the current point, you have to go through results of the entire file minus the section between target and point and that's obviously not very efficient.

Actually it is efficient. You can simply press `M->` to move to the last candidate. `M-> <up>` will give you the candidate before the last one, and so on `M-> <up> <up>`, ...

`M-<` will again bring you back to the first matching line after the current line.

> Could wrap-around be made to also wrap at the top? That could alleviate my problem.

If you set `vertico-cycle=t` then you can move upwards. You will end up at the last candidate, which corresponds to a match before the current line.

**Comment by Atemu** [comment]
> This is not entirely true. Vertico does not allow you to select the input line for `consult-line`, since `consult-line` sets `REQUIRE-MATCH=t`.

Oh yes, sorry. It does nothing instead indeed.

> Actually it is efficient. You can simply press `M->` to move to the last candidate. `M-> <up>` will give you the candidate before the last one, and so on `M-> <up> <up>`, ...
> 
> `M-<` will again bring you back to the first matching line after the current line.

Sadly, that's quite unergonomic and requires mental overhead when I'd really rather just focus on the thing I'm looking for.

> If you set `vertico-cycle=t` then you can move upwards. You will end up at the last candidate, which corresponds to a match before the current line.

That does indeed work, thank you!

Only slight annoyance is that the wraps don't continue showing the lines that would come after the wrap but hacking around that would probably be harder than the optimal solution that doesn't need wraps in the first place.

**Comment by Atemu** [comment]
Yeah, I've realised that isearch covers lots of my use-cases too. It doesn't neatly show all results in a quick overview for the in-buffer grep use-case however, so I still need consult-line for that.

I'll have to look into getting just swiper from ivy/counsel somehow perhaps because it covered that use-case very well.

**Comment by minad** [comment]
> I'll have to look into getting just swiper from ivy/counsel somehow perhaps because it covered that use-case very well.

It could be that Swiper handles some edge cases better, but I doubt that it is worth to use Swiper just for that if you prefer the rest from Consult. But if you are happy with Ivy/Counsel, you could just stick to that. Swiper (or swiper-isearch) also has the goal of replacing Isearch, which I don't think is a great idea. Overall the priorities of Ivy and Vertico are different. For Vertico it is acceptable to make some minor usability sacrifices if at the same time we end up with a system which is simpler and more coherent as a whole. I mean one can implement arbitrary complicated behavior by adding adding adding, handling more special cases and so on. I like how Vertico is quite simple in its current form and I want to keep it like this.
