### ISSUE TITLE
bufferless Ibuffer leaves a persistent message

### ISSUE THREAD

**Issue by jdtsmith** [minad/vertico#93]
When Ibuffer, whether started from embark export or the old fashioned way, has no buffers, it leaves an aggressively persistent message `No buffers! (note: filtering in effect)` in the mini buffer, which Vertico keeps showing for all future invocations.  In fact the Ibuffer can be buried and Vertico will keep on showing it, for as long as the Ibuffer exists and has no buffers shown! Hours later it will still be showing it.  

In plain emacs, this message is shown once, but does not persist in this manner.  Not sure if this can be considered an Ibuffer bug, but it seems another inactive tool shouldn't be able to continuously clutter the mini buffer prompt in that way.  

To reproduce:

- start Ibuffer
- `/n matches_nothing! [Ret]`
- (Optional) bury the buffer
- Invoke `switch-to-buffer`, or `consult-buffer`, `consult-line`, or almost any mini buffer using command.

**Comment by minad** [comment]
I cannot reproduce this on Emacs 27 and 28, neither with emacs -Q nor in my configuration.

**Comment by jdtsmith** [comment]
Thank you.  I narrowed down to this offender:

```elisp
(add-hook 'ibuffer-mode-hook (lambda () (ibuffer-auto-mode 1)))
```

which is a recommended config option.  Perhaps vertico ends up calling the mode-hook where the default mini buffer read does not?

**Comment by minad** [comment]
Okay, seems to be an Ibuffer issue. The issue is not related to Vertico, since the message also appears for default completion. For me the persistent message goes away when I kill the Ibuffer.

**Comment by minad** [comment]
There seems to be no easy way to disable this message. I have some code in my init.el, which completely suppresses messages. Maybe this Ibuffer message would be a contender to be added to the list of suppressed messages.

~~~ elisp
;; completely suppress some standard messages
(defconst +suppressed-messages
  '("\\`Mark \\(set\\|activated\\|deactivated\\|saved\\)"
    "\\`Back to top level\\'"
    ;; "Undo" "Redo" TODO does not work?
    ;; "No other windows to delete" "No other window to select"
    ;; Some commands use message instead of the command-error-function!
    "\\`\\(Beginning\\|End\\) of buffer\\'"
    ;; TODO this messages can be supressed with server-client-instructions=nil on 28
    "\\`When done with this frame, type"))

(defun +message-adv (fun fmt &rest args)
  (catch '+suppressed
    (when (and fmt (not (string= fmt "")))
      (let ((msg (if args (apply #'format fmt args) fmt)))
        (dolist (suppressed +suppressed-messages)
          (when (string-match-p suppressed msg)
            (throw '+suppressed msg)))))
    (apply fun fmt args)))

(advice-add #'message :around #'+message-adv)
~~~
