### ISSUE TITLE
small vertico-directory feature request: clear old file path when new root is selected

### ISSUE THREAD

**Issue by jdtsmith** [minad/vertico#94]
A simple but great feature of ido I miss, even with `vertico-directory` loaded:  if you have a path like `/path/to/foo/` and then start entering another path which is clearly _not_ a subpath, like `/another/path` or `~/`, ido will clear out the old path and start fresh.  It's a great way to switch to your home directory from elsewhere, for example.  Or to start a new tramp connection `/ssh:...`.

**Comment by minad** [comment]
See vertico-directory-tidy in the README.
