### ISSUE TITLE
No multiline support with vertico-flat

### ISSUE THREAD

**Issue by spiderbit** [minad/vertico#99]
With smex as example I get 10 results, always (probably somewhere configurable but that is the default), which seems to be the same for vertico, with all configurations I see also 10 results except with the flat extensions, there I only see as much examples as fit in 1 line, depending on how long the words are for the matches, I get that much matches.

So if you have a to small resolution / to big fonts, you don't get your 10 results. smex just makes a line break at the end of the line and shows then 2-3 lines...

**Comment by minad** [comment]
Good point. Fixed by adding `vertico-flat-max-lines`, which defaults to 1. If you set it to a higher value you will get your desired result.
